function slug(title) {
  return String(title).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
function item(title, packageKey, objective = '', tags = [], mastery = [], checkpoint = '') {
  return { title, packageKey, objective, tags, mastery, checkpoint };
}
function simple(titles, packageRules, objectivePrefix, tag) {
  return titles.map((title, index) => item(title, packageRules(index + 1), `${objectivePrefix}: ${title}.`, [tag, slug(title)]));
}
function total(maps) { return Object.values(maps).reduce((sum, lessons) => sum + lessons.length, 0); }

export const B1_PACKAGES = Object.freeze({
  independence: { id: 'B1.1', title: 'B1.1 Independent foundations', goal: 'Sustentar conversas simples, narrar experiências e lidar com situações previsíveis.' },
  narrative: { id: 'B1.2', title: 'B1.2 Narratives and experiences', goal: 'Contar histórias, experiências e planos com sequência e clareza.' },
  opinions: { id: 'B1.3', title: 'B1.3 Opinions and explanations', goal: 'Dar opinião, justificar escolhas e explicar problemas cotidianos.' },
  practical: { id: 'B1.4', title: 'B1.4 Practical independence', goal: 'Resolver tarefas de viagem, trabalho, estudo, saúde e serviços.' },
  reviewsCheckpoints: { id: 'B1.5', title: 'B1.5 Reviews and checkpoints', goal: 'Integrar habilidades e confirmar autonomia B1.' },
});
export const B1_GRAMMAR_MAP = simple(['A2 repair and fluency bridge','Past Continuous','Past Simple vs Past Continuous','Present Perfect — experience','Present Perfect with ever and never','Present Perfect vs Past Simple','Present Perfect with for and since','Future review: going to, will and present continuous','First Conditional','Zero Conditional','Modals of obligation and advice review','Must / have to / should contrast','Used to','Relative clauses: who, which, that','Gerunds and infinitives basic','Passive voice present simple','Passive voice past simple','Reported speech basic statements','Question tags basic','Indirect questions','Linkers: although, however, therefore','B1 Grammar Review 1','B1 Grammar Review 2','B1 Grammar Checkpoint'], (n) => n <= 1 ? 'independence' : n <= 8 ? 'narrative' : n <= 15 ? 'opinions' : n <= 21 ? 'practical' : 'reviewsCheckpoints', 'Gramática B1 para independência', 'grammar').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'grammar-checkpoint' } : l);
export const B1_VOCABULARY_MAP = simple(['Life events','Education and learning','Work and careers','Travel problems','Health and appointments','Money and services','Technology and communication','Feelings and relationships','Opinions and reasons','Media and entertainment','Environment basics','City life and community','Home repairs and problems','Food habits and lifestyle','Personal goals','Common collocations B1','Phrasal verbs B1 set 1','Phrasal verbs B1 set 2','Vocabulary Review B1','Vocabulary Checkpoint B1'], (n) => n <= 4 ? 'independence' : n <= 8 ? 'narrative' : n <= 13 ? 'opinions' : n <= 18 ? 'practical' : 'reviewsCheckpoints', 'Vocabulário B1 funcional', 'vocabulary').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'vocabulary-checkpoint' } : l);
export const B1_READING_MAP = simple(['A personal experience story','A travel problem email','An online review','A work update message','A short news article','An advice column','A study blog post','A health information leaflet','A simple opinion article','A community announcement','Reading for sequence and timeline','Reading for opinion and reason','Reading for problem and solution','Reading for contrast','Reading for implied meaning basic','Reading vocabulary from context B1','Reading Review B1','Reading Checkpoint B1'], (n) => n <= 4 ? 'independence' : n <= 8 ? 'narrative' : n <= 14 ? 'opinions' : n <= 16 ? 'practical' : 'reviewsCheckpoints', 'Leitura B1 com sequência e opinião', 'reading').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'reading-checkpoint' } : l);
export const B1_LISTENING_MAP = simple(['A story about a trip','A problem at work','A doctor appointment','A study plan discussion','A radio announcement','A simple podcast extract','A customer service call','A conversation about plans','Listening for sequence','Listening for opinion','Listening for reason','Listening for problem and solution','Listening for contrast markers','Listening for key details B1','Listening Review B1','Listening Checkpoint B1'], (n) => n <= 4 ? 'independence' : n <= 8 ? 'narrative' : n <= 13 ? 'opinions' : n <= 14 ? 'practical' : 'reviewsCheckpoints', 'Escuta B1 em diálogos e monólogos simples', 'listening').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'listening-checkpoint' } : l);
export const B1_SPEAKING_MAP = simple(['Talk about a past experience','Tell a story with sequence','Explain a problem','Ask for help in a service situation','Give an opinion with reasons','Compare two options with reasons','Talk about goals','Discuss study and work','Describe a health problem','Handle travel problems','Give advice','Make suggestions','Agree and disagree politely','Speak for 2 minutes about your week','Speaking Review B1','Speaking Checkpoint B1'], (n) => n <= 4 ? 'independence' : n <= 8 ? 'narrative' : n <= 13 ? 'opinions' : n <= 14 ? 'practical' : 'reviewsCheckpoints', 'Speaking B1 com autonomia', 'speaking').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'speaking-checkpoint' } : l);
export const B1_WRITING_MAP = simple(['Write a story about an experience','Write an email explaining a problem','Write a review','Write an opinion paragraph','Write advice','Write a complaint message','Write a work update','Write a study plan','Write a travel problem report','Write a comparison paragraph','Connect paragraphs with linkers','Revise clarity and sequence','Writing Review B1','Writing Checkpoint B1'], (n) => n <= 3 ? 'independence' : n <= 7 ? 'narrative' : n <= 12 ? 'opinions' : 'reviewsCheckpoints', 'Writing B1 organizado', 'writing').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'writing-checkpoint' } : l);
export const B1_PILLAR_MAPS = Object.freeze({ grammar: B1_GRAMMAR_MAP, vocabulary: B1_VOCABULARY_MAP, reading: B1_READING_MAP, listening: B1_LISTENING_MAP, speaking: B1_SPEAKING_MAP, writing: B1_WRITING_MAP });
export const B1_EXIT_CRITERIA = Object.freeze({ grammar: 78, vocabulary: 82, reading: 78, listening: 74, speaking: 70, writing: 74, finalCheckpoint: true });

export const B2_PACKAGES = Object.freeze({ precision: { id: 'B2.1', title: 'B2.1 Precision and range', goal: 'Aumentar precisão gramatical, vocabulário e flexibilidade.' }, argumentation: { id: 'B2.2', title: 'B2.2 Argumentation and analysis', goal: 'Argumentar, comparar, defender pontos de vista e responder contra-argumentos.' }, professional: { id: 'B2.3', title: 'B2.3 Professional and academic communication', goal: 'Comunicar-se em contextos profissionais, acadêmicos e digitais.' }, fluency: { id: 'B2.4', title: 'B2.4 Fluency and long-form input', goal: 'Lidar com textos e áudios longos com autonomia.' }, reviewsCheckpoints: { id: 'B2.5', title: 'B2.5 Reviews and checkpoints', goal: 'Confirmar domínio B2.' } });
export const B2_GRAMMAR_MAP = simple(['B1 repair and complexity bridge','Present Perfect Continuous','Past Perfect','Future Continuous and Future Perfect basics','Second Conditional','Third Conditional introduction','Mixed conditionals basic','Modal verbs of deduction','Advanced passive voice','Reported speech questions and commands','Relative clauses defining and non-defining','Participle clauses introduction','Cleft sentences basic','Inversion basic for emphasis','Advanced linkers and discourse markers','B2 Grammar Review 1','B2 Grammar Review 2','B2 Grammar Checkpoint'], (n) => n <= 4 ? 'precision' : n <= 9 ? 'argumentation' : n <= 15 ? 'professional' : 'reviewsCheckpoints', 'Gramática B2 para precisão e argumento', 'grammar').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'grammar-checkpoint' } : l);
export const B2_VOCABULARY_MAP = simple(['Abstract nouns and concepts','Workplace communication','Meetings and negotiation','Academic vocabulary basics','Media and society','Technology and AI','Environment and sustainability','Health and wellbeing','Economics and consumer behavior','Culture and identity','Argumentation phrases','Cause and effect vocabulary','Contrast and concession vocabulary','Professional email phrases','Presentation language','Idioms B2 set 1','Phrasal verbs B2 set 1','Vocabulary Review B2','Vocabulary Checkpoint B2'], (n) => n <= 4 ? 'precision' : n <= 10 ? 'argumentation' : n <= 17 ? 'professional' : 'reviewsCheckpoints', 'Vocabulário B2 abstrato e profissional', 'vocabulary').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'vocabulary-checkpoint' } : l);
export const B2_READING_MAP = simple(['A long opinion article','A workplace report','A research-style summary','A product comparison review','A social issue article','A technology article','An environmental article','A professional email chain','Reading for argument structure','Reading for stance','Reading for inference','Reading for nuance','Reading for data and examples','Reading for author purpose','Reading Review B2','Reading Checkpoint B2'], (n) => n <= 4 ? 'precision' : n <= 10 ? 'argumentation' : n <= 14 ? 'fluency' : 'reviewsCheckpoints', 'Leitura B2 com argumento e nuance', 'reading').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'reading-checkpoint' } : l);
export const B2_LISTENING_MAP = simple(['A meeting discussion','A presentation excerpt','A debate excerpt','A podcast interview','A workplace problem discussion','A news report','An academic mini lecture','A negotiation dialogue','Listening for stance','Listening for supporting evidence','Listening for concession','Listening for implied attitude','Listening for long-form structure','Listening Review B2','Listening Checkpoint B2'], (n) => n <= 4 ? 'precision' : n <= 9 ? 'argumentation' : n <= 13 ? 'fluency' : 'reviewsCheckpoints', 'Escuta B2 em fala natural controlada', 'listening').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'listening-checkpoint' } : l);
export const B2_SPEAKING_MAP = simple(['Give a structured opinion','Defend an argument','Compare complex options','Respond to disagreement','Present a problem and solution','Lead a short meeting','Give a 3-minute presentation','Summarize an article orally','Discuss advantages and disadvantages','Negotiate a practical outcome','Clarify and reformulate','Use discourse markers naturally','Speaking Review B2','Speaking Checkpoint B2'], (n) => n <= 4 ? 'precision' : n <= 10 ? 'argumentation' : n <= 12 ? 'professional' : 'reviewsCheckpoints', 'Speaking B2 estruturado e fluente', 'speaking').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'speaking-checkpoint' } : l);
export const B2_WRITING_MAP = simple(['Write a structured opinion essay','Write a professional email','Write a report summary','Write advantages and disadvantages','Write a problem-solution text','Write a formal complaint','Write meeting notes','Write a presentation outline','Write a balanced argument','Improve cohesion and paragraphing','Writing Review B2','Writing Checkpoint B2'], (n) => n <= 4 ? 'precision' : n <= 9 ? 'argumentation' : n <= 10 ? 'professional' : 'reviewsCheckpoints', 'Writing B2 com coesão', 'writing').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'writing-checkpoint' } : l);
export const B2_PILLAR_MAPS = Object.freeze({ grammar: B2_GRAMMAR_MAP, vocabulary: B2_VOCABULARY_MAP, reading: B2_READING_MAP, listening: B2_LISTENING_MAP, speaking: B2_SPEAKING_MAP, writing: B2_WRITING_MAP });
export const B2_EXIT_CRITERIA = Object.freeze({ grammar: 80, vocabulary: 84, reading: 80, listening: 76, speaking: 72, writing: 76, finalCheckpoint: true });

function advancedLevel(prefix, descriptor, pkgPrefix, criteria, counts = {}) {
  const packages = Object.freeze({ control: { id: `${prefix}.1`, title: `${prefix}.1 Control and precision`, goal: `Desenvolver controle ${descriptor}.` }, nuance: { id: `${prefix}.2`, title: `${prefix}.2 Nuance and style`, goal: `Entender e produzir nuance ${descriptor}.` }, professional: { id: `${prefix}.3`, title: `${prefix}.3 Professional mastery`, goal: `Comunicação profissional/acadêmica ${descriptor}.` }, reviewsCheckpoints: { id: `${prefix}.4`, title: `${prefix}.4 Reviews and checkpoints`, goal: `Confirmar domínio ${prefix}.` } });
  const grammar = simple(['Advanced tense control','Subtle modal meanings','Advanced conditionals','Nominalization','Advanced passive and causative','Emphasis and inversion','Advanced clauses','Register and grammar choice','Discourse grammar','Grammar Review','Grammar Checkpoint'], (n) => n <= 4 ? 'control' : n <= 9 ? 'nuance' : 'reviewsCheckpoints', `Gramática ${prefix}`, 'grammar').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'grammar-checkpoint' } : l);
  const vocabulary = simple(['High-frequency advanced vocabulary','Register and tone','Academic word families','Professional vocabulary','Idioms and fixed expressions','Nuance in adjectives and adverbs','Collocations advanced','Topic vocabulary: society','Topic vocabulary: work and technology','Vocabulary Review','Vocabulary Checkpoint'], (n) => n <= 4 ? 'control' : n <= 9 ? 'nuance' : 'reviewsCheckpoints', `Vocabulário ${prefix}`, 'vocabulary').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'vocabulary-checkpoint' } : l);
  const reading = simple(['Long-form article analysis','Opinion and bias','Academic extract','Literary/non-fiction style','Reading between the lines','Reading for rhetorical structure','Reading for nuance','Reading Review','Reading Checkpoint'], (n) => n <= 3 ? 'control' : n <= 7 ? 'nuance' : 'reviewsCheckpoints', `Leitura ${prefix}`, 'reading').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'reading-checkpoint' } : l);
  const listening = simple(['Natural conversation','Interview analysis','Lecture extract','Debate and disagreement','Listening for attitude','Listening for implication','Listening for nuance','Listening Review','Listening Checkpoint'], (n) => n <= 3 ? 'control' : n <= 7 ? 'nuance' : 'reviewsCheckpoints', `Escuta ${prefix}`, 'listening').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'listening-checkpoint' } : l);
  const speaking = simple(['Sustain a complex opinion','Handle interruptions','Clarify nuance','Present advanced argument','Discuss abstract topics','Professional speaking task','Speaking Review','Speaking Checkpoint'], (n) => n <= 3 ? 'control' : n <= 6 ? 'professional' : 'reviewsCheckpoints', `Speaking ${prefix}`, 'speaking').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'speaking-checkpoint' } : l);
  const writing = simple(['Advanced paragraph control','Formal email and proposal','Argument essay','Synthesis writing','Style and register editing','Professional report','Writing Review','Writing Checkpoint'], (n) => n <= 3 ? 'control' : n <= 6 ? 'professional' : 'reviewsCheckpoints', `Writing ${prefix}`, 'writing').map((l) => l.title.includes('Checkpoint') ? { ...l, checkpoint: 'writing-checkpoint' } : l);
  const maps = Object.freeze({ grammar, vocabulary, reading, listening, speaking, writing });
  return { packages, maps, criteria };
}

const C1 = advancedLevel('C1', 'avançado com nuance', 'C1', { grammar: 82, vocabulary: 86, reading: 82, listening: 78, speaking: 74, writing: 78, finalCheckpoint: true });
const C2 = advancedLevel('C2', 'quase nativo e sofisticado', 'C2', { grammar: 85, vocabulary: 88, reading: 85, listening: 80, speaking: 76, writing: 80, finalCheckpoint: true });
export const C1_PACKAGES = C1.packages; export const C1_PILLAR_MAPS = C1.maps; export const C1_EXIT_CRITERIA = Object.freeze(C1.criteria);
export const C2_PACKAGES = C2.packages; export const C2_PILLAR_MAPS = C2.maps; export const C2_EXIT_CRITERIA = Object.freeze(C2.criteria);

export function getB1TotalLessonCount() { return total(B1_PILLAR_MAPS); }
export function getB2TotalLessonCount() { return total(B2_PILLAR_MAPS); }
export function getC1TotalLessonCount() { return total(C1_PILLAR_MAPS); }
export function getC2TotalLessonCount() { return total(C2_PILLAR_MAPS); }
