import { useMemo, useState } from 'react';
import { BookOpenCheck, CheckCircle2, Headphones, ListChecks, Mic, PencilLine, Sparkles, Target, XCircle } from 'lucide-react';
import { Card } from '../../components/ui/Card.jsx';
import { AiTutorPanel } from '../../components/tutor/AiTutorPanel.jsx';
import { StaticCompletionGate } from './StaticCompletionGate.jsx';

function safeArray(value) { return Array.isArray(value) ? value : []; }
function clean(value) { return String(value ?? '').trim(); }
function textOf(value) { return clean(value?.text || value?.content || value?.instruction || value?.question || value?.title || value); }
function normalizeAnswer(value) { return clean(value).toLowerCase().replace(/[.!?]+$/g, '').replace(/\s+/g, ' '); }
function isCorrect(value, answer) { return Boolean(answer) && normalizeAnswer(value) === normalizeAnswer(answer); }
function pillarLabel(pillar) { return ({ grammar: 'Grammar', vocabulary: 'Vocabulary', reading: 'Reading', listening: 'Listening', speaking: 'Speaking', writing: 'Writing' }[pillar] || 'Aula'); }
function getIntro(lesson) { const firstObjective = safeArray(lesson?.objectives)[0]; if (lesson?.intro) return lesson.intro; if (firstObjective) return firstObjective; return 'Aula fixa premium do currículo Fluency, criada para estudar com explicação, exemplos, prática guiada e produção própria.'; }
function LessonFooterTools({ lesson }) { return <><AiTutorPanel lesson={lesson} /><StaticCompletionGate lesson={lesson} /></>; }
function uniqueCleanOptions(options = []) { const seen = new Set(); return safeArray(options).map(clean).filter(Boolean).filter((option) => { const key = normalizeAnswer(option); if (!key || seen.has(key)) return false; seen.add(key); return true; }); }
function stableHash(value) { const text = String(value || ''); let hash = 2166136261; for (let index = 0; index < text.length; index += 1) { hash ^= text.charCodeAt(index); hash = Math.imul(hash, 16777619); } return hash >>> 0; }
function stableShuffle(options = [], seed = '') { const list = [...options]; if (list.length < 2) return list; for (let index = list.length - 1; index > 0; index -= 1) { const swapIndex = stableHash(`${seed}:${index}`) % (index + 1); [list[index], list[swapIndex]] = [list[swapIndex], list[index]]; } return list; }

function ObjectiveCard({ lesson }) {
  return <Card eyebrow={`${pillarLabel(lesson.pillar)} fixa · ${lesson.level || 'A1'}`} title={lesson.title}><div className="static-lesson-objective-grid"><p>{getIntro(lesson)}</p><div className="lesson-objective-card"><Target size={18} /><span>Objetivos</span><ul>{safeArray(lesson.objectives).length ? safeArray(lesson.objectives).map((item, index) => <li key={`${item}-${index}`}>{item}</li>) : <li>Entender, praticar e produzir usando o conteúdo da aula.</li>}</ul></div></div></Card>;
}
function SectionStack({ title, icon: Icon = BookOpenCheck, items = [], renderItem, empty = 'Sem itens cadastrados ainda.' }) { return <section className="static-lesson-card"><div className="panel-title"><Icon size={18} /> {title}</div>{safeArray(items).length ? <div className="static-lesson-stack">{items.map((item, index) => renderItem(item, index))}</div> : <p>{empty}</p>}</section>; }
function QuizList({ title = 'Prática guiada', items = [] }) {
  const [answers, setAnswers] = useState({});
  const questions = useMemo(() => safeArray(items).filter((item) => textOf(item)), [items]);
  if (!questions.length) return null;
  return <section className="static-lesson-card static-practice-card"><div className="panel-title"><ListChecks size={18} /> {title}</div><p className="static-lesson-muted">Tente responder antes de olhar o feedback. O gabarito só aparece depois da sua tentativa.</p><div className="static-question-list">{questions.map((item, index) => { const id = `${title}-${index}`; const selected = answers[id] || ''; const attempted = Boolean(selected); const expected = item.answer || item.expectedAnswer || item.correctAnswer; const correct = attempted && isCorrect(selected, expected); const seed = `${title}:${index}:${textOf(item)}:${expected}`; const options = stableShuffle(uniqueCleanOptions(item.options), seed); return <article className="static-question-card" key={id}><span>Questão {index + 1}</span><strong>{textOf(item)}</strong>{options.length ? <div className="static-option-list">{options.map((option) => { const active = selected === option; const optionCorrect = attempted && isCorrect(option, expected); const optionWrong = active && attempted && !correct; return <button type="button" key={option} className={`${active ? 'selected' : ''}${optionCorrect ? ' correct' : ''}${optionWrong ? ' incorrect' : ''}`} onClick={() => setAnswers((current) => ({ ...current, [id]: option }))}>{option}</button>; })}</div> : <textarea value={selected} onChange={(event) => setAnswers((current) => ({ ...current, [id]: event.target.value }))} placeholder="Digite sua resposta..." />}{attempted ? <div className={correct ? 'question-feedback correct' : 'question-feedback incorrect'}><strong>{correct ? <><CheckCircle2 size={15} /> Correto.</> : <><XCircle size={15} /> Revise o modelo.</>}</strong>{!correct && expected ? <p>Modelo correto: <b>{expected}</b></p> : null}{item.explanation ? <p>{item.explanation}</p> : null}</div> : <small>Escolha uma alternativa ou escreva sua tentativa.</small>}</article>; })}</div></section>;
}
function StaticGrammarLesson({ lesson }) { return <article className="static-lesson-layout static-grammar-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Explicação completa" items={lesson.explanationSections} renderItem={(item, index) => <article className="static-deep-section" key={index}><span>Parte {index + 1}</span><h3>{item.title}</h3><p>{item.content}</p></article>} /><SectionStack title="Exemplos do professor" icon={Sparkles} items={lesson.professorExamples} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{item.english || item.text}</strong>{item.translation ? <p>{item.translation}</p> : null}{item.note ? <small>{item.note}</small> : null}</article>} /><SectionStack title="Erros comuns de brasileiros" icon={XCircle} items={lesson.commonMistakes} renderItem={(item, index) => <article className="static-mistake-card" key={index}><p><b>Errado:</b> {item.wrong}</p><p><b>Certo:</b> {item.right}</p><small>{item.why}</small></article>} /><QuizList title="Exercícios internos da aula" items={lesson.guidedPractice} /><QuizList title="Transformação e correção" items={lesson.transformationPractice} /><SectionStack title="Produção própria" icon={PencilLine} items={lesson.productionTasks} renderItem={(item, index) => <article className="static-production-card" key={index}><span>Produção {index + 1}</span><strong>{textOf(item)}</strong></article>} /><SectionStack title="Checklist final" icon={CheckCircle2} items={lesson.finalChecklist} renderItem={(item, index) => <article className="static-check-card" key={index}>✓ {textOf(item)}</article>} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticVocabularyLesson({ lesson }) { const lexicalItems = safeArray(lesson.lexicalSets).flatMap((set) => safeArray(set.items).map((item) => ({ set: set.title, item }))); return <article className="static-lesson-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Grupos de vocabulário" items={lexicalItems} renderItem={(entry, index) => <article className="static-vocab-card" key={index}><span>{entry.set}</span><strong>{entry.item}</strong></article>} /><SectionStack title="Exemplos de uso" icon={Sparkles} items={lesson.examples} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{item.text || item.english || textOf(item)}</strong>{item.translation ? <p>{item.translation}</p> : null}</article>} /><QuizList title="Reconhecimento" items={lesson.recognitionPractice} /><SectionStack title="Uso e produção" icon={PencilLine} items={[...safeArray(lesson.usagePractice), ...safeArray(lesson.productionTasks)]} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticReadingLesson({ lesson }) { return <article className="static-lesson-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Antes de ler" items={lesson.preReading} renderItem={(item, index) => <article className="static-check-card" key={index}>{textOf(item)}</article>} /><section className="static-lesson-card static-main-text-card"><div className="panel-title"><BookOpenCheck size={18} /> Texto principal</div><p>{lesson.mainText}</p></section><SectionStack title="Vocabulário de apoio" items={lesson.vocabulary} renderItem={(item, index) => <article className="static-vocab-card" key={index}><strong>{item.word}</strong><span>{item.meaning}</span>{item.example ? <p>{item.example}</p> : null}</article>} /><QuizList title="Compreensão do texto" items={lesson.comprehensionQuestions} /><SectionStack title="Evidência textual" icon={Target} items={lesson.evidenceTasks} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong><small>Copie a frase do texto que prova sua resposta.</small></article>} /><SectionStack title="Resposta curta e produção" icon={PencilLine} items={[...safeArray(lesson.shortResponse), lesson.productionTask].filter(Boolean)} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticListeningLesson({ lesson }) { return <article className="static-lesson-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Primeira escuta sem texto" icon={Headphones} items={lesson.firstListenTasks} renderItem={(item, index) => <article className="static-check-card" key={index}>{textOf(item)}</article>} /><SectionStack title="Segunda escuta com foco" icon={Target} items={lesson.secondListenTasks} renderItem={(item, index) => <article className="static-check-card" key={index}>{textOf(item)}</article>} /><section className="static-lesson-card static-main-text-card"><div className="panel-title"><BookOpenCheck size={18} /> Transcript</div><p>{lesson.transcript || lesson.audioScript}</p></section><SectionStack title="Shadowing" icon={Mic} items={lesson.shadowing} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong><small>Repita em voz alta.</small></article>} /><QuizList title="Compreensão auditiva" items={lesson.comprehensionQuestions} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticSpeakingLesson({ lesson }) { return <article className="static-lesson-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Frases-modelo" icon={Mic} items={lesson.modelPhrases} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong></article>} /><SectionStack title="Substitution drills" icon={Sparkles} items={lesson.substitutionDrills} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>} />{lesson.pronunciationFocus ? <section className="static-lesson-card"><div className="panel-title"><Headphones size={18} /> Pronúncia</div><h3>{lesson.pronunciationFocus.title}</h3><ul>{safeArray(lesson.pronunciationFocus.tips).map((tip, index) => <li key={index}>{tip}</li>)}</ul></section> : null}<SectionStack title="Fala guiada" items={lesson.guidedSpeaking} renderItem={(item, index) => <article className="static-check-card" key={index}>{textOf(item)}</article>} /><SectionStack title="Gravação e fala livre" icon={Mic} items={[...safeArray(lesson.recordingTasks), ...safeArray(lesson.freeSpeaking)]} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticWritingLesson({ lesson }) { return <article className="static-lesson-layout"><ObjectiveCard lesson={lesson} /><section className="static-lesson-card static-main-text-card"><div className="panel-title"><PencilLine size={18} /> Modelo</div><p>{lesson.modelText}</p></section><SectionStack title="Blocos úteis" items={lesson.writingBlocks} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong></article>} /><SectionStack title="Substituição guiada" icon={Sparkles} items={lesson.guidedSubstitution} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>} /><SectionStack title="Gramática para escrever" items={lesson.grammarForWriting} renderItem={(item, index) => <article className="static-check-card" key={index}>{textOf(item)}</article>} /><SectionStack title="Checklist, rascunho e revisão" icon={CheckCircle2} items={[...safeArray(lesson.checklist), lesson.draftTask, lesson.revisionTask].filter(Boolean)} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>} /><LessonFooterTools lesson={lesson} /></article>; }
export function isStaticLesson(lesson) { return clean(lesson?.schemaVersion).startsWith('static-lesson-schema') || Boolean(lesson?.pillar && lesson?.status === 'ready'); }
export function StaticLessonRenderer({ lesson }) { if (lesson?.pillar === 'grammar') return <StaticGrammarLesson lesson={lesson} />; if (lesson?.pillar === 'vocabulary') return <StaticVocabularyLesson lesson={lesson} />; if (lesson?.pillar === 'reading') return <StaticReadingLesson lesson={lesson} />; if (lesson?.pillar === 'listening') return <StaticListeningLesson lesson={lesson} />; if (lesson?.pillar === 'speaking') return <StaticSpeakingLesson lesson={lesson} />; if (lesson?.pillar === 'writing') return <StaticWritingLesson lesson={lesson} />; return <><ObjectiveCard lesson={lesson} /><LessonFooterTools lesson={lesson} /></>; }
