import { useMemo, useState } from 'react';
import { BookOpenCheck, CheckCircle2, Headphones, Lightbulb, ListChecks, Map, Mic, PencilLine, Repeat, Sparkles, Target, XCircle } from 'lucide-react';
import { Card } from '../../components/ui/Card.jsx';
import { AiTutorPanel } from '../../components/tutor/AiTutorPanel.jsx';
import { SpeakExercise } from '../../practice/components/SpeakExercise.jsx';
import { StaticCompletionGate } from './StaticCompletionGate.jsx';

const TECHNICAL_KEYS = new Set(['schemaVersion', 'status', 'level', 'pillar', 'order', 'id', 'checkpoint', 'tags', 'estimatedMinutes', 'subject', 'expected', 'answer', 'expectedAnswer', 'correctAnswer', 'options']);
const TECHNICAL_WORDS = new Set(['subject', 'expected', 'answer', 'correctAnswer', 'expectedAnswer', 'schemaVersion', 'undefined', 'null', '[object Object]']);

function safeArray(value) { return Array.isArray(value) ? value : []; }
function clean(value) { return String(value ?? '').trim(); }
function isTechnicalText(value) { return TECHNICAL_WORDS.has(clean(value)); }
function hasText(value) { const text = clean(value); return text.length > 0 && !isTechnicalText(text); }
function firstUseful(...values) { return values.map(clean).find((value) => hasText(value)) || ''; }
function objectFallback(value) {
  if (!value || typeof value !== 'object') return '';
  const entry = Object.entries(value).find(([key, item]) => !TECHNICAL_KEYS.has(key) && hasText(item) && typeof item !== 'object');
  return entry ? clean(entry[1]) : '';
}
function textOf(value) {
  if (typeof value === 'string' || typeof value === 'number') return hasText(value) ? clean(value) : '';
  if (!value || typeof value !== 'object') return '';
  return firstUseful(value.instruction, value.question, value.prompt, value.text, value.content, value.chunk, value.word, value.phrase, value.example, value.pattern, value.title, value.label, objectFallback(value));
}
function noteOf(value) { if (!value || typeof value !== 'object') return ''; return firstUseful(value.note, value.why, value.explanation, value.reason, value.tip, value.translation, value.meaning, value.expectedUse); }
function expectedOf(value) { if (!value || typeof value !== 'object') return ''; return firstUseful(value.expected, value.answer, value.expectedAnswer, value.correctAnswer); }
function normalizeAnswer(value) { return clean(value).toLowerCase().replace(/[.!?]+$/g, '').replace(/\s+/g, ' '); }
function isCorrect(value, answer) { return Boolean(answer) && normalizeAnswer(value) === normalizeAnswer(answer); }
function pillarLabel(pillar) { return ({ grammar: 'Grammar', vocabulary: 'Vocabulary', reading: 'Reading', listening: 'Listening', speaking: 'Speaking', writing: 'Writing' }[pillar] || 'Aula'); }
function isDeepLesson(lesson) { return clean(lesson?.schemaVersion).startsWith('static-lesson-schema-v2'); }
function getIntro(lesson) { const firstObjective = safeArray(lesson?.objectives)[0]; return lesson?.teacherOpening || lesson?.intro || textOf(firstObjective) || 'Aula fixa premium do currículo Fluency, criada para estudar com explicação, exemplos, prática guiada e produção própria.'; }
function LessonFooterTools({ lesson }) { return <><AiTutorPanel lesson={lesson} /><StaticCompletionGate lesson={lesson} /></>; }
function uniqueCleanOptions(options = []) { const seen = new Set(); return safeArray(options).map(clean).filter(hasText).filter((option) => { const key = normalizeAnswer(option); if (!key || seen.has(key)) return false; seen.add(key); return true; }); }
function stableHash(value) { const text = String(value || ''); let hash = 2166136261; for (let index = 0; index < text.length; index += 1) { hash ^= text.charCodeAt(index); hash = Math.imul(hash, 16777619); } return hash >>> 0; }
function stableShuffle(options = [], seed = '') { const list = [...options]; if (list.length < 2) return list; for (let index = list.length - 1; index > 0; index -= 1) { const swapIndex = stableHash(`${seed}:${index}`) % (index + 1); [list[index], list[swapIndex]] = [list[swapIndex], list[index]]; } return list; }
function asList(value) { if (Array.isArray(value)) return value; if (hasText(value)) return [value]; return []; }
function hasItems(value) { return safeArray(value).length > 0; }
function wordCount(value) { return clean(value).split(/\s+/).filter(Boolean).length; }
function mergeLists(...groups) { return groups.flatMap((group) => asList(group)).filter((item) => hasText(textOf(item)) || hasText(noteOf(item)) || hasText(item?.wrong) || hasText(item?.right)); }

function ObjectiveCard({ lesson }) { return <Card eyebrow={`${pillarLabel(lesson.pillar)} fixa · ${lesson.level || 'A1'}`} title={lesson.title}><div className="static-lesson-objective-grid"><p>{getIntro(lesson)}</p><div className="lesson-objective-card"><Target size={18} /><span>Objetivos</span><ul>{safeArray(lesson.objectives).length ? safeArray(lesson.objectives).map((item, index) => <li key={`${textOf(item)}-${index}`}>{textOf(item)}</li>).filter((item) => item.props.children) : <li>Entender, praticar e produzir usando o conteúdo da aula.</li>}</ul></div></div></Card>; }
function SectionStack({ title, icon: Icon = BookOpenCheck, items = [], renderItem, empty = 'Sem itens cadastrados ainda.' }) { const list = mergeLists(items); if (!list.length && !empty) return null; return <section className="static-lesson-card"><div className="panel-title"><Icon size={18} /> {title}</div>{list.length ? <div className="static-lesson-stack">{list.map((item, index) => renderItem(item, index))}</div> : <p>{empty}</p>}</section>; }
function RevealTextCard({ title, icon: Icon = BookOpenCheck, text = '', helper = 'Tente responder as tarefas antes de revelar este conteúdo.', buttonLabel = 'Mostrar transcript' }) { const [visible, setVisible] = useState(false); if (!hasText(text)) return null; return <section className="static-lesson-card static-main-text-card static-reveal-card"><div className="panel-title"><Icon size={18} /> {title}</div>{!visible ? <><p className="static-lesson-muted">{helper}</p><button type="button" className="btn-secondary" onClick={() => setVisible(true)}>{buttonLabel}</button></> : <><p>{text}</p><button type="button" className="btn-secondary" onClick={() => setVisible(false)}>Ocultar novamente</button></>}</section>; }

function QuizList({ title = 'Prática guiada', items = [] }) {
  const [answers, setAnswers] = useState({});
  const questions = useMemo(() => mergeLists(items), [items]);
  if (!questions.length) return null;
  return <section className="static-lesson-card static-practice-card"><div className="panel-title"><ListChecks size={18} /> {title}</div><p className="static-lesson-muted">Tente responder antes de olhar o feedback. O gabarito só aparece depois da sua tentativa.</p><div className="static-question-list">{questions.map((item, index) => { const id = `${title}-${index}`; const selected = answers[id] || ''; const attempted = Boolean(clean(selected)); const expected = expectedOf(item); const correct = attempted && expected ? isCorrect(selected, expected) : false; const seed = `${title}:${index}:${textOf(item)}:${expected}`; const options = stableShuffle(uniqueCleanOptions(item.options), seed); return <article className="static-question-card" key={id}><span>Questão {index + 1}</span><strong>{textOf(item)}</strong>{item.context ? <p>{item.context}</p> : null}{options.length ? <div className="static-option-list">{options.map((option) => { const active = selected === option; const optionCorrect = attempted && expected && isCorrect(option, expected); const optionWrong = active && attempted && expected && !correct; return <button type="button" key={option} className={`${active ? 'selected' : ''}${optionCorrect ? ' correct' : ''}${optionWrong ? ' incorrect' : ''}`} onClick={() => setAnswers((current) => ({ ...current, [id]: option }))}>{option}</button>; })}</div> : <textarea value={selected} onChange={(event) => setAnswers((current) => ({ ...current, [id]: event.target.value }))} placeholder="Digite sua resposta..." />}{attempted ? <div className={correct || !expected ? 'question-feedback correct' : 'question-feedback incorrect'}><strong>{correct ? <><CheckCircle2 size={15} /> Correto.</> : expected ? <><XCircle size={15} /> Revise o modelo.</> : <><CheckCircle2 size={15} /> Tentativa registrada.</>}</strong>{expected && !correct ? <p>Modelo correto: <b>{expected}</b></p> : null}{item.explanation ? <p>{item.explanation}</p> : null}</div> : <small>Escolha uma alternativa ou escreva sua tentativa.</small>}</article>; })}</div></section>;
}
function AttemptList({ title, icon: Icon = PencilLine, items = [], helper = 'Escreva sua tentativa. O modelo só aparece depois que você responder.' }) { const [answers, setAnswers] = useState({}); const list = mergeLists(items); if (!list.length) return null; return <section className="static-lesson-card static-practice-card static-reading-practice-card"><div className="panel-title"><Icon size={18} /> {title}</div><p className="static-lesson-muted">{helper}</p><div className="static-question-list">{list.map((item, index) => { const id = `${title}-${index}`; const value = answers[id] || ''; const attempted = clean(value).length > 0; const expected = expectedOf(item); return <article className="static-question-card" key={id}><span>{title} {index + 1}</span><strong>{textOf(item)}</strong>{noteOf(item) ? <p>{noteOf(item)}</p> : null}<textarea value={value} onChange={(event) => setAnswers((current) => ({ ...current, [id]: event.target.value }))} placeholder="Digite sua resposta..." />{attempted ? <div className="question-feedback correct"><strong><CheckCircle2 size={15} /> Tentativa registrada.</strong>{expected ? <p>Modelo para comparar: <b>{expected}</b></p> : <p>Revise sua resposta antes de avançar.</p>}</div> : <small>Responda com suas palavras antes de ver qualquer modelo.</small>}</article>; })}</div></section>; }
function WritingAttemptList({ title, icon: Icon = PencilLine, items = [], helper = 'Escreva sua resposta. O modelo só aparece depois da tentativa.', placeholder = 'Escreva aqui...', minWords = 0 }) { const [answers, setAnswers] = useState({}); const list = mergeLists(items); if (!list.length) return null; return <section className="static-lesson-card static-practice-card static-writing-practice-card"><div className="panel-title"><Icon size={18} /> {title}</div><p className="static-lesson-muted">{helper}</p><div className="static-question-list">{list.map((item, index) => { const id = `${title}-${index}`; const value = answers[id] || ''; const attempted = clean(value).length > 0; const expected = expectedOf(item); const count = wordCount(value); const enough = !minWords || count >= minWords; return <article className="static-question-card static-writing-answer-card" key={id}><span>{title} {index + 1}</span><strong>{textOf(item)}</strong>{noteOf(item) ? <p>{noteOf(item)}</p> : null}<textarea value={value} rows={8} onChange={(event) => setAnswers((current) => ({ ...current, [id]: event.target.value }))} placeholder={placeholder} /><small>{count} palavras{minWords ? ` · meta mínima: ${minWords}` : ''}</small>{attempted ? <div className={enough ? 'question-feedback correct' : 'question-feedback incorrect'}><strong>{enough ? <><CheckCircle2 size={15} /> Texto registrado.</> : <><XCircle size={15} /> Desenvolva mais um pouco.</>}</strong>{expected ? <p>Modelo para comparar depois da sua versão: <b>{expected}</b></p> : <p>Revise clareza, conectores, verbos e pontuação antes de avançar.</p>}</div> : <small>Escreva primeiro. Não existe modelo visível antes da tentativa.</small>}</article>; })}</div></section>; }
function SpeakingAttemptList({ title, icon: Icon = Mic, items = [], helper = 'Fale em voz alta. Use o botão de fala quando disponível ou digite o que você falou.' }) { const [answers, setAnswers] = useState({}); const [feedback, setFeedback] = useState({}); const list = mergeLists(items); if (!list.length) return null; function startSpeech(id) { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { setFeedback((current) => ({ ...current, [id]: { message: 'Microfone automático indisponível neste navegador. Digite o que você falou no campo abaixo.' } })); return; } const recognition = new SpeechRecognition(); recognition.lang = 'en-US'; recognition.interimResults = false; recognition.maxAlternatives = 1; setFeedback((current) => ({ ...current, [id]: { message: 'Ouvindo... fale sua resposta em inglês.' } })); recognition.onresult = (event) => { const transcript = event.results?.[0]?.[0]?.transcript || ''; setAnswers((current) => ({ ...current, [id]: transcript })); setFeedback((current) => ({ ...current, [id]: { message: 'Fala capturada. Revise o texto e regrave se quiser melhorar.' } })); }; recognition.onerror = () => setFeedback((current) => ({ ...current, [id]: { message: 'Não consegui capturar o áudio. Use o campo de texto como fallback.' } })); recognition.start(); } return <section className="static-lesson-card static-practice-card static-speaking-practice-card"><div className="panel-title"><Icon size={18} /> {title}</div><p className="static-lesson-muted">{helper}</p><div className="static-question-list">{list.map((item, index) => { const id = `${title}-${index}`; const value = answers[id] || ''; const attempted = clean(value).length > 0; const currentFeedback = feedback[id]; return <article className="static-question-card" key={id}><span>Fala {index + 1}</span><strong>{textOf(item)}</strong>{noteOf(item) ? <p>{noteOf(item)}</p> : null}<SpeakExercise value={value} feedback={null} onSpeak={() => startSpeech(id)} onChange={(nextValue) => setAnswers((current) => ({ ...current, [id]: nextValue }))} />{currentFeedback ? <small>{currentFeedback.message}</small> : <small>Fale primeiro. Depois revise se sua resposta ficou clara.</small>}{attempted ? <div className="question-feedback correct"><strong><CheckCircle2 size={15} /> Resposta de fala registrada.</strong><p>Leia o que ficou no campo e veja se representa o que você quis dizer.</p></div> : null}</article>; })}</div></section>; }

function DeepHero({ lesson }) { return <Card eyebrow={`${pillarLabel(lesson.pillar)} profunda · ${lesson.level || 'A1'}`} title={lesson.title}><div className="static-lesson-objective-grid"><p>{lesson.teacherOpening || getIntro(lesson)}</p><div className="lesson-objective-card"><Target size={18} /><span>Ao final você vai conseguir</span><ul>{safeArray(lesson.objectives).length ? safeArray(lesson.objectives).map((item, index) => <li key={`${textOf(item)}-${index}`}>{textOf(item)}</li>).filter((item) => item.props.children) : <li>usar o conteúdo da aula em uma situação real.</li>}</ul></div></div></Card>; }
function DeepTextCard({ title, icon: Icon = Lightbulb, children }) { if (!children) return null; return <section className="static-lesson-card static-deep-flow-card"><div className="panel-title"><Icon size={18} /> {title}</div>{children}</section>; }
function DeepListCard({ title, icon: Icon = CheckCircle2, items = [], renderItem, empty = '' }) { const list = mergeLists(items); if (!list.length && !empty) return null; return <section className="static-lesson-card static-deep-flow-card"><div className="panel-title"><Icon size={18} /> {title}</div>{list.length ? <div className="static-lesson-stack">{list.map((item, index) => renderItem ? renderItem(item, index) : <article className="static-check-card" key={index}>{textOf(item)}</article>)}</div> : <p>{empty}</p>}</section>; }
function DeepMentalModel({ lesson }) { const model = lesson.mentalModel; if (!model) return null; const steps = safeArray(model.steps || model.flow || model.items); return <DeepTextCard title="Mapa mental da aula" icon={Map}>{hasText(model.title) ? <h3>{model.title}</h3> : null}{hasText(model.summary || model.text || model.content) ? <p>{model.summary || model.text || model.content}</p> : null}{steps.length ? <div className="static-lesson-stack">{steps.map((step, index) => <article className="static-check-card" key={index}><b>{index + 1}.</b> {textOf(step)}{noteOf(step) ? <small>{noteOf(step)}</small> : null}</article>)}</div> : null}</DeepTextCard>; }
function DeepCoreFlow({ lesson }) { return <><DeepTextCard title="Por que isso importa" icon={Sparkles}>{lesson.whyItMatters ? <p>{lesson.whyItMatters}</p> : null}{hasItems(lesson.realLifeUseCases) ? <ul>{lesson.realLifeUseCases.map((item, index) => <li key={index}>{textOf(item)}</li>).filter((item) => item.props.children)}</ul> : null}</DeepTextCard><DeepTextCard title="Conceito central" icon={BookOpenCheck}>{lesson.conceptExplanation ? <p>{lesson.conceptExplanation}</p> : null}</DeepTextCard><DeepMentalModel lesson={lesson} /><DeepListCard title="Passo a passo" icon={Target} items={lesson.stepByStep} renderItem={(item, index) => <article className="static-check-card" key={index}><b>Passo {index + 1}</b><p>{textOf(item)}</p>{noteOf(item) ? <small>{noteOf(item)}</small> : null}</article>} /><DeepListCard title="Comparação com português" icon={Repeat} items={lesson.portugueseContrast} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong>{noteOf(item) ? <p>{noteOf(item)}</p> : null}</article>} /><QuizList title="Pratique comigo antes do quiz" items={lesson.guidedBeforeQuiz || lesson.guidedDiscovery} /></>; }
function DeepExamples({ items = [], title = 'Exemplos comentados' }) { return <DeepListCard title={title} icon={Sparkles} items={items} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{firstUseful(item.english, item.text, textOf(item))}</strong>{item.translation ? <p>{item.translation}</p> : null}{item.why ? <small><b>Por que funciona:</b> {item.why}</small> : null}{item.warning ? <small><b>Cuidado:</b> {item.warning}</small> : null}{noteOf(item) && !item.why && !item.warning ? <small>{noteOf(item)}</small> : null}</article>} />; }
function DeepMistakes({ items = [], title = 'Erros comuns de brasileiros' }) { return <DeepListCard title={title} icon={XCircle} items={items} renderItem={(item, index) => <article className="static-mistake-card" key={index}><p><b>Errado:</b> {item.wrong || item.error || '—'}</p><p><b>Certo:</b> {item.right || item.correct || '—'}</p>{item.why ? <small><b>Por que acontece:</b> {item.why}</small> : null}{item.howToAvoid ? <small><b>Como evitar:</b> {item.howToAvoid}</small> : null}{item.miniPractice ? <small><b>Mini treino:</b> {textOf(item.miniPractice)}</small> : null}</article>} />; }
function DeepProduction({ items, title = 'Produção própria' }) { return <AttemptList title={title} icon={PencilLine} items={items} />; }
function DeepRecap({ lesson }) { return <section className="static-lesson-card static-deep-flow-card"><div className="panel-title"><CheckCircle2 size={18} /> Revisão final</div>{safeArray(lesson.lessonRecap).length ? <div className="static-lesson-stack">{lesson.lessonRecap.map((item, index) => <article className="static-check-card" key={index}>✓ {textOf(item)}</article>).filter((item) => item.props.children !== '✓ ')}</div> : <p>Revise o conceito, os exemplos, os erros comuns e sua produção antes de concluir.</p>}{safeArray(lesson.selfAssessment).length ? <div className="static-lesson-stack">{lesson.selfAssessment.map((item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>).filter((item) => item.props.children.props.children)}</div> : null}{lesson.nextLessonBridge ? <p className="static-lesson-muted">Próximo passo: {lesson.nextLessonBridge}</p> : null}</section>; }

function DeepGrammarLesson({ lesson }) { return <article className="static-lesson-layout static-grammar-layout static-deep-lesson-layout"><DeepHero lesson={lesson} /><DeepCoreFlow lesson={lesson} /><DeepListCard title="Objetivo gramatical" icon={Target} items={[lesson.grammarGoal]} /><DeepListCard title="Como formar" icon={BookOpenCheck} items={lesson.formationGuide} /><DeepListCard title="Quando usar" icon={CheckCircle2} items={lesson.whenToUse} /><DeepListCard title="Quando não usar" icon={XCircle} items={lesson.whenNotToUse} />{hasItems(lesson.grammarTable) ? <DeepListCard title="Tabela rápida" icon={Map} items={lesson.grammarTable} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{firstUseful(item.label, item.pattern, textOf(item))}</strong>{item.example ? <p>{item.example}</p> : null}{item.translation ? <small>{item.translation}</small> : null}{item.note ? <small>{item.note}</small> : null}</article>} /> : null}<DeepExamples items={lesson.teacherExamples || lesson.professorExamples} /><DeepMistakes items={lesson.commonBrazilianMistakes || lesson.commonMistakes} /><QuizList title="Prática controlada" items={lesson.controlledPractice} /><QuizList title="Agora tente sozinho" items={lesson.guidedPractice} /><QuizList title="Correção de erro" items={lesson.errorCorrectionPractice} /><QuizList title="Transformação" items={lesson.transformationPractice} /><QuizList title="Tradução controlada" items={lesson.translationPractice} /><DeepProduction items={lesson.productionTasks} /><DeepRecap lesson={lesson} /><LessonFooterTools lesson={lesson} /></article>; }
function DeepVocabularyLesson({ lesson }) { const words = hasItems(lesson.essentialWords) ? lesson.essentialWords : safeArray(lesson.lexicalSets).flatMap((set) => safeArray(set.items).map((item) => ({ word: item, meaning: set.title }))); return <article className="static-lesson-layout static-deep-lesson-layout static-vocabulary-layout"><DeepHero lesson={lesson} /><DeepCoreFlow lesson={lesson} /><DeepTextCard title="Contexto real" icon={Map}>{lesson.topicContext ? <p>{lesson.topicContext}</p> : null}</DeepTextCard><DeepListCard title="Palavras essenciais" icon={BookOpenCheck} items={words} renderItem={(item, index) => <article className="static-vocab-card" key={index}><strong>{firstUseful(item.word, textOf(item))}</strong>{item.meaning ? <span>{item.meaning}</span> : null}{item.example ? <p>{item.example}</p> : null}{item.note ? <small>{item.note}</small> : null}</article>} /><DeepListCard title="Chunks úteis" icon={Sparkles} items={lesson.chunks} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{firstUseful(item.chunk, item.text, textOf(item))}</strong>{item.translation ? <p>{item.translation}</p> : null}{noteOf(item) ? <small>{noteOf(item)}</small> : null}</article>} /><DeepExamples items={lesson.examples} title="Exemplos em frases" /><DeepListCard title="Mini diálogos" icon={Mic} items={lesson.miniDialogues} renderItem={(item, index) => <article className="static-main-text-card" key={index}><strong>{item.title || `Diálogo ${index + 1}`}</strong><p>{item.lines ? item.lines.join('\n') : textOf(item)}</p></article>} /><DeepListCard title="Cuidado com confusões" icon={XCircle} items={lesson.dangerousConfusions} /><DeepListCard title="Combinações naturais" icon={Sparkles} items={lesson.collocations} /><QuizList title="Reconhecimento" items={lesson.recognitionPractice} /><QuizList title="Uso em contexto" items={lesson.usagePractice} /><AttemptList title="Produção com vocabulário" items={lesson.productionTasks} helper="Use as palavras/chunks da aula em frases suas antes de comparar modelos." /><DeepRecap lesson={lesson} /><LessonFooterTools lesson={lesson} /></article>; }
function DeepReadingLesson({ lesson }) { return <article className="static-lesson-layout static-deep-lesson-layout static-reading-layout"><DeepHero lesson={lesson} /><DeepCoreFlow lesson={lesson} /><DeepTextCard title="Objetivo de leitura" icon={Target}>{lesson.readingPurpose ? <p>{lesson.readingPurpose}</p> : null}</DeepTextCard><DeepListCard title="Vocabulário antes do texto" items={lesson.preReadingVocabulary || lesson.vocabulary} renderItem={(item, index) => <article className="static-vocab-card" key={index}><strong>{firstUseful(item.word, textOf(item))}</strong>{item.meaning ? <span>{item.meaning}</span> : null}{item.example ? <p>{item.example}</p> : null}</article>} /><DeepListCard title="Estratégia de leitura" icon={Map} items={lesson.readingStrategy || lesson.preReading} /><section className="static-lesson-card static-main-text-card"><div className="panel-title"><BookOpenCheck size={18} /> Texto principal</div><p>{lesson.mainText}</p></section><AttemptList title="Primeira leitura" icon={BookOpenCheck} items={[lesson.firstReadTask].filter(Boolean)} helper="Leia o texto acima e responda sem olhar modelo. Se houver modelo, ele aparece só depois da tentativa." /><AttemptList title="Segunda leitura com foco" icon={Target} items={lesson.secondReadTasks} helper="Volte ao texto principal, procure evidência e responda com suas palavras." /><QuizList title="Perguntas com evidência" items={lesson.evidenceQuestions || lesson.comprehensionQuestions} /><DeepListCard title="Vocabulário pelo contexto" icon={Lightbulb} items={lesson.contextVocabularyTasks} /><AttemptList title="Resumo e produção" icon={PencilLine} items={[lesson.guidedSummary, lesson.connectedProduction || lesson.productionTask].filter(Boolean)} helper="Escreva sua resposta primeiro. O modelo de comparação aparece apenas depois da sua tentativa." /><DeepRecap lesson={lesson} /><LessonFooterTools lesson={lesson} /></article>; }
function DeepListeningLesson({ lesson }) { return <article className="static-lesson-layout static-deep-lesson-layout static-listening-layout"><DeepHero lesson={lesson} /><DeepCoreFlow lesson={lesson} /><DeepListCard title="Antes de ouvir" icon={Headphones} items={lesson.listeningPreparation} /><DeepListCard title="Palavras para tentar ouvir" icon={Target} items={lesson.keyWordsToHear || lesson.vocabulary} /><AttemptList title="Primeira escuta sem texto" icon={Headphones} items={lesson.firstListenTasks} helper="Ouça primeiro sem ler o transcript. Anote o que entendeu." /><AttemptList title="Segunda escuta com foco" icon={Target} items={lesson.secondListenTasks} helper="Ouça de novo procurando detalhes: lugar, horário, ação, problema ou intenção." /><QuizList title="Compreensão auditiva" items={lesson.listeningComprehension || lesson.comprehensionQuestions} /><QuizList title="Dictation" items={lesson.dictationTasks} /><DeepListCard title="Shadowing" icon={Mic} items={lesson.shadowing} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong><small>Repita em voz alta tentando imitar ritmo e clareza.</small></article>} /><RevealTextCard title="Transcript depois da escuta" icon={BookOpenCheck} text={lesson.transcript || lesson.audioScript} helper="Tente primeira escuta, segunda escuta, compreensão e dictation antes de revelar o transcript." buttonLabel="Mostrar transcript" /><SpeakingAttemptList title="Produção oral curta" items={[lesson.oralProduction].filter(Boolean)} /><DeepRecap lesson={lesson} /><LessonFooterTools lesson={lesson} /></article>; }
function DeepSpeakingLesson({ lesson }) { return <article className="static-lesson-layout static-deep-lesson-layout static-speaking-layout"><DeepHero lesson={lesson} /><DeepCoreFlow lesson={lesson} /><DeepTextCard title="Situação de fala" icon={Mic}>{lesson.speakingSituation ? <p>{lesson.speakingSituation}</p> : null}</DeepTextCard><SectionStack title="Frases-modelo" icon={Mic} items={lesson.modelPhrases} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong>{noteOf(item) ? <small>{noteOf(item)}</small> : null}</article>} /><DeepListCard title="Pronúncia e chunks" icon={Headphones} items={lesson.pronunciationChunks} /><DeepListCard title="Repita comigo" icon={Repeat} items={lesson.repeatAfterMe} /><DeepListCard title="Substitution drills" icon={Sparkles} items={lesson.substitutionDrills} /><QuizList title="Pergunta e resposta" items={lesson.questionAnswerDrills} /><SpeakingAttemptList title="Fala guiada" items={lesson.guidedSpeaking} helper="Responda em voz alta. Depois confira se o texto capturado ou digitado representa sua resposta." /><DeepListCard title="Construa sua resposta" icon={PencilLine} items={lesson.buildYourAnswer} /><SpeakingAttemptList title="Gravação guiada" items={lesson.recordingTasks} helper="Use o botão de fala para gravar/simular sua resposta. Se o iPhone bloquear, digite o que falou." /><DeepListCard title="Checklist de fala" icon={CheckCircle2} items={lesson.speakingChecklist || lesson.feedbackChecklist} /><SpeakingAttemptList title="Fala livre curta" items={lesson.freeSpeaking} helper="Faça a fala final em inglês. Registre pelo microfone ou digite o que você falou." /><DeepRecap lesson={lesson} /><LessonFooterTools lesson={lesson} /></article>; }
function DeepWritingLesson({ lesson }) { return <article className="static-lesson-layout static-deep-lesson-layout static-writing-layout"><DeepHero lesson={lesson} /><DeepCoreFlow lesson={lesson} /><section className="static-lesson-card static-main-text-card"><div className="panel-title"><PencilLine size={18} /> Modelo de texto</div><p>{lesson.modelText}</p></section><DeepListCard title="Como o modelo é construído" icon={Map} items={lesson.modelTextBreakdown || lesson.writingBlocks} /><DeepListCard title="Blocos úteis" items={lesson.writingBlocks} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong>{noteOf(item) ? <small>{noteOf(item)}</small> : null}</article>} /><DeepListCard title="Gramática para escrever" items={lesson.grammarForWriting} /><DeepListCard title="Frases úteis" icon={Sparkles} items={lesson.usefulSentences} /><DeepListCard title="Substituição guiada" icon={Repeat} items={lesson.guidedSubstitution} /><DeepMistakes title="Erros comuns na escrita" items={lesson.commonWritingMistakes || lesson.commonMistakes} /><WritingAttemptList title="Rascunho" items={[lesson.draftTask].filter(Boolean)} helper="Escreva uma primeira versão sem se preocupar com perfeição. Depois revise com o checklist." placeholder="Escreva seu rascunho aqui..." minWords={20} /><DeepListCard title="Checklist de revisão" icon={CheckCircle2} items={lesson.revisionChecklist || lesson.checklist} /><WritingAttemptList title="Versão final" items={[lesson.finalVersionTask || lesson.revisionTask].filter(Boolean)} helper="Reescreva a versão final depois de revisar. Use conectores, verbos corretos e fechamento claro." placeholder="Escreva sua versão final aqui..." minWords={30} /><DeepProduction title="Produções extras" items={lesson.productionTasks} /><DeepRecap lesson={lesson} /><LessonFooterTools lesson={lesson} /></article>; }

function StaticGrammarLesson({ lesson }) { return <article className="static-lesson-layout static-grammar-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Explicação completa" items={lesson.explanationSections} renderItem={(item, index) => <article className="static-deep-section" key={index}><span>Parte {index + 1}</span><h3>{textOf(item) || item.title}</h3><p>{item.content || noteOf(item)}</p></article>} /><SectionStack title="Exemplos do professor" icon={Sparkles} items={lesson.professorExamples} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{firstUseful(item.english, item.text, textOf(item))}</strong>{item.translation ? <p>{item.translation}</p> : null}{item.note ? <small>{item.note}</small> : null}</article>} /><SectionStack title="Erros comuns de brasileiros" icon={XCircle} items={lesson.commonMistakes} renderItem={(item, index) => <article className="static-mistake-card" key={index}><p><b>Errado:</b> {item.wrong}</p><p><b>Certo:</b> {item.right}</p><small>{item.why}</small></article>} /><QuizList title="Exercícios internos da aula" items={lesson.guidedPractice} /><QuizList title="Transformação e correção" items={lesson.transformationPractice} /><AttemptList title="Produção própria" items={lesson.productionTasks} /><SectionStack title="Checklist final" icon={CheckCircle2} items={lesson.finalChecklist} renderItem={(item, index) => <article className="static-check-card" key={index}>✓ {textOf(item)}</article>} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticVocabularyLesson({ lesson }) { const lexicalItems = safeArray(lesson.lexicalSets).flatMap((set) => safeArray(set.items).map((item) => ({ set: set.title, item }))); return <article className="static-lesson-layout static-vocabulary-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Grupos de vocabulário" items={lexicalItems} renderItem={(entry, index) => <article className="static-vocab-card" key={index}><span>{entry.set}</span><strong>{entry.item}</strong></article>} /><SectionStack title="Exemplos de uso" icon={Sparkles} items={lesson.examples} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{firstUseful(item.text, item.english, textOf(item))}</strong>{item.translation ? <p>{item.translation}</p> : null}</article>} /><QuizList title="Reconhecimento" items={lesson.recognitionPractice} /><QuizList title="Uso em contexto" items={lesson.usagePractice} /><AttemptList title="Produção com vocabulário" items={lesson.productionTasks} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticReadingLesson({ lesson }) { return <article className="static-lesson-layout static-reading-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Antes de ler" items={lesson.preReading} renderItem={(item, index) => <article className="static-check-card" key={index}>{textOf(item)}</article>} /><section className="static-lesson-card static-main-text-card"><div className="panel-title"><BookOpenCheck size={18} /> Texto principal</div><p>{lesson.mainText}</p></section><SectionStack title="Vocabulário de apoio" items={lesson.vocabulary} renderItem={(item, index) => <article className="static-vocab-card" key={index}><strong>{firstUseful(item.word, textOf(item))}</strong><span>{item.meaning}</span>{item.example ? <p>{item.example}</p> : null}</article>} /><QuizList title="Compreensão do texto" items={lesson.comprehensionQuestions} /><AttemptList title="Evidência textual" icon={Target} items={lesson.evidenceTasks} helper="Copie a frase do texto que prova sua resposta." /><AttemptList title="Resposta curta e produção" icon={PencilLine} items={[...safeArray(lesson.shortResponse), lesson.productionTask].filter(Boolean)} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticListeningLesson({ lesson }) { return <article className="static-lesson-layout static-listening-layout"><ObjectiveCard lesson={lesson} /><AttemptList title="Primeira escuta sem texto" icon={Headphones} items={lesson.firstListenTasks} helper="Ouça primeiro sem transcript. Anote a ideia geral." /><AttemptList title="Segunda escuta com foco" icon={Target} items={lesson.secondListenTasks} helper="Ouça novamente para detalhes importantes." /><QuizList title="Compreensão auditiva" items={lesson.comprehensionQuestions || lesson.listeningComprehension} /><QuizList title="Dictation" items={lesson.dictationTasks} /><SectionStack title="Shadowing" icon={Mic} items={lesson.shadowing} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong><small>Repita em voz alta.</small></article>} /><RevealTextCard title="Transcript depois da escuta" icon={BookOpenCheck} text={lesson.transcript || lesson.audioScript} helper="Faça as tentativas e só depois revele o transcript para conferir." buttonLabel="Mostrar transcript" /><LessonFooterTools lesson={lesson} /></article>; }
function StaticSpeakingLesson({ lesson }) { return <article className="static-lesson-layout static-speaking-layout"><ObjectiveCard lesson={lesson} /><SectionStack title="Frases-modelo" icon={Mic} items={lesson.modelPhrases} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong></article>} /><SectionStack title="Substitution drills" icon={Sparkles} items={lesson.substitutionDrills} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>} />{lesson.pronunciationFocus ? <section className="static-lesson-card"><div className="panel-title"><Headphones size={18} /> Pronúncia</div><h3>{lesson.pronunciationFocus.title}</h3><ul>{safeArray(lesson.pronunciationFocus.tips).map((tip, index) => <li key={index}>{tip}</li>)}</ul></section> : null}<SpeakingAttemptList title="Fala guiada" items={lesson.guidedSpeaking} /><SpeakingAttemptList title="Gravação e fala livre" items={[...safeArray(lesson.recordingTasks), ...safeArray(lesson.freeSpeaking)]} /><LessonFooterTools lesson={lesson} /></article>; }
function StaticWritingLesson({ lesson }) { return <article className="static-lesson-layout static-writing-layout"><ObjectiveCard lesson={lesson} /><section className="static-lesson-card static-main-text-card"><div className="panel-title"><PencilLine size={18} /> Modelo</div><p>{lesson.modelText}</p></section><SectionStack title="Blocos úteis" items={lesson.writingBlocks} renderItem={(item, index) => <article className="static-example-card" key={index}><strong>{textOf(item)}</strong></article>} /><SectionStack title="Substituição guiada" icon={Sparkles} items={lesson.guidedSubstitution} renderItem={(item, index) => <article className="static-production-card" key={index}><strong>{textOf(item)}</strong></article>} /><SectionStack title="Gramática para escrever" items={lesson.grammarForWriting} renderItem={(item, index) => <article className="static-check-card" key={index}>{textOf(item)}</article>} /><WritingAttemptList title="Rascunho" icon={PencilLine} items={[lesson.draftTask].filter(Boolean)} placeholder="Escreva seu rascunho aqui..." minWords={15} /><SectionStack title="Checklist de revisão" icon={CheckCircle2} items={lesson.checklist || lesson.revisionChecklist} renderItem={(item, index) => <article className="static-check-card" key={index}>✓ {textOf(item)}</article>} /><WritingAttemptList title="Versão final" icon={CheckCircle2} items={[lesson.revisionTask || lesson.finalVersionTask || lesson.productionTask].filter(Boolean)} placeholder="Escreva sua versão final aqui..." minWords={25} /><LessonFooterTools lesson={lesson} /></article>; }
export function isStaticLesson(lesson) { return clean(lesson?.schemaVersion).startsWith('static-lesson-schema') || Boolean(lesson?.pillar && lesson?.status === 'ready'); }
export function StaticLessonRenderer({ lesson }) { if (isDeepLesson(lesson) && lesson?.pillar === 'grammar') return <DeepGrammarLesson lesson={lesson} />; if (isDeepLesson(lesson) && lesson?.pillar === 'vocabulary') return <DeepVocabularyLesson lesson={lesson} />; if (isDeepLesson(lesson) && lesson?.pillar === 'reading') return <DeepReadingLesson lesson={lesson} />; if (isDeepLesson(lesson) && lesson?.pillar === 'listening') return <DeepListeningLesson lesson={lesson} />; if (isDeepLesson(lesson) && lesson?.pillar === 'speaking') return <DeepSpeakingLesson lesson={lesson} />; if (isDeepLesson(lesson) && lesson?.pillar === 'writing') return <DeepWritingLesson lesson={lesson} />; if (lesson?.pillar === 'grammar') return <StaticGrammarLesson lesson={lesson} />; if (lesson?.pillar === 'vocabulary') return <StaticVocabularyLesson lesson={lesson} />; if (lesson?.pillar === 'reading') return <StaticReadingLesson lesson={lesson} />; if (lesson?.pillar === 'listening') return <StaticListeningLesson lesson={lesson} />; if (lesson?.pillar === 'speaking') return <StaticSpeakingLesson lesson={lesson} />; if (lesson?.pillar === 'writing') return <StaticWritingLesson lesson={lesson} />; return <><ObjectiveCard lesson={lesson} /><LessonFooterTools lesson={lesson} /></>; }
