import { createReadingLesson } from '../../../schemas/index.js';

const level = 'A1';
const status = 'ready';

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function q(question, answer, evidence = '', explanation = '', options = []) { return { question, answer, evidence, explanation, options }; }

function makeReadingLesson(input) {
  return createReadingLesson({
    level,
    status,
    estimatedMinutes: 55,
    ...input,
    masteryCriteria: { minPracticeAccuracy: 80, requiredProduction: 1, tags: ['a1-reading', input.id, 'deep-approved-target'] },
  });
}

export const A1_DEEP_READING_FOUNDATIONS = Object.freeze([
  makeReadingLesson({
    id: 'A1-READING-001',
    order: 1,
    title: 'Short introductions',
    tags: ['a1', 'reading', 'gist', 'self-introduction', 'personal-profile', 'beginner-comprehension'],
    objectives: ['Ler apresentações curtas sem traduzir palavra por palavra.', 'Identificar nome, país, cidade, idade e ocupação.', 'Encontrar evidência no texto antes de responder.', 'Produzir uma introdução curta seguindo o modelo.'],
    teacherOpening: 'Reading no A1 não é tentar entender todas as palavras de um texto. A primeira habilidade real é saber procurar informações importantes. Em uma apresentação curta, o texto normalmente responde perguntas simples: quem é a pessoa, de onde ela é, quantos anos ela tem, onde ela mora e o que ela faz. Nesta aula, você vai aprender a ler com uma estratégia: primeiro entender o assunto geral, depois procurar detalhes com evidência no próprio texto. Isso evita o erro de traduzir palavra por palavra e se perder.',
    whyItMatters: 'Apresentações curtas aparecem em perfis, mensagens, cadastros, aulas e aplicativos. Se você domina esse tipo de texto, já consegue entender muita coisa real em inglês básico. A lógica é reconhecer blocos que você já estudou em Grammar e Vocabulary: My name is, I am from, I am years old, I am a student. Reading junta tudo e treina seu cérebro a encontrar sentido dentro de um texto, não só em frases isoladas.',
    realLifeUseCases: ['Ler perfil simples de estudante.', 'Entender apresentação em app ou curso.', 'Identificar país e cidade em uma bio.', 'Responder perguntas com base em evidência.', 'Criar sua própria introdução.'],
    conceptExplanation: 'Uma short introduction é um texto curto em que uma pessoa se apresenta. No A1, ela geralmente usa verb to be, subject pronouns, possessive adjectives e vocabulário pessoal. A estratégia é ler em duas passagens. Na primeira, você não para em cada palavra; procura a ideia geral: é uma pessoa se apresentando? Na segunda, você procura detalhes específicos: nome, idade, cidade, país, profissão ou estudo. A resposta precisa vir do texto. Se a pergunta é “Where is Ana from?”, você deve achar uma frase como “I am from Brazil” ou “Ana is from Brazil”.',
    mentalModel: { title: 'Geral → detalhes → evidência', summary: 'Primeiro descubra sobre o que é o texto. Depois procure informação específica e copie a evidência mentalmente.', steps: ['Leia o título e primeiras frases.', 'Identifique quem fala.', 'Procure blocos conhecidos: my name, from, years old.', 'Responda usando a frase do texto como prova.'] },
    stepByStep: [task('Leia uma vez sem parar.', 'Objetivo: entender a situação geral.'), task('Marque mentalmente nomes próprios.', 'Nomes geralmente começam com letra maiúscula.'), task('Procure country/city/age/student.', 'Essas palavras indicam dados pessoais.'), task('Leia a pergunta e volte ao texto.', 'Não responda por memória se puder confirmar.'), task('Encontre a frase de evidência.', 'A resposta precisa estar no texto.'), task('Produza um texto parecido usando seu próprio dado.')],
    portugueseContrast: [task('Em português você talvez leia procurando tradução completa. Em inglês A1, primeiro procure blocos conhecidos.'), task('Português pode esconder sujeito; inglês mostra sujeito. Isso ajuda na leitura: I, she, he, they indicam quem faz parte do texto.'), task('Cognatos e nomes próprios ajudam, mas não bastam. Sempre confirme pela frase.'), task('Não chute por conhecimento externo. Reading cobra o que o texto diz.')],
    guidedDiscovery: [task('Antes de ler, olhe para palavras com letra maiúscula. Elas podem ser nomes, cidades ou países.'), task('Se aparecer “I am from Brazil”, qual detalhe você encontrou?', 'Origem/país.'), task('Se aparecer “I am 20 years old”, qual detalhe você encontrou?', 'Idade.')],
    guidedBeforeQuiz: [task('Pergunta: What is her name? Procure My name is... ou Her name is...'), task('Pergunta: Where is he from? Procure from + country.'), task('Pergunta: How old is she? Procure number + years old.'), task('Pergunta: What does she do? Procure student, teacher ou profissão/papel.')],
    readingPurpose: 'Aprender a ler apresentações curtas procurando informações pessoais e evidência textual.',
    preReadingVocabulary: [vocab('name','nome','My name is Ana.'), vocab('from','de/origem','I am from Brazil.'), vocab('city','cidade','My city is Recife.'), vocab('country','país','My country is Brazil.'), vocab('years old','anos de idade','I am 20 years old.'), vocab('student','estudante','I am a student.'), vocab('teacher','professor/professora','She is a teacher.'), vocab('friend','amigo/amiga','He is my friend.')],
    readingStrategy: [task('Não traduza tudo na primeira leitura.', 'Procure a ideia geral.'), task('Circule mentalmente nomes e lugares.', 'Ana, Brazil, Recife.'), task('Use palavras-chave para detalhes.', 'name, from, years old, student.'), task('Responda sempre com evidência.', 'A frase do texto precisa apoiar sua resposta.')],
    mainText: `Hi! My name is Ana. I am 19 years old. I am from Brazil, and my city is Recife. I am a student. My English class is online. I have a friend in my class. His name is Luis. He is from Brazil too. He is 20 years old. We are students, and we are ready to study English together.`,
    firstReadTask: task('Leia o texto uma vez e escolha a ideia geral.', 'O texto apresenta Ana e Luis com informações pessoais.', 'Duas pessoas se apresentam como estudantes.'),
    secondReadTasks: [task('Encontre o nome da primeira pessoa.', 'A evidência é “My name is Ana”.', 'Ana'), task('Encontre a idade de Ana.', 'A evidência é “I am 19 years old”.', '19'), task('Encontre a cidade de Ana.', 'A evidência é “my city is Recife”.', 'Recife'), task('Encontre a idade de Luis.', 'A evidência é “He is 20 years old”.', '20')],
    evidenceQuestions: [q('What is her name?', 'Ana', 'My name is Ana.', 'A frase diz diretamente o nome.', ['Ana','Luis','Carla']), q('How old is Ana?', '19 years old', 'I am 19 years old.', 'A idade está na segunda frase.', ['19 years old','20 years old','18 years old']), q('Where is Ana from?', 'Brazil', 'I am from Brazil.', 'From indica origem.', ['Brazil','Canada','Argentina']), q('What is Ana\'s city?', 'Recife', 'my city is Recife.', 'City indica cidade.', ['Recife','São Paulo','Curitiba']), q('What does Ana do?', 'She is a student.', 'I am a student.', 'Student mostra o papel dela.', ['She is a student.','She is a teacher.','She is a doctor.']), q('Who is Luis?', 'Ana\'s friend', 'I have a friend in my class. His name is Luis.', 'A frase conecta Luis à classe de Ana.', ['Ana\'s friend','Ana\'s teacher','Ana\'s father']), q('How old is Luis?', '20 years old', 'He is 20 years old.', 'He retoma Luis.', ['20 years old','19 years old','21 years old']), q('Are Ana and Luis students?', 'Yes, they are.', 'We are students.', 'We se refere a Ana e Luis.', ['Yes, they are.','No, they are not.','Only Ana is.'])],
    contextVocabularyTasks: [task('No texto, “from” ajuda a encontrar origem.', 'I am from Brazil.'), task('No texto, “city” ajuda a encontrar cidade.', 'my city is Recife.'), task('No texto, “too” mostra que Luis também é do Brasil.', 'He is from Brazil too.')],
    guidedSummary: task('Complete o resumo: Ana is ___ years old. She is from ___. Luis is her ___. They are ___.', 'Use apenas informações do texto.', 'Ana is 19 years old. She is from Brazil. Luis is her friend. They are students.'),
    connectedProduction: task('Escreva uma apresentação curta com 5 frases usando: My name is, I am from, my city is, I am ... years old, I am a student.', 'Use o texto como modelo, mas troque pelos seus dados.'),
    selfAssessment: [task('Consigo achar nome no texto?'), task('Consigo achar idade com years old?'), task('Consigo responder usando evidência?'), task('Consigo escrever uma introdução parecida?')],
    lessonRecap: ['Reading A1 começa com ideia geral.', 'Depois você procura detalhes.', 'Perguntas precisam de evidência textual.', 'Introductions usam name, from, city, years old e student.', 'Você não precisa traduzir cada palavra para entender o essencial.'],
    nextLessonBridge: 'Na próxima Reading, você vai ler um perfil simples com mais informações organizadas em parágrafos curtos.',
  }),

  makeReadingLesson({
    id: 'A1-READING-002',
    order: 2,
    title: 'A simple profile',
    tags: ['a1', 'reading', 'profile', 'scanning', 'personal-information', 'beginner-comprehension'],
    objectives: ['Ler um perfil simples em inglês.', 'Separar informações pessoais, país, rotina e preferências.', 'Usar evidência para responder perguntas.', 'Criar um perfil curto seguindo o modelo.'],
    teacherOpening: 'Um perfil simples é diferente de uma apresentação de duas ou três frases. Ele organiza informações em pequenos blocos: nome, idade, origem, estudo, rotina e preferências. A habilidade de leitura aqui é perceber a organização do texto. Você não precisa entender tudo de uma vez. Primeiro veja quem é a pessoa. Depois procure cada tipo de informação. Nesta aula, você vai ler como alguém vê um perfil real: procurando dados úteis, não traduzindo palavra por palavra.',
    whyItMatters: 'Perfis aparecem em redes sociais, plataformas de estudo, cadastros, apps e atividades de sala. Eles conectam Vocabulary Foundations com Reading: nome, idade, país, cidade, família e rotina aparecem juntos. O erro comum é responder pelo que parece provável, não pelo que o texto diz. Aqui você vai treinar a voltar ao texto e justificar cada resposta com evidência.',
    realLifeUseCases: ['Ler perfil de colega de turma.', 'Entender bio curta em app.', 'Identificar informações em cadastro.', 'Separar rotina e preferência.', 'Escrever seu próprio perfil A1.'],
    conceptExplanation: 'Um simple profile normalmente tem informações agrupadas. Em A1, você pode procurar marcadores: My name is para nome, I am from para país, I live in para cidade, I study para estudo, I like para preferência. Ler perfil é como preencher uma ficha mental. A primeira leitura responde: quem é essa pessoa? A segunda leitura responde: quais detalhes aparecem? Para cada pergunta, encontre uma frase que prove sua resposta. Essa é a diferença entre entender de verdade e só adivinhar.',
    mentalModel: { title: 'Perfil = ficha em forma de texto', summary: 'Leia como se estivesse preenchendo campos: nome, idade, país, cidade, estudo, preferência.', steps: ['Quem é?', 'De onde é?', 'Onde mora?', 'O que faz?', 'Do que gosta?'] },
    stepByStep: [task('Leia o perfil inteiro rapidamente.', 'Procure quem é a pessoa.'), task('Identifique blocos de informação.', 'name, age, country, city, study, like.'), task('Leia uma pergunta por vez.', 'Não tente memorizar tudo.'), task('Volte ao trecho certo.', 'Use palavras-chave.'), task('Copie a evidência mentalmente.', 'A evidência valida a resposta.'), task('Use o modelo para escrever seu perfil.')],
    portugueseContrast: [task('Em português você pode dizer “moro em”; em inglês A1 aparece “I live in”.'), task('“I like English” não significa “eu sou como inglês”; like aqui é gostar.'), task('Perfil em inglês usa frases curtas e repetição de sujeito. Isso é normal no A1.'), task('Não confunda country com city: Brazil é país; Curitiba é cidade.')],
    guidedDiscovery: [task('Qual expressão mostra cidade?', 'I live in...'), task('Qual expressão mostra preferência?', 'I like...'), task('Qual expressão mostra estudo?', 'I study...')],
    guidedBeforeQuiz: [task('Para nome, procure My name is.'), task('Para cidade, procure I live in.'), task('Para preferência, procure I like.'), task('Para rotina/estudo, procure I study ou every day.')],
    readingPurpose: 'Ler um perfil A1 e separar informações pessoais, localização, estudo e preferência.',
    preReadingVocabulary: [vocab('profile','perfil','This is my profile.'), vocab('live in','morar em','I live in Curitiba.'), vocab('study','estudar','I study English.'), vocab('like','gostar de','I like music.'), vocab('every day','todos os dias','I study every day.'), vocab('small','pequeno/pequena','My family is small.'), vocab('big','grande','My city is big.'), vocab('online','online','My class is online.')],
    readingStrategy: [task('Leia como uma ficha.', 'Procure campos de informação.'), task('Use palavras-chave.', 'live, study, like, from.'), task('Separe fato de preferência.', 'I live in é fato; I like é preferência.'), task('Toda resposta deve apontar para uma frase.')],
    mainText: `My name is Bruno. I am 21 years old. I am from Brazil, and I live in Curitiba. I am a student. I study English online every day. My family is small: my mother, my father, and my sister. I like music and coffee. My friend Ana is in my English class. She is from Recife. We are ready to learn together.`,
    firstReadTask: task('Leia uma vez e diga que tipo de texto é.', 'É um perfil simples de Bruno.', 'A simple profile.'),
    secondReadTasks: [task('Encontre onde Bruno mora.', 'I live in Curitiba.', 'Curitiba'), task('Encontre o que Bruno estuda.', 'I study English online every day.', 'English'), task('Encontre duas coisas que Bruno gosta.', 'I like music and coffee.', 'music and coffee'), task('Encontre quem está na aula de inglês dele.', 'My friend Ana is in my English class.', 'Ana')],
    evidenceQuestions: [q('What is his name?', 'Bruno', 'My name is Bruno.', 'O nome aparece na primeira frase.', ['Bruno','Luis','Carla']), q('How old is Bruno?', '21 years old', 'I am 21 years old.', 'A idade aparece com years old.', ['21 years old','19 years old','20 years old']), q('Where does Bruno live?', 'Curitiba', 'I live in Curitiba.', 'Live in indica cidade onde mora.', ['Curitiba','Recife','São Paulo']), q('What does Bruno study?', 'English', 'I study English online every day.', 'Study indica o que ele estuda.', ['English','homework','sports']), q('Is his family big or small?', 'small', 'My family is small', 'O texto diz diretamente small.', ['small','big','medium']), q('Who is in his family?', 'mother, father, and sister', 'my mother, my father, and my sister', 'A lista aparece depois de family is small.', ['mother, father, and sister','brother and cousin','two brothers']), q('What does Bruno like?', 'music and coffee', 'I like music and coffee.', 'Like indica preferência.', ['music and coffee','English and Curitiba','family and study']), q('Where is Ana from?', 'Recife', 'She is from Recife.', 'She retoma Ana.', ['Recife','Curitiba','São Paulo'])],
    contextVocabularyTasks: [task('No texto, “live in” significa morar em.', 'I live in Curitiba.'), task('No texto, “like” mostra preferência.', 'I like music and coffee.'), task('No texto, “together” mostra que Bruno e Ana aprendem juntos.', 'We are ready to learn together.')],
    guidedSummary: task('Complete: Bruno is ___. He lives in ___. He studies ___. His family is ___. He likes ___.', 'Use evidência do texto.', 'Bruno is 21. He lives in Curitiba. He studies English. His family is small. He likes music and coffee.'),
    connectedProduction: task('Escreva um perfil simples com 6 frases: nome, idade, país, cidade, estudo e uma coisa de que você gosta.', 'Siga o modelo de Bruno.'),
    selfAssessment: [task('Consigo separar país e cidade?'), task('Consigo achar preferência com like?'), task('Consigo achar rotina com every day?'), task('Consigo resumir o perfil em 5 frases?')],
    lessonRecap: ['Um perfil organiza dados pessoais.', 'Use palavras-chave para encontrar informação.', 'Live in mostra cidade onde mora.', 'Like mostra preferência.', 'Responder Reading exige evidência do texto.'],
    nextLessonBridge: 'Na próxima aula, você vai ler uma descrição de família e usar my, his, her, parents, brother e sister com evidência textual.',
  }),

  makeReadingLesson({
    id: 'A1-READING-003',
    order: 3,
    title: 'A family description',
    tags: ['a1', 'reading', 'family', 'description', 'he-she-pronouns', 'beginner-comprehension'],
    objectives: ['Ler uma descrição simples de família.', 'Identificar relações familiares no texto.', 'Entender his/her/my em contexto.', 'Responder perguntas com evidência textual.'],
    teacherOpening: 'Descrições de família são ótimas para Reading A1 porque juntam vocabulário de família, possessives e verb to be. O desafio não é só saber que mother significa mãe. O desafio é entender de quem é a mãe, o irmão ou a irmã. Em inglês, palavras como my, his e her carregam essa relação. Nesta aula, você vai ler procurando relações: quem pertence a qual família, quem é estudante, quem é professor e onde as pessoas estão.',
    whyItMatters: 'Família aparece em apresentações, perfis, conversas e textos básicos. Se você entende relações familiares em inglês, consegue ler descrições pessoais mais completas. Brasileiros erram quando ignoram his/her ou quando confundem parents com parentes. Parents significa pais, não parentes em geral. A leitura vai treinar você a ver cada possessive como uma pista de relação.',
    realLifeUseCases: ['Ler descrição de família em aula.', 'Entender perfil pessoal.', 'Identificar relações em texto curto.', 'Responder sobre família com evidência.', 'Escrever sobre sua própria família.'],
    conceptExplanation: 'Uma family description apresenta pessoas e relações. A estratégia é mapear personagens. Primeiro identifique a pessoa principal. Depois marque cada familiar: mother, father, sister, brother, parents. Em seguida observe possessives: my fala da família de quem narra; his fala de um homem/menino; her fala de uma mulher/menina. Parents é plural e normalmente usa are. Mother, father, brother e sister são singulares e normalmente usam is. Essa leitura reforça Grammar e Vocabulary ao mesmo tempo.',
    mentalModel: { title: 'Pessoa principal → relação → informação', summary: 'Monte um pequeno mapa: quem é a pessoa, qual familiar aparece e o que o texto diz sobre ele/ela.', steps: ['Identifique quem narra.', 'Liste familiares.', 'Observe my/his/her.', 'Use is/are para perceber singular/plural.', 'Confirme respostas com evidência.'] },
    stepByStep: [task('Leia procurando nomes e family words.'), task('Marque my, his e her.', 'Eles dizem de quem é a relação.'), task('Separe singular e plural.', 'Mother is; parents are.'), task('Faça um mapa simples da família.'), task('Volte ao texto para cada pergunta.'), task('Escreva sua própria descrição com o mesmo padrão.')],
    portugueseContrast: [task('Parents não significa parentes. Significa pais.'), task('Relatives seria parentes em geral, mas não é foco desta aula.'), task('His/her dependem da pessoa relacionada, não da palavra mãe/pai.'), task('Português pode usar “dela/dele” depois; inglês coloca her/his antes do substantivo: her brother, his mother.')],
    guidedDiscovery: [task('Em “My parents are here”, por que are?', 'Parents é plural.'), task('Em “Her brother is a student”, her fala de quem?', 'Da mulher/menina relacionada.'), task('Em “His mother is a teacher”, mother é singular ou plural?', 'Singular.')],
    guidedBeforeQuiz: [task('Para descobrir quem são os pais, procure parents.'), task('Para irmão, procure brother.'), task('Para irmã, procure sister.'), task('Para saber de quem é, leia my/his/her antes da palavra de família.')],
    readingPurpose: 'Ler uma descrição de família e mapear relações com evidência textual.',
    preReadingVocabulary: [vocab('family','família','My family is small.'), vocab('mother','mãe','My mother is Ana.'), vocab('father','pai','My father is Carlos.'), vocab('parents','pais','My parents are here.'), vocab('brother','irmão','Her brother is a student.'), vocab('sister','irmã','His sister is a teacher.'), vocab('teacher','professor/professora','My mother is a teacher.'), vocab('doctor','médico/médica','Her father is a doctor.')],
    readingStrategy: [task('Leia para montar um mapa familiar.', 'Pessoa principal no centro.'), task('Procure family words.', 'mother, father, parents, sister, brother.'), task('Use my/his/her como setas de relação.'), task('Confirme singular/plural com is/are.')],
    mainText: `My name is Carla. My family is small. My mother is Ana, and my father is Roberto. My mother is a teacher. My father is a doctor. I have one brother. His name is Pedro. He is 16 years old, and he is a student. My grandmother is Maria. She is from Brazil, and she is very kind. We are a happy family.`,
    firstReadTask: task('Leia uma vez e identifique o tema geral.', 'O texto descreve a família de Carla.', "Carla's family."),
    secondReadTasks: [task('Encontre o nome da mãe de Carla.', 'My mother is Ana.', 'Ana'), task('Encontre a profissão do pai.', 'My father is a doctor.', 'doctor'), task('Encontre o nome do irmão.', 'His name is Pedro.', 'Pedro'), task('Encontre quem é Maria.', 'My grandmother is Maria.', 'grandmother')],
    evidenceQuestions: [q('What is her name?', 'Carla', 'My name is Carla.', 'A narradora se apresenta.', ['Carla','Ana','Maria']), q('Is her family big or small?', 'small', 'My family is small.', 'O texto diz small.', ['small','big','online']), q("What is her mother's name?", 'Ana', 'My mother is Ana.', 'Mother indica mãe.', ['Ana','Maria','Carla']), q('What does her mother do?', 'She is a teacher.', 'My mother is a teacher.', 'Teacher indica profissão.', ['She is a teacher.','She is a doctor.','She is a student.']), q("What is her father's name?", 'Roberto', 'my father is Roberto.', 'Father indica pai.', ['Roberto','Pedro','Luis']), q('What does her father do?', 'He is a doctor.', 'My father is a doctor.', 'Doctor indica profissão.', ['He is a doctor.','He is a teacher.','He is 16.']), q('Who is Pedro?', 'Her brother', 'I have one brother. His name is Pedro.', 'Brother identifica Pedro.', ['Her brother','Her father','Her teacher']), q('Who is Maria?', 'Her grandmother', 'My grandmother is Maria.', 'Grandmother identifica Maria.', ['Her grandmother','Her sister','Her mother'])],
    contextVocabularyTasks: [task('No texto, “parents” não aparece, mas mother + father formam os pais.', 'My mother... my father...'), task('No texto, “His name is Pedro” usa his porque fala do brother.', 'His retoma o irmão.'), task('No texto, “She is very kind” usa she para grandmother Maria.', 'She retoma Maria.')],
    guidedSummary: task("Complete: Carla's family is ___. Her mother is ___ and her father is ___. Pedro is her ___. Maria is her ___.", 'Use o texto como evidência.', "Carla's family is small. Her mother is Ana and her father is Roberto. Pedro is her brother. Maria is her grandmother."),
    connectedProduction: task('Escreva 6 frases sobre sua família ou uma família fictícia usando mother, father, brother/sister, grandmother e is/are.', 'Use my, his ou her corretamente.'),
    selfAssessment: [task('Consigo diferenciar parents e parentes?'), task('Consigo seguir my/his/her no texto?'), task('Consigo montar mapa familiar?'), task('Consigo responder com evidência?')],
    lessonRecap: ['Family description exige mapear relações.', 'My/his/her mostram de quem é a relação.', 'Mother/father/brother/sister usam is quando singulares.', 'Parents é pais e é plural.', 'Toda resposta deve apontar para uma frase do texto.'],
    nextLessonBridge: 'Reading Foundations agora prepara o aluno para textos de rotina e situações práticas nas próximas unidades A1.',
  }),
]);

export const A1_DEEP_READING_BY_PILLAR = Object.freeze({
  reading: A1_DEEP_READING_FOUNDATIONS,
});
