import { createGrammarLesson } from '../../../schemas/index.js';

const level = 'A1';
const status = 'ready';
function q(question, options, answer, explanation = '', context = '') { return { question, options, answer, explanation, context }; }
function ex(english, translation, why, warning = '') { return { english, translation, why, warning }; }
function mistake(wrong, right, why, howToAvoid, miniPractice = '') { return { wrong, right, why, howToAvoid, miniPractice }; }
function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function step(text, note = '') { return { text, note }; }

function commonToBeExamples(kind) {
  const affirmative = kind === 'affirmative';
  const negative = kind === 'negative';
  const questions = kind === 'questions';
  const shortAnswers = kind === 'shortAnswers';
  if (affirmative) return [
    ex('I am a student.', 'Eu sou estudante.', 'I combina com am. A frase liga o sujeito I à informação a student.', 'Não diga “I is”.'),
    ex('You are ready.', 'Você está pronto.', 'You combina com are, mesmo quando significa você no singular.', 'Não diga “you is”.'),
    ex('He is my brother.', 'Ele é meu irmão.', 'He é terceira pessoa singular; por isso usamos is.', 'Não use are com he.'),
    ex('She is from Brazil.', 'Ela é do Brasil.', 'She pede is e a informação depois mostra origem.', 'Não traduza como “She has from Brazil”.'),
    ex('It is my phone.', 'É meu celular.', 'It funciona como sujeito para coisa/objeto.', 'Não comece direto com is.'),
    ex('We are friends.', 'Nós somos amigos.', 'We é plural/inclui o falante, então usa are.', 'Não diga “we is”.'),
    ex('They are teachers.', 'Eles são professores.', 'They representa grupo e combina com are.', 'Não diga “they is”.'),
    ex('My name is Ana.', 'Meu nome é Ana.', 'My name é o sujeito; por ser singular, usa is.', 'Não diga “my name are”.'),
    ex('My parents are here.', 'Meus pais estão aqui.', 'Parents é plural, então usa are.', 'Não use is com plural.'),
    ex('This book is new.', 'Este livro é novo.', 'This book é singular, então is.', 'Não use are só porque a frase parece descritiva.'),
    ex('The books are new.', 'Os livros são novos.', 'The books é plural, então are.', 'Não use is com books.'),
    ex('Brazil is big.', 'O Brasil é grande.', 'Brazil é um país singular, então is.', 'País/lugar no singular usa is.'),
  ];
  if (negative) return [
    ex('I am not tired.', 'Eu não estou cansado.', 'A negação com to be coloca not depois de am.', 'Não diga “I not am”.'),
    ex('You are not late.', 'Você não está atrasado.', 'Not vem depois de are.', 'Não use don’t com to be neste padrão.'),
    ex('He is not my teacher.', 'Ele não é meu professor.', 'Not vem depois de is e antes da informação.', 'Não diga “He not is”.'),
    ex('She is not from Canada.', 'Ela não é do Canadá.', 'A ordem é she + is + not + informação.', 'Não coloque not antes de is.'),
    ex('It is not my phone.', 'Não é meu celular.', 'It é o sujeito e not nega a ligação feita por is.', 'Não comece com “Is not my phone” no A1 afirmativo/negativo.'),
    ex('We are not ready.', 'Nós não estamos prontos.', 'We combina com are; not vem depois.', 'Não diga “we not are”.'),
    ex('They are not students.', 'Eles não são estudantes.', 'They + are + not forma a negativa.', 'Não diga “they is not”.'),
    ex('My name is not Lucas.', 'Meu nome não é Lucas.', 'My name é singular, então is not.', 'Não use are not.'),
    ex('My parents are not here.', 'Meus pais não estão aqui.', 'Parents é plural, então are not.', 'Não use is not com plural.'),
    ex('The book is not blue.', 'O livro não é azul.', 'Book é singular; is not nega a descrição.', 'Não confunda com do not.'),
    ex('The books are not old.', 'Os livros não são velhos.', 'Books é plural; are not nega a descrição.', 'Não use is not.'),
    ex('Brazil is not small.', 'O Brasil não é pequeno.', 'País singular usa is not.', 'Não use are not com Brazil.'),
  ];
  if (questions) return [
    ex('Are you ready?', 'Você está pronto?', 'Em perguntas com to be, are vai antes de you.', 'Não diga “Do you are ready?”.'),
    ex('Is he your brother?', 'Ele é seu irmão?', 'Is vem antes de he porque é pergunta com to be.', 'Não mantenha “He is your brother?” como padrão principal.'),
    ex('Is she from Brazil?', 'Ela é do Brasil?', 'She combina com is, e is abre a pergunta.', 'Não use are com she.'),
    ex('Is it your phone?', 'É seu celular?', 'It representa o objeto, e is começa a pergunta.', 'Não comece com “Do it is”.'),
    ex('Are we late?', 'Estamos atrasados?', 'We combina com are; na pergunta, are vem primeiro.', 'Não use is we.'),
    ex('Are they students?', 'Eles são estudantes?', 'They combina com are, então are abre a pergunta.', 'Não use is they.'),
    ex('Am I late?', 'Eu estou atrasado?', 'Com I, a pergunta começa com am.', 'É menos frequente, mas correto.'),
    ex('Is your name Ana?', 'Seu nome é Ana?', 'Your name é singular; a pergunta começa com is.', 'Não use are your name.'),
    ex('Are your parents here?', 'Seus pais estão aqui?', 'Parents é plural, então a pergunta começa com are.', 'Não use is.'),
    ex('Is this book new?', 'Este livro é novo?', 'This book é singular; use is.', 'Não use are com singular.'),
    ex('Are the books new?', 'Os livros são novos?', 'Books é plural; use are.', 'Não use is com plural.'),
    ex('Is Brazil big?', 'O Brasil é grande?', 'Brazil é singular; use is.', 'Não use do nesta pergunta com to be.'),
  ];
  if (shortAnswers) return [
    ex('Are you ready? Yes, I am.', 'Você está pronto? Sim, estou.', 'A pergunta usa are you, mas a resposta fala de I, então I am.', 'Não responda “Yes, I are”.'),
    ex('Are you ready? No, I am not.', 'Você está pronto? Não, não estou.', 'A resposta negativa mantém am not com I.', 'Não use don’t.'),
    ex('Is he your brother? Yes, he is.', 'Ele é seu irmão? Sim, é.', 'A resposta repete o pronome he e o verbo is.', 'Não diga “Yes, he do”.'),
    ex('Is she from Brazil? No, she is not.', 'Ela é do Brasil? Não, não é.', 'Pergunta com is pede resposta com is/is not.', 'Não use are.'),
    ex('Is it your phone? Yes, it is.', 'É seu celular? Sim, é.', 'It retoma o objeto da pergunta.', 'Não responda só “yes” quando estiver treinando A1.'),
    ex('Are we late? No, we are not.', 'Estamos atrasados? Não, não estamos.', 'We combina com are na resposta.', 'Não diga “we is not”.'),
    ex('Are they students? Yes, they are.', 'Eles são estudantes? Sim, são.', 'They combina com are.', 'Não use is.'),
    ex('Am I late? No, you are not.', 'Estou atrasado? Não, você não está.', 'A pessoa responde sobre you porque está falando com quem perguntou.', 'Não responda “No, I am not” se quem pergunta é outra pessoa e você responde a ela.'),
    ex('Is your name Ana? Yes, it is.', 'Seu nome é Ana? Sim, é.', 'It retoma a ideia “your name”.', 'Também é comum responder “Yes, my name is Ana”.'),
    ex('Are your parents here? No, they are not.', 'Seus pais estão aqui? Não, não estão.', 'Parents vira they na resposta.', 'Não use he/she para parents.'),
    ex('Is this book new? Yes, it is.', 'Este livro é novo? Sim, é.', 'Book vira it na resposta curta.', 'Não use he/she.'),
    ex('Are the books new? No, they are not.', 'Os livros são novos? Não, não são.', 'Books é plural; use they are not.', 'Não use it para plural.'),
  ];
  return [];
}

function makeToBeLesson({ id, order, title, kind, tags, pattern, goal, opening, why, concept, bridge, useCases, formation, whenUse, whenNot, guidedBeforeQuiz, mistakes, guided, errors, transforms, translations, production, recap }) {
  return createGrammarLesson({
    id, level, order, title, status, estimatedMinutes: 60,
    tags: tags || ['a1', 'grammar', 'be-verb', kind, 'beginner-foundation'],
    objectives: [
      `Entender a lógica de ${title}.`,
      'Aplicar a regra em frases A1 sem traduzir palavra por palavra.',
      'Reconhecer e corrigir erros comuns de brasileiros.',
      'Produzir frases próprias com segurança antes de avançar.',
    ],
    teacherOpening: opening,
    whyItMatters: why,
    realLifeUseCases: useCases,
    conceptExplanation: concept,
    mentalModel: { title: pattern, summary: 'Pense no sujeito, escolha a forma correta do to be e depois complete a informação. A ordem muda quando a frase é pergunta ou negativa.', steps: formation.map((item) => item.instruction || item.text || String(item)) },
    stepByStep: [
      step('Identifique o sujeito da frase.', 'I, you, he, she, it, we, they, um nome singular ou um plural.'),
      step('Escolha a forma correta do verb to be.', 'I am; he/she/it is; you/we/they are.'),
      step('Aplique a ordem do tipo de frase.', 'Afirmativa, negativa, pergunta ou resposta curta têm ordens diferentes.'),
      step('Complete com a informação.', 'Nome, profissão, origem, lugar, estado ou descrição.'),
      step('Revise o erro brasileiro mais provável.', 'Não pule sujeito, não use do com to be e não misture am/is/are.'),
    ],
    portugueseContrast: [
      task('Português esconde muita informação no verbo; inglês normalmente exige sujeito visível.', 'Por isso dizemos I am, she is, they are.'),
      task('Português permite “sou”, “é”, “estão”; inglês precisa separar sujeito e verbo.', 'O aluno deve pensar em blocos: I am / she is / they are.'),
      task('Em português a ordem da pergunta pode ser só entonação; em inglês com to be a ordem muda.', 'You are ready → Are you ready?'),
      task('Em português usamos “não” antes do verbo principal; em inglês com to be, not vem depois de am/is/are.', 'I am not, she is not, they are not.'),
    ],
    guidedDiscovery: [
      task('Compare: “I am ready” e “Are you ready?” O que mudou?', 'Na pergunta, are foi para o começo.'),
      task('Compare: “She is here” e “She is not here.” Onde entrou a negação?', 'Not entrou depois de is.'),
      task('Compare: “Are they students?” e “Yes, they are.” O que a resposta curta reaproveita?', 'Reaproveita pronome + forma correta do to be.'),
    ],
    guidedBeforeQuiz,
    grammarGoal: goal,
    formationGuide: formation,
    whenToUse: whenUse,
    whenNotToUse: whenNot,
    grammarTable: [
      { label: 'I', pattern: 'I am', example: kind === 'questions' ? 'Am I late?' : 'I am ready.', note: 'I combina com am.' },
      { label: 'he / she / it', pattern: 'he/she/it is', example: 'She is here.', note: 'Terceira pessoa singular usa is.' },
      { label: 'you / we / they', pattern: 'you/we/they are', example: 'They are students.', note: 'You, we e they usam are.' },
      { label: 'negative', pattern: 'subject + am/is/are + not', example: 'She is not here.', note: 'Not vem depois do to be.' },
      { label: 'question', pattern: 'am/is/are + subject', example: 'Are you ready?', note: 'To be vem antes do sujeito.' },
    ],
    teacherExamples: commonToBeExamples(kind),
    commonBrazilianMistakes: mistakes,
    controlledPractice: formation.slice(0, 6),
    guidedPractice: guided,
    errorCorrectionPractice: errors,
    transformationPractice: transforms,
    translationPractice: translations,
    productionTasks: production,
    selfAssessment: [
      task('Consigo explicar a regra sem olhar?'),
      task('Consigo dizer por que a ordem muda?'),
      task('Consigo corrigir o erro brasileiro mais comum desta aula?'),
      task('Consigo criar frases próprias usando o padrão?'),
    ],
    lessonRecap: recap,
    nextLessonBridge: bridge,
    masteryCriteria: { minPracticeAccuracy: 80, requiredProduction: 3, tags: ['a1-grammar', kind, 'deep-approved-target'] },
  });
}

export const A1_DEEP_GRAMMAR_EXTRA = Object.freeze([
  makeToBeLesson({
    id: 'A1-GRAMMAR-002', order: 2, title: 'Verb to be — affirmative', kind: 'affirmative', tags: ['a1', 'grammar', 'be-verb', 'affirmative', 'is-am-are', 'beginner-foundation'], pattern: 'subject + am/is/are + information',
    goal: 'Formar frases afirmativas com verb to be para dizer quem a pessoa é, como ela está, de onde ela é, onde algo está ou como algo é.',
    opening: 'Agora que você já sabe escolher o sujeito com I, you, he, she, it, we e they, chegou a hora de entender o primeiro verbo essencial do inglês: o verb to be. Ele aparece como am, is ou are. Essa aula não é para decorar três palavrinhas soltas. É para entender que o to be liga o sujeito a uma informação. Quando você diz “I am a student”, você está ligando I à informação a student. Quando diz “She is happy”, liga she ao estado happy. Essa lógica é a base para descrição, apresentação, origem, profissão e localização no A1.',
    why: 'Sem o verb to be afirmativo, você não consegue montar as frases mais básicas de apresentação e descrição. Ele responde perguntas como: quem sou eu, quem é essa pessoa, de onde ela é, onde algo está e como algo é. Brasileiros erram porque tentam traduzir “sou”, “é” e “estão” como se o inglês funcionasse igual ao português. Em inglês, você precisa escolher a forma certa de acordo com o sujeito: I am, he/she/it is, you/we/they are. A regra existe para mostrar concordância entre sujeito e verbo.',
    concept: 'O verb to be afirmativo liga um sujeito a uma informação. A fórmula é: sujeito + am/is/are + complemento. O complemento pode ser nome, profissão, origem, idade em contextos simples, lugar, estado ou descrição. A escolha entre am, is e are depende do sujeito, não da tradução em português. I sempre usa am. He, she e it usam is porque são terceira pessoa singular. You, we e they usam are. Quando o sujeito é um nome singular, como Ana ou Brazil, normalmente usamos is. Quando é plural, como my parents ou the books, usamos are.',
    useCases: ['Apresentar-se: I am Luis.', 'Dizer profissão ou papel: She is a student.', 'Dizer origem: He is from Brazil.', 'Descrever objeto: It is black.', 'Falar de grupo: They are friends.'],
    formation: [task('I + am + information', 'I am a student.'), task('You + are + information', 'You are ready.'), task('He/She/It + is + information', 'She is my sister.'), task('We/They + are + information', 'They are students.'), task('Nome singular + is + information', 'Ana is here.'), task('Nome plural + are + information', 'My parents are here.')],
    whenUse: [task('Para apresentação pessoal.'), task('Para profissão/papel.'), task('Para origem/nacionalidade.'), task('Para localização simples.'), task('Para estado ou descrição.')],
    whenNot: [task('Não use para ações comuns como “I study” no A1.'), task('Não use do/does junto com am/is/are em afirmativa.'), task('Não escolha am/is/are pela tradução; escolha pelo sujeito.')],
    guidedBeforeQuiz: [task('I → am → I am ready.'), task('She → is → She is here.'), task('They → are → They are students.'), task('My phone → is → My phone is black.')],
    mistakes: [mistake('I is ready.', 'I am ready.', 'O aluno escolheu is pela tradução “estou”, mas I combina com am.', 'Memorize I am.', 'I ___ ready.'), mistake('She are happy.', 'She is happy.', 'She é singular; usa is.', 'He/she/it sempre pedem is neste padrão.', 'She ___ happy.'), mistake('They is students.', 'They are students.', 'They é plural/grupo; usa are.', 'They/we/you pedem are.', 'They ___ students.'), mistake('My parents is here.', 'My parents are here.', 'Parents é plural.', 'Plural pede are.', 'My parents ___ here.'), mistake('Am a student.', 'I am a student.', 'Português permite omitir sujeito; inglês não.', 'Coloque I antes de am.', '___ am a student.'), mistake('Ana are here.', 'Ana is here.', 'Ana é nome singular.', 'Nome singular usa is.', 'Ana ___ here.'), mistake('The books is new.', 'The books are new.', 'Books é plural.', 'Plural usa are.', 'The books ___ new.'), mistake('You is my friend.', 'You are my friend.', 'You usa are, mesmo no singular.', 'Memorize you are.', 'You ___ my friend.')],
    guided: [q('Complete: I ___ from Brazil.', ['is','am','are'], 'am', 'I combina com am.'), q('Complete: She ___ my sister.', ['are','am','is'], 'is', 'She usa is.'), q('Complete: They ___ friends.', ['is','are','am'], 'are', 'They usa are.'), q('Complete: My phone ___ black.', ['is','are','am'], 'is', 'Objeto singular usa is.'), q('Complete: We ___ ready.', ['am','is','are'], 'are', 'We usa are.'), q('Complete: Ana ___ here.', ['is','are','am'], 'is', 'Nome singular usa is.'), q('Complete: My parents ___ at home.', ['is','are','am'], 'are', 'Parents é plural.'), q('Qual frase está correta?', ['I is tired.','I am tired.','I are tired.'], 'I am tired.', 'I am é o par correto.')],
    errors: [q('Corrija: She are here.', ['She is here.','She am here.','She here is.'], 'She is here.', 'She usa is.'), q('Corrija: They is students.', ['They are students.','They am students.','They students are.'], 'They are students.', 'They usa are.'), q('Corrija: Am from Brazil.', ['I am from Brazil.','He am from Brazil.','It are from Brazil.'], 'I am from Brazil.', 'Falta sujeito.'), q('Corrija: You is kind.', ['You are kind.','You am kind.','You kind is.'], 'You are kind.', 'You usa are.')],
    transforms: [q('Monte: I / a student', ['I am a student.','I is a student.','Am I a student.'], 'I am a student.', 'Afirmativa: sujeito + am/is/are + informação.'), q('Monte: she / happy', ['She is happy.','She are happy.','Is she happy.'], 'She is happy.', 'She usa is.'), q('Monte: they / friends', ['They are friends.','They is friends.','Are they friends.'], 'They are friends.', 'They usa are.'), q('Monte: my books / new', ['My books are new.','My books is new.','My books am new.'], 'My books are new.', 'Plural usa are.')],
    translations: [q('Traduza: “Eu sou estudante.”', ['I am a student.','I is a student.','Am a student.'], 'I am a student.', 'Use I am.'), q('Traduza: “Ela está feliz.”', ['She is happy.','She are happy.','She am happy.'], 'She is happy.', 'Use she is.'), q('Traduza: “Eles são amigos.”', ['They are friends.','They is friends.','They am friends.'], 'They are friends.', 'Use they are.')],
    production: [task('Escreva 5 frases afirmativas sobre você com I am.'), task('Escreva 5 frases sobre pessoas próximas usando he is ou she is.'), task('Escreva 5 frases sobre objetos/lugares usando it is.'), task('Escreva 5 frases sobre grupos usando we are ou they are.')],
    recap: ['Verb to be afirmativo liga sujeito a informação.', 'I usa am; he/she/it usa is; you/we/they usa are.', 'Nome singular geralmente usa is; plural usa are.', 'Não pule o sujeito por influência do português.', 'A próxima aula vai negar essas frases usando not.'],
    bridge: 'Agora que você sabe afirmar com am/is/are, a próxima aula mostra como negar sem usar don’t: I am not, she is not, they are not.',
  }),
  makeToBeLesson({
    id: 'A1-GRAMMAR-003', order: 3, title: 'Verb to be — negative', kind: 'negative', tags: ['a1', 'grammar', 'be-verb', 'negative', 'is-not-am-not', 'beginner-foundation'], pattern: 'subject + am/is/are + not + information',
    goal: 'Negar frases com verb to be colocando not depois de am, is ou are.',
    opening: 'Negar em inglês não é apenas jogar “not” em qualquer lugar. Com o verb to be, existe uma ordem muito segura: sujeito, am/is/are, not e depois a informação. Em português dizemos “eu não estou cansado” e o “não” aparece antes do verbo. Em inglês com to be, a lógica é diferente: primeiro você monta a ligação com am/is/are e depois nega essa ligação com not. Por isso a frase correta é “I am not tired”, não “I not am tired”.',
    why: 'Essa regra importa porque o aluno brasileiro costuma misturar a lógica do português com a do inglês. Também é comum tentar usar don’t em frases com to be, como “I don’t am tired”, mas isso não funciona. A negativa com to be é essencial para dizer que você não é algo, não está em algum lugar, não está em determinado estado ou que uma coisa não tem uma característica. Ela prepara você para respostas curtas e conversas básicas.',
    concept: 'A negativa do verb to be acontece quando você coloca not depois da forma correta de to be. A fórmula é: sujeito + am/is/are + not + complemento. O sujeito ainda decide se usamos am, is ou are. Depois disso, not nega a relação entre sujeito e informação. “She is happy” afirma que ela está feliz. “She is not happy” nega essa informação. Para o A1, a forma completa é mais segura: am not, is not, are not. Contrações como isn’t e aren’t existem, mas primeiro você precisa dominar a ordem completa.',
    useCases: ['Dizer que você não está pronto: I am not ready.', 'Dizer que alguém não está aqui: She is not here.', 'Dizer que algo não é seu: It is not my phone.', 'Dizer que um grupo não é de estudantes: They are not students.', 'Dizer que um lugar não é grande: It is not big.'],
    formation: [task('I + am + not + information', 'I am not tired.'), task('You + are + not + information', 'You are not late.'), task('He/She/It + is + not + information', 'She is not here.'), task('We/They + are + not + information', 'They are not students.'), task('Nome singular + is not', 'Ana is not my teacher.'), task('Plural + are not', 'My parents are not here.')],
    whenUse: [task('Para negar estado.'), task('Para negar profissão/papel.'), task('Para negar origem.'), task('Para negar localização.'), task('Para negar descrição de coisa/pessoa.')],
    whenNot: [task('Não use don’t com am/is/are neste padrão.'), task('Não coloque not antes de am/is/are.'), task('Não esqueça o sujeito.')],
    guidedBeforeQuiz: [task('I am ready → I am not ready.'), task('She is here → She is not here.'), task('They are students → They are not students.'), task('It is my phone → It is not my phone.')],
    mistakes: [mistake('I not am ready.', 'I am not ready.', 'Português coloca não antes do verbo; inglês com to be coloca not depois.', 'Use sujeito + am/is/are + not.', 'I ___ not ready.'), mistake('She not is here.', 'She is not here.', 'A ordem foi copiada do português.', 'Not vem depois de is.', 'She is ___ here.'), mistake('They not are students.', 'They are not students.', 'Not precisa vir depois de are.', 'They are not...', 'They ___ not students.'), mistake('I don’t am tired.', 'I am not tired.', 'Don’t não acompanha am.', 'Com to be, use am not.', 'I ___ not tired.'), mistake('He are not my brother.', 'He is not my brother.', 'He combina com is.', 'Escolha o verbo antes de colocar not.', 'He ___ not my brother.'), mistake('It not is blue.', 'It is not blue.', 'Ordem incorreta.', 'It + is + not.', 'It ___ not blue.'), mistake('We is not ready.', 'We are not ready.', 'We usa are.', 'We are not.', 'We ___ not ready.'), mistake('My parents is not here.', 'My parents are not here.', 'Parents é plural.', 'Plural usa are not.', 'My parents ___ not here.')],
    guided: [q('Complete: I am ___ ready.', ['no','not','don’t'], 'not', 'Not vem depois de am.'), q('Complete: She ___ not here.', ['are','is','am'], 'is', 'She usa is.'), q('Complete: They are ___ students.', ['not','no','don’t'], 'not', 'Not nega are.'), q('Qual frase está correta?', ['I not am tired.','I am not tired.','I don’t am tired.'], 'I am not tired.', 'Ordem correta.'), q('Complete: It ___ not my phone.', ['is','are','am'], 'is', 'It usa is.'), q('Complete: We ___ not ready.', ['are','is','am'], 'are', 'We usa are.'), q('Complete: You are ___ late.', ['not','no','is'], 'not', 'Not depois de are.'), q('Complete: My parents ___ not here.', ['is','are','am'], 'are', 'Parents plural usa are.')],
    errors: [q('Corrija: She not is happy.', ['She is not happy.','She not happy is.','She are not happy.'], 'She is not happy.', 'Not depois de is.'), q('Corrija: They is not teachers.', ['They are not teachers.','They am not teachers.','They not are teachers.'], 'They are not teachers.', 'They usa are.'), q('Corrija: I don’t am ready.', ['I am not ready.','I do not am ready.','I not am ready.'], 'I am not ready.', 'Don’t não acompanha am.'), q('Corrija: It are not red.', ['It is not red.','It am not red.','It not is red.'], 'It is not red.', 'It usa is.')],
    transforms: [q('Negue: I am ready.', ['I am not ready.','I not am ready.','I don’t am ready.'], 'I am not ready.', 'Coloque not depois de am.'), q('Negue: She is here.', ['She is not here.','She not is here.','She are not here.'], 'She is not here.', 'Not depois de is.'), q('Negue: They are students.', ['They are not students.','They not are students.','They is not students.'], 'They are not students.', 'Not depois de are.'), q('Negue: It is blue.', ['It is not blue.','It not is blue.','It are not blue.'], 'It is not blue.', 'It + is not.')],
    translations: [q('Traduza: “Eu não estou pronto.”', ['I am not ready.','I not am ready.','I don’t am ready.'], 'I am not ready.', 'I am not.'), q('Traduza: “Ela não está aqui.”', ['She is not here.','She not is here.','She are not here.'], 'She is not here.', 'She is not.'), q('Traduza: “Eles não são professores.”', ['They are not teachers.','They is not teachers.','They not are teachers.'], 'They are not teachers.', 'They are not.')],
    production: [task('Escreva 5 frases negativas sobre você usando I am not.'), task('Escreva 5 frases negativas sobre uma pessoa usando he/she is not.'), task('Escreva 5 frases negativas sobre objetos usando it is not.'), task('Escreva 5 frases negativas sobre grupos usando they are not.')],
    recap: ['A negativa com to be usa not depois de am/is/are.', 'Não use don’t com am/is/are no A1.', 'O sujeito ainda decide am, is ou are.', 'A ordem segura é subject + to be + not + information.', 'A próxima aula transforma essas estruturas em perguntas.'],
    bridge: 'Agora que você sabe afirmar e negar, a próxima aula muda a ordem para perguntar: Are you ready? Is she here?',
  }),
  makeToBeLesson({
    id: 'A1-GRAMMAR-004', order: 4, title: 'Verb to be — questions', kind: 'questions', tags: ['a1', 'grammar', 'be-verb', 'questions', 'are-you-is-she', 'beginner-foundation'], pattern: 'am/is/are + subject + information?',
    goal: 'Transformar frases com verb to be em perguntas mudando a posição de am, is ou are.',
    opening: 'Em português, muitas perguntas podem ser feitas só com entonação: “Você está pronto?” parece parecido com “Você está pronto.” Na escrita, mudamos o ponto por interrogação. Em inglês com verb to be, a estrutura muda de verdade. A frase “You are ready” vira “Are you ready?” porque o to be vai para antes do sujeito. Essa é uma das primeiras vezes em que você percebe que inglês depende muito da ordem das palavras.',
    why: 'Entender perguntas com to be é essencial para conversas simples: perguntar nome, origem, estado, localização, profissão e descrição. Brasileiros erram muito dizendo “Do you are...?” porque tentam usar do como marcador de pergunta em qualquer situação. Mas com to be, você não precisa de do. A própria forma am/is/are vai para o começo e cria a pergunta.',
    concept: 'A pergunta com verb to be acontece invertendo a ordem da afirmativa. Na afirmativa, dizemos sujeito + am/is/are: “You are ready.” Na pergunta, colocamos am/is/are antes do sujeito: “Are you ready?” A forma do verbo continua dependendo do sujeito: I usa am, he/she/it usa is, you/we/they usa are. A regra principal é: escolha a forma correta do to be e coloque essa forma antes do sujeito. Não adicione do/does.',
    useCases: ['Perguntar se alguém está pronto.', 'Perguntar se uma pessoa é estudante.', 'Perguntar origem.', 'Perguntar se um objeto é de alguém.', 'Perguntar onde ou como algo está em frases simples.'],
    formation: [task('You are ready → Are you ready?'), task('She is here → Is she here?'), task('They are students → Are they students?'), task('It is your phone → Is it your phone?'), task('I am late → Am I late?'), task('Your parents are here → Are your parents here?')],
    whenUse: [task('Para perguntas com estado: Are you tired?'), task('Para perguntas com identidade/profissão: Is she a student?'), task('Para perguntas com origem: Is he from Brazil?'), task('Para perguntas com objeto: Is it your phone?'), task('Para confirmar informação simples.')],
    whenNot: [task('Não use do/does com am/is/are.'), task('Não deixe a ordem afirmativa como pergunta principal no A1.'), task('Não misture is com they ou are com she.')],
    guidedBeforeQuiz: [task('You are ready → Are you ready?'), task('She is from Brazil → Is she from Brazil?'), task('They are here → Are they here?'), task('It is blue → Is it blue?')],
    mistakes: [mistake('Do you are ready?', 'Are you ready?', 'O aluno usou do com to be, mas to be já faz a pergunta.', 'Comece com are.', '___ you ready?'), mistake('You are ready?', 'Are you ready?', 'A entonação sozinha não é o padrão que estamos treinando.', 'Inverta are e you.', 'Are ___ ready?'), mistake('Is they students?', 'Are they students?', 'They combina com are.', 'Escolha o verbo pelo sujeito antes de inverter.', '___ they students?'), mistake('Are she here?', 'Is she here?', 'She combina com is.', 'Use is para she.', '___ she here?'), mistake('Do it is your phone?', 'Is it your phone?', 'Do não entra com is.', 'Comece com is.', '___ it your phone?'), mistake('Am you late?', 'Are you late?', 'You combina com are.', 'Am só com I.', '___ you late?'), mistake('Is we okay?', 'Are we okay?', 'We combina com are.', 'Use are com we.', '___ we okay?'), mistake('Are my name Ana?', 'Is my name Ana?', 'My name é singular.', 'Singular usa is.', '___ my name Ana?')],
    guided: [q('Transforme em pergunta: You are ready.', ['Are you ready?','You are ready?','Do you are ready?'], 'Are you ready?', 'Are vem antes de you.'), q('Complete: ___ she your sister?', ['Are','Am','Is'], 'Is', 'She usa is.'), q('Complete: ___ they students?', ['Is','Are','Am'], 'Are', 'They usa are.'), q('Complete: ___ it your phone?', ['Is','Are','Do'], 'Is', 'It usa is; sem do.'), q('Complete: ___ I late?', ['Am','Are','Is'], 'Am', 'I usa am em pergunta.'), q('Qual pergunta está correta?', ['Do you are from Brazil?','Are you from Brazil?','You are from Brazil?'], 'Are you from Brazil?', 'To be vem antes do sujeito.'), q('Complete: ___ your parents here?', ['Is','Are','Am'], 'Are', 'Parents é plural.'), q('Complete: ___ this book new?', ['Are','Is','Am'], 'Is', 'This book é singular.')],
    errors: [q('Corrija: Do you are happy?', ['Are you happy?','Do you happy?','You are happy?'], 'Are you happy?', 'Não use do com to be.'), q('Corrija: Is they ready?', ['Are they ready?','They are ready?','Am they ready?'], 'Are they ready?', 'They usa are.'), q('Corrija: Are she here?', ['Is she here?','She is here?','Are here she?'], 'Is she here?', 'She usa is.'), q('Corrija: Do it is blue?', ['Is it blue?','It is blue?','Are it blue?'], 'Is it blue?', 'It usa is.')],
    transforms: [q('Transforme: She is a student.', ['Is she a student?','She is a student?','Are she a student?'], 'Is she a student?', 'Is antes de she.'), q('Transforme: They are friends.', ['Are they friends?','Is they friends?','They are friends?'], 'Are they friends?', 'Are antes de they.'), q('Transforme: It is your book.', ['Is it your book?','Are it your book?','Do it is your book?'], 'Is it your book?', 'Is antes de it.'), q('Transforme: We are late.', ['Are we late?','Is we late?','Do we are late?'], 'Are we late?', 'Are antes de we.')],
    translations: [q('Traduza: “Você está pronto?”', ['Are you ready?','Do you are ready?','You are ready?'], 'Are you ready?', 'Pergunta com to be começa com are.'), q('Traduza: “Ela é sua irmã?”', ['Is she your sister?','Are she your sister?','Do she is your sister?'], 'Is she your sister?', 'She usa is.'), q('Traduza: “Eles são estudantes?”', ['Are they students?','Is they students?','Do they are students?'], 'Are they students?', 'They usa are.')],
    production: [task('Escreva 5 perguntas com Are you...?', 'Use ready, tired, from Brazil, a student, okay.'), task('Escreva 5 perguntas com Is he/she/it...?', 'Use pessoas e objetos reais.'), task('Escreva 5 perguntas com Are they/we...?', 'Use grupos.'), task('Transforme 5 frases afirmativas suas em perguntas.')],
    recap: ['Pergunta com to be muda a ordem.', 'A fórmula é am/is/are + subject + information?', 'Não use do/does com to be.', 'Escolha am/is/are pelo sujeito antes de inverter.', 'A próxima aula ensina respostas curtas para essas perguntas.'],
    bridge: 'Agora que você sabe perguntar, a próxima aula ensina como responder sem repetir a frase inteira: Yes, I am. No, she is not.',
  }),
  makeToBeLesson({
    id: 'A1-GRAMMAR-005', order: 5, title: 'Short answers with to be', kind: 'shortAnswers', tags: ['a1', 'grammar', 'be-verb', 'short-answers', 'yes-no-responses', 'beginner-foundation'], pattern: 'Yes/No + subject + am/is/are',
    goal: 'Responder perguntas com to be usando respostas curtas corretas e naturais.',
    opening: 'Em inglês, responder apenas “yes” ou “no” pode funcionar em algumas conversas, mas no estudo A1 isso não treina a estrutura completa. Short answers ajudam você a confirmar ou negar usando o pronome e a forma correta do verb to be. Quando alguém pergunta “Are you ready?”, a resposta completa curta é “Yes, I am” ou “No, I am not”. Você não repete tudo, mas também não responde de forma solta. Isso treina concordância e evita respostas como “Yes, I do” em perguntas com to be.',
    why: 'Short answers importam porque aparecem o tempo todo em conversas reais e consolidam três coisas de uma vez: o sujeito da resposta, a forma correta de am/is/are e a lógica da pergunta. Brasileiros erram porque decoram yes/no e esquecem que a resposta curta precisa combinar com a pergunta. Se a pergunta usa to be, a resposta também usa to be; se pergunta sobre you, muitas vezes a resposta vira I; se pergunta sobre your parents, a resposta vira they.',
    concept: 'Uma short answer é uma resposta curta que evita repetir toda a frase, mas mantém a estrutura essencial. A fórmula é: Yes/No + pronome + am/is/are. Na negativa, usamos not depois de am/is/are. Você precisa olhar para o sujeito da pergunta e decidir como ele aparece na resposta. “Are you ready?” pergunta sobre you, mas quem responde fala de si mesmo, então diz “Yes, I am”. “Is Ana here?” pode virar “Yes, she is”. “Are the books new?” vira “Yes, they are”.',
    useCases: ['Responder se você está pronto.', 'Confirmar se alguém está em algum lugar.', 'Responder se algo é seu.', 'Responder perguntas sobre grupo.', 'Treinar conversa curta sem repetir a frase inteira.'],
    formation: [task('Are you...? → Yes, I am / No, I am not'), task('Is he...? → Yes, he is / No, he is not'), task('Is she...? → Yes, she is / No, she is not'), task('Is it...? → Yes, it is / No, it is not'), task('Are we...? → Yes, we are / No, we are not'), task('Are they...? → Yes, they are / No, they are not')],
    whenUse: [task('Para responder perguntas com am/is/are.'), task('Para confirmar informação simples.'), task('Para negar sem repetir a frase toda.'), task('Para conversa oral básica.'), task('Para mostrar domínio de sujeito + to be.')],
    whenNot: [task('Não responda com do/don’t quando a pergunta usa to be.'), task('Não mantenha you na resposta quando você está falando de si mesmo.'), task('Não troque is e are na resposta curta.')],
    guidedBeforeQuiz: [task('Are you ready? → Yes, I am.'), task('Is she here? → No, she is not.'), task('Are they students? → Yes, they are.'), task('Is it your phone? → No, it is not.')],
    mistakes: [mistake('Are you ready? Yes, I do.', 'Are you ready? Yes, I am.', 'A pergunta usa are, então a resposta usa to be, não do.', 'Pergunta com to be pede resposta com to be.', 'Yes, I ___.'), mistake('Is she here? Yes, she are.', 'Is she here? Yes, she is.', 'She combina com is.', 'Repita pronome + verbo correto.', 'Yes, she ___.'), mistake('Are they students? Yes, they is.', 'Are they students? Yes, they are.', 'They combina com are.', 'They are.', 'Yes, they ___.'), mistake('Are you late? Yes, you are.', 'Are you late? Yes, I am.', 'Quem responde fala de si mesmo.', 'You da pergunta vira I na resposta.', 'Yes, ___ am.'), mistake('Is it your book? Yes, he is.', 'Is it your book? Yes, it is.', 'Book/it é objeto.', 'Use it para objeto.', 'Yes, it ___.'), mistake('Are your parents here? Yes, he is.', 'Are your parents here? Yes, they are.', 'Parents é plural.', 'Use they are.', 'Yes, they ___.'), mistake('Am I late? No, I am not.', 'Am I late? No, you are not.', 'Se outra pessoa pergunta “Am I late?”, você responde sobre ela: you.', 'Observe quem está falando.', 'No, you ___ not.'), mistake('Is this book new? No, they are not.', 'Is this book new? No, it is not.', 'This book é singular.', 'Singular objeto vira it.', 'No, it ___ not.')],
    guided: [q('Resposta para “Are you ready?”', ['Yes, I am.','Yes, I are.','Yes, I do.'], 'Yes, I am.', 'You da pergunta vira I na resposta.'), q('Resposta para “Is she here?”', ['Yes, she is.','Yes, she are.','Yes, she do.'], 'Yes, she is.', 'She usa is.'), q('Resposta para “Are they students?”', ['Yes, they are.','Yes, they is.','Yes, they do.'], 'Yes, they are.', 'They usa are.'), q('Resposta para “Is it your phone?”', ['No, it is not.','No, he is not.','No, it are not.'], 'No, it is not.', 'Objeto usa it is not.'), q('Complete: Are we late? No, we ___.', ['are not','is not','am not'], 'are not', 'We usa are.'), q('Complete: Am I late? No, you ___ not.', ['am','is','are'], 'are', 'Quem responde diz you are not.'), q('Complete: Is your name Ana? Yes, it ___.', ['are','is','am'], 'is', 'Your name pode virar it.'), q('Complete: Are your parents here? No, they ___ not.', ['is','are','am'], 'are', 'Parents vira they are not.')],
    errors: [q('Corrija: Yes, I do.', ['Yes, I am.','Yes, I are.','Yes, I is.'], 'Yes, I am.', 'Para “Are you...?”, use I am.'), q('Corrija: No, she are not.', ['No, she is not.','No, she am not.','No, she do not.'], 'No, she is not.', 'She usa is.'), q('Corrija: Yes, they is.', ['Yes, they are.','Yes, they am.','Yes, they do.'], 'Yes, they are.', 'They usa are.'), q('Corrija: Is it your book? Yes, he is.', ['Yes, it is.','Yes, she is.','Yes, they are.'], 'Yes, it is.', 'Book vira it.')],
    transforms: [q('Responda positivo: Are you ready?', ['Yes, I am.','Yes, you are.','Yes, I do.'], 'Yes, I am.', 'Resposta sobre si mesmo.'), q('Responda negativo: Is he your brother?', ['No, he is not.','No, he are not.','No, he do not.'], 'No, he is not.', 'He usa is not.'), q('Responda positivo: Are they friends?', ['Yes, they are.','Yes, they is.','Yes, it is.'], 'Yes, they are.', 'They usa are.'), q('Responda negativo: Is this your phone?', ['No, it is not.','No, he is not.','No, they are not.'], 'No, it is not.', 'Objeto singular vira it.')],
    translations: [q('Traduza: “Sim, eu estou.”', ['Yes, I am.','Yes, I do.','Yes, I are.'], 'Yes, I am.', 'Resposta curta com to be.'), q('Traduza: “Não, ela não está.”', ['No, she is not.','No, she are not.','No, she do not.'], 'No, she is not.', 'She is not.'), q('Traduza: “Sim, eles são.”', ['Yes, they are.','Yes, they is.','Yes, they do.'], 'Yes, they are.', 'They are.')],
    production: [task('Crie 5 perguntas com Are you...? e responda com Yes, I am / No, I am not.'), task('Crie 5 perguntas com Is he/she...? e responda.'), task('Crie 5 perguntas com Is it...? sobre objetos.'), task('Crie 5 perguntas com Are they...? sobre grupos.')],
    recap: ['Short answers respondem sem repetir a frase inteira.', 'Pergunta com to be pede resposta com to be.', 'Are you...? geralmente vira Yes, I am / No, I am not.', 'Is he/she/it...? usa he/she/it is ou is not.', 'Are they/we...? usa they/we are ou are not.'],
    bridge: 'Depois de dominar respostas curtas, você vai aprender possessive adjectives para falar de nome, família, celular e objetos: my, your, his, her.',
  }),
  createGrammarLesson({
    id: 'A1-GRAMMAR-006', level, order: 6, title: 'Possessive adjectives: my, your, his, her', status, estimatedMinutes: 60,
    tags: ['a1', 'grammar', 'possessive-adjectives', 'my-your-his-her', 'possession', 'beginner-foundation'],
    objectives: ['Entender a diferença entre sujeito e posse.', 'Usar my, your, his e her antes de substantivos.', 'Evitar traduções como “I name” e “she book”.', 'Produzir frases sobre nome, família e objetos pessoais.'],
    teacherOpening: 'Nesta aula você vai aprender uma diferença que parece pequena, mas muda muitas frases: I não é a mesma coisa que my, he não é a mesma coisa que his, e she não é a mesma coisa que her. Em português, dizemos “meu nome”, “seu celular”, “o livro dela”. Em inglês, essas ideias usam possessive adjectives, palavras que aparecem antes de um substantivo para mostrar posse, relação ou pertencimento. O ponto principal é: subject pronoun faz o papel de sujeito; possessive adjective acompanha um nome.',
    whyItMatters: 'Possessive adjectives são essenciais porque você usa isso para se apresentar, falar da família, dos objetos, do celular, da cidade, dos amigos e da rotina. Se você diz “I name is Luis”, o inglês fica errado porque I é sujeito, não posse. A lógica correta é “My name is Luis”: my acompanha name. Entender essa diferença evita muitos erros de brasileiro e prepara você para escrever apresentações e diálogos simples.',
    realLifeUseCases: ['Dizer seu nome: My name is Luis.', 'Perguntar nome: What is your name?', 'Falar de família: Her mother is a teacher.', 'Falar de objeto: His phone is black.', 'Apresentar outra pessoa: His name is Pedro.'],
    conceptExplanation: 'Possessive adjective é uma palavra que vem antes de um substantivo para mostrar a quem aquilo está ligado. A fórmula é: possessive adjective + noun. My name, your phone, his book, her mother. Ele não substitui o sujeito da frase; ele acompanha um nome. Por isso “I name” não funciona: I é usado como sujeito em frases como “I am Luis”. Para dizer “meu nome”, você precisa de my antes de name. A mesma lógica vale para he/his e she/her: he é sujeito; his mostra posse. She é sujeito; her mostra posse.',
    mentalModel: { title: 'Pessoa dona/relação → possessive adjective → noun', summary: 'Primeiro pense de quem é ou com quem está relacionado. Depois escolha my, your, his ou her e coloque antes do nome.', steps: ['I → my → my name', 'you → your → your phone', 'he → his → his book', 'she → her → her mother'] },
    stepByStep: [step('Identifique se você quer falar de pessoa ou de posse/relação.'), step('Se a palavra for o sujeito, use I/he/she/you.'), step('Se a palavra vier antes de um nome para indicar posse, use my/your/his/her.'), step('Coloque o possessive adjective antes do substantivo.', 'my name, your phone, his car, her book.'), step('Complete a frase com is/are ou outra informação simples.')],
    portugueseContrast: [task('Português: “meu nome”. Inglês: “my name”. Não use I antes de name.'), task('Português: “o livro dela”. Inglês: “her book”. Her vem antes de book.'), task('Português: “o celular dele”. Inglês: “his phone”. His vem antes de phone.'), task('Em inglês, his/her dependem da pessoa dona, não do objeto.', 'His book pode ser “o livro dele”; her book é “o livro dela”.')],
    guidedDiscovery: [task('Compare: I am Luis / My name is Luis. O que mudou?', 'I é sujeito; my acompanha name.'), task('Compare: She is Ana / Her phone is black.', 'She é sujeito; her mostra posse/relação.'), task('Compare: He is Pedro / His mother is here.', 'He é sujeito; his acompanha mother.')],
    guidedBeforeQuiz: [task('I → my: I am Luis. My name is Luis.'), task('You → your: You are Ana. Your phone is black.'), task('He → his: He is Pedro. His book is new.'), task('She → her: She is Maria. Her mother is kind.')],
    grammarGoal: 'Usar possessive adjectives antes de substantivos para indicar posse ou relação.',
    formationGuide: [task('my + noun', 'my name'), task('your + noun', 'your phone'), task('his + noun', 'his book'), task('her + noun', 'her mother'), task('possessive adjective + noun + is/are + information', 'My name is Luis.')],
    whenToUse: [task('Para falar de nome.'), task('Para falar de família.'), task('Para falar de objetos pessoais.'), task('Para apresentar outra pessoa.'), task('Para dizer relação: my friend, her sister, his father.')],
    whenNotToUse: [task('Não use my como sujeito sozinho.'), task('Não use I antes de noun para posse.'), task('Não use she/he antes de noun para posse.'), task('Não escolha his/her pelo gênero do objeto; escolha pela pessoa dona.')],
    grammarTable: [{ label: 'I → my', pattern: 'my + noun', example: 'My name is Luis.', note: 'I é sujeito; my é posse.' }, { label: 'you → your', pattern: 'your + noun', example: 'Your phone is black.', note: 'Your pode ser seu/sua/seus/suas.' }, { label: 'he → his', pattern: 'his + noun', example: 'His book is new.', note: 'A pessoa dona é homem/menino.' }, { label: 'she → her', pattern: 'her + noun', example: 'Her mother is here.', note: 'A pessoa dona é mulher/menina.' }],
    teacherExamples: [ex('My name is Luis.', 'Meu nome é Luis.', 'My acompanha name para indicar posse/relação.', 'Não diga “I name”.'), ex('I am Luis.', 'Eu sou Luis.', 'Aqui I é sujeito da frase.', 'Não use my como sujeito.'), ex('Your phone is black.', 'Seu celular é preto.', 'Your acompanha phone.', 'Não diga “you phone”.'), ex('You are my friend.', 'Você é meu amigo.', 'You é sujeito; my acompanha friend.', 'Duas funções diferentes na mesma frase.'), ex('His name is Pedro.', 'O nome dele é Pedro.', 'His mostra que o nome pertence/está ligado a ele.', 'Não diga “he name”.'), ex('He is Pedro.', 'Ele é Pedro.', 'He é sujeito.', 'His não substitui he aqui.'), ex('Her book is new.', 'O livro dela é novo.', 'Her acompanha book.', 'Não diga “she book”.'), ex('She is Ana.', 'Ela é Ana.', 'She é sujeito.', 'Her não funciona como sujeito nesta frase.'), ex('My family is small.', 'Minha família é pequena.', 'My acompanha family.', 'Family é singular neste exemplo, então is.'), ex('Your mother is kind.', 'Sua mãe é gentil.', 'Your acompanha mother.', 'Your não muda por masculino/feminino.'), ex('His phone is new.', 'O celular dele é novo.', 'His depende do dono masculino, não do objeto phone.', 'Não traduza pelo gênero de celular.'), ex('Her father is a teacher.', 'O pai dela é professor.', 'Her depende da dona/relação feminina.', 'Mesmo father sendo homem, her fala “dela”.')],
    commonBrazilianMistakes: [mistake('I name is Luis.', 'My name is Luis.', 'I é sujeito, não posse.', 'Antes de name use my.', '___ name is Luis.'), mistake('You phone is black.', 'Your phone is black.', 'You é sujeito; your mostra posse.', 'Use your antes de noun.', '___ phone is black.'), mistake('He book is new.', 'His book is new.', 'He é sujeito; his acompanha book.', 'Use his + noun.', '___ book is new.'), mistake('She mother is here.', 'Her mother is here.', 'She é sujeito; her acompanha mother.', 'Use her + noun.', '___ mother is here.'), mistake('His sister is Ana. She phone is black.', 'His sister is Ana. Her phone is black.', 'A dona do celular é Ana, então her.', 'Escolha pela pessoa dona.', 'Ana → ___ phone.'), mistake('Her father is João. His book is here.', 'Her father is João. His book is here.', 'Aqui his está correto se o livro é do pai João; a escolha depende do dono.', 'Pergunte: de quem é?', 'João → ___ book.'), mistake('My is Luis.', 'I am Luis.', 'My precisa acompanhar um noun.', 'Para sujeito, use I.', '___ am Luis.'), mistake('Her is Ana.', 'She is Ana.', 'Her não é sujeito neste padrão.', 'Para sujeito feminino, use she.', '___ is Ana.')],
    controlledPractice: [task('I → my → my name'), task('you → your → your phone'), task('he → his → his book'), task('she → her → her mother'), task('my name + is + Luis'), task('her phone + is + black')],
    guidedPractice: [q('Complete: ___ name is Luis.', ['I','My','Me'], 'My', 'Antes de name use my.'), q('Complete: ___ phone is black.', ['You','Your','He'], 'Your', 'Your acompanha phone.'), q('Complete: ___ book is new. Pedro has a book.', ['His','He','Her'], 'His', 'Pedro é homem; posse = his.'), q('Complete: ___ mother is here. Ana is my friend.', ['She','Her','His'], 'Her', 'Ana é mulher; posse/relação = her.'), q('Qual frase está correta?', ['I name is Ana.','My name is Ana.','Me name is Ana.'], 'My name is Ana.', 'My acompanha name.'), q('Qual palavra é posse?', ['he','his','is'], 'his', 'His acompanha noun.'), q('Qual frase usa sujeito?', ['She is Ana.','Her is Ana.','His is Ana.'], 'She is Ana.', 'She é sujeito.'), q('Qual frase usa posse?', ['He phone is black.','His phone is black.','Him phone is black.'], 'His phone is black.', 'His acompanha phone.')],
    errorCorrectionPractice: [q('Corrija: I name is Luis.', ['My name is Luis.','I am name Luis.','Me name is Luis.'], 'My name is Luis.', 'Use my antes de name.'), q('Corrija: She book is here.', ['Her book is here.','His book is here.','She is book here.'], 'Her book is here.', 'She vira her para posse.'), q('Corrija: He phone is new.', ['His phone is new.','Her phone is new.','He is phone new.'], 'His phone is new.', 'He vira his para posse.'), q('Corrija: My is Ana.', ['I am Ana.','My name Ana.','Me is Ana.'], 'I am Ana.', 'My não é sujeito.')],
    transformationPractice: [q('Transforme: I → ___ name', ['my','I','me'], 'my', 'I vira my para posse.'), q('Transforme: you → ___ phone', ['your','you','yours phone'], 'your', 'Use your antes de noun.'), q('Transforme: he → ___ car', ['his','he','her'], 'his', 'He vira his.'), q('Transforme: she → ___ book', ['her','she','his'], 'her', 'She vira her.')],
    translationPractice: [q('Traduza: “Meu nome é Ana.”', ['My name is Ana.','I name is Ana.','Me name is Ana.'], 'My name is Ana.', 'Meu nome = my name.'), q('Traduza: “Seu celular é preto.”', ['Your phone is black.','You phone is black.','His phone is black.'], 'Your phone is black.', 'Seu/sua = your.'), q('Traduza: “O livro dele é novo.”', ['His book is new.','He book is new.','Her book is new.'], 'His book is new.', 'Dele = his.'), q('Traduza: “A mãe dela está aqui.”', ['Her mother is here.','She mother is here.','His mother is here.'], 'Her mother is here.', 'Dela = her.')],
    productionTasks: [task('Escreva 5 frases com my sobre você.'), task('Escreva 5 frases com your em perguntas ou afirmações.'), task('Escreva 5 frases sobre um homem/menino usando his.'), task('Escreva 5 frases sobre uma mulher/menina usando her.'), task('Escreva uma mini apresentação de 5 linhas usando my, his e her.')],
    selfAssessment: [task('Sei explicar diferença entre I e my?'), task('Sei explicar diferença entre he e his?'), task('Sei explicar diferença entre she e her?'), task('Consigo escolher his/her pela pessoa dona, não pelo objeto?')],
    lessonRecap: ['Subject pronoun faz papel de sujeito: I, you, he, she.', 'Possessive adjective acompanha substantivo: my, your, his, her.', 'A fórmula é possessive adjective + noun.', 'Não diga I name, she book ou he phone.', 'Para decidir his/her, pergunte de quem é ou com quem está relacionado.'],
    nextLessonBridge: 'Agora Grammar Foundations tem a base para apresentações simples. Vocabulary e Speaking vão usar my name, your phone, his/her family e frases com to be em contextos reais.',
    masteryCriteria: { minPracticeAccuracy: 80, requiredProduction: 3, tags: ['a1-grammar', 'possessive-adjectives', 'deep-approved-target'] },
  }),
]);

export const A1_DEEP_GRAMMAR_EXTRA_BY_PILLAR = Object.freeze({
  grammar: A1_DEEP_GRAMMAR_EXTRA,
});
