import { createSpeakingLesson } from '../../../schemas/index.js';

const level = 'A1';
const status = 'ready';

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function phrase(text, translation = '', note = '') { return { text, translation, note }; }
function drill(prompt, answer, variations = []) { return { prompt, answer, variations }; }

function makeSpeakingLesson(input) {
  return createSpeakingLesson({
    level,
    status,
    estimatedMinutes: 50,
    ...input,
    masteryCriteria: { minPracticeAccuracy: 80, requiredProduction: 2, tags: ['a1-speaking', input.id, 'deep-approved-target'] },
  });
}

export const A1_DEEP_SPEAKING_FOUNDATIONS = Object.freeze([
  makeSpeakingLesson({
    id: 'A1-SPEAKING-001',
    order: 1,
    title: 'Say hello and goodbye',
    objectives: ['Cumprimentar e se despedir em inglês com segurança.', 'Repetir chunks curtos com ritmo natural.', 'Escolher uma frase adequada para início e fim de conversa.', 'Gravar um mini diálogo sem improvisar do zero.'],
    teacherOpening: 'Speaking no A1 precisa começar com frases muito curtas e úteis. Você não deve ser jogado em fala livre sem preparação. Nesta aula, você vai treinar cumprimentos e despedidas como blocos prontos: Hi, hello, good morning, bye, see you later. Primeiro você vê o modelo, depois repete, troca pequenas partes e só no final grava uma versão curta. O objetivo é falar com clareza, não falar muito.',
    whyItMatters: 'Cumprimentar e se despedir é a primeira função oral de qualquer conversa. Se você trava no começo, a conversa inteira fica mais difícil. O aluno brasileiro costuma tentar traduzir tudo ou inventar frases longas demais. Aqui vamos usar chunks naturais e seguros para que você consiga abrir e fechar uma conversa sem depender de português.',
    realLifeUseCases: ['Cumprimentar professor em aula online.', 'Entrar em uma chamada.', 'Encerrar conversa com colega.', 'Responder um greeting simples.', 'Criar um diálogo curto de apresentação.'],
    conceptExplanation: 'Falar bem no início não significa criar frases novas. Significa escolher um bloco adequado e dizê-lo com ritmo. Hi e hello abrem conversa. Good morning é usado pela manhã. Bye e see you later encerram. Speaking A1 funciona em três etapas: repetir modelo, trocar uma parte pequena e responder uma pergunta previsível. Só depois disso você grava uma fala curta.',
    mentalModel: { title: 'Modelo → repetição → troca → resposta → gravação', summary: 'Você não improvisa do zero. Primeiro copia, depois muda uma parte.', steps: ['Ouça/veja o modelo.', 'Repita em voz alta.', 'Troque uma palavra.', 'Responda uma pergunta simples.', 'Grave um mini diálogo.'] },
    stepByStep: [task('Leia o modelo em voz baixa.'), task('Repita cada chunk 3 vezes.'), task('Troque hello por hi ou good morning.'), task('Combine greeting + resposta curta.'), task('Use bye ou see you later para encerrar.'), task('Grave 4 linhas curtas.')],
    portugueseContrast: [task('Português permite “e aí?” em muitos contextos; inglês A1 deve começar seguro com hi/hello.'), task('Good night é mais despedida à noite; good evening é greeting ao chegar à noite.'), task('Não traduza “até logo” palavra por palavra. Use See you later.'), task('Falar devagar e claro no A1 é melhor do que tentar soar rápido.')],
    guidedDiscovery: [task('Qual frase abre uma conversa casual?', 'Hi.'), task('Qual frase encerra uma conversa casual?', 'See you later.'), task('Qual greeting é bom para aula de manhã?', 'Good morning.')],
    guidedBeforeQuiz: [task('Repita: Hi.'), task('Repita: Hello, teacher.'), task('Repita: Good morning, everyone.'), task('Repita: Bye. See you later.')],
    speakingSituation: 'Você entrou em uma aula online e precisa cumprimentar o professor/colega e se despedir no final.',
    modelPhrases: [phrase('Hi!', 'Oi!'), phrase('Hello!', 'Olá!'), phrase('Good morning, teacher.', 'Bom dia, professor/professora.'), phrase('Good afternoon, everyone.', 'Boa tarde a todos.'), phrase('How are you?', 'Como você está?'), phrase('I am good, thanks.', 'Estou bem, obrigado.'), phrase('And you?', 'E você?'), phrase('Bye!', 'Tchau!'), phrase('See you later.', 'Até mais.'), phrase('Have a good day.', 'Tenha um bom dia.')],
    pronunciationChunks: [task('Hi', 'Curto e aberto.'), task('How are you?', 'Fale como bloco: hau-ar-yu.'), task('See you later', 'Ritmo em três partes: see-you-la-ter.')],
    repeatAfterMe: [task('Hi!'), task('Hello!'), task('How are you?'), task('I am good, thanks.'), task('And you?'), task('See you later.')],
    substitutionDrills: [drill('Troque o greeting: Hello, teacher.', 'Hi, teacher.', ['Good morning, teacher.', 'Good afternoon, teacher.']), drill('Troque a pessoa: Hello, Ana.', 'Hello, Luis.', ['Hello, teacher.', 'Hello, everyone.']), drill('Troque a despedida: Bye.', 'See you later.', ['Have a good day.', 'Goodbye.']), drill('Troque a resposta: I am good.', 'I am fine.', ['I am okay.', 'I am good, thanks.']), drill('Complete: Good ___, teacher.', 'morning', ['afternoon', 'evening'])],
    questionAnswerDrills: [drill('How are you?', 'I am good, thanks.', ['I am fine, thank you.', 'I am okay.']), drill('Hi!', 'Hello!', ['Hi!', 'Hello, Ana.']), drill('See you later.', 'Bye!', ['See you later.', 'Have a good day.']), drill('Good morning!', 'Good morning!', ['Good morning, teacher.', 'Good morning, everyone.'])],
    buildYourAnswer: [task('Escolha um greeting.', 'Hi / Hello / Good morning'), task('Adicione uma pergunta curta.', 'How are you?'), task('Responda com estado.', 'I am good, thanks.'), task('Finalize.', 'See you later.')],
    recordingTasks: [task('Grave: Hi, my name is ___. How are you?'), task('Grave um diálogo de 4 linhas usando Hi, How are you, I am good, Bye.'), task('Grave uma versão formal com Good morning, teacher.')],
    speakingChecklist: [task('Falei sem traduzir palavra por palavra?'), task('Usei greeting adequado?'), task('Fiz pausa curta entre frases?'), task('Terminei com despedida?'), task('Minha gravação tem 4 linhas curtas?')],
    freeSpeaking: task('Fale por 20 segundos simulando entrada e saída de uma aula: cumprimente, responda como está e se despeça.', 'Use apenas frases treinadas nesta aula. Use 4 frases curtas: greeting → pergunta → resposta → despedida.', 'Hi! How are you? I am good, thanks. See you later!'),
    selfAssessment: [task('Consigo dizer hello/hi?'), task('Consigo perguntar How are you?'), task('Consigo responder I am good?'), task('Consigo encerrar com See you later?')],
    lessonRecap: ['Speaking A1 começa com chunks curtos.', 'Não improvise antes de repetir modelos.', 'Hi/Hello abrem conversa.', 'Bye/See you later encerram.', 'Gravação curta é suficiente quando há clareza.'],
    nextLessonBridge: 'Na próxima aula, você vai usar greetings para se apresentar com nome, idade e uma frase simples.',
  }),

  makeSpeakingLesson({
    id: 'A1-SPEAKING-002',
    order: 2,
    title: 'Introduce yourself',
    objectives: ['Apresentar-se com nome, idade, país e papel.', 'Usar modelo antes de falar livremente.', 'Construir respostas em blocos curtos.', 'Gravar uma apresentação pessoal A1.'],
    teacherOpening: 'Apresentar-se em inglês não precisa começar com uma fala longa. No A1, uma boa apresentação tem blocos simples: My name is, I am from, I am years old, I am a student. Primeiro você vai copiar um modelo, depois substituir informações e só no final falar sobre você. Isso garante que a fala livre não venha antes da preparação.',
    whyItMatters: 'Saber se apresentar é essencial em aula, entrevista simples, viagem e conversa online. Também junta Grammar, Vocabulary, Reading e Listening já estudados. O erro brasileiro comum é tentar traduzir “tenho X anos” como I have X years. Nesta aula, a fala correta será treinada como chunk: I am 20 years old.',
    realLifeUseCases: ['Apresentar-se em uma aula.', 'Gravar áudio de apresentação.', 'Responder em chamada online.', 'Falar nome e país.', 'Dizer que é estudante.'],
    conceptExplanation: 'Uma introdução oral A1 é uma sequência de blocos. Você não cria tudo do zero: escolhe blocos e troca dados. A ordem segura é greeting → name → age → country/city → role. Exemplo: Hi, my name is Ana. I am 19 years old. I am from Brazil. I am a student. A fala deve ser curta, clara e pausada.',
    mentalModel: { title: 'Greeting + dados pessoais + papel', summary: 'Monte uma apresentação em blocos previsíveis.', steps: ['Hi.', 'My name is...', 'I am ... years old.', 'I am from...', 'I am a student.'] },
    stepByStep: [task('Repita o modelo completo.'), task('Troque apenas o nome.'), task('Troque apenas a idade.'), task('Troque país/cidade.'), task('Junte os blocos.'), task('Grave e confira com checklist.')],
    portugueseContrast: [task('Português: tenho 20 anos. Inglês: I am 20 years old.'), task('Português pode dizer “sou do Brasil”. Inglês: I am from Brazil.'), task('Não diga I am Brazil. Use I am Brazilian ou I am from Brazil.'), task('Em inglês A1, repetir I am é normal e seguro.')],
    guidedDiscovery: [task('Qual chunk apresenta nome?', 'My name is...'), task('Qual chunk apresenta idade?', 'I am ... years old.'), task('Qual chunk apresenta origem?', 'I am from...')],
    guidedBeforeQuiz: [task('Repita: My name is Ana.'), task('Repita: I am 19 years old.'), task('Repita: I am from Brazil.'), task('Repita: I am a student.')],
    speakingSituation: 'Você está no primeiro dia de aula e precisa se apresentar em 20 a 30 segundos.',
    modelPhrases: [phrase('Hi, my name is Ana.', 'Oi, meu nome é Ana.'), phrase('I am 19 years old.', 'Tenho 19 anos.'), phrase('I am from Brazil.', 'Sou do Brasil.'), phrase('My city is Recife.', 'Minha cidade é Recife.'), phrase('I am a student.', 'Sou estudante.'), phrase('I study English online.', 'Eu estudo inglês online.'), phrase('Nice to meet you.', 'Prazer em conhecer você.'), phrase('Thank you.', 'Obrigado.'), phrase('Hello, everyone.', 'Olá a todos.'), phrase('That is my introduction.', 'Essa é minha apresentação.')],
    pronunciationChunks: [task('My name is', 'Ligue name + is.'), task('years old', 'Fale como bloco.'), task('I am from Brazil', 'Pausa curta depois de Brazil.')],
    repeatAfterMe: [task('Hi, my name is Ana.'), task('I am 19 years old.'), task('I am from Brazil.'), task('My city is Recife.'), task('I am a student.'), task('Nice to meet you.')],
    substitutionDrills: [drill('My name is Ana.', 'My name is Luis.', ['My name is Bruno.', 'My name is Carla.']), drill('I am 19 years old.', 'I am 20 years old.', ['I am 18 years old.', 'I am 21 years old.']), drill('I am from Brazil.', 'I am from Canada.', ['I am from Japan.', 'I am from Mexico.']), drill('My city is Recife.', 'My city is Curitiba.', ['My city is São Paulo.', 'My city is Santa Maria.']), drill('I am a student.', 'I am a teacher.', ['I am a student.', 'I am an English student.'])],
    questionAnswerDrills: [drill('What is your name?', 'My name is Luis.', ['My name is Ana.', 'My name is Bruno.']), drill('How old are you?', 'I am 20 years old.', ['I am 19 years old.', 'I am 21 years old.']), drill('Where are you from?', 'I am from Brazil.', ['I am from Canada.', 'I am from Japan.']), drill('What do you do?', 'I am a student.', ['I am a teacher.', 'I study English.'])],
    buildYourAnswer: [task('Comece com greeting.', 'Hi / Hello, everyone.'), task('Diga seu nome.', 'My name is...'), task('Diga idade.', 'I am ... years old.'), task('Diga origem/cidade.', 'I am from... / My city is...'), task('Diga papel.', 'I am a student.')],
    recordingTasks: [task('Grave uma apresentação de 4 frases com nome, idade, país e papel.'), task('Grave respondendo às perguntas: What is your name? How old are you? Where are you from?'), task('Grave uma versão final de 20 segundos.')],
    speakingChecklist: [task('Usei My name is?'), task('Usei I am para idade?'), task('Usei from para país?'), task('Falei frases curtas?'), task('Não traduzi “tenho” como have?')],
    freeSpeaking: task('Fale por 20 a 30 segundos se apresentando. Use no máximo 6 frases curtas.', 'Use os blocos treinados nesta ordem: greeting → nome → idade → país/cidade → papel. Exemplo completo: "Hi! My name is [seu nome]. I am [sua idade] years old. I am from Brazil. My city is [sua cidade]. I am a student. Nice to meet you."', 'Hi! My name is Luis. I am 20 years old. I am from Brazil. My city is Santa Maria. I am a student. Nice to meet you.'),
    selfAssessment: [task('Consigo dizer meu nome?'), task('Consigo dizer idade corretamente?'), task('Consigo dizer país/cidade?'), task('Consigo gravar 20 segundos?')],
    lessonRecap: ['Introdução A1 usa blocos prontos.', 'My name is apresenta nome.', 'I am ... years old apresenta idade.', 'I am from apresenta país.', 'Fala curta e correta é melhor que fala longa e confusa.'],
    nextLessonBridge: 'Na próxima aula, você vai treinar spelling para soletrar seu nome em voz alta.',
  }),

  makeSpeakingLesson({
    id: 'A1-SPEAKING-003',
    order: 3,
    title: 'Spell your name',
    objectives: ['Soletrar nome e sobrenome em inglês.', 'Responder Can you spell that?', 'Treinar letras difíceis para brasileiros.', 'Gravar uma resposta de cadastro curta.'],
    teacherOpening: 'Soletrar em voz alta é Speaking, não apenas Listening. Você precisa produzir as letras com clareza para que outra pessoa entenda seu nome. Nesta aula, você vai treinar a situação real: alguém pergunta seu nome e depois pede para soletrar. Primeiro você repete modelos, depois troca nomes e finalmente grava seu próprio nome.',
    whyItMatters: 'Soletrar nome é comum em aula online, cadastro e atendimento. O erro brasileiro é pronunciar letras com som do português ou falar rápido demais. Aqui o objetivo é clareza. Você pode falar devagar, letra por letra, e ainda soar correto. A habilidade é responder a Can you spell your name? sem travar.',
    realLifeUseCases: ['Cadastro em curso.', 'Chamada online.', 'Confirmação de sobrenome.', 'Informar e-mail simples.', 'Pedir para repetir.'],
    conceptExplanation: 'Spelling speaking tem uma estrutura previsível: My name is Luis. L-U-I-S. My last name is Silva. S-I-L-V-A. Se a pessoa perguntar Can you spell that?, você não precisa repetir uma frase longa. Basta soletrar com pausas claras. A regra prática é separar letras, manter ritmo lento e repetir se necessário.',
    mentalModel: { title: 'Nome → soletração → confirmação', summary: 'Diga o nome, depois as letras com pausa curta.', steps: ['My name is...', 'It is spelled...', 'L-U-I-S.', 'Can you repeat?', 'Sure: L-U-I-S.'] },
    stepByStep: [task('Diga seu nome completo.'), task('Soletra o primeiro nome.'), task('Soletra o sobrenome.'), task('Faça pausa entre letras.'), task('Repita se necessário.'), task('Grave versão final.')],
    portugueseContrast: [task('As letras em inglês não têm o mesmo som do português.'), task('A, E, I e Y confundem brasileiros.'), task('Falar devagar é aceitável e recomendado.'), task('Spell é soletrar neste contexto.')],
    guidedDiscovery: [task('O que responder a Can you spell that?', 'As letras do nome.'), task('Qual é mais claro: LUIS rápido ou L-U-I-S pausado?', 'L-U-I-S pausado.'), task('Quando usar last name?', 'Para sobrenome.')],
    guidedBeforeQuiz: [task('Repita: Can you spell your name?'), task('Repita: My name is Luis.'), task('Repita: L-U-I-S.'), task('Repita: My last name is Silva. S-I-L-V-A.')],
    speakingSituation: 'Você está fazendo cadastro em uma aula e precisa soletrar nome e sobrenome.',
    modelPhrases: [phrase('What is your name?', 'Qual é seu nome?'), phrase('My name is Luis Silva.', 'Meu nome é Luis Silva.'), phrase('Can you spell your first name?', 'Você pode soletrar seu primeiro nome?'), phrase('L-U-I-S.', 'L-U-I-S.'), phrase('Can you spell your last name?', 'Você pode soletrar seu sobrenome?'), phrase('S-I-L-V-A.', 'S-I-L-V-A.'), phrase('Can you repeat that?', 'Você pode repetir?'), phrase('Sure.', 'Claro.'), phrase('Please repeat.', 'Por favor, repita.'), phrase('Thank you.', 'Obrigado.')],
    pronunciationChunks: [task('Can you spell', 'Fale como bloco.'), task('first name', 'Pausa depois de first name.'), task('L-U-I-S', 'Pausa curta entre letras.')],
    repeatAfterMe: [task('What is your name?'), task('My name is Luis Silva.'), task('Can you spell your first name?'), task('L-U-I-S.'), task('Can you spell your last name?'), task('S-I-L-V-A.')],
    substitutionDrills: [drill('My name is Luis.', 'My name is Ana.', ['My name is Bruno.', 'My name is Carla.']), drill('L-U-I-S.', 'A-N-A.', ['B-R-U-N-O.', 'C-A-R-L-A.']), drill('My last name is Silva.', 'My last name is Santos.', ['My last name is Costa.', 'My last name is Lima.']), drill('S-I-L-V-A.', 'S-A-N-T-O-S.', ['C-O-S-T-A.', 'L-I-M-A.']), drill('Can you spell your first name?', 'Can you spell your last name?', ['Can you repeat that?', 'Please repeat.'])],
    questionAnswerDrills: [drill('Can you spell your name?', 'L-U-I-S.', ['A-N-A.', 'B-R-U-N-O.']), drill('Can you spell your last name?', 'S-I-L-V-A.', ['S-A-N-T-O-S.', 'C-O-S-T-A.']), drill('Can you repeat that?', 'Sure: L-U-I-S.', ['Sure: A-N-A.', 'Sure: S-I-L-V-A.']), drill('What is your first name?', 'My first name is Luis.', ['My first name is Ana.', 'My first name is Bruno.'])],
    buildYourAnswer: [task('Diga o nome.', 'My name is...'), task('Introduza a soletração.', 'It is spelled...'), task('Soletra com pausas.', 'L-U-I-S'), task('Soletra sobrenome.', 'S-I-L-V-A'), task('Finalize educadamente.', 'Thank you.')],
    recordingTasks: [task('Grave: My name is ___. It is spelled ___.'), task('Grave nome + sobrenome soletrados.'), task('Grave respondendo Can you repeat that?')],
    speakingChecklist: [task('Fiz pausa entre letras?'), task('Usei first name e last name corretamente?'), task('Pronunciei devagar?'), task('Consegui repetir sem travar?'), task('Falei uma resposta curta?')],
    freeSpeaking: task('Simule um cadastro de 20 segundos: diga nome, sobrenome e soletração.', 'Use nome real ou fictício.'),
    selfAssessment: [task('Consigo responder Can you spell?'), task('Consigo soletrar primeiro nome?'), task('Consigo soletrar sobrenome?'), task('Consigo pedir repetição?')],
    lessonRecap: ['Spell significa soletrar.', 'Speaking de spelling exige clareza, não velocidade.', 'First name é primeiro nome.', 'Last name é sobrenome.', 'Pausas entre letras ajudam muito.'],
    nextLessonBridge: 'Na próxima aula, você vai falar país, nacionalidade e cidade em uma mini apresentação oral.',
  }),

  makeSpeakingLesson({
    id: 'A1-SPEAKING-004',
    order: 4,
    title: 'Say your country and city',
    objectives: ['Dizer país, nacionalidade e cidade em voz alta.', 'Responder Where are you from?', 'Usar I live in para cidade.', 'Gravar uma mini fala sobre origem.'],
    teacherOpening: 'Agora você vai transformar country, nationality e city em fala. A ordem é simples: I am from Brazil. I am Brazilian. I live in Santa Maria. A dificuldade não está em criar frases novas; está em falar os blocos com clareza e escolher country ou city corretamente. Primeiro você repete modelos, depois substitui lugares e no final grava uma resposta curta.',
    whyItMatters: 'Falar de onde você é aparece em quase toda apresentação. Também conecta Listening e Vocabulary: você ouviu Where are you from? e agora precisa responder. Brasileiros erram dizendo I am Brazil ou confundindo city com country. Nesta aula, você vai treinar a resposta correta em voz alta até ficar automática.',
    realLifeUseCases: ['Responder Where are you from?', 'Dizer sua cidade.', 'Apresentar nacionalidade.', 'Falar origem em aula online.', 'Criar uma mini apresentação com país e cidade.'],
    conceptExplanation: 'Para falar origem, use from + país: I am from Brazil. Para nacionalidade, use I am Brazilian. Para cidade onde mora, use I live in + city. Essas frases são blocos separados. Não misture país e nacionalidade. Brazil é país; Brazilian é nacionalidade. Speaking A1 pede clareza e ordem: país, nacionalidade, cidade.',
    mentalModel: { title: 'Country → nationality → city', summary: 'Fale em três blocos: origem, identidade e cidade.', steps: ['I am from Brazil.', 'I am Brazilian.', 'I live in Santa Maria.', 'My city is Santa Maria.'] },
    stepByStep: [task('Responda Where are you from?'), task('Diga nacionalidade.'), task('Diga cidade com I live in.'), task('Junte em 3 frases.'), task('Adicione greeting se quiser.'), task('Grave a fala final.')],
    portugueseContrast: [task('Não diga I am Brazil. Diga I am Brazilian ou I am from Brazil.'), task('Sou de Santa Maria pode virar I am from Santa Maria, mas para A1 pratique I live in Santa Maria.'), task('City é cidade; country é país.'), task('Brazilian é nacionalidade/adjetivo.')],
    guidedDiscovery: [task('Where are you from? pede o quê?', 'Origem/país.'), task('I live in pede o quê depois?', 'Cidade.'), task('Brazilian é país ou nacionalidade?', 'Nacionalidade.')],
    guidedBeforeQuiz: [task('Repita: Where are you from?'), task('Repita: I am from Brazil.'), task('Repita: I am Brazilian.'), task('Repita: I live in Santa Maria.')],
    speakingSituation: 'Você está se apresentando para uma turma internacional e precisa dizer país, nacionalidade e cidade.',
    modelPhrases: [phrase('Where are you from?', 'De onde você é?'), phrase('I am from Brazil.', 'Sou do Brasil.'), phrase('Are you Brazilian?', 'Você é brasileiro?'), phrase('Yes, I am Brazilian.', 'Sim, sou brasileiro.'), phrase('What is your city?', 'Qual é sua cidade?'), phrase('My city is Santa Maria.', 'Minha cidade é Santa Maria.'), phrase('I live in Santa Maria.', 'Eu moro em Santa Maria.'), phrase('She is from Brazil.', 'Ela é do Brasil.'), phrase('He lives in Curitiba.', 'Ele mora em Curitiba.'), phrase('Nice to meet you.', 'Prazer em conhecer você.')],
    pronunciationChunks: [task('Where are you from?', 'Fale como bloco.'), task('I am from Brazil', 'Faça pausa depois de Brazil.'), task('I live in', 'Ligue live + in.')],
    repeatAfterMe: [task('Where are you from?'), task('I am from Brazil.'), task('I am Brazilian.'), task('My city is Santa Maria.'), task('I live in Santa Maria.'), task('Nice to meet you.')],
    substitutionDrills: [drill('I am from Brazil.', 'I am from Canada.', ['I am from Japan.', 'I am from Mexico.']), drill('I am Brazilian.', 'I am Canadian.', ['I am Japanese.', 'I am Mexican.']), drill('I live in Santa Maria.', 'I live in Recife.', ['I live in Curitiba.', 'I live in São Paulo.']), drill('My city is Santa Maria.', 'My city is Recife.', ['My city is Curitiba.', 'My city is Brasília.']), drill('She is from Brazil.', 'He is from Brazil.', ['They are from Brazil.', 'We are from Brazil.'])],
    questionAnswerDrills: [drill('Where are you from?', 'I am from Brazil.', ['I am from Canada.', 'I am from Japan.']), drill('Are you Brazilian?', 'Yes, I am Brazilian.', ['No, I am Canadian.', 'Yes, I am.']), drill('What is your city?', 'My city is Santa Maria.', ['My city is Recife.', 'My city is Curitiba.']), drill('Where do you live?', 'I live in Santa Maria.', ['I live in Recife.', 'I live in Curitiba.'])],
    buildYourAnswer: [task('Comece com origem.', 'I am from Brazil.'), task('Diga nacionalidade.', 'I am Brazilian.'), task('Diga cidade.', 'My city is...'), task('Diga onde mora.', 'I live in...'), task('Finalize.', 'Nice to meet you.')],
    recordingTasks: [task('Grave 3 frases: I am from ___. I am ___. I live in ___.'), task('Grave respondendo Where are you from? Are you Brazilian? What is your city?'), task('Grave uma mini apresentação de 20 segundos.')],
    speakingChecklist: [task('Usei from para país?'), task('Não disse I am Brazil?'), task('Usei Brazilian para nacionalidade?'), task('Usei live in para cidade?'), task('Falei em blocos curtos?')],
    freeSpeaking: task('Fale por 20 segundos dizendo país, nacionalidade, cidade e uma despedida curta.', 'Use os blocos treinados.'),
    selfAssessment: [task('Consigo responder Where are you from?'), task('Consigo dizer nacionalidade?'), task('Consigo dizer cidade?'), task('Consigo gravar sem ler tudo?')],
    lessonRecap: ['From + country fala origem.', 'Brazilian é nacionalidade.', 'I live in + city fala onde mora.', 'City e country são diferentes.', 'Speaking melhora quando você usa blocos treinados.'],
    nextLessonBridge: 'Speaking Foundations está pronto para alimentar Writing e futuras unidades de conversa A1.',
  }),
]);

export const A1_DEEP_SPEAKING_BY_PILLAR = Object.freeze({
  speaking: A1_DEEP_SPEAKING_FOUNDATIONS,
});
