import { createGrammarLesson } from '../../../schemas/index.js';

const level = 'A1';
const status = 'ready';
function q(question, options, answer, explanation = '', context = '') { return { question, options, answer, explanation, context }; }
function ex(english, translation, why, warning = '') { return { english, translation, why, warning }; }
function mistake(wrong, right, why, howToAvoid, miniPractice = '') { return { wrong, right, why, howToAvoid, miniPractice }; }
function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function step(text, note = '') { return { text, note }; }

export const A1_DEEP_GRAMMAR_FOUNDATIONS = Object.freeze([
  createGrammarLesson({
    id: 'A1-GRAMMAR-001',
    level,
    order: 1,
    title: 'Subject pronouns',
    status,
    estimatedMinutes: 55,
    objectives: [
      'Entender por que o inglês precisa de sujeito claro na frase.',
      'Escolher corretamente I, you, he, she, it, we e they.',
      'Substituir nomes, objetos e grupos por pronomes sem traduzir palavra por palavra.',
      'Evitar erros comuns de brasileiros, como pular o sujeito ou usar he/she para objetos.',
    ],
    teacherOpening: 'Antes de decorar I, you, he, she, it, we e they, você precisa entender a lógica: o inglês gosta de frases com sujeito visível. Em português, muitas vezes dizemos “sou brasileiro”, “é meu celular”, “estamos prontos” e o sujeito fica escondido na forma do verbo ou no contexto. Em inglês A1, esse atalho geralmente não funciona. A frase precisa mostrar quem estamos falando antes do verbo. Os subject pronouns resolvem isso: eles dizem quem é o sujeito da frase sem repetir nomes o tempo todo.',
    whyItMatters: 'Subject pronouns são uma das bases do inglês porque quase todas as frases que você vai montar depois dependem deles. Eles ajudam você a escolher o verbo correto, organizar a frase e evitar traduções literais do português. Se você erra o pronome, a frase inteira fica confusa: a pessoa pode entender que você está falando de outra pessoa, de um objeto ou de um grupo diferente. Dominar isso agora deixa o verb to be, perguntas, negativas, possessivos e frases simples muito mais fáceis.',
    realLifeUseCases: [
      'Apresentar você mesmo: I am Luis.',
      'Falar de outra pessoa: She is my sister.',
      'Falar de um objeto: It is my phone.',
      'Falar de você e outra pessoa: We are friends.',
      'Falar de um grupo: They are students.',
    ],
    conceptExplanation: 'Um subject pronoun é uma palavra que substitui o nome do sujeito da frase. O sujeito é quem a frase está apresentando, descrevendo ou colocando em ação. Em “Luis is a student”, o sujeito é Luis. Para não repetir Luis várias vezes, usamos “he”: “He is a student”. Em “my phone is black”, o sujeito é “my phone”. Como é uma coisa, usamos “it”: “It is black”. A regra principal é: primeiro descubra quem ou o que é o sujeito; depois escolha o pronome que representa esse sujeito; depois coloque o verbo ou a informação. A lógica não é decorar tradução isolada, é identificar o papel da palavra na frase.',
    mentalModel: {
      title: 'Pessoa/coisa → pronome → verbo/informação',
      summary: 'Pense sempre em três passos: quem é o sujeito, qual pronome representa esse sujeito, qual informação vem depois.',
      steps: [
        'Luis → he → He is my friend.',
        'Ana → she → She is my sister.',
        'My phone → it → It is black.',
        'Ana and Luis → they → They are students.',
        'You and I → we → We are ready.',
      ],
    },
    stepByStep: [
      step('Encontre o sujeito da ideia.', 'Pergunte: estou falando de quem ou do quê?'),
      step('Veja se o sujeito é você, a pessoa com quem você fala, outra pessoa, uma coisa ou um grupo.', 'Essa decisão define o pronome.'),
      step('Escolha o pronome sujeito correto.', 'I, you, he, she, it, we ou they.'),
      step('Coloque o pronome antes do verbo.', 'Em frases A1, a ordem segura é sujeito + verbo + informação.'),
      step('Revise se você não pulou o sujeito por influência do português.', 'Se a frase começou direto com am/is/are, provavelmente falta pronome.'),
      step('Revise se você não usou he/she para objeto.', 'Objetos, ideias e lugares normalmente usam it no A1.'),
    ],
    portugueseContrast: [
      task('Português permite sujeito escondido: “sou estudante”. Inglês pede sujeito visível: “I am a student”.', 'A lógica é diferente: em inglês, o aluno precisa escrever I.'),
      task('Português diz “é meu celular” sem dizer “ele”. Inglês precisa de it: “It is my phone”.', 'Para coisa ou objeto, use it, não he/she.'),
      task('Português usa “você” e “vocês”. Inglês usa you para os dois.', 'O contexto mostra se é uma pessoa ou mais de uma.'),
      task('Português pode repetir nomes naturalmente. Inglês usa pronomes para evitar repetição.', 'Maria is here. She is my friend.'),
    ],
    guidedDiscovery: [
      task('Leia: “Ana is my friend. Ana is kind.” O que fica repetido?', 'O nome Ana aparece duas vezes. Em inglês natural, substituímos a segunda ocorrência por she.'),
      task('Leia: “My phone is new. My phone is black.” O que representa my phone?', 'É um objeto. O pronome seguro é it.'),
      task('Leia: “Luis and Pedro are here.” Quantas pessoas aparecem?', 'Duas pessoas. O pronome seguro é they.'),
    ],
    guidedBeforeQuiz: [
      task('Vamos juntos: “Maria is my sister.” Maria é mulher/menina, então o pronome é she. Resultado: “She is my sister.”'),
      task('Vamos juntos: “The book is blue.” The book é uma coisa, então o pronome é it. Resultado: “It is blue.”'),
      task('Vamos juntos: “You and I are friends.” Eu estou incluído no grupo, então o pronome é we. Resultado: “We are friends.”'),
      task('Vamos juntos: “Ana and Lucas are students.” São outras pessoas, eu não estou incluído, então o pronome é they. Resultado: “They are students.”'),
    ],
    grammarGoal: 'Usar pronomes sujeitos para indicar claramente quem ou o que é o sujeito da frase antes do verbo.',
    formationGuide: [
      task('Regra base: subject pronoun + verb + information.', 'I am Luis. / She is Ana. / They are students.'),
      task('Para uma pessoa falando de si mesma, use I.', 'I am Brazilian.'),
      task('Para a pessoa com quem você fala, use you.', 'You are my friend.'),
      task('Para homem/menino, use he.', 'Pedro → he.'),
      task('Para mulher/menina, use she.', 'Ana → she.'),
      task('Para coisa, animal não identificado, lugar ou ideia, use it.', 'my phone → it.'),
      task('Para você + outra pessoa, use we.', 'You and I → we.'),
      task('Para duas ou mais pessoas/coisas fora de você, use they.', 'Ana and Lucas → they.'),
    ],
    whenToUse: [
      task('Use quando o nome já foi citado e você não quer repetir.', 'Maria is here. She is ready.'),
      task('Use quando a frase começa com verbo em português, mas precisa de sujeito em inglês.', 'Sou estudante → I am a student.'),
      task('Use para substituir objetos no singular.', 'My phone is new. It is black.'),
      task('Use para substituir grupos de pessoas ou coisas.', 'My friends are here. They are happy.'),
      task('Use para montar frases curtas de apresentação, descrição e localização.', 'He is from Brazil. It is on the table.'),
    ],
    whenNotToUse: [
      task('Não use it para pessoa conhecida.', 'Ana is here → She is here, não It is here.'),
      task('Não use he/she para objeto.', 'My phone is black → It is black, não He is black.'),
      task('Não use we se você não está incluído.', 'Ana and Lucas → they, não we.'),
      task('Não pule o pronome só porque em português a frase parece completa.', '“Am tired” não é seguro; use “I am tired”.'),
    ],
    grammarTable: [
      { label: 'I', pattern: 'eu', example: 'I am Luis.', note: 'Sempre com letra maiúscula.' },
      { label: 'you', pattern: 'você / vocês', example: 'You are my friend.', note: 'Pode ser singular ou plural.' },
      { label: 'he', pattern: 'ele', example: 'He is Pedro.', note: 'Homem/menino.' },
      { label: 'she', pattern: 'ela', example: 'She is Ana.', note: 'Mulher/menina.' },
      { label: 'it', pattern: 'isso / ele / ela para coisa', example: 'It is my phone.', note: 'Objeto, coisa, lugar, ideia ou animal quando o gênero não importa.' },
      { label: 'we', pattern: 'nós', example: 'We are students.', note: 'Você está incluído no grupo.' },
      { label: 'they', pattern: 'eles / elas', example: 'They are friends.', note: 'Duas ou mais pessoas/coisas fora de você.' },
    ],
    teacherExamples: [
      ex('I am Luis.', 'Eu sou Luis.', 'I aparece porque o falante está falando de si mesmo. Em inglês, não começamos apenas com “am” nesse tipo de frase.', 'Não diga “Am Luis”.'),
      ex('I am from Brazil.', 'Eu sou do Brasil.', 'A frase informa origem. O sujeito I vem antes de am para deixar claro quem é do Brasil.', 'I sempre aparece com letra maiúscula.'),
      ex('You are my friend.', 'Você é meu amigo/minha amiga.', 'You representa a pessoa com quem estou falando. Ele pode significar você ou vocês.', 'O contexto decide se é singular ou plural.'),
      ex('You are students.', 'Vocês são estudantes.', 'Mesmo falando com mais de uma pessoa, o pronome continua you.', 'Não existe “yous” no inglês padrão.'),
      ex('He is Pedro.', 'Ele é Pedro.', 'He substitui um nome masculino, neste caso Pedro.', 'Não use he para objeto.'),
      ex('He is my brother.', 'Ele é meu irmão.', 'He mostra que estou falando de um homem/menino já identificado.', 'Depois, o verbo precisa combinar: he is.'),
      ex('She is Ana.', 'Ela é Ana.', 'She substitui um nome feminino, neste caso Ana.', 'Não use she para objeto só porque em português “mesa” é feminino.'),
      ex('She is my mother.', 'Ela é minha mãe.', 'She representa uma mulher conhecida no contexto.', 'A escolha é pela pessoa, não pela palavra em português.'),
      ex('It is my phone.', 'É meu celular.', 'Em português podemos começar com “é”; em inglês usamos it para representar o objeto.', 'Não diga “Is my phone”.'),
      ex('It is black.', 'Ele/isso é preto.', 'It retoma “my phone”. Como phone é objeto, o pronome é it.', 'Não use he só porque em português “celular” pode parecer “ele”.'),
      ex('It is on the table.', 'Está na mesa.', 'Para falar de localização de uma coisa, it funciona como sujeito.', 'Em inglês, a frase precisa de sujeito antes de is.'),
      ex('We are ready.', 'Nós estamos prontos.', 'We inclui o falante e pelo menos mais uma pessoa.', 'Use we quando você faz parte do grupo.'),
      ex('We are friends.', 'Nós somos amigos.', 'We substitui “you and I” ou “my friend and I”.', 'Não use they se você está incluído.'),
      ex('They are students.', 'Eles/elas são estudantes.', 'They substitui um grupo de pessoas fora de você.', 'They pede are em frases com to be.'),
      ex('They are my parents.', 'Eles são meus pais.', 'They pode representar duas pessoas: mother and father → they.', 'Não use he ou she para grupo.'),
      ex('Ana is my sister. She is kind.', 'Ana é minha irmã. Ela é gentil.', 'Na segunda frase, she evita repetir Ana.', 'O pronome precisa combinar com a pessoa.'),
      ex('Luis is my friend. He is from Brazil.', 'Luis é meu amigo. Ele é do Brasil.', 'He substitui Luis porque Luis é homem/menino.', 'Não troque por she.'),
      ex('My phone is new. It is black.', 'Meu celular é novo. Ele é preto.', 'It substitui my phone porque é uma coisa.', 'Português pode dizer “ele”, mas inglês usa it para objeto.'),
      ex('Ana and Luis are here. They are ready.', 'Ana e Luis estão aqui. Eles estão prontos.', 'They substitui duas pessoas.', 'Não use we se você não está nesse grupo.'),
      ex('You and I are a team. We are ready.', 'Você e eu somos um time. Nós estamos prontos.', 'We substitui you and I porque o falante está incluído.', 'Não use they para um grupo que inclui você.'),
      ex('The books are new. They are on the table.', 'Os livros são novos. Eles estão na mesa.', 'They também pode substituir coisas no plural.', 'It seria singular; para plural use they.'),
      ex('My city is small. It is beautiful.', 'Minha cidade é pequena. Ela é bonita.', 'City é lugar/coisa no inglês básico, então usamos it.', 'Não use she por causa de “cidade” em português.'),
    ],
    commonBrazilianMistakes: [
      mistake('Am Brazilian.', 'I am Brazilian.', 'Em português “sou brasileiro” já mostra o sujeito pela forma verbal. Em inglês, am precisa de I antes.', 'Antes de am, pergunte: quem? Se for eu, coloque I.', 'Complete: ___ am Brazilian.'),
      mistake('Is my phone.', 'It is my phone.', 'Em português “é meu celular” parece completo, mas inglês pede sujeito visível.', 'Para objeto singular, coloque it antes de is.', 'Transforme: my phone → ___ is my phone.'),
      mistake('Ana is my sister. He is kind.', 'Ana is my sister. She is kind.', 'O aluno traduziu “ele/ela” sem conferir a pessoa. Ana é mulher/menina.', 'Identifique a pessoa antes de escolher he ou she.', 'Ana → ___'),
      mistake('My phone is new. He is black.', 'My phone is new. It is black.', 'Brasileiros às vezes usam he porque em português “celular” pode ser tratado como ele.', 'Para coisa/objeto, use it.', 'my phone → ___'),
      mistake('Luis and Pedro are here. We are ready.', 'Luis and Pedro are here. They are ready.', 'We inclui quem fala. Se estou só falando de Luis e Pedro, o grupo é they.', 'Pergunte: eu estou incluído? Se não, use they.', 'Luis and Pedro → ___'),
      mistake('You and I are friends. They are friends.', 'You and I are friends. We are friends.', 'You and I inclui o falante. Por isso, o pronome é we.', 'Quando “I” aparece dentro do grupo, pense em we.', 'You and I → ___'),
      mistake('She is my book.', 'It is my book.', 'Book é uma coisa. O gênero da palavra em português não decide o pronome em inglês.', 'Para objetos, use it no singular.', 'the book → ___'),
      mistake('They is students.', 'They are students.', 'O pronome they normalmente combina com are no verb to be.', 'Depois de escolher o pronome, confira o verbo.', 'They ___ students.'),
      mistake('I am Luis. I is from Brazil.', 'I am Luis. I am from Brazil.', 'O pronome I combina com am, não com is.', 'Memorize o par seguro: I am.', 'I ___ from Brazil.'),
      mistake('My parents are here. He is happy.', 'My parents are here. They are happy.', 'Parents é plural, então o pronome é they.', 'Plural de pessoas ou coisas: they.', 'my parents → ___'),
    ],
    controlledPractice: [
      task('Modelo guiado: Luis is my friend → He is my friend.', 'Luis é homem/menino, então use he.'),
      task('Modelo guiado: Ana is my sister → She is my sister.', 'Ana é mulher/menina, então use she.'),
      task('Modelo guiado: My phone is new → It is new.', 'Phone é objeto, então use it.'),
      task('Modelo guiado: Ana and Luis are students → They are students.', 'Duas pessoas fora de você, então use they.'),
      task('Modelo guiado: You and I are ready → We are ready.', 'O grupo inclui I, então use we.'),
    ],
    guidedPractice: [
      q('Complete: ___ am a student.', ['He', 'They', 'I'], 'I', 'Am combina com I. A frase fala de “eu”.'),
      q('Complete: ___ is Ana.', ['She', 'They', 'We'], 'She', 'Ana é uma mulher/menina, então use she.'),
      q('Complete: ___ is my phone.', ['He', 'It', 'They'], 'It', 'Phone é objeto singular, então use it.'),
      q('Complete: Luis is my brother. ___ is kind.', ['He', 'She', 'It'], 'He', 'Luis é homem/menino, então use he.'),
      q('Complete: My mother is here. ___ is happy.', ['He', 'They', 'She'], 'She', 'Mother é mulher, então use she.'),
      q('Complete: Ana and Luis are friends. ___ are students.', ['It', 'They', 'He'], 'They', 'Ana and Luis formam um grupo fora de você.'),
      q('Complete: You and I are a team. ___ are ready.', ['They', 'It', 'We'], 'We', 'You and I inclui o falante, então use we.'),
      q('Complete: The books are new. ___ are on the table.', ['They', 'It', 'He'], 'They', 'Books está no plural; coisas no plural usam they.'),
      q('Qual frase está correta?', ['Is my city.', 'She is my city.', 'It is my city.'], 'It is my city.', 'City é lugar/coisa no inglês A1, então use it.'),
      q('Qual pronome substitui “my parents”?', ['They', 'He', 'It'], 'They', 'Parents é plural, então they.'),
    ],
    errorCorrectionPractice: [
      q('Corrija: Am tired.', ['I am tired.', 'It am tired.', 'They is tired.'], 'I am tired.', 'A frase precisa de sujeito. Para “eu”, use I.'),
      q('Corrija: My phone is new. He is black.', ['My phone is new. It is black.', 'My phone is new. She is black.', 'My phone is new. They is black.'], 'My phone is new. It is black.', 'Objeto singular usa it.'),
      q('Corrija: Ana is here. He is ready.', ['Ana is here. She is ready.', 'Ana is here. It is ready.', 'Ana is here. They are ready.'], 'Ana is here. She is ready.', 'Ana é mulher/menina, então she.'),
      q('Corrija: Luis and Ana are here. We are happy.', ['Luis and Ana are here. They are happy.', 'Luis and Ana are here. He is happy.', 'Luis and Ana are here. It is happy.'], 'Luis and Ana are here. They are happy.', 'Se você não está incluído, o grupo é they.'),
      q('Corrija: The book is blue. She is new.', ['The book is blue. It is new.', 'The book is blue. He is new.', 'The book is blue. They are new.'], 'The book is blue. It is new.', 'Book é coisa, então it.'),
    ],
    transformationPractice: [
      q('Substitua “Pedro”: Pedro is my friend.', ['He is my friend.', 'She is my friend.', 'It is my friend.'], 'He is my friend.', 'Pedro → he.'),
      q('Substitua “Maria”: Maria is from Brazil.', ['They are from Brazil.', 'She is from Brazil.', 'It is from Brazil.'], 'She is from Brazil.', 'Maria → she.'),
      q('Substitua “the phone”: The phone is black.', ['It is black.', 'He is black.', 'She is black.'], 'It is black.', 'The phone → it.'),
      q('Substitua “my friends”: My friends are here.', ['We are here.', 'It is here.', 'They are here.'], 'They are here.', 'My friends → they.'),
      q('Substitua “you and I”: You and I are ready.', ['They are ready.', 'We are ready.', 'It is ready.'], 'We are ready.', 'You and I inclui o falante, então we.'),
    ],
    translationPractice: [
      q('Traduza de forma segura: “Eu sou estudante.”', ['I am a student.', 'Am a student.', 'He is a student.'], 'I am a student.', 'Em inglês, coloque I antes de am.'),
      q('Traduza: “Ela é minha irmã.”', ['She is my sister.', 'He is my sister.', 'It is my sister.'], 'She is my sister.', 'Ela pessoa feminina → she.'),
      q('Traduza: “É meu celular.”', ['It is my phone.', 'He is my phone.', 'Is my phone.'], 'It is my phone.', 'Objeto singular → it.'),
      q('Traduza: “Eles são meus amigos.”', ['They are my friends.', 'We are my friends.', 'It is my friends.'], 'They are my friends.', 'Grupo fora de você → they.'),
    ],
    productionTasks: [
      task('Escreva 3 frases sobre você usando I.', 'Modelo: I am Luis. / I am from Brazil. / I am a student.'),
      task('Escreva 3 frases sobre uma pessoa da sua família usando he ou she.', 'Escolha uma pessoa real e confira se o pronome combina.'),
      task('Escreva 3 frases sobre objetos próximos usando it.', 'Modelo: It is my phone. It is black. It is on the table.'),
      task('Escreva 3 frases sobre grupos usando we e they.', 'Use we quando você estiver incluído; use they quando estiver falando de outras pessoas.'),
    ],
    selfAssessment: [
      task('Consigo explicar por que inglês precisa de sujeito visível?'),
      task('Consigo escolher entre he, she e it sem pensar no gênero da palavra em português?'),
      task('Consigo diferenciar we e they perguntando se eu estou incluído no grupo?'),
      task('Consigo corrigir frases que começam direto com am/is/are?'),
    ],
    lessonRecap: [
      'Subject pronouns mostram quem ou o que é o sujeito da frase.',
      'Em inglês A1, não pule o sujeito: use I, you, he, she, it, we ou they antes do verbo.',
      'He/she são para pessoas; it é para objeto, coisa, lugar ou ideia no singular.',
      'We inclui o falante; they normalmente fala de um grupo fora do falante.',
      'Antes de responder, pense: quem é o sujeito, qual pronome representa esse sujeito e qual verbo vem depois.',
    ],
    nextLessonBridge: 'Na próxima aula de Grammar, o pronome que você escolher vai decidir a forma correta do verb to be: I am, he/she/it is, you/we/they are.',
    masteryCriteria: { minPracticeAccuracy: 80, requiredProduction: 3, tags: ['a1-grammar', 'subject-pronouns', 'deep-approved-target'] },
  }),
]);

export const A1_DEEP_GRAMMAR_BY_PILLAR = Object.freeze({
  grammar: A1_DEEP_GRAMMAR_FOUNDATIONS,
});
