import { createGrammarLesson, createVocabularyLesson } from '../../../schemas/index.js';

const level = 'C2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 75, tags: ['c2-3', 'complex-discourse', 'mastery', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }

export const C2_DEEP_COMPLEX_DISCOURSE_PART1 = Object.freeze([

  // ─── GRAMMAR-005: Advanced conditional constructions ─────────────────────────
  createGrammarLesson({
    ...common,
    id: 'C2-GRAMMAR-005',
    order: 5,
    title: 'Grammar: Advanced conditional constructions — the complete conditional system at C2',
    objectives: [
      'Command the full English conditional system at C2, from Type 0 to mixed conditionals.',
      'Use modal variants (can, may, might, should) in the if-clause result to express nuanced degrees of possibility and obligation.',
      'Produce and recognise formal conditional inversion structures (Should…, Were…, Had…) without the word "if".',
      'Identify and avoid the most persistent Brazilian errors in the conditional system, including the would-in-if-clause error.',
      'Choose the correct mixed conditional type depending on whether the hypothetical involves a past event, a present state, or both.',
    ],
    teacherOpening: 'Most learners know the four "types" of conditional. At C2, the question is not whether you know them but whether you can use them with the full range of modals, recognise inverted formal variants, and select the correct mixed type for a specific logical relationship. The conditional system is not four boxes — it is a single system for expressing hypothetical relationships, and the boxes are heuristics, not rules. This lesson maps the whole system.',
    portugueseContrast: [task('Em Grammar: Advanced conditional constructions — the complete conditional system at C2, observe que a estrutura do inglês difere da ordem natural do português.'), task('Não traduza literalmente; identifique o padrão do inglês antes de produzir.')], 
    grammarTable: {
      headers: ['Conditional type', 'Structure', 'Key examples', 'Nuance / C2 note'],
      rows: [
        ['Type 0 — habit or natural law (with reduced forms)', '"If + present simple → present simple." Reduced: "When / Whenever + present simple → present simple."', '"If you heat ice, it melts." / "When governments cut funding for the arts, cultural production suffers." / "Whenever this variable is manipulated, the effect size decreases."', 'Type 0 is often used in academic writing with "when" or "whenever" rather than "if" to signal that the condition reliably produces the result. "If" implies the condition may or may not obtain; "when/whenever" implies it regularly does. In formal writing, the result clause can use a modal: "If investment falls, growth will typically slow."'],
        ['Type 1 — real conditional (with modal variants)', '"If + present simple → will/shall/can/may/might/should + infinitive."', '"If the study replicates, it will change the field." / "If the intervention is introduced early, outcomes may improve." / "If you need clarification, you should contact the supervisor directly." / "If the proposal is accepted, we can begin immediately."', 'The result clause is not limited to "will." Use "may/might" to signal possibility rather than certainty; "can" for capability or permission; "should" for advice or recommended action. Calibrating the modal to the epistemic status of the claim is a C2 skill — not every real condition has a certain result.'],
        ['Type 2 — unreal present or future', '"If + past simple → would/could/might + infinitive."', '"If the government increased funding, researchers could explore these questions more rigorously." / "If I were advising the committee, I would recommend a phased approach." / "If this hypothesis were correct, we would expect to see X."', 'Use "were" (not "was") with all subjects in formal, academic, and written registers. "If I were" is standard in formal writing; "if I was" is acceptable in informal speech but not at C2 academic register. Use "could" to signal capability and "might" to signal possibility in the result.'],
        ['Type 3 — unreal past', '"If + past perfect → would/could/might have + past participle."', '"If the researchers had controlled for confounding variables, the results would have been more reliable." / "If the intervention had been introduced earlier, outcomes might have been significantly better." / "Had this been considered, the design could have been improved."', 'The most common error is "would have" in the if-clause: NEVER "If it would have been the case that…" The if-clause requires past perfect. Use "might have" for possibility, "could have" for capability, "would have" for the most certain hypothetical result.'],
        ['Mixed conditional — unreal past → present result', '"If + past perfect → would/could/might + infinitive (present)."', '"If the researchers had taken a different methodological approach, the field would look very different today." / "If the policy had been implemented in the 1990s, we might now have a more equitable distribution of resources."', 'This type imagines a past event that did not happen and traces its consequence into the present. The if-clause is past perfect (as in Type 3); the result clause is present conditional (as in Type 2). Students often use a uniform Type 3 structure; the mixed type is needed when the result is ongoing or current, not a past counterfactual.'],
        ['Mixed conditional — unreal present state → past result', '"If + past simple → would/could/might have + past participle."', '"If the organism were less resilient by nature, it would not have survived the experiment\'s conditions." / "If she were not an expert in the field, she could not have identified the flaw so quickly."', 'This type takes a present (or permanent) hypothetical state and asks what would have happened in the past if that state obtained. The if-clause is past simple (as in Type 2); the result clause is past conditional (as in Type 3). It is rarer than the other mixed type but important for precision when the hypothetical is about an inherent quality, not a specific event.'],
        ['Formal inversion — should / were to / had (no if)', '"Should + subject + infinitive…" / "Were + subject + to + infinitive…" / "Had + subject + past participle…"', '"Should the proposal be rejected, the team will seek alternative funding." / "Were the data to support a different interpretation, the argument would need to be revised." / "Had the review committee considered this evidence, the decision might have been different."', 'These are formal variants of Types 1, 2, and 3 respectively, produced by inverting subject and auxiliary and dropping "if." "Should" = Type 1 formal; "Were … to" = Type 2 formal (note: "were + subject + to + infinitive," not "were + subject + infinitive"); "Had" = Type 3 formal. These constructions are standard in academic, legal, and official writing. In formal prose, they signal precision and register competence.'],
      ],
    },
    brazilianMistakes: [
      { mistake: '"If the government would invest more in education, the outcomes would be better."', correction: '"If the government invested more in education [Type 2], the outcomes would be better." — or, for a real conditional: "If the government invests more in education [Type 1], the outcomes will be better." The word "would" NEVER appears in the if-clause of a conditional in standard English.', explanation: 'In Brazilian Portuguese, the future of the past (conditional tense: "investisse") can appear in both the condition clause and the result. English requires a modal in the result only; the if-clause uses the indicative or past tense form. This is the single most persistent conditional error among Brazilian learners at all levels — it must be eliminated at C2.' },
      { mistake: '"If I was the director of this department, I would restructure the curriculum."', correction: '"If I were the director of this department, I would restructure the curriculum." — "were" is required in all formal and academic contexts with all subjects (I/he/she/it/we/they).', explanation: '"If I was" is accepted in informal spoken English, but at C2 academic and formal written register, "were" is the required subjunctive form. The pattern "if I were you," "if she were here," "if it were possible" signals register competence. Using "was" in formal conditionals is a register error at C2 level.' },
      { mistake: 'Confusing mixed conditional types: "If they had used a larger sample [past], the findings would be more generalisable today [present]" treated as equivalent to "If they had used a larger sample [past], the findings would have been more generalisable [past]."', correction: 'These are different logical claims. The first (mixed: past → present) says the consequence is ongoing — the findings still suffer from the limitation today. The second (pure Type 3: past → past) says the consequence was at that time. Choose the type that matches the temporal scope of the result.', explanation: 'At C2, precision in conditional selection demonstrates that you understand the logical relationship you are expressing, not just the grammatical form. The choice between "would be" and "would have been" in the result clause is not stylistic — it expresses a different temporal claim about when the consequence obtains.' },
    ],
    controlledPractice: [
      task(
        'Identify which conditional type is most precise for each situation, then write the sentence:\n(a) A past policy decision that was never made; the consequence is still felt today (ongoing gap in research infrastructure).\n(b) A permanent characteristic of a species that, had it been different, would have produced a different evolutionary outcome in the Pleistocene.\n(c) A recommendation to a colleague who is considering submitting a paper to a journal (real, possible future).',
        'Think about the temporal relationship in each case before selecting the type. For (a) and (b), which mixed type is needed and why?',
        '(a) Mixed conditional (past → present result): "If the government had invested in research infrastructure in the 1980s, the field would now be considerably more developed." (b) Mixed conditional (present state → past result): "If this species were not genetically predisposed to cooperative behaviour, it would not have survived the conditions of the Pleistocene." (c) Type 1 with "should": "If you submit the paper to Nature, you should expect a rigorous peer review process." — or inverted formal: "Should you choose to submit, you will need to address the methodological concerns raised."'
      ),
      task(
        'Rewrite each sentence using formal conditional inversion (no "if"):\n(a) "If the proposal is not approved, the project will be suspended."\n(b) "If the data were to support a third interpretation, the entire theoretical framework would require revision."\n(c) "If the committee had been informed earlier, the decision would have been different."',
        'Match the inversion form to the conditional type: "Should" (Type 1), "Were … to" (Type 2), "Had" (Type 3).',
        '(a) "Should the proposal not be approved, the project will be suspended." (b) "Were the data to support a third interpretation, the entire theoretical framework would require revision." (c) "Had the committee been informed earlier, the decision would have been different."'
      ),
      task(
        'Correct the error in each sentence and explain the error type:\n(a) "If the researchers would have controlled for socioeconomic status, the correlation would have disappeared."\n(b) "If she was more familiar with the literature, her argument would be more persuasive."\n(c) "If the intervention had been implemented two years ago, we would now have the results." — is this sentence correct? If so, which conditional type is it?',
        'For (c), decide whether the sentence requires correction or recognition.',
        '(a) Error: "would have" in the if-clause. Correction: "If the researchers had controlled for socioeconomic status, the correlation would have disappeared." (Type 3 — past perfect in if-clause.) (b) Error: "was" in formal conditional (Type 2). Correction: "If she were more familiar with the literature, her argument would be more persuasive." (c) This sentence is correct — it is a mixed conditional (past → present result): the intervention was not implemented two years ago (past); the consequence is that we do not have the results now (present). "Would now have" correctly uses the present conditional in the result clause.'
      ),
    ],
    productionTasks: [
      task(
        'Write 150 words on a hypothetical scenario of your choice (academic, political, scientific, or personal) using at least four different conditional types, each clearly deployed for a distinct logical purpose. Underline each conditional and label its type in brackets.',
        'Choose a scenario that genuinely requires multiple types — for instance: a historical counterfactual (Type 3), an ongoing consequence (mixed past → present), a present recommendation (Type 1 with "should"), and a formal hypothesis (Type 2 with inversion). Do not use the same type four times.',
        'Evaluate: Is each conditional type used for the correct logical relationship? Is "would" absent from every if-clause? Is "were" used correctly in all Type 2 and formal contexts? Are the mixed conditionals logically distinguishable from pure Type 2 and Type 3 forms? Does the text read naturally, or does the use of conditionals feel forced?'
      ),
    ],
  }),

  // ─── GRAMMAR-006: Relative clauses, appositives, and non-restrictive modification ───
  createGrammarLesson({
    ...common,
    id: 'C2-GRAMMAR-006',
    order: 6,
    title: 'Grammar: Advanced relative clauses, appositives, and non-restrictive modification',
    objectives: [
      'Command the full range of English relative clause types, including restrictive, non-restrictive, reduced, and prepositional forms.',
      'Deploy appositives (defining and non-defining) to incorporate complex information economically.',
      'Use formal relative pronouns (whom, which as sentence relative, whose) and prepositional relatives (in which, at which, for whom) correctly.',
      'Recognise and avoid the most persistent Brazilian errors in relative clause use, including comma placement and inappropriate pronoun choice.',
    ],
    teacherOpening: 'Relative clauses are one of the primary mechanisms for packing complex information into dense, precise sentences. At C2, the goal is not just to form relative clauses correctly but to choose the right type for the information structure you need: to know when to reduce, when to use a non-restrictive form, when a formal prepositional relative is required, and when an appositive is more economical. The difference between "the researcher who led the study" and "the researcher, who has published extensively in this area," is not just grammatical — it reflects a decision about which information is essential to identification and which is additional.',
    portugueseContrast: [task('Em Grammar: Advanced relative clauses, appositives, and non-restrictive modification, observe que a estrutura do inglês difere da ordem natural do português.'), task('Não traduza literalmente; identifique o padrão do inglês antes de produzir.')], 
    grammarTable: {
      headers: ['Structure', 'Formation and function', 'Example', 'Register / C2 note'],
      rows: [
        ['Restrictive relative clause', '"[Head noun] + who/that/which/whose/where/when + [clause]" — no commas; defines or identifies the head noun', '"The study that produced the most significant findings was published in 2019." / "Researchers who use qualitative methods face different challenges." / "The mechanism by which this occurs is not yet understood."', 'Restrictive clauses identify which member of a class is meant — they are essential to the meaning of the sentence. Removing them changes or destroys the meaning. In formal contexts, "which" is preferred over "that" for non-human referents in complex sentences; "that" is more natural in informal contexts. Never use a comma before a restrictive relative clause.'],
        ['Non-restrictive relative clause', '"[Head noun], + who/which/whose/where + [clause]," — commas required; adds information about an already-identified noun', '"Professor Chen, who has led the department for fifteen years, announced her retirement." / "The study, which was funded by the European Research Council, attracted significant attention."', 'Non-restrictive clauses add supplementary information about something already uniquely identified. They are grammatically separable from the main clause (the sentence would still make sense without them). NEVER use "that" in a non-restrictive relative clause — "that" is only for restrictive clauses. Commas are mandatory; their absence changes the grammatical function of the clause.'],
        ['Reduced relative clause (present participle)', '"[Head noun] + present participle phrase" — active meaning; simultaneous or ongoing action', '"The researchers conducting the trial observed unexpected results." (= who were conducting) / "Data suggesting a correlation between these variables exists in multiple datasets."', 'Reduced relatives (participial post-modifiers) are common in formal and academic writing because they increase density. The present participle is used when the relative clause is active and the action is ongoing or simultaneous with the main clause event. Do not confuse with the dangling participle error: the participle must be modifiable to the head noun.'],
        ['Reduced relative clause (past participle)', '"[Head noun] + past participle phrase" — passive meaning; completed or defining action', '"The results obtained from the third trial were inconsistent." (= which were obtained) / "The approach adopted by most researchers in this field has significant limitations." / "Evidence accumulated over decades points to a different conclusion."', 'Past participial post-modifiers carry a passive meaning. They are among the most frequent structures in formal academic prose — learn to recognise and produce them fluently. The head noun is the patient of the past participle\'s implied action.'],
        ['Appositives (defining and non-defining)', '"[Noun phrase], [appositive noun phrase]," — defines or elaborates on the preceding noun phrase', 'Non-defining (most common): "Foucault, the French philosopher, argued that knowledge and power are inseparable." Defining (rarer): "His claim that all definition is political rests on a circular argument." (here "that all definition is political" is an appositive clause defining "claim")', 'Appositives allow the insertion of explanatory or identifying information without a relative clause. Non-defining appositives are set off by commas (or dashes in more dramatic use); defining appositives (often that-clauses) are not. At C2, appositives allow for significant information compression: "The study — a longitudinal analysis of twelve cohorts — produced several unexpected findings." The dash appositive is particularly effective in academic writing for parenthetical elaboration.'],
        ['Cleft-like structures with relative clauses / relative clauses in formal contexts (which/who/whom/that)', '"It is [X] who/that [clause]." / "What [clause] is [noun phrase]."', '"It is the methodological rigour, not the theoretical novelty, that distinguishes this study." / "What the data reveal is a pattern of systematic underinvestment across all three sectors." / "The committee, to which the report was addressed, has not yet responded."', '"Whom" is required after prepositions in formal writing ("to whom," "for whom," "with whom"). At C2, using "who" after a preposition ("to who") is a register error. "Which" as a sentence-level relative (non-restrictive: "She argued that the data were incomplete, which undermined the entire conclusion") refers back to the whole preceding clause, not to a specific noun.'],
        ['Zero relative pronoun (contact clause)', '"[Head noun] + Ø + [clause]" — relative pronoun omitted; only possible in restrictive clauses when the relative is the object', '"The study Ø we discussed earlier has now been retracted." / "The argument Ø the author makes in chapter three is the most compelling." / "The approach Ø most researchers prefer involves…"', 'The zero relative (contact clause) is only possible when the relative pronoun is the object of the relative clause — NEVER when it is the subject. "The researcher Ø led the study" is ungrammatical; "the study Ø the researcher led" is acceptable. Contact clauses are more common in informal contexts; in formal academic prose, the explicit relative pronoun is often retained for clarity.'],
        ['Prepositional relative clauses (in which, at which, for whom, etc.)', '"[Noun] + preposition + which/whom + [clause]"', '"The conditions under which the experiment was conducted are described in detail." / "The mechanism by which the effect is produced has not yet been identified." / "The participants for whom the intervention was designed showed the greatest improvement." / "The moment at which the two theories diverge is crucial."', 'Prepositional relative clauses are standard in formal academic prose. Stranding the preposition ("The conditions which the experiment was conducted under") is acceptable in informal English but inappropriate in formal writing. "In which" and "by which" are particularly common in academic prose. These constructions often replace relative clauses with "where" ("the context in which" rather than "the context where") in the most formal registers.'],
      ],
    },
    brazilianMistakes: [
      { mistake: '"The study that was published in Nature, that attracted significant attention, has now been retracted."', correction: '"The study that was published in Nature, which attracted significant attention, has now been retracted." — Once the head noun is already identified by the restrictive clause ("that was published in Nature"), the second clause is non-restrictive and requires "which" (with a comma), not "that."', explanation: '"That" signals a restrictive clause (essential to identification); "which" (with a comma) signals a non-restrictive clause (supplementary information). Once a noun has already been uniquely identified, any further relative clause is non-restrictive. Using "that" in a non-restrictive clause is a consistent marker that the speaker has not fully internalised the distinction. This error is extremely common among Brazilian learners at C1–C2 level.' },
      { mistake: '"The committee voted against the proposal which it had previously supported" — written without commas, intended as non-restrictive (the committee is already identified)."', correction: '"The committee, which had previously supported the proposal, voted against it." — or, if non-restrictive is intended but without commas: restructure. Missing commas around a non-restrictive clause change its grammatical function: without commas, "which it had previously supported" looks restrictive (which committee? — the one that had previously supported it), potentially creating ambiguity.', explanation: 'Comma placement in relative clauses is not optional punctuation at C2 — it marks the grammatical and semantic distinction between restrictive and non-restrictive. Learners who punctuate intuitively rather than systematically often produce sentences whose intended meaning is unclear or different from what the punctuation implies.' },
      { mistake: '"The mechanism which the effect is produced by has not been identified." — stranded preposition in a formal context.', correction: '"The mechanism by which the effect is produced has not been identified." — move the preposition to precede the relative pronoun in formal writing.', explanation: 'Preposition stranding ("which… by") is grammatically acceptable in informal and colloquial English, but formal academic prose requires the preposition to precede the relative pronoun: "by which," "in which," "at which," "for whom." At C2, using stranded prepositions in academic writing is a register error. The prepositional relative construction is one of the markers of high formal register competence.' },
    ],
    controlledPractice: [
      task(
        'Classify each relative clause and explain the role of the comma (or its absence):\n(a) "The argument that the author develops in chapter five challenges the consensus in the field."\n(b) "This argument, which the author develops across three chapters, challenges the consensus in the field."\n(c) "The researchers studying long-term cognitive effects have produced a substantial body of evidence."\n(d) "Evidence accumulated over forty years points consistently in one direction."',
        'Identify: restrictive or non-restrictive; full or reduced; active or passive participle (for c and d).',
        '(a) Restrictive relative clause — "that the author develops in chapter five" identifies which argument (not all arguments, but this specific one in chapter five). No comma: correct. The omitted relative pronoun ("that Ø the author develops") would also be acceptable. (b) Non-restrictive relative clause — the argument is already identified; "which the author develops across three chapters" is supplementary information. Commas are mandatory. "That" would be incorrect here. (c) Reduced relative clause — present participle ("studying long-term cognitive effects"), active meaning (= who are studying). The head noun "researchers" is the agent. No comma: restrictive. (d) Reduced relative clause — past participle ("accumulated over forty years"), passive meaning (= which has been accumulated). The head noun "evidence" is the patient.'
      ),
      task(
        'Rewrite each sentence to use the appropriate formal relative clause or prepositional relative:\n(a) "The conditions that the experiment was done in are described in the appendix." [formalise]\n(b) "She is the person who we should address our concerns to." [formalise]\n(c) "The data we collected over three years forms the basis of our analysis." [make explicit, formal]\n(d) "The moment where the two theoretical traditions part ways is the question of ontological commitment." [formalise]',
        'For each, move stranded prepositions to pre-relative position; make zero relatives explicit; replace "where" with "at which" where appropriate.',
        '(a) "The conditions under which the experiment was conducted are described in the appendix." (b) "She is the person to whom we should address our concerns." (c) "The data which/that we collected over three years forms the basis of our analysis." (explicit relative pronoun; in very formal prose, use "which") (d) "The moment at which the two theoretical traditions part ways is the question of ontological commitment."'
      ),
      task(
        'Combine each pair of sentences using the most appropriate relative or appositive structure:\n(a) "The study was conducted in 2021. It involved over 3,000 participants from twelve countries." [one sentence, formal]\n(b) "Foucault introduced the concept of biopower. Biopower refers to the administration of life through institutions and knowledge." [appositive]\n(c) "The committee rejected the proposal. The committee had initially endorsed the proposal enthusiastically." [non-restrictive relative]',
        'For (b), decide whether a full relative clause, an appositive, or a defining that-clause is most economical.',
        '(a) "The study, which was conducted in 2021, involved over 3,000 participants from twelve countries." — or, with a dash: "The study — conducted in 2021 and involving over 3,000 participants from twelve countries — produced results that…" (b) "Foucault introduced the concept of biopower — the administration of life through institutions and knowledge — as a central analytical tool." — or: "Foucault introduced biopower, a concept referring to the administration of life through institutional and epistemic mechanisms." (c) "The committee, which had initially endorsed the proposal enthusiastically, rejected it at the final vote."'
      ),
    ],
    productionTasks: [
      task(
        'Write one dense analytical paragraph (120–150 words) in which you incorporate at least five of the following: a restrictive relative clause, a non-restrictive relative clause, a reduced relative clause (present participle), a reduced relative clause (past participle), an appositive (with dash or comma), a prepositional relative clause (in which / by which / for whom), and a zero relative pronoun. Label each structure in brackets after the relevant phrase.',
        'Choose a topic that lends itself to complex noun modification — a scientific study, a historical event, a theoretical position, or a policy debate. The paragraph should make a real analytical point, not just be a vehicle for the structures.',
        'Evaluate: Is each structure grammatically correct (commas, pronoun choice, preposition placement)? Is the density of modification manageable — can a reader follow the sentence? Is the paragraph making a coherent analytical point, or is it a list of structures that happen to be grammatically correct? Would a native academic reader find the prose natural?'
      ),
    ],
  }),

  // ─── VOCABULARY-005: Scientific and analytical discourse ──────────────────────
  createVocabularyLesson({
    ...common,
    id: 'C2-VOCABULARY-005',
    order: 5,
    title: 'Vocabulary: Scientific and analytical discourse — precision at the highest level',
    objectives: [
      'Deploy the vocabulary of scientific methodology and epistemology at C2 level.',
      'Distinguish the precise meanings of near-synonyms that are used interchangeably by non-specialists.',
      'Use these terms in their correct collocational environments in academic and analytical prose.',
      'Avoid the "dangerous confusions" that produce subtle but significant errors in scientific writing.',
    ],
    teacherOpening: 'The vocabulary of scientific discourse is not merely technical jargon — it encodes precise distinctions about evidence, method, and inference that are essential for any serious engagement with research. At C2, confusing "replicate" with "reproduce," or using "confound" loosely, is not merely a vocabulary error — it is an epistemic error. These words exist because the distinctions matter.',
    words: [
      { word: 'corroborate', definition: 'To confirm or give support to (a statement, theory, or finding); implies that independent evidence from a different source or method supports the same conclusion.', example: 'The qualitative findings were corroborated by the quantitative data from the longitudinal study, lending considerable strength to the theoretical claim.', collocations: ['corroborate a finding', 'corroborate an account', 'independently corroborated', 'corroborating evidence', 'the results corroborate the hypothesis'] },
      { word: 'parsimonious', definition: 'In scientific and analytical contexts: using the fewest assumptions or explanatory elements necessary to account for the data. A parsimonious explanation is economical, elegant, and not unnecessarily complex. (Review from C2-VOCABULARY-004; here the focus is collocational use in research contexts.)', example: 'Of the three competing models, Model A is the most parsimonious: it accounts for the observed variance with two variables rather than seven, and it introduces no untestable auxiliary assumptions.', collocations: ['the most parsimonious explanation', 'a parsimonious model', 'parsimony as a criterion', 'the principle of parsimony', 'prefer the more parsimonious account'] },
      { word: 'robust', definition: 'Of findings, methods, or results: strong and unlikely to change if the conditions, sample, or analytic approach are varied; resistant to challenge or modification. A robust finding holds across multiple tests.', example: 'The effect has proven robust: it has been replicated across twelve independent studies, across different cultural contexts, and using both self-report and behavioural measures.', collocations: ['robust findings', 'a robust effect', 'a robust methodology', 'the results are robust', 'robust across conditions', 'surprisingly robust'] },
      { word: 'confound (noun and verb)', definition: 'Noun: a confound (also confounder or confounding variable) is a variable that correlates with both the independent and dependent variable, potentially producing a spurious association. Verb: to confound means to confuse or muddle — in research, the passive "confounded by" means distorted or invalidated by a confounding variable.', example: 'The apparent correlation between coffee consumption and cardiovascular disease may be confounded by smoking behaviour, which correlates with both variables. [noun] The study\'s internal validity is undermined by a serious confound: participants who volunteered for the intervention were, on average, more health-conscious than the control group.', collocations: ['a significant confound', 'confounded by', 'to control for confounds', 'identify confounding variables', 'the results are confounded by'] },
      { word: 'iterate', definition: 'In scientific and analytical contexts: to repeat a process with modifications, each cycle building on and improving the previous one. Iteration implies a systematic process of progressive refinement, not mere repetition.', example: 'The research team iterated the experimental design across three pilot studies before arriving at a protocol that was both feasible and sufficiently sensitive to detect the predicted effect size.', collocations: ['iterate the design', 'iterate through possible solutions', 'iterative process', 'iterative refinement', 'an iterative approach to'] },
      { word: 'proximate', definition: 'Nearest; immediate; in causal analysis, the proximate cause is the most immediate cause of an event (what directly triggered it), as distinct from the ultimate cause (the deeper underlying reason). The distinction is fundamental in biology, medicine, history, and social science.', example: 'The proximate cause of the bank\'s collapse was a sudden withdrawal of liquidity; the ultimate cause was a decade of undercapitalisation and inadequate regulatory oversight.', collocations: ['proximate cause', 'the proximate factor', 'proximate vs. ultimate', 'in the proximate sense', 'at the proximate level'] },
      { word: 'attenuate', definition: 'To reduce in force, effect, or intensity; to weaken (a signal, an effect, a finding). In research contexts, used to describe the reduction of an effect size or the weakening of a relationship.', example: 'The relationship between social deprivation and educational outcomes is significantly attenuated when parental education level is controlled for, suggesting that the relationship is partly mediated by this variable.', collocations: ['attenuate the effect', 'the relationship is attenuated by', 'significantly attenuated', 'attenuate a signal', 'attenuation of the effect'] },
      { word: 'replicate', definition: 'In scientific methodology: to reproduce an experiment using the same method and protocol in order to test whether the original finding holds. Replication is the foundation of scientific credibility. A finding that does not replicate is suspect, regardless of how statistically significant the original study was.', example: 'The original finding has failed to replicate in six independent attempts using the same protocol. This raises serious questions about the robustness of the original result and whether publication bias may have played a role.', collocations: ['replicate the finding', 'the study failed to replicate', 'independently replicated', 'a replication crisis', 'replicate across different samples'] },
      { word: 'operationalise', definition: 'To define an abstract concept in terms of concrete, measurable operations or indicators; to translate a theoretical construct into something that can be measured, observed, or tested empirically. Operationalisation is a critical step in empirical research design.', example: 'One of the most contentious methodological debates in the field concerns how to operationalise "wellbeing" — whether to use self-report scales, objective indicators (life expectancy, income), or a combination of both.', collocations: ['operationalise a concept', 'operationalise the variable', 'how X is operationalised', 'the operationalisation of', 'a contested operationalisation'] },
      { word: 'null hypothesis', definition: 'In statistical hypothesis testing, the null hypothesis (H₀) is the default assumption that there is no effect, no relationship, or no difference between groups. The purpose of a statistical test is to assess whether the data provide sufficient evidence to reject the null hypothesis. Failing to reject the null does not prove it true — it means the evidence is insufficient to disprove it.', example: 'The study set out to test whether the intervention produced a statistically significant reduction in anxiety. The null hypothesis — that there is no difference between intervention and control groups — could not be rejected at the p < .05 threshold, suggesting the effect, if any, is smaller than the study was powered to detect.', collocations: ['reject the null hypothesis', 'fail to reject the null', 'the null hypothesis holds', 'under the null hypothesis', 'test the null hypothesis'] },
    ],
    dangerousConfusions: [
      { pair: ['replicate', 'reproduce'], explanation: 'In scientific methodology, these terms have subtly distinct meanings: to replicate is to repeat the original study using the same protocol, instruments, and procedure to verify the original finding. To reproduce is sometimes used to mean achieving the same result using the same data (computational reproduction) or, in broader usage, conducting a similar study that finds a similar result using a different method. The "replication crisis" in psychology concerns whether original findings replicate — not whether they can be reproduced from the same dataset. In less technical contexts these words overlap, but in research methodology they are distinct. At C2, use "replicate" when the same protocol is being followed; use "reproduce" when you mean to recreate an outcome by any available means.' },
      { pair: ['confound (noun/verb)', 'confuse'], explanation: 'In everyday English, "confound" can be a near-synonym of "confuse" — to confound someone is to perplex them. In research methodology, "confound" or "confounder" is a specific technical term referring to an extraneous variable that distorts an apparent relationship between two variables. "The results are confounded by age effects" does not mean the results are confusing — it means an age-related variable has distorted the measured relationship. These two meanings coexist in the language; context disambiguates. At C2, do not use "confounded" in research writing to mean "confused" or "surprising" — the technical meaning will be inferred, and it will be wrong.' },
    ],
  }),

  // ─── VOCABULARY-006: Political and sociological discourse ──────────────────────
  createVocabularyLesson({
    ...common,
    id: 'C2-VOCABULARY-006',
    order: 6,
    title: 'Vocabulary: Political and sociological discourse at C2',
    objectives: [
      'Use the vocabulary of critical social theory and political analysis at C2 level.',
      'Understand and deploy terms from sociology and political philosophy without reducing them to clichés.',
      'Distinguish between terms that are superficially similar but theoretically distinct.',
      'Use these words with appropriate collocations and register awareness.',
    ],
    teacherOpening: 'The vocabulary of political and sociological discourse at C2 is not neutral — many of these words carry theoretical commitments and have been contested within academic and political debates. Understanding "hegemonic" or "subaltern" is not just learning a word; it is engaging with a tradition of critical thought. At C2, you must be able to use these words precisely and to understand the theoretical positions they encode.',
    words: [
      { word: 'hegemonic', definition: 'Relating to hegemony — the dominant social, cultural, or ideological power exercised by a state, class, or group, often in ways that make its dominance appear natural or inevitable. Derived from Gramsci\'s theoretical framework; a "hegemonic" idea or discourse is one that has been so normalised that alternatives seem unthinkable.', example: 'The hegemonic assumption that economic growth is synonymous with social progress has proven remarkably difficult to dislodge, despite mounting evidence that GDP increases can coexist with declining quality of life for large segments of the population.', collocations: ['hegemonic discourse', 'the hegemonic position', 'hegemonic power', 'challenge the hegemonic view', 'culturally hegemonic'] },
      { word: 'subaltern', definition: 'In postcolonial and critical theory (drawing on Gramsci and Spivak): a person or group that is socially, politically, and geographically outside the dominant power structure; those whose voices are systematically excluded from the structures of representation and whose perspectives cannot be heard within dominant discourse.', example: 'Spivak\'s provocative question — "Can the subaltern speak?" — challenges the assumption that giving a marginalised group a platform within existing institutional structures constitutes genuine inclusion; the subaltern, by definition, cannot speak within the terms that mainstream discourse allows.', collocations: ['subaltern groups', 'subaltern voices', 'subaltern studies', 'the subaltern subject', 'represent the subaltern'] },
      { word: 'praxis', definition: 'In Marxist and critical theory: the integration of theory and practice; the process by which theoretical knowledge is applied to transform social reality, and through which practice in turn refines theory. Praxis is not merely doing — it is doing informed by critical reflection, and reflecting informed by transformative action.', example: 'Freire\'s pedagogy of the oppressed is premised on praxis: the liberation of the oppressed cannot come through the transmission of knowledge from teacher to student, but only through a cycle of critical reflection on lived experience and collective action to transform the conditions that produce that experience.', collocations: ['revolutionary praxis', 'critical praxis', 'theory and praxis', 'transform through praxis', 'a praxis-oriented approach'] },
      { word: 'reify', definition: 'To treat an abstraction or social construct as if it were a concrete, natural, or fixed thing; to make something that is historically produced and therefore changeable appear as an inevitable, objective reality. Often used critically: to reify a social category is to naturalise and thus entrench it.', example: 'Gender categories, the author argues, are reified by the very institutions — census classifications, medical taxonomies, legal codes — that present themselves as merely describing a pre-existing biological reality; the description is also a constitutive act.', collocations: ['reify a concept', 'reify social structures', 'the reification of', 'reified categories', 'resist the reification of'] },
      { word: 'dialectical', definition: 'Relating to the dialectic — in Hegelian and Marxist thought, the process by which contradictions between opposing forces or ideas are resolved through synthesis, which in turn generates new contradictions. More broadly: characterised by the interplay of opposing forces or ideas; involving dialogue and contradiction as drivers of development.', example: 'The relationship between the state and civil society is dialectical: the state shapes the conditions under which civil society operates, but civil society, through its contestation of state power, also transforms the state. Neither can be understood in isolation from the other.', collocations: ['a dialectical relationship', 'dialectical tension', 'dialectical process', 'dialectical materialism', 'the dialectic between'] },
      { word: 'asymmetry (of power / information)', definition: 'The condition of being unequal or not corresponding, particularly in terms of access to resources, power, or information. Power asymmetry describes relationships where one party has significantly more capacity to determine outcomes than the other; information asymmetry describes situations where one party has more or better information.', example: 'The fundamental information asymmetry between employer and employee — the employer typically knows more about the firm\'s financial health than the worker — is one reason labour markets are not simply governed by the price mechanism, as classical economics assumed.', collocations: ['power asymmetry', 'information asymmetry', 'structural asymmetry', 'asymmetric power relations', 'reduce the asymmetry'] },
      { word: 'legitimacy', definition: 'The quality of being accepted, recognised, or justified on the basis of widely shared norms, values, or procedures — as distinct from mere legality (conformity with law) or effective power (the capacity to enforce compliance). A government, institution, or decision can be legal without being legitimate, and legitimate without being strictly legal.', example: 'The election results were legally valid under the existing constitutional framework; their legitimacy, however, was widely questioned, given the systematic exclusion of opposition candidates from the ballot.', collocations: ['political legitimacy', 'democratic legitimacy', 'legitimacy crisis', 'confer legitimacy', 'question the legitimacy of', 'derive legitimacy from'] },
      { word: 'accountability', definition: 'The obligation of an individual or institution to accept responsibility for its actions and to be answerable to those who are affected by them or who have authority over them; the existence of mechanisms by which this obligation can be enforced. Accountability differs from responsibility: responsibility is having an obligation; accountability is being answerable for meeting it.', example: 'Without robust mechanisms of accountability — independent oversight, transparency obligations, enforceable consequences for misconduct — the formal assignment of responsibility to public officials is largely symbolic.', collocations: ['hold to account', 'democratic accountability', 'accountability mechanisms', 'lack of accountability', 'transparency and accountability', 'downward accountability'] },
      { word: 'ameliorate', definition: 'To make something bad or unsatisfactory better; to improve a condition, especially a social or political one. More formal than "improve"; often used when the improvement is partial or when the underlying problem persists.', example: 'The policy was designed to ameliorate the worst effects of the housing shortage, though its critics argued that it addressed symptoms rather than causes and would not ameliorate the structural inequalities driving the crisis.', collocations: ['ameliorate conditions', 'ameliorate the effects of', 'ameliorate suffering', 'attempts to ameliorate', 'partially ameliorate'] },
      { word: 'countervailing', definition: 'Acting as a counterbalance or opposing force; tending to offset or neutralise a dominant tendency, power, or influence. A countervailing power is one that checks or limits a dominant power without necessarily replacing it.', example: 'The concentration of market power in a small number of technology firms has not been offset by sufficient countervailing forces — neither regulatory action nor consumer pressure has proven adequate to restore competitive conditions.', collocations: ['countervailing power', 'countervailing forces', 'a countervailing tendency', 'countervailing pressure', 'lack of countervailing'] },
    ],
    dangerousConfusions: [
      { pair: ['legitimacy', 'legality'], explanation: '"Legality" refers strictly to conformity with law: an action is legal if it does not violate any applicable law. "Legitimacy" refers to wider social acceptance or normative justification: an action or institution is legitimate if it is broadly recognised as rightful, appropriate, or justified by shared values and norms. The two can diverge: apartheid-era legislation was legal within its own framework but widely regarded as illegitimate; acts of civil disobedience may be illegal but are considered legitimate by those who recognise the justice of the cause. In political theory, this distinction is fundamental. Do not use "legal" when you mean "recognised as rightful" — in politically contested contexts, the difference matters enormously.' },
      { pair: ['praxis', 'practice'], explanation: '"Practice" in everyday English refers to any repeated activity — the practice of medicine, the practice of law, a daily practice. In critical theory, "praxis" is a philosophical concept that specifically denotes theory and practice unified in the service of social transformation: it implies critical reflection, a relationship to theory, and a commitment to changing the conditions being reflected upon. "Practice" can occur without theory; "praxis" cannot. Do not use "praxis" simply to mean "practice" or "application" in non-theoretical contexts — this drains the word of its specific meaning and signals that you are using it as an elegant synonym rather than deploying a theoretical concept.' },
    ],
  }),

]);

export const C2_DEEP_COMPLEX_DISCOURSE_PART1_BY_PILLAR = Object.freeze({
  grammar: Object.freeze([
    C2_DEEP_COMPLEX_DISCOURSE_PART1.find(l => l.id === 'C2-GRAMMAR-005'),
    C2_DEEP_COMPLEX_DISCOURSE_PART1.find(l => l.id === 'C2-GRAMMAR-006'),
  ]),
  vocabulary: Object.freeze([
    C2_DEEP_COMPLEX_DISCOURSE_PART1.find(l => l.id === 'C2-VOCABULARY-005'),
    C2_DEEP_COMPLEX_DISCOURSE_PART1.find(l => l.id === 'C2-VOCABULARY-006'),
  ]),
  reading: Object.freeze([]),
  listening: Object.freeze([]),
  speaking: Object.freeze([]),
  writing: Object.freeze([]),
  checkpoint: Object.freeze([]),
});
