import { createGrammarLesson, createVocabularyLesson, createReadingLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-4', 'comparisons-needs', 'comparatives', 'superlatives', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }
function q(question, answer, evidence = '', explanation = '', options = []) { return { question, answer, evidence, explanation, options }; }
function ex(text, translation, why = '', warning = '') { return { text, translation, why, warning }; }

export const A2_DEEP_COMPARISONS_NEEDS_PART3 = Object.freeze([
  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-017',
    order: 17,
    title: 'Comparatives',
    objectives: ['Formar comparativos com -er e more.', 'Usar than para comparar duas opções.', 'Aplicar comparações em produtos, lugares e pessoas.', 'Evitar erros como more cheaper e more better.'],
    teacherOpening: 'Comparatives servem para comparar duas coisas: cheaper than, bigger than, more comfortable than. Se o adjetivo é curto, normalmente use -er: cheap → cheaper. Se é longo, use more: comfortable → more comfortable.',
    whyItMatters: 'Você usa comparativos para comprar melhor, escolher produto, comparar cidades, roupas, cursos, trabalho e rotinas.',
    realLifeUseCases: ['Comparar dois produtos.', 'Escolher roupa pelo preço e conforto.', 'Comparar lugares.', 'Dar opinião sobre opções.', 'Justificar uma decisão.'],
    conceptExplanation: 'Use adjective + -er + than para adjetivos curtos: cheaper than, smaller than, faster than. Use more + adjective + than para adjetivos longos: more expensive than, more comfortable than. Irregulares importantes: good → better, bad → worse, far → farther/further.',
    mentalModel: { title: 'comparative = A é mais X que B', summary: 'Escolha -er para curto, more para longo, e use than.', steps: ['cheap → cheaper than', 'big → bigger than', 'comfortable → more comfortable than', 'good → better than'] },
    stepByStep: [task('Escolha as duas opções.'), task('Escolha o adjetivo.'), task('Se curto, use -er.'), task('Se longo, use more.'), task('Adicione than + segunda opção.'), task('Revise irregulars: better/worse.')],
    portugueseContrast: [task('Em português usamos “mais” quase sempre; em inglês não diga more cheaper.'), task('Better já significa melhor; não use more better.'), task('Than = do que.'), task('Big dobra consoante: bigger.')],
    guidedDiscovery: [task('Cheap é curto → cheaper.'), task('Comfortable é longo → more comfortable.'), task('Good é irregular → better.'), task('Use than para completar comparação.')],
    guidedBeforeQuiz: [task('Complete: This jacket is ___ than that one. (cheap)', 'cheaper'), task('Complete: This chair is ___ comfortable than that chair.', 'more'), task('Corrija: more better', 'better')],
    grammarGoal: 'Comparar duas opções com -er/more + than.',
    formationGuide: [task('Short adjective', 'This shirt is cheaper than that shirt.'), task('Long adjective', 'This jacket is more comfortable than that jacket.'), task('CVC doubling', 'This bag is bigger than that bag.'), task('Irregular', 'This option is better than the other one.')],
    whenToUse: [task('Quando comparar duas opções.'), task('Ao decidir compra.'), task('Ao justificar preferência.'), task('Ao comparar lugares, produtos, pessoas ou tarefas.')],
    whenNotToUse: [task('Não use more + -er junto.'), task('Não use than sem segunda opção quando precisa clareza.'), task('Não use better com more.')],
    grammarTable: [
      { pattern: 'cheap → cheaper than', example: 'This T-shirt is cheaper than that jacket.', translation: 'Esta camiseta é mais barata que aquela jaqueta.' },
      { pattern: 'comfortable → more comfortable than', example: 'These shoes are more comfortable than those shoes.', translation: 'Estes sapatos são mais confortáveis que aqueles.' },
      { pattern: 'good → better than', example: 'This option is better than the first one.', translation: 'Esta opção é melhor que a primeira.' }
    ],
    teacherExamples: [
      { english: 'The blue jacket is cheaper than the black jacket.', translation: 'A jaqueta azul é mais barata que a preta.', why: 'Cheap é curto.' },
      { english: 'The black jacket is more comfortable than the blue jacket.', translation: 'A jaqueta preta é mais confortável que a azul.', why: 'Comfortable é longo.' },
      { english: 'This store is better than the other store.', translation: 'Esta loja é melhor que a outra loja.', why: 'Good → better.' }
    ],
    commonBrazilianMistakes: [mistake('more cheaper', 'cheaper', 'Não use more com -er.'), mistake('more better', 'better', 'Better já é comparativo.'), mistake('comfortabler', 'more comfortable', 'Adjetivo longo usa more.'), mistake('biger', 'bigger', 'Big dobra g.')],
    controlledPractice: [task('Complete: cheap → ___', 'cheaper'), task('Complete: expensive → ___ expensive', 'more'), task('Complete: good → ___', 'better'), task('Complete: bad → ___', 'worse')],
    errorCorrectionPractice: [task('Corrija: This one is more cheaper.', 'This one is cheaper.'), task('Corrija: This product is more better.', 'This product is better.'), task('Corrija: This chair is comfortabler.', 'This chair is more comfortable.')],
    transformationPractice: [task('Compare: blue jacket / cheap / black jacket', 'The blue jacket is cheaper than the black jacket.'), task('Compare: black shoes / comfortable / white shoes', 'The black shoes are more comfortable than the white shoes.'), task('Compare: this option / good / that option', 'This option is better than that option.')],
    translationPractice: [task('Esta opção é mais barata que aquela.', 'This option is cheaper than that one.'), task('Este lugar é mais confortável que o outro.', 'This place is more comfortable than the other one.'), task('Este produto é melhor que o primeiro.', 'This product is better than the first one.')],
    productionTasks: [task('Escreva 10 comparações entre produtos.'), task('Compare duas cidades ou lugares.'), task('Explique 3 escolhas usando because.')],
    finalChecklist: [task('Estou comparando duas opções?'), task('Usei -er ou more corretamente?'), task('Usei than?'), task('Evitei more better/more cheaper?')],
    selfAssessment: [task('Consigo formar comparativos?'), task('Consigo usar than?'), task('Consigo corrigir erros comuns?')],
    lessonRecap: ['Comparatives comparam duas opções.', 'Adjetivos curtos usam -er.', 'Adjetivos longos usam more.', 'Good/bad viram better/worse.'],
    nextLessonBridge: 'Agora você vai comparar grupos com superlatives.',
  }),

  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-018',
    order: 18,
    title: 'Superlatives',
    objectives: ['Formar superlativos com the -est e the most.', 'Usar superlativos para escolher o melhor/pior/maior/mais confortável em um grupo.', 'Aplicar em produtos, lugares e pessoas.', 'Evitar the most cheapest e the bestest.'],
    teacherOpening: 'Comparatives comparam duas opções. Superlatives escolhem um item dentro de um grupo: the cheapest, the most comfortable, the best. Use the antes do superlativo.',
    whyItMatters: 'Superlatives ajudam a dizer qual é a melhor opção, o maior problema, a roupa mais confortável, o produto mais barato ou o lugar mais interessante.',
    realLifeUseCases: ['Escolher o melhor produto.', 'Falar do lugar mais barato.', 'Descrever a pessoa mais organizada.', 'Comparar várias opções.', 'Justificar decisão final.'],
    conceptExplanation: 'Use the + adjective-est para adjetivos curtos: the cheapest, the smallest. Use the most + adjective para adjetivos longos: the most comfortable, the most expensive. Irregulares: good → the best, bad → the worst.',
    mentalModel: { title: 'superlative = o mais X do grupo', summary: 'Use the e escolha um destaque no grupo.', steps: ['the cheapest', 'the biggest', 'the most expensive', 'the best'] },
    stepByStep: [task('Identifique o grupo.'), task('Escolha o adjetivo.'), task('Curto: the + -est.'), task('Longo: the most + adjective.'), task('Irregular: the best/the worst.'), task('Explique com because se necessário.')],
    portugueseContrast: [task('Use the antes de superlativo.'), task('Não diga the most cheapest.'), task('Best já significa o melhor; não diga bestest.'), task('Worst = o pior.')],
    guidedDiscovery: [task('Cheap → the cheapest.'), task('Comfortable → the most comfortable.'), task('Good → the best.'), task('Bad → the worst.')],
    guidedBeforeQuiz: [task('Complete: This is ___ cheapest option.', 'the'), task('Complete: This is the ___ comfortable chair.', 'most'), task('Corrija: the most best', 'the best')],
    grammarGoal: 'Escolher um destaque dentro de um grupo com superlativos.',
    formationGuide: [task('Short adjective', 'This is the cheapest jacket in the store.'), task('Long adjective', 'This is the most comfortable chair here.'), task('Irregular good', 'This is the best option.'), task('Irregular bad', 'This is the worst problem.')],
    whenToUse: [task('Quando há três ou mais opções ou um grupo.'), task('Ao escolher o melhor/maior/mais barato.'), task('Ao fazer recomendação final.')],
    whenNotToUse: [task('Não use superlativo para comparar só duas opções se o foco é A vs B.'), task('Não use most + -est.'), task('Não esqueça the.')],
    grammarTable: [
      { pattern: 'cheap → the cheapest', example: 'This is the cheapest T-shirt.', translation: 'Esta é a camiseta mais barata.' },
      { pattern: 'comfortable → the most comfortable', example: 'These are the most comfortable shoes.', translation: 'Estes são os sapatos mais confortáveis.' },
      { pattern: 'good → the best', example: 'This is the best choice.', translation: 'Esta é a melhor escolha.' }
    ],
    teacherExamples: [
      { english: 'This is the cheapest restaurant in the area.', translation: 'Este é o restaurante mais barato da área.', why: 'Cheap é curto.' },
      { english: 'This is the most comfortable jacket in the store.', translation: 'Esta é a jaqueta mais confortável da loja.', why: 'Comfortable é longo.' },
      { english: 'That was the worst option for our budget.', translation: 'Aquela foi a pior opção para nosso orçamento.', why: 'Bad → worst.' }
    ],
    commonBrazilianMistakes: [mistake('the most cheapest', 'the cheapest', 'Não use most com -est.'), mistake('the bestest', 'the best', 'Best já é superlativo.'), mistake('most comfortable option', 'the most comfortable option', 'Normalmente precisa the.'), mistake('the expensivest', 'the most expensive', 'Adjetivo longo usa most.')],
    controlledPractice: [task('Complete: cheap → the ___', 'cheapest'), task('Complete: comfortable → the ___ comfortable', 'most'), task('Complete: good → the ___', 'best'), task('Complete: bad → the ___', 'worst')],
    errorCorrectionPractice: [task('Corrija: This is the most cheapest.', 'This is the cheapest.'), task('Corrija: It is best option.', 'It is the best option.'), task('Corrija: This is the comfortablest chair.', 'This is the most comfortable chair.')],
    transformationPractice: [task('Grupo: cheap option', 'This is the cheapest option.'), task('Grupo: comfortable shoes', 'These are the most comfortable shoes.'), task('Grupo: good choice', 'This is the best choice.')],
    translationPractice: [task('Esta é a melhor escolha.', 'This is the best choice.'), task('Este é o produto mais barato.', 'This is the cheapest product.'), task('Este é o lugar mais confortável.', 'This is the most comfortable place.')],
    productionTasks: [task('Escreva 8 frases com superlativos.'), task('Escolha o melhor produto entre 3 opções e explique.'), task('Compare 3 lugares usando the cheapest/the best/the most comfortable.')],
    finalChecklist: [task('Há um grupo?'), task('Usei the?'), task('Usei -est ou most corretamente?'), task('Evitei bestest/most cheapest?')],
    selfAssessment: [task('Consigo formar superlativos?'), task('Consigo escolher melhor opção?'), task('Consigo explicar com because?')],
    lessonRecap: ['Superlatives escolhem um item dentro de grupo.', 'Use the.', 'Curto usa -est; longo usa most.', 'Good/bad viram best/worst.'],
    nextLessonBridge: 'Agora você vai usar adjetivos de personalidade para comparar pessoas.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-015',
    order: 15,
    title: 'Personality adjectives',
    objectives: ['Aprender adjetivos básicos de personalidade.', 'Descrever pessoas de forma respeitosa.', 'Comparar características simples.', 'Usar adjetivos em frases com be e comparatives.'],
    teacherOpening: 'Personality adjectives ajudam a descrever pessoas: friendly, quiet, shy, funny, serious, polite, rude, kind, patient, impatient, careful, careless, organized, lazy, hardworking.',
    whyItMatters: 'Você usa personalidade para falar de colegas, atendimento, família, trabalho e preferências. Também ajuda a comparar pessoas e situações.',
    realLifeUseCases: ['Descrever colega de trabalho.', 'Falar de atendimento em loja.', 'Comparar duas pessoas.', 'Explicar preferência por professor/equipe.', 'Dar opinião simples.'],
    conceptExplanation: 'Use be + adjective: She is friendly. He is quiet. Para comparar: She is more patient than me. He is funnier than his brother. Use cuidado com palavras negativas para manter respeito.',
    mentalModel: { title: 'personality = person + be + adjective', summary: 'Descreva característica de forma clara e respeitosa.', steps: ['She is friendly.', 'He is organized.', 'They are polite.', 'She is more patient than me.'] },
    stepByStep: [task('Escolha a pessoa.'), task('Use be.'), task('Escolha adjetivo.'), task('Adicione exemplo se quiser.'), task('Compare com than se necessário.')],
    portugueseContrast: [task('Friendly = amigável, não apenas amigo.'), task('Polite = educado no sentido de bons modos.'), task('Rude = grosso/mal-educado.'), task('Hardworking = trabalhador/esforçado.')],
    guidedDiscovery: [task('Friendly é positivo.'), task('Rude é negativo.'), task('Careful/careless são opostos.'), task('Patient/impatient são opostos.')],
    guidedBeforeQuiz: [task('She is friendly.'), task('He is more organized than me.'), task('They are polite.'), task('My brother is funny.')],
    topicContext: 'Você vai descrever e comparar pessoas em contexto de trabalho, estudo e atendimento.',
    essentialWords: [vocab('friendly', 'amigável', 'She is very friendly.'), vocab('quiet', 'quieto/calado', 'He is quiet in class.'), vocab('shy', 'tímido', 'I am a little shy.'), vocab('funny', 'engraçado', 'My friend is funny.'), vocab('serious', 'sério', 'The teacher is serious.'), vocab('polite', 'educado', 'The assistant was polite.'), vocab('rude', 'grosso/mal-educado', 'The customer was rude.'), vocab('kind', 'gentil', 'She is kind.'), vocab('patient', 'paciente', 'He is patient with children.'), vocab('impatient', 'impaciente', 'I get impatient sometimes.'), vocab('careful', 'cuidadoso', 'Be careful.'), vocab('careless', 'descuidado', 'That was careless.'), vocab('organized', 'organizado', 'She is organized.'), vocab('lazy', 'preguiçoso', 'He is lazy on Sundays.'), vocab('hardworking', 'trabalhador/esforçado', 'My mother is hardworking.')],
    chunks: [{ chunk: 'a friendly person', translation: 'uma pessoa amigável', example: 'She is a friendly person.' }, { chunk: 'more organized than me', translation: 'mais organizado que eu', example: 'He is more organized than me.' }, { chunk: 'the most patient person', translation: 'a pessoa mais paciente', example: 'She is the most patient person I know.' }, { chunk: 'a little shy', translation: 'um pouco tímido', example: 'I am a little shy.' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Friendly tem som de friend + ly.', 'Patient soa PEI-shent.', 'Organized tem stress em OR.'] },
    dangerousConfusions: [task('Sympathetic não é simpático; use friendly/kind.'), task('Educated é instruído; polite é educado em comportamento.'), task('Funny é engraçado; fun é divertido.'), task('Sensible não é sensível; sensitive é sensível.')],
    collocations: [task('very friendly'), task('a little shy'), task('really organized'), task('more patient than'), task('the most careful person'), task('hardworking student')],
    miniDialogues: [{ title: 'Describing a coworker', lines: ['A: What is Ana like?', 'B: She is friendly and organized.', 'A: Is she patient?', 'B: Yes. She is more patient than me.'], focus: 'Personalidade + comparação.' }],
    examples: [ex('My teacher is more patient than my old teacher.', 'Meu professor é mais paciente que meu professor antigo.', 'Comparativo.'), ex('She is the most organized person on the team.', 'Ela é a pessoa mais organizada da equipe.', 'Superlativo.'), ex('He is polite, but he is very serious.', 'Ele é educado, mas é muito sério.', 'Contraste com but.')],
    recognitionPractice: [task('Qual palavra significa amigável?', 'friendly'), task('Qual palavra significa educado em comportamento?', 'polite'), task('Qual palavra é o oposto de careful?', 'careless')],
    usagePractice: [task('Complete: She is very ___. (amigável)', 'friendly'), task('Complete: He is more organized ___ me.', 'than'), task('Complete: She is the ___ patient person here.', 'most')],
    productionTasks: [task('Descreva 5 pessoas com adjetivos de personalidade.'), task('Compare duas pessoas de forma respeitosa.'), task('Crie 5 frases com more... than e 3 com the most...')],
    spacedReview: [task('Revise friendly/polite/kind/patient amanhã.'), task('Crie frases com careful/careless e organized/hardworking.')],
    selfAssessment: [task('Consigo descrever personalidade?'), task('Consigo evitar false friends?'), task('Consigo comparar pessoas?')],
    lessonRecap: ['Personality adjectives descrevem pessoas.', 'Use be + adjective.', 'Comparatives e superlatives funcionam com personalidade.', 'Friendly/polite evitam falsos cognatos.'],
    nextLessonBridge: 'Agora você vai comparar lugares e produtos com vocabulário mais amplo.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-016',
    order: 16,
    title: 'Comparing places and products',
    objectives: ['Aprender vocabulário para comparar lugares e produtos.', 'Falar de preço, qualidade, distância, conforto e utilidade.', 'Usar critérios para tomar decisão.', 'Preparar leituras de problema/solução e planos/intenção.'],
    teacherOpening: 'Comparing places and products expande suas escolhas: cheap, expensive, comfortable, useful, practical, modern, old, close, far, crowded, quiet, clean, dirty, safe, dangerous, quality, price, service.',
    whyItMatters: 'Você compara lugares, lojas, produtos, restaurantes, apps e serviços quase todo dia. O A2.4 transforma opinião em decisão com critérios.',
    realLifeUseCases: ['Comparar lojas.', 'Escolher restaurante.', 'Comparar produtos online.', 'Falar de bairro/cidade.', 'Decidir melhor opção pelo preço e qualidade.'],
    conceptExplanation: 'Compare usando critérios: price, quality, comfort, distance, service, safety. Exemplo: This restaurant is cheaper, but that one is cleaner and quieter.',
    mentalModel: { title: 'comparison criteria', summary: 'Toda escolha precisa de critérios claros.', steps: ['price', 'quality', 'distance', 'comfort', 'service', 'safety'] },
    stepByStep: [task('Nomeie as opções.'), task('Escolha critérios.'), task('Compare um critério por frase.'), task('Use but para contraste.'), task('Escolha com because.')],
    portugueseContrast: [task('Close = perto; closed = fechado.'), task('Safe = seguro; dangerous = perigoso.'), task('Crowded = lotado.'), task('Useful = útil; practical = prático.')],
    guidedDiscovery: [task('Cheap/expensive falam de preço.'), task('Clean/dirty falam de condição.'), task('Close/far falam de distância.'), task('Safe/dangerous falam de segurança.')],
    guidedBeforeQuiz: [task('This store is cheaper.'), task('That restaurant is cleaner.'), task('This app is more useful.'), task('The park is quieter than the mall.')],
    topicContext: 'Você vai comparar opções por critérios práticos.',
    essentialWords: [vocab('cheap', 'barato', 'This store is cheap.'), vocab('expensive', 'caro', 'That phone is expensive.'), vocab('comfortable', 'confortável', 'This chair is comfortable.'), vocab('useful', 'útil', 'This app is useful.'), vocab('practical', 'prático', 'This option is practical.'), vocab('modern', 'moderno', 'The hotel is modern.'), vocab('old', 'velho/antigo', 'The building is old.'), vocab('close', 'perto', 'The store is close to my house.'), vocab('far', 'longe', 'The mall is far.'), vocab('crowded', 'lotado', 'The restaurant is crowded.'), vocab('quiet', 'calmo/silencioso', 'The park is quiet.'), vocab('clean', 'limpo', 'The hotel is clean.'), vocab('dirty', 'sujo', 'The room is dirty.'), vocab('safe', 'seguro', 'This area is safe.'), vocab('dangerous', 'perigoso', 'That street is dangerous.'), vocab('quality', 'qualidade', 'The quality is good.'), vocab('price', 'preço', 'The price is high.'), vocab('service', 'atendimento/serviço', 'The service is good.')],
    chunks: [{ chunk: 'better quality', translation: 'melhor qualidade', example: 'This product has better quality.' }, { chunk: 'lower price', translation: 'preço mais baixo', example: 'This store has lower prices.' }, { chunk: 'closer to my house', translation: 'mais perto da minha casa', example: 'This market is closer to my house.' }, { chunk: 'the best choice for me', translation: 'a melhor escolha para mim', example: 'This is the best choice for me.' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Comfortable pode soar COMF-ter-bol.', 'Quality começa com som de KW.', 'Dangerous tem stress em DAIN.'] },
    dangerousConfusions: [task('Close vs closed.'), task('Quiet vs quite.'), task('Economic não é sempre cheap; use cheap/affordable.'), task('Safe é seguro; sure é certeza.')],
    collocations: [task('good quality'), task('high price'), task('low price'), task('good service'), task('safe area'), task('crowded place'), task('quiet restaurant')],
    miniDialogues: [{ title: 'Choosing a restaurant', lines: ['A: Which restaurant is better?', 'B: This one is cheaper, but that one is cleaner.', 'A: Which one do you prefer?', 'B: The cleaner one. It is the best choice for dinner.'], focus: 'Critérios + escolha.' }],
    examples: [ex('This market is closer than the mall.', 'Este mercado é mais perto que o shopping.', 'Comparativo de distância.'), ex('That restaurant is the cleanest option.', 'Aquele restaurante é a opção mais limpa.', 'Superlativo.'), ex('This app is more useful than the old app.', 'Este app é mais útil que o app antigo.', 'Adjetivo longo com more.')],
    recognitionPractice: [task('Qual palavra significa lotado?', 'crowded'), task('Qual palavra significa seguro?', 'safe'), task('Qual expressão significa melhor qualidade?', 'better quality')],
    usagePractice: [task('Complete: This store is closer ___ my house.', 'to'), task('Complete: This app is more useful ___ the old app.', 'than'), task('Complete: This is the ___ choice for me.', 'best')],
    productionTasks: [task('Compare duas lojas por preço e distância.'), task('Compare dois restaurantes por limpeza e serviço.'), task('Compare dois apps por utilidade e praticidade.')],
    spacedReview: [task('Revise close/crowded/quiet/safe amanhã.'), task('Crie 5 frases com better quality/lower price.')],
    selfAssessment: [task('Consigo comparar lugares?'), task('Consigo comparar produtos?'), task('Consigo justificar escolha com critérios?')],
    lessonRecap: ['Comparar lugares e produtos exige critérios.', 'Preço, qualidade, distância e conforto são centrais.', 'But mostra contraste entre critérios.', 'Because justifica decisão final.'],
    nextLessonBridge: 'Agora você vai ler textos de problema/solução e planos/intenção conectados a escolhas.',
  }),

  createReadingLesson({
    ...common,
    id: 'A2-READING-014',
    order: 14,
    title: 'A problem and solution text',
    objectives: ['Ler texto de problema e solução.', 'Identificar problema, opções e decisão.', 'Reconhecer comparatives e superlatives em contexto.', 'Responder com evidência textual.'],
    teacherOpening: 'Nesta leitura, você vai entender um problema prático: escolher uma opção melhor para resolver algo. O foco é problema, opções, comparação e solução final.',
    whyItMatters: 'Textos de problema e solução aparecem em trabalho, compras, casa, estudo e tecnologia. Você precisa localizar o problema e entender por que uma solução foi escolhida.',
    realLifeUseCases: ['Escolher loja ou produto.', 'Resolver problema de transporte.', 'Comparar soluções.', 'Ler recomendação curta.', 'Justificar decisão.'],
    conceptExplanation: 'Procure problem, options, comparison words e final solution. Palavras como cheaper, closer, more useful, best choice e because mostram raciocínio.',
    mentalModel: { title: 'problem → options → comparison → solution', summary: 'Leia o problema, compare soluções e ache a decisão.', steps: ['problem', 'option A', 'option B', 'comparison', 'solution'] },
    stepByStep: [task('Identifique o problema.'), task('Marque as opções.'), task('Sublinhe comparatives.'), task('Procure best/better choice.'), task('Copie evidência.')],
    portugueseContrast: [task('Solution = solução.'), task('Option = opção.'), task('Closer = mais perto.'), task('More useful = mais útil.')],
    guidedDiscovery: [task('But mostra contraste.'), task('Because explica escolha.'), task('Best choice mostra solução final.')],
    guidedBeforeQuiz: [task('Procure problem.'), task('Procure options.'), task('Procure better/best.'), task('Use evidência.')],
    readingPurpose: 'Entender problema e solução com comparação.',
    preReadingVocabulary: [vocab('problem', 'problema'), vocab('solution', 'solução'), vocab('option', 'opção'), vocab('closer', 'mais perto'), vocab('more useful', 'mais útil'), vocab('best choice', 'melhor escolha')],
    readingStrategy: [task('Leia para entender problema geral.'), task('Faça tabela de opções.'), task('Marque critérios.'), task('Ache solução final.')],
    mainText: `My phone app is not working well, so I need a better solution. The old app is simple, but it is slow and it freezes a lot. The new app is more modern and more useful. It is also easier to use. The old app is cheaper, but the new app is the best choice for my work because it saves time.`,
    firstReadTask: task('Qual é o problema geral?', 'O app antigo não funciona bem / precisa de solução melhor.'),
    secondReadTasks: [task('Qual é o problema do app antigo?', 'slow and freezes a lot'), task('Como é o app novo?', 'more modern and more useful'), task('Qual app é mais barato?', 'old app'), task('Qual é a melhor escolha?', 'new app')],
    evidenceQuestions: [q('Why does the person need a better solution?', 'the phone app is not working well', 'My phone app is not working well', '', ['app not working well','jacket too tight','store far']), q('What is the old app like?', 'simple but slow and freezes a lot', 'simple, but it is slow and it freezes a lot', '', ['simple but slow','modern and useful','expensive and clean']), q('What is the new app like?', 'more modern and more useful', 'The new app is more modern and more useful.', '', ['more modern and useful','cheaper only','older']), q('Which app is cheaper?', 'old app', 'The old app is cheaper', '', ['old app','new app','both']), q('Why is the new app the best choice?', 'it saves time', 'because it saves time', '', ['saves time','is cheaper','is older'])],
    contextVocabularyTasks: [task('Saves time significa economiza tempo.'), task('A better solution é uma solução melhor.'), task('Easier to use significa mais fácil de usar.')],
    guidedSummary: task('Complete: The old app is simple but ___. The new app is more ___ and more ___. It is the best choice because it saves ___.', '', 'slow / modern / useful / time'),
    connectedProduction: task('Escreva 4 frases comparando um app antigo e um app novo.'),
    selfAssessment: [task('Consigo identificar problema?'), task('Consigo comparar soluções?'), task('Consigo justificar escolha com evidência?')],
    lessonRecap: ['Problem/solution texts mostram decisão prática.', 'Comparatives explicam diferenças.', 'Best choice mostra solução final.', 'Because dá motivo da escolha.'],
    nextLessonBridge: 'Na próxima leitura, você vai ler planos e intenções usando comparação.',
  }),

  createReadingLesson({
    ...common,
    id: 'A2-READING-016',
    order: 16,
    title: 'Reading for plans and intentions',
    objectives: ['Ler texto com planos e intenções ligados a escolhas.', 'Identificar going to, comparatives e motivo.', 'Entender decisão entre lugares/produtos.', 'Responder com evidência textual.'],
    teacherOpening: 'Nesta leitura, você vai integrar A2.3 e A2.4: planos futuros com going to e escolhas baseadas em comparação. O texto mostra intenção, opções e decisão.',
    whyItMatters: 'Na vida real, planos quase sempre envolvem escolhas: qual lugar visitar, qual produto comprar, qual opção é melhor para você.',
    realLifeUseCases: ['Planejar compra.', 'Escolher restaurante ou loja.', 'Decidir onde ir.', 'Justificar plano futuro.', 'Comparar lugar por preço e distância.'],
    conceptExplanation: 'Procure going to para intenção/plano. Procure comparative/superlative para decisão. Procure because para motivo.',
    mentalModel: { title: 'plan + comparison + reason', summary: 'O plano mostra futuro; a comparação explica escolha.', steps: ['I am going to...', 'Option A vs B', 'better/best', 'because'] },
    stepByStep: [task('Marque going to.'), task('Identifique opções.'), task('Sublinhe comparativos/superlativos.'), task('Procure because.'), task('Responda com evidência.')],
    portugueseContrast: [task('I am going to choose = vou escolher.'), task('Closer to my house = mais perto da minha casa.'), task('The best option = a melhor opção.')],
    guidedDiscovery: [task('Going to indica plano.'), task('Closer/cheaper indicam comparação.'), task('Best indica escolha final.'), task('Because explica motivo.')],
    guidedBeforeQuiz: [task('Procure going to.'), task('Procure closer.'), task('Procure best option.'), task('Use evidência.')],
    readingPurpose: 'Entender plano futuro baseado em comparação.',
    preReadingVocabulary: [vocab('plan', 'plano'), vocab('intention', 'intenção'), vocab('closer', 'mais perto'), vocab('cheaper', 'mais barato'), vocab('best option', 'melhor opção')],
    readingStrategy: [task('Leia para entender o plano.'), task('Compare as opções.'), task('Ache motivo da escolha.'), task('Separe plano de justificativa.')],
    mainText: `This weekend, I am going to buy a new pair of shoes. I visited two stores yesterday. The first store is closer to my house, but the shoes are more expensive. The second store is farther, but it has better prices and more comfortable shoes. I am going to choose the second store because it is the best option for my budget.`,
    firstReadTask: task('Qual é o plano?', 'Comprar um par novo de sapatos.'),
    secondReadTasks: [task('Qual loja é mais perto?', 'first store'), task('Qual loja tem preços melhores?', 'second store'), task('Qual loja tem sapatos mais confortáveis?', 'second store'), task('Qual loja será escolhida?', 'second store')],
    evidenceQuestions: [q('What is the person going to buy?', 'a new pair of shoes', 'I am going to buy a new pair of shoes.', '', ['new pair of shoes','new phone','new jacket']), q('Which store is closer?', 'first store', 'The first store is closer to my house', '', ['first store','second store','both']), q('What is the problem with the first store?', 'shoes are more expensive', 'the shoes are more expensive', '', ['more expensive','dirty','crowded']), q('Why is the second store better?', 'better prices and more comfortable shoes', 'it has better prices and more comfortable shoes', '', ['better prices and comfort','closer','older']), q('Why will the person choose the second store?', 'best option for budget', 'because it is the best option for my budget', '', ['best for budget','closest','has no shoes'])],
    contextVocabularyTasks: [task('Budget significa orçamento.'), task('Farther significa mais longe.'), task('Better prices significa preços melhores.')],
    guidedSummary: task('Complete: The first store is ___, but more expensive. The second store is ___, but has better ___ and more comfortable ___.', '', 'closer / farther / prices / shoes'),
    connectedProduction: task('Escreva 5 frases sobre um plano de compra baseado em comparação.'),
    selfAssessment: [task('Consigo identificar plano?'), task('Consigo entender comparação de lugares?'), task('Consigo justificar escolha?')],
    lessonRecap: ['Plans and intentions podem depender de comparação.', 'Going to marca plano futuro.', 'Closer/farther/cheaper/better explicam decisão.', 'Best option fecha a escolha.'],
    nextLessonBridge: 'A próxima parte fechará A2.4 com possessive pronouns e leituras restantes alinhadas ao pacote.',
  }),
]);

export const A2_DEEP_COMPARISONS_NEEDS_PART3_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART3.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART3.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART3.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART3.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART3.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART3.filter((lesson) => lesson.pillar === 'writing')),
});
