import { createGrammarLesson, createVocabularyLesson, createReadingLesson, createListeningLesson, createSpeakingLesson, createWritingLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-1', 'bridge', 'survival-expansion', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function phrase(text, translation = '', note = '') { return { text, translation, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }
function q(question, answer, evidence = '', explanation = '', options = []) { return { question, answer, evidence, explanation, options }; }
function ex(text, translation, why = '', warning = '') { return { text, translation, why, warning }; }

export const A2_DEEP_BRIDGE = Object.freeze([
  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-001',
    order: 1,
    title: 'A1 repair: sentence order and auxiliaries',
    objectives: ['Reparar lacunas essenciais do A1 antes do A2.', 'Organizar frases com sujeito, verbo e complemento.', 'Usar auxiliares básicos em perguntas e negativas.', 'Evitar erros que travam o passado, planos e comparações no A2.'],
    teacherOpening: 'O A2 começa com uma ponte. Antes de entrar em passado, planos e comparações, você precisa garantir que frases simples estão limpas. Nesta aula, vamos revisar ordem de frase, perguntas, negativas e auxiliares. O objetivo é não carregar erros do A1 para o A2.',
    whyItMatters: 'Se você escreve “You can help me?” ou “She work?” no A2, o passado e o futuro ficam instáveis. Esta aula conserta a base para você avançar com segurança.',
    realLifeUseCases: ['Fazer perguntas corretas.', 'Negar frases simples.', 'Pedir ajuda com clareza.', 'Falar rotina sem erro básico.', 'Preparar estrutura para Past Simple e Present Continuous.'],
    conceptExplanation: 'Uma frase afirmativa básica em inglês segue sujeito + verbo + complemento: I study English. Perguntas podem usar inversão com to be/can ou auxiliares do/does. Negativas usam not com to be/can ou do not/does not com verbos comuns. No A2, você precisa escolher o auxiliar certo.',
    mentalModel: { title: 'Sujeito + auxiliar certo + verbo certo', summary: 'A pergunta muda conforme o verbo.', steps: ['Are you Brazilian?', 'Can you help me?', 'Do you work today?', 'Does she study English?'] },
    stepByStep: [task('Identifique o verbo principal.'), task('Se for to be, inverta: Are you...?'), task('Se for can, comece com Can... ?'), task('Se for verbo comum, use do/does.'), task('Na negativa, use not ou do not/does not.'), task('Revise se o verbo principal voltou para a forma base com do/does.')],
    portugueseContrast: [task('Português permite só entonação para pergunta; inglês precisa ordem/auxiliar.'), task('Não diga You can help me? no padrão de checkpoint.', 'Use Can you help me?'), task('Não diga She don’t work.', 'Use She doesn’t work.'), task('Não diga Does she works?', 'Use Does she work?')],
    guidedDiscovery: [task('Em “Can you repeat?”, can é auxiliar.'), task('Em “Does she work?”, does carrega a marca de terceira pessoa.'), task('Em “She doesn’t work”, work fica na forma base.')],
    guidedBeforeQuiz: [task('Corrija: You can help me?', 'Can you help me?'), task('Corrija: She don’t work.', 'She doesn’t work.'), task('Corrija: Does he studies?', 'Does he study?')],
    grammarGoal: 'Estabilizar ordem de frase e auxiliares antes do A2.',
    formationGuide: [task('To be question: be + subject', 'Are you ready?'), task('Can question: can + subject + verb', 'Can you repeat?'), task('Do question: do/does + subject + base verb', 'Does she work?'), task('Negative: subject + auxiliary + not + verb', 'I don’t understand.')],
    whenToUse: [task('Use be para identidade, estado e descrição.'), task('Use can para capacidade/pedido.'), task('Use do/does para perguntas com verbos comuns no presente.'), task('Use not para negativas.')],
    whenNotToUse: [task('Não use do com can.'), task('Não use does + verbo com s.'), task('Não transforme toda pergunta em entonação de afirmação.'), task('Não omita o sujeito.')],
    grammarTable: [
      { pattern: 'Be question', example: 'Are you from Brazil?', translation: 'Você é do Brasil?' },
      { pattern: 'Can question', example: 'Can you help me?', translation: 'Você pode me ajudar?' },
      { pattern: 'Do/does question', example: 'Does she work today?', translation: 'Ela trabalha hoje?' },
      { pattern: 'Negative', example: 'I don’t understand.', translation: 'Eu não entendo.' }
    ],
    teacherExamples: [
      { english: 'Do you study English every day?', translation: 'Você estuda inglês todos os dias?', why: 'Verbo comum no presente usa do.' },
      { english: 'Can you write it, please?', translation: 'Você pode escrever isso, por favor?', why: 'Can não precisa de do.' },
      { english: 'She doesn’t work on Sunday.', translation: 'Ela não trabalha no domingo.', why: 'Doesn’t + verbo base.' },
      { english: 'Are they at home?', translation: 'Eles estão em casa?', why: 'To be faz inversão.' }
    ],
    commonBrazilianMistakes: [mistake('You can repeat?', 'Can you repeat?', 'Pergunta com can começa com can.'), mistake('Does she works?', 'Does she work?', 'Com does, o verbo fica base.'), mistake('She don’t study.', 'She doesn’t study.', 'She usa does/doesn’t.'), mistake('Is you ready?', 'Are you ready?', 'You usa are.')],
    controlledPractice: [task('Complete: ___ you work today?', 'Do'), task('Complete: ___ she study English?', 'Does'), task('Complete: ___ you help me?', 'Can'), task('Complete: I ___ understand.', 'don’t')],
    errorCorrectionPractice: [task('Corrija: Do she work?', 'Does she work?'), task('Corrija: Can you to help me?', 'Can you help me?'), task('Corrija: I not understand.', 'I don’t understand.'), task('Corrija: Are he here?', 'Is he here?')],
    transformationPractice: [task('Transforme em pergunta: You study English.', 'Do you study English?'), task('Transforme em negativa: She works today.', 'She doesn’t work today.'), task('Transforme em pergunta: You can help me.', 'Can you help me?')],
    translationPractice: [task('Você trabalha hoje?', 'Do you work today?'), task('Ela não estuda à noite.', 'She doesn’t study at night.'), task('Você pode repetir?', 'Can you repeat?')],
    productionTasks: [task('Escreva 5 perguntas com do/does.'), task('Escreva 5 perguntas com can/to be.'), task('Escreva 5 negativas corrigindo erros comuns.')],
    finalChecklist: [task('Escolhi o auxiliar certo?'), task('Usei verbo base depois de do/does/can?'), task('Evitei pergunta com ordem de afirmação?'), task('Revisei he/she/it?')],
    selfAssessment: [task('Consigo formar perguntas básicas?'), task('Consigo negar frases simples?'), task('Consigo corrigir erros de auxiliar?')],
    lessonRecap: ['A2 começa reparando a base.', 'To be e can fazem inversão.', 'Verbos comuns usam do/does.', 'Depois de does, use verbo base.'],
    nextLessonBridge: 'Na próxima aula, você vai expandir vocabulário de eventos passados e datas para começar a falar do passado.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-001',
    order: 1,
    title: 'Past events and dates',
    objectives: ['Aprender vocabulário inicial para falar de eventos passados.', 'Usar datas e expressões como yesterday, last week e last year.', 'Preparar o Past Simple do pacote A2.2.', 'Criar frases simples sobre o que aconteceu.'],
    teacherOpening: 'A2 começa a abrir espaço para passado. Antes da gramática completa do Past Simple, você precisa reconhecer palavras de tempo e eventos: yesterday, last night, last week, birthday, trip, meeting, class, party. O foco é entender quando algo aconteceu.',
    whyItMatters: 'Sem expressões de tempo, o passado vira confuso. Saber dizer “yesterday”, “last week” e “two days ago” ajuda você a contar histórias simples, marcar eventos e entender mensagens.',
    realLifeUseCases: ['Falar do fim de semana.', 'Contar um evento simples.', 'Entender datas em mensagens.', 'Falar de aniversário, viagem ou aula.', 'Preparar relatos no passado.'],
    conceptExplanation: 'Past events são eventos que já aconteceram. Dates são datas. Time expressions localizam o evento: yesterday, last night, last week, last month, last year, two days ago. No A2.1, você ainda não precisa narrar tudo; precisa reconhecer e usar blocos básicos.',
    mentalModel: { title: 'evento + tempo', summary: 'Para falar do passado, diga o que aconteceu e quando.', steps: ['a party yesterday', 'a trip last week', 'a meeting two days ago'] },
    stepByStep: [task('Aprenda a expressão de tempo.'), task('Conecte com um evento.'), task('Monte frase curta.'), task('Use last para períodos passados.'), task('Use ago para contar para trás.')],
    portugueseContrast: [task('Last week = semana passada, não última semana no sentido literal.'), task('Ago vem depois da quantidade: two days ago.'), task('Birthday é aniversário de nascimento; anniversary é aniversário de casamento/evento.')],
    guidedDiscovery: [task('Yesterday indica passado recente.'), task('Last year indica ano passado.'), task('Two days ago indica dois dias atrás.')],
    guidedBeforeQuiz: [task('Yesterday = ontem.'), task('Last night = ontem à noite.'), task('Last week = semana passada.'), task('Two days ago = dois dias atrás.')],
    topicContext: 'Você vai começar a falar de eventos que já aconteceram usando datas e expressões de passado.',
    essentialWords: [vocab('yesterday', 'ontem', 'I had class yesterday.'), vocab('last night', 'ontem à noite', 'I was tired last night.'), vocab('last week', 'semana passada', 'I had a meeting last week.'), vocab('last month', 'mês passado', 'My trip was last month.'), vocab('last year', 'ano passado', 'I studied a lot last year.'), vocab('two days ago', 'dois dias atrás', 'The party was two days ago.'), vocab('event', 'evento', 'It was a small event.'), vocab('birthday', 'aniversário', 'My birthday was yesterday.'), vocab('party', 'festa', 'The party was fun.'), vocab('trip', 'viagem', 'The trip was good.'), vocab('meeting', 'reunião', 'The meeting was at work.'), vocab('class', 'aula', 'The class was at night.'), vocab('weekend', 'fim de semana', 'My weekend was busy.'), vocab('date', 'data', 'What is the date?')],
    chunks: [{ chunk: 'yesterday morning', translation: 'ontem de manhã', example: 'I worked yesterday morning.' }, { chunk: 'last weekend', translation: 'fim de semana passado', example: 'Last weekend was good.' }, { chunk: 'two days ago', translation: 'dois dias atrás', example: 'I had class two days ago.' }, { chunk: 'What happened?', translation: 'O que aconteceu?', example: 'What happened yesterday?' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Yesterday tem stress em yes.', 'Ago vem depois da quantidade.', 'Birthday tem th; pratique devagar.'] },
    dangerousConfusions: [task('Birthday ≠ anniversary em muitos contextos.'), task('Last night = ontem à noite; tonight = hoje à noite.'), task('Ago não vem antes: não diga ago two days.')],
    collocations: [task('last weekend'), task('last night'), task('two days ago'), task('birthday party'), task('work meeting'), task('English class')],
    miniDialogues: [{ title: 'Past event', lines: ['A: What happened yesterday?', 'B: I had English class.', 'A: Was it good?', 'B: Yes, it was good.'], focus: 'Evento passado simples.' }],
    examples: [ex('My birthday was last week.', 'Meu aniversário foi semana passada.', 'Evento + tempo.'), ex('The meeting was two days ago.', 'A reunião foi dois dias atrás.', 'Ago depois da quantidade.'), ex('I had English class yesterday.', 'Eu tive aula de inglês ontem.', 'Primeiro contato com passado funcional.')],
    recognitionPractice: [task('Qual expressão significa ontem?', 'yesterday'), task('Qual expressão significa semana passada?', 'last week'), task('Qual expressão significa dois dias atrás?', 'two days ago')],
    usagePractice: [task('Complete: ___ night.', 'last'), task('Complete: two days ___.', 'ago'), task('Complete: My birthday was ___ week.', 'last')],
    productionTasks: [task('Liste 5 eventos passados.'), task('Escreva 5 expressões de tempo passado.'), task('Crie 5 frases simples com event + time expression.')],
    spacedReview: [task('Revise yesterday/last/ago amanhã.'), task('Crie 3 frases sobre a semana passada.')],
    selfAssessment: [task('Consigo reconhecer tempo passado?'), task('Consigo usar last e ago?'), task('Consigo falar de um evento simples?')],
    lessonRecap: ['A2 começa preparando o passado.', 'Yesterday, last e ago localizam eventos.', 'Evento + tempo é a base de histórias simples.'],
    nextLessonBridge: 'Na Reading A2.1, você vai ler uma história curta no passado com essas expressões.',
  }),

  createReadingLesson({
    ...common,
    id: 'A2-READING-001',
    order: 1,
    title: 'A short past story',
    objectives: ['Ler uma história curta no passado.', 'Identificar sequência simples de eventos.', 'Localizar expressões de tempo passado.', 'Responder com evidência textual.'],
    teacherOpening: 'Esta é sua primeira leitura A2. O texto ainda é curto, mas agora traz uma história simples sobre algo que aconteceu. O foco é entender sequência: first, then, after that e yesterday.',
    whyItMatters: 'No A2, você começa a contar e entender pequenas histórias. Para isso, precisa localizar tempo, ações e ordem dos acontecimentos.',
    realLifeUseCases: ['Ler mensagem sobre fim de semana.', 'Entender relato curto.', 'Responder o que aconteceu primeiro/depois.', 'Preparar escrita de história simples.'],
    conceptExplanation: 'Em uma história curta, procure quando aconteceu, quem participou e quais ações aconteceram. Sequence words como first, then e after that mostram ordem.',
    mentalModel: { title: 'quando + quem + sequência', summary: 'Toda história simples tem tempo, pessoa e ações em ordem.', steps: ['When?', 'Who?', 'First?', 'Then?', 'After that?'] },
    stepByStep: [task('Leia para descobrir quando aconteceu.'), task('Identifique a pessoa principal.'), task('Marque first/then/after that.'), task('Responda perguntas com evidência.'), task('Resuma em 2 frases.')],
    portugueseContrast: [task('Não tente traduzir todos os verbos irregulares agora; use contexto.'), task('Then indica depois.'), task('After that indica depois disso.')],
    guidedDiscovery: [task('Yesterday mostra tempo passado.'), task('First mostra primeiro evento.'), task('Then mostra próximo evento.')],
    guidedBeforeQuiz: [task('Procure time expressions.'), task('Procure sequence words.'), task('Use evidência textual.')],
    readingPurpose: 'Entender uma história curta no passado com sequência simples.',
    preReadingVocabulary: [vocab('yesterday', 'ontem'), vocab('first', 'primeiro'), vocab('then', 'então/depois'), vocab('after that', 'depois disso'), vocab('tired', 'cansado')],
    readingStrategy: [task('Leia o começo para achar quando.'), task('Use first/then/after that para ordem.'), task('Volte ao texto para evidência.'), task('Não chute ação fora do texto.')],
    mainText: `Yesterday was a busy day for Marco. He woke up early and worked at the coffee shop in the morning. Then he had lunch with his mother, Dona Lúcia, at her house. After lunch, Marco took the bus to his English class downtown. The class was interesting, but Marco was very tired. He liked the lesson because he learned new words about travel and dates.`,
    firstReadTask: task('Qual é o assunto geral do texto?', 'Marco conta seu dia ocupado de ontem.', "Marco's busy day"),
    secondReadTasks: [task('Quando aconteceu?', 'yesterday'), task('Onde Marco trabalhou de manhã?', 'at the coffee shop'), task('Com quem Marco almoçou?', 'with his mother, Dona Lúcia'), task('Como Marco foi para a aula?', 'took the bus')],
    evidenceQuestions: [q("When was Marco's busy day?", 'yesterday', 'Yesterday was a busy day for Marco.', '', ['yesterday','last week','today']), q('Where did Marco work in the morning?', 'at the coffee shop', 'He worked at the coffee shop in the morning.', '', ['at the coffee shop','at school','downtown']), q('Who did Marco have lunch with?', 'his mother, Dona Lúcia', 'he had lunch with his mother, Dona Lúcia', '', ['his mother','his teacher','his friend']), q('How was the class?', 'interesting', 'The class was interesting, but Marco was very tired.', '', ['interesting','boring','short']), q('Why did Marco like the lesson?', 'because he learned new words about travel and dates', 'He liked the lesson because he learned new words about travel and dates.', '', ['learned new words about travel and dates','met a friend','finished early'])],
    contextVocabularyTasks: [task('Busy significa cheio/ocupado pelo contexto.', 'Yesterday was a busy day for Marco.'), task('Learned indica algo aprendido no passado.', 'He learned new words.'), task('Travel and dates prepara vocabulário A2.')],
    guidedSummary: task('Complete: Yesterday, Marco worked at the ___, had lunch with ___ and went to English class by ___.', '', 'coffee shop / his mother Dona Lúcia / bus'),
    connectedProduction: task('Escreva 3 frases sobre seu dia de ontem usando first, then e after that.'),
    selfAssessment: [task('Consigo achar sequência?'), task('Consigo responder com evidência?'), task('Consigo reconhecer yesterday/then/after that?')],
    lessonRecap: ['Reading A2 começa com histórias curtas.', 'Sequence words mostram ordem.', 'Evidência continua obrigatória.', 'Passado pode ser entendido por contexto.'],
    nextLessonBridge: 'No Listening, você vai ouvir uma conversa curta sobre fim de semana passado.',
  }),

  createListeningLesson({
    ...common,
    id: 'A2-LISTENING-001',
    order: 1,
    title: 'Past weekend conversation',
    objectives: ['Ouvir uma conversa curta sobre fim de semana passado.', 'Identificar atividades principais.', 'Reconhecer yesterday, last weekend e then.', 'Praticar dictation e shadowing de frases no passado.'],
    teacherOpening: 'No A2, listening começa a incluir relatos sobre o passado. Na primeira escuta, entenda o tema geral. Na segunda, procure as atividades. Depois, confira com transcript e repita frases-chave.',
    whyItMatters: 'Conversas sobre o fim de semana são comuns. Você precisa entender perguntas como What did you do? e respostas simples sobre atividades passadas.',
    realLifeUseCases: ['Conversar sobre fim de semana.', 'Entender relato simples.', 'Responder o que alguém fez.', 'Praticar past time expressions.'],
    conceptExplanation: 'Ouça por blocos: last weekend, yesterday, worked, visited, studied, watched. Não tente traduzir tudo; identifique evento e tempo.',
    mentalModel: { title: 'tempo + atividade', summary: 'Ouça quando e o que aconteceu.', steps: ['last weekend', 'visited family', 'watched a movie', 'studied English'] },
    stepByStep: [task('Primeira escuta: assunto geral.'), task('Segunda escuta: atividades.'), task('Terceira etapa: ordem.'), task('Leia transcript.'), task('Faça dictation.'), task('Faça shadowing.')],
    portugueseContrast: [task('What did you do? é pergunta sobre passado.'), task('Did já marca passado; o verbo fica base depois dele.'), task('Last weekend = fim de semana passado.')],
    guidedDiscovery: [task('What did you do? anuncia relato passado.'), task('Last weekend localiza o tempo.'), task('Then mostra sequência.')],
    guidedBeforeQuiz: [task('Primeira escuta: sobre o quê falam?'), task('Segunda escuta: quais atividades aparecem?')],
    listeningPreparation: [task('Não leia transcript antes da primeira escuta.'), task('Prepare: last weekend, visited, watched, studied, tired.'), task('Objetivo: tempo + atividade.')],
    keyWordsToHear: [vocab('last weekend','fim de semana passado'), vocab('visited','visitei'), vocab('watched','assisti'), vocab('studied','estudei'), vocab('tired','cansado')],
    audioScript: `A: Hey! What did you do last weekend?
B: It was great, actually. I visited my family on Saturday. We had a big lunch — my grandmother cooked everything.
A: Nice! Did you go out at night?
B: Yes, we watched a movie. It was in English, which was a bit difficult!
A: Ha! Did you study English on Sunday too?
B: Yes, I did. I studied on Sunday morning. I was tired, but the class was really good.`,
    firstListenTasks: [task('Sem transcript: a conversa é sobre fim de semana, trabalho ou viagem?', 'fim de semana'), task('Sem transcript: a pessoa assistiu a um filme?', 'yes'), task('Sem transcript: a pessoa estudou inglês?', 'yes')],
    secondListenTasks: [task('Quando a pessoa visitou a família?', 'on Saturday'), task('O que a avó fez?', 'cooked everything'), task('Por que o filme foi difícil?', 'it was in English'), task('Quando estudou inglês?', 'on Sunday morning')],
    transcript: `A: Hey! What did you do last weekend?
B: It was great, actually. I visited my family on Saturday. We had a big lunch — my grandmother cooked everything.
A: Nice! Did you go out at night?
B: Yes, we watched a movie. It was in English, which was a bit difficult!
A: Ha! Did you study English on Sunday too?
B: Yes, I did. I studied on Sunday morning. I was tired, but the class was really good.`,
    vocabulary: [vocab('what did you do?', 'o que você fez?'), vocab('visited', 'visitou/visitei'), vocab('watched', 'assistiu/assisti'), vocab('studied', 'estudou/estudei')],
    shadowing: [task('What did you do last weekend?'), task('I visited my family on Saturday.'), task('Then I watched a movie at night.'), task('Did you study English?'), task('I was tired, but the class was good.')],
    dictationTasks: [task('Digite: What did you do last weekend?', 'What did you do last weekend?'), task('Digite: I visited my family on Saturday.', 'I visited my family on Saturday.'), task('Digite: I was tired, but the class was good.', 'I was tired, but the class was good.')],
    pronunciationChunks: [task('What did you do', 'Pode soar conectado.'), task('last weekend', 'Bloco de tempo.'), task('visited my family', 'Atenção ao -ed de visited.')],
    listeningComprehension: [q('Áudio da aula — Past weekend conversation — what did the person do on Saturday?', 'visited family', 'I visited my family on Saturday.', '', ['visited family','worked','went shopping']), q('What did the person watch?', 'a movie', 'I watched a movie at night.', '', ['a movie','a class','a game']), q('Áudio da aula — Past weekend conversation — when did the person study English?', 'on Sunday morning', 'I studied on Sunday morning.', '', ['on Sunday morning','on Friday night','on Monday'])],
    oralProduction: task('Grave uma resposta curta: What did you do last weekend?'),
    selfAssessment: [task('Consegui ouvir last weekend?'), task('Consegui identificar atividades?'), task('Consegui repetir uma pergunta no passado?')],
    lessonRecap: ['Listening A2 começa com relatos passados simples.', 'What did you do? é pergunta-chave.', 'Last weekend localiza o tempo.', 'Then organiza sequência.'],
    nextLessonBridge: 'No Speaking, você vai falar sobre ontem usando frases curtas.',
  }),

  createSpeakingLesson({
    ...common,
    id: 'A2-SPEAKING-001',
    order: 1,
    title: 'Talk about yesterday',
    objectives: ['Falar sobre ontem com frases curtas.', 'Usar sequência simples: first, then, after that.', 'Responder What did you do yesterday?', 'Gravar um relato curto de 30 segundos.'],
    teacherOpening: 'Agora você começa a falar no passado de forma simples. O objetivo não é contar uma história perfeita; é responder com segurança: Yesterday, I worked. Then I studied English. After that, I watched a movie.',
    whyItMatters: 'Falar sobre ontem é a porta de entrada para histórias A2. Você pratica passado, sequência e fluência sem precisar de frases longas.',
    realLifeUseCases: ['Responder sobre ontem.', 'Falar do fim de semana.', 'Contar rotina passada.', 'Participar de conversa simples.'],
    conceptExplanation: 'Use frases curtas e sequência. Comece com Yesterday. Depois use first, then e after that. Use verbos passados que você já viu: worked, studied, watched, visited, had.',
    mentalModel: { title: 'Yesterday + sequence', summary: 'Três frases já formam um relato A2.', steps: ['Yesterday, I worked.', 'Then I studied English.', 'After that, I watched a movie.'] },
    stepByStep: [task('Comece com Yesterday.'), task('Diga a primeira ação.'), task('Use then para a segunda.'), task('Use after that para a terceira.'), task('Adicione sentimento: I was tired/happy.'), task('Grave e repita.')],
    portugueseContrast: [task('Não tente traduzir “eu fui fazendo”.'), task('Use ações simples no passado.'), task('Did aparece em pergunta, não em toda resposta afirmativa.')],
    guidedDiscovery: [task('What did you do yesterday? pede passado.'), task('Yesterday localiza o tempo.'), task('Then organiza sequência.')],
    guidedBeforeQuiz: [task('Repita: Yesterday, I worked.'), task('Repita: Then I studied English.'), task('Repita: After that, I watched a movie.'), task('Repita: I was tired, but happy.')],
    speakingSituation: 'Você vai responder a uma pergunta simples sobre o que fez ontem.',
    modelPhrases: [phrase('What did you do yesterday?', 'O que você fez ontem?'), phrase('Yesterday, I worked in the morning.', 'Ontem, eu trabalhei de manhã.'), phrase('Then I studied English.', 'Depois eu estudei inglês.'), phrase('After that, I watched a movie.', 'Depois disso, eu assisti um filme.'), phrase('I was tired, but happy.', 'Eu estava cansado, mas feliz.')],
    pronunciationChunks: [task('What did you do', 'Pratique como bloco.'), task('Yesterday, I', 'Conecte naturalmente.'), task('After that', 'Bloco de sequência.')],
    repeatAfterMe: [task('What did you do yesterday?'), task('Yesterday, I worked.'), task('Then I studied English.'), task('After that, I watched a movie.'), task('I was tired, but happy.')],
    substitutionDrills: [task('worked → studied', 'Yesterday, I studied.'), task('watched a movie → visited my family', 'After that, I visited my family.'), task('tired → happy', 'I was happy.')],
    guidedSpeaking: [task('Diga uma ação de ontem.'), task('Diga uma segunda ação com then.'), task('Diga uma terceira ação com after that.'), task('Diga como você se sentiu.')],
    recordingTasks: [task('Grave 3 frases sobre ontem.'), task('Grave resposta completa de 30 segundos.'), task('Grave novamente usando first/then/after that.')],
    freeSpeaking: task('Fale por 30–45 segundos sobre ontem ou fim de semana passado.'),
    feedbackChecklist: [task('Usei yesterday/last weekend?'), task('Usei sequência?'), task('Usei frases curtas?'), task('Incluí sentimento?'), task('Minha fala ficou compreensível?')],
    selfAssessment: [task('Consigo responder What did you do yesterday?'), task('Consigo usar then/after that?'), task('Consigo gravar 30 segundos?')],
    lessonRecap: ['Falar do passado começa com frases curtas.', 'Yesterday e last weekend localizam tempo.', 'Then e after that organizam sequência.', 'Sentimento fecha o relato.'],
    nextLessonBridge: 'Na Writing, você vai escrever sobre ontem com a mesma estrutura.',
  }),

  createWritingLesson({
    ...common,
    id: 'A2-WRITING-001',
    order: 1,
    title: 'Write about yesterday',
    objectives: ['Escrever um parágrafo curto sobre ontem.', 'Usar sequência simples no passado.', 'Revisar pontuação e conectores de sequência.', 'Preparar escrita de histórias curtas A2.'],
    teacherOpening: 'Nesta primeira escrita A2, você vai escrever sobre ontem. O texto precisa ser simples e claro: Yesterday, I worked in the morning. Then I studied English. After that, I watched a movie. I was tired, but happy.',
    whyItMatters: 'Escrever sobre ontem prepara você para histórias curtas, mensagens e relatos simples. É a ponte entre A1 e A2 real.',
    realLifeUseCases: ['Escrever sobre o dia anterior.', 'Mandar mensagem sobre fim de semana.', 'Criar diário simples.', 'Preparar relatos mais longos no A2.'],
    conceptExplanation: 'Use um parágrafo de 4 a 6 frases. Comece com Yesterday. Use then e after that para sequência. Termine com opinião ou sentimento. Revise maiúsculas, ponto final e verbos no passado.',
    mentalModel: { title: 'tempo + ações + sentimento', summary: 'Um texto A2 simples conta o que aconteceu em ordem.', steps: ['Yesterday...', 'Then...', 'After that...', 'I was...'] },
    stepByStep: [task('Escreva uma frase com Yesterday.'), task('Adicione uma segunda ação com Then.'), task('Adicione uma terceira ação com After that.'), task('Adicione sentimento/opinião.'), task('Revise pontuação.'), task('Leia em voz alta.')],
    portugueseContrast: [task('Não escreva frases muito longas.'), task('Use ponto final para separar ações.'), task('Não use did em afirmativas simples como regra geral.'), task('Use was para estado passado: I was tired.')],
    guidedDiscovery: [task('Yesterday inicia o tempo.'), task('Then mostra próxima ação.'), task('After that mostra sequência.'), task('I was tired mostra estado no passado.')],
    guidedBeforeQuiz: [task('Modelo: Yesterday, I worked.'), task('Modelo: Then I studied English.'), task('Modelo: After that, I watched a movie.'), task('Modelo: I was tired, but happy.')],
    writingPurpose: 'Escrever um relato curto sobre ontem.',
    modelText: `Yesterday, I worked in the morning. Then I had lunch with my family. After that, I studied English at night. The class was good. I was tired, but happy.`,
    writingBlocks: [task('Time', 'Yesterday, I worked in the morning.'), task('Second action', 'Then I had lunch with my family.'), task('Third action', 'After that, I studied English at night.'), task('Opinion', 'The class was good.'), task('Feeling', 'I was tired, but happy.')],
    guidedSubstitution: [task('Troque worked por studied.', 'Yesterday, I studied in the morning.'), task('Troque had lunch por visited my family.', 'Then I visited my family.'), task('Troque tired por happy.', 'I was happy.')],
    grammarForWriting: [task('Use letra maiúscula no começo.'), task('Use vírgula depois de Yesterday quando fizer sentido.'), task('Use ponto final em cada ação.'), task('Use then/after that para ordem.'), task('Use was/were para estado passado.')],
    checklist: [task('Meu texto tem 4 a 6 frases?'), task('Comecei com Yesterday ou Last weekend?'), task('Usei sequência?'), task('Incluí sentimento/opinião?'), task('Revisei pontuação?')],
    draftTask: task('Escreva 4 a 6 frases sobre ontem.'),
    revisionTask: task('Revise tempo, sequência, pontuação e verbos.'),
    commonMistakes: [mistake('Yesterday I work.', 'Yesterday, I worked.', 'Evento passado pede forma passada.'), mistake('Then I did studied.', 'Then I studied.', 'Não use did em afirmativa simples.'), mistake('I was tired but.', 'I was tired, but happy.', 'But precisa completar contraste.')],
    productionTasks: [task('Escreva um parágrafo sobre ontem.'), task('Escreva uma versão sobre last weekend.'), task('Reescreva melhorando sequência com first/then/after that.')],
    selfAssessment: [task('Consigo escrever sobre ontem?'), task('Consigo organizar sequência?'), task('Consigo revisar frases no passado?')],
    lessonRecap: ['Writing A2 começa com relatos curtos.', 'Yesterday e last weekend dão tempo.', 'Then/after that organizam ações.', 'Sentimento/opinião fecha o texto.'],
    nextLessonBridge: 'No próximo bloco A2, você vai aprofundar Past Simple regular verbs.',
  }),
]);

export const A2_DEEP_BRIDGE_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_BRIDGE.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_BRIDGE.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_BRIDGE.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_BRIDGE.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_BRIDGE.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_BRIDGE.filter((lesson) => lesson.pillar === 'writing')),
});
