import { createGrammarLesson, createVocabularyLesson, createReadingLesson, createListeningLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-4', 'comparisons-needs', 'quantities', 'food-containers', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }
function q(question, answer, evidence = '', explanation = '', options = []) { return { question, answer, evidence, explanation, options }; }
function ex(text, translation, why = '', warning = '') { return { text, translation, why, warning }; }

export const A2_DEEP_COMPARISONS_NEEDS_PART2 = Object.freeze([
  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-015',
    order: 15,
    title: 'Some / any',
    objectives: ['Usar some em afirmações e ofertas/pedidos educados.', 'Usar any em negativas e perguntas neutras.', 'Aplicar some/any com contáveis plurais e incontáveis.', 'Evitar erros como I don’t have some money.'],
    teacherOpening: 'Depois de countable e uncountable, você precisa escolher some ou any. Some normalmente aparece em afirmações: I have some apples. Any normalmente aparece em negativas e perguntas: I don’t have any money. Do you have any water?',
    whyItMatters: 'Some/any aparece em compras, comida, dinheiro, informação, roupas e decisões. É uma base para falar de quantidade sem número exato.',
    realLifeUseCases: ['Perguntar se há comida em casa.', 'Dizer que tem algumas roupas.', 'Dizer que não tem dinheiro/informação.', 'Fazer pedido educado em loja ou restaurante.'],
    conceptExplanation: 'Use some em afirmações: We have some apples. Use any em negativas: We don’t have any bread. Use any em perguntas neutras: Do you have any jackets? Use some em ofertas e pedidos quando você espera sim: Would you like some water? Can I have some information?',
    mentalModel: { title: 'some = existe / any = pergunta ou ausência', summary: 'Some afirma ou oferece. Any pergunta de forma neutra ou nega.', steps: ['I have some...', 'I don’t have any...', 'Do you have any...?', 'Can I have some...?'] },
    stepByStep: [task('Identifique o tipo de frase.'), task('Afirmação comum: use some.'), task('Negativa: use any.'), task('Pergunta neutra: use any.'), task('Oferta/pedido educado esperando sim: use some.')],
    portugueseContrast: [task('Em português “algum/alguns” muda muito; em inglês a lógica é tipo de frase.'), task('Não diga I don’t have some money.'), task('Can I have some...? é pedido educado natural.'), task('Any em negativa pode significar nenhum/nenhuma.')],
    guidedDiscovery: [task('I have some money é afirmação.'), task('I don’t have any money é negativa.'), task('Do you have any water? é pergunta neutra.'), task('Would you like some coffee? é oferta.')],
    guidedBeforeQuiz: [task('Complete: I have ___ apples.', 'some'), task('Complete: I don’t have ___ money.', 'any'), task('Complete: Do you have ___ water?', 'any'), task('Complete: Can I have ___ information?', 'some')],
    grammarGoal: 'Controlar some/any em frases de quantidade A2.',
    formationGuide: [task('Affirmative', 'I have some oranges.'), task('Negative', 'I don’t have any milk.'), task('Question', 'Do you have any bread?'), task('Offer/request', 'Would you like some water? / Can I have some information?')],
    whenToUse: [task('Some: afirmação, oferta, pedido educado.'), task('Any: negativa e pergunta neutra.'), task('Com plural contável e incontável.')],
    whenNotToUse: [task('Não use some em negativa comum.'), task('Não use any em afirmação comum no A2, salvo sentido especial.'), task('Não use a/an com incontáveis quando some resolve melhor.')],
    grammarTable: [
      { pattern: 'some affirmative', example: 'I bought some apples.', translation: 'Comprei algumas maçãs.' },
      { pattern: 'any negative', example: 'I don’t have any cash.', translation: 'Não tenho nenhum dinheiro em espécie.' },
      { pattern: 'any question', example: 'Do you have any jackets in size M?', translation: 'Tem jaquetas tamanho M?' },
      { pattern: 'some request', example: 'Can I have some water?', translation: 'Posso tomar um pouco de água?' }
    ],
    teacherExamples: [
      { english: 'There are some bottles of water in the kitchen.', translation: 'Há algumas garrafas de água na cozinha.', why: 'Afirmação com plural contável.' },
      { english: 'We don’t have any bread.', translation: 'Não temos pão.', why: 'Negativa com incontável.' },
      { english: 'Do you have any T-shirts in large?', translation: 'Tem camisetas tamanho G?', why: 'Pergunta neutra.' },
      { english: 'Can I have some advice?', translation: 'Pode me dar um conselho?', why: 'Pedido educado com incontável.' }
    ],
    commonBrazilianMistakes: [mistake('I don’t have some money.', 'I don’t have any money.', 'Negativa comum usa any.'), mistake('Do you have some jackets?', 'Do you have any jackets?', 'Pergunta neutra usa any.'), mistake('I need any water.', 'I need some water.', 'Afirmação comum usa some.'), mistake('Can I have any water?', 'Can I have some water?', 'Pedido educado geralmente usa some.')],
    controlledPractice: [task('Complete: We have ___ rice.', 'some'), task('Complete: We don’t have ___ eggs.', 'any'), task('Complete: Are there ___ apples?', 'any'), task('Complete: Would you like ___ coffee?', 'some')],
    errorCorrectionPractice: [task('Corrija: I don’t have some time.', 'I don’t have any time.'), task('Corrija: I bought any oranges.', 'I bought some oranges.'), task('Corrija: Do you have some milk?', 'Do you have any milk?')],
    transformationPractice: [task('Afirmação → negativa: I have some money.', 'I don’t have any money.'), task('Afirmação → pergunta: We have some apples.', 'Do we have any apples?'), task('Pedido: water', 'Can I have some water?')],
    translationPractice: [task('Eu tenho algumas maçãs.', 'I have some apples.'), task('Não tenho dinheiro.', 'I don’t have any money.'), task('Você tem alguma informação?', 'Do you have any information?')],
    productionTasks: [task('Escreva 6 afirmações com some.'), task('Escreva 6 negativas com any.'), task('Crie 5 perguntas de loja/restaurante com any e 3 pedidos com some.')],
    finalChecklist: [task('A frase é afirmação, negativa ou pergunta?'), task('Usei any em negativa?'), task('Usei some em afirmação/pedido?'), task('O substantivo é plural contável ou incontável?')],
    selfAssessment: [task('Consigo escolher some/any?'), task('Consigo fazer pedido educado com some?'), task('Consigo evitar negativa com some?')],
    lessonRecap: ['Some aparece em afirmações e pedidos/ofertas.', 'Any aparece em negativas e perguntas neutras.', 'Ambos funcionam com plural contável e incontável.', 'O tipo de frase guia a escolha.'],
    nextLessonBridge: 'Agora você vai falar de quantidade com much, many e a lot of.',
  }),

  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-016',
    order: 16,
    title: 'Much / many / a lot of',
    objectives: ['Usar many com contáveis plurais.', 'Usar much com incontáveis.', 'Usar a lot of com contáveis plurais e incontáveis.', 'Aplicar em comida, dinheiro, tempo, roupas e escolhas.'],
    teacherOpening: 'Much, many e a lot of respondem “quanto?”. Many combina com coisas contáveis no plural: many apples. Much combina com incontáveis: much money. A lot of funciona com os dois: a lot of apples, a lot of money.',
    whyItMatters: 'Quantidade aparece em compras, comida, dinheiro, tempo, tarefas e comparação de produtos. Essa aula evita erros muito comuns como much apples e many money.',
    realLifeUseCases: ['Perguntar preço e quantidade.', 'Falar de comida disponível.', 'Comparar dinheiro e tempo.', 'Descrever muitas roupas/produtos.', 'Dizer que há muito trabalho.'],
    conceptExplanation: 'Use many com plural contável: many shirts, many bottles. Use much com incontável: much water, much time, much money. Use a lot of em frases afirmativas com ambos: a lot of shirts, a lot of water.',
    mentalModel: { title: 'many = countable / much = uncountable / a lot of = ambos', summary: 'Primeiro identifique o substantivo.', steps: ['many apples', 'much water', 'a lot of apples', 'a lot of water'] },
    stepByStep: [task('Veja se o substantivo é contável plural ou incontável.'), task('Contável plural: many.'), task('Incontável: much.'), task('Quando estiver em dúvida em afirmação: a lot of geralmente funciona.'), task('Revise erros comuns.')],
    portugueseContrast: [task('Money é incontável: much money / a lot of money.'), task('Time é incontável quando significa tempo geral.'), task('Work é incontável quando significa trabalho/tarefas no geral.'), task('Many clothes é possível porque clothes é plural.')],
    guidedDiscovery: [task('Apples são contáveis → many apples.'), task('Water é incontável → much water.'), task('A lot of serve nos dois.'), task('Questions usam How much/How many.')],
    guidedBeforeQuiz: [task('Complete: How ___ apples?', 'many'), task('Complete: How ___ water?', 'much'), task('Complete: I have ___ of work.', 'a lot')],
    grammarGoal: 'Quantificar substantivos contáveis e incontáveis com much/many/a lot of.',
    formationGuide: [task('many + plural countable', 'many bottles / many shirts'), task('much + uncountable', 'much money / much time'), task('a lot of + both', 'a lot of food / a lot of products'), task('How many?', 'How many apples do we need?'), task('How much?', 'How much water do we need?')],
    whenToUse: [task('Many: quantidade de itens contáveis.'), task('Much: quantidade de massa/ideia/incontável.'), task('A lot of: quantidade grande em fala comum.')],
    whenNotToUse: [task('Não use many com money/water/time.'), task('Não use much com apples/shirts/bottles.'), task('Não esqueça plural depois de many.')],
    grammarTable: [
      { pattern: 'many + countable', example: 'There are many bottles on the table.', translation: 'Há muitas garrafas na mesa.' },
      { pattern: 'much + uncountable', example: 'We don’t have much water.', translation: 'Não temos muita água.' },
      { pattern: 'a lot of + countable', example: 'She bought a lot of apples.', translation: 'Ela comprou muitas maçãs.' },
      { pattern: 'a lot of + uncountable', example: 'He has a lot of work today.', translation: 'Ele tem muito trabalho hoje.' }
    ],
    teacherExamples: [
      { english: 'How many containers do we need?', translation: 'De quantos recipientes precisamos?', why: 'Containers são contáveis.' },
      { english: 'How much rice do we have?', translation: 'Quanto arroz temos?', why: 'Rice é incontável.' },
      { english: 'There is a lot of food in the kitchen.', translation: 'Há muita comida na cozinha.', why: 'Food é geralmente incontável.' },
      { english: 'There are a lot of shoes in this store.', translation: 'Há muitos sapatos nesta loja.', why: 'Shoes é plural contável.' }
    ],
    commonBrazilianMistakes: [mistake('many money', 'much money / a lot of money', 'Money é incontável.'), mistake('much apples', 'many apples / a lot of apples', 'Apples é contável plural.'), mistake('how many water', 'how much water', 'Water é incontável.'), mistake('how much bottles', 'how many bottles', 'Bottles é contável plural.')],
    controlledPractice: [task('Complete: How ___ bottles?', 'many'), task('Complete: How ___ milk?', 'much'), task('Complete: There are ___ of oranges.', 'a lot'), task('Complete: I don’t have ___ time.', 'much')],
    errorCorrectionPractice: [task('Corrija: How many money do you have?', 'How much money do you have?'), task('Corrija: I need much apples.', 'I need many apples. / a lot of apples.'), task('Corrija: There is many food.', 'There is a lot of food.')],
    transformationPractice: [task('Pergunta: bottles', 'How many bottles do we need?'), task('Pergunta: water', 'How much water do we need?'), task('Afirmação grande quantidade: food', 'There is a lot of food.')],
    translationPractice: [task('Quanto dinheiro você tem?', 'How much money do you have?'), task('Quantas garrafas precisamos?', 'How many bottles do we need?'), task('Há muita comida na cozinha.', 'There is a lot of food in the kitchen.')],
    productionTasks: [task('Escreva 5 perguntas com how many.'), task('Escreva 5 perguntas com how much.'), task('Crie 8 frases com a lot of em compras e comida.')],
    finalChecklist: [task('O substantivo é plural contável? many/how many.'), task('É incontável? much/how much.'), task('É afirmação com grande quantidade? a lot of.'), task('Evitei many money?')],
    selfAssessment: [task('Consigo usar how much/how many?'), task('Consigo usar a lot of?'), task('Consigo corrigir much apples/many money?')],
    lessonRecap: ['Many acompanha plurais contáveis.', 'Much acompanha incontáveis.', 'A lot of funciona com ambos em fala comum.', 'How many e How much dependem do substantivo.'],
    nextLessonBridge: 'Agora você vai aplicar quantidade em comida e recipientes.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-014',
    order: 14,
    title: 'Food quantities and containers',
    objectives: ['Aprender vocabulário de comida, quantidades e recipientes.', 'Usar bottle, can, bag, box, piece, slice, cup e kilo.', 'Falar de compras de mercado.', 'Aplicar some/any, much/many e a lot of em contexto.'],
    teacherOpening: 'Food quantities and containers transforma quantidade em situação real. Você vai falar de a bottle of water, a can of soda, a bag of rice, a box of cereal, a piece of cake, a slice of bread, a cup of coffee e a kilo of apples.',
    whyItMatters: 'Muita comida é incontável em inglês, então você precisa de recipientes e unidades para comprar, pedir ou comparar.',
    realLifeUseCases: ['Fazer lista de mercado.', 'Pedir comida/bebida.', 'Comparar quantidades.', 'Perguntar o que tem em casa.', 'Planejar compras.'],
    conceptExplanation: 'Use container/unit + of + noun: a bottle of water, two cans of soda, a bag of rice. Isso transforma incontáveis em unidades contáveis.',
    mentalModel: { title: 'container + of + food', summary: 'O recipiente conta aquilo que sozinho seria difícil contar.', steps: ['a bottle of water', 'a bag of rice', 'two cans of soda'] },
    stepByStep: [task('Identifique alimento/bebida.'), task('Escolha recipiente/unidade.'), task('Use of.'), task('Coloque número se necessário.'), task('Use some/any/much/many corretamente.')],
    portugueseContrast: [task('A bottle of water = uma garrafa de água.'), task('A piece of cake = um pedaço de bolo.'), task('A slice of bread = uma fatia de pão.'), task('A can of soda = uma lata de refrigerante.')],
    guidedDiscovery: [task('Water precisa de bottle/cup se contar unidade.'), task('Rice usa bag/kilo.'), task('Bread usa slice/loaf.'), task('Apples são contáveis: many apples / a kilo of apples.')],
    guidedBeforeQuiz: [task('a bottle of water'), task('two cans of soda'), task('a bag of rice'), task('a slice of bread')],
    topicContext: 'Você vai comprar comida e falar de quantidade com unidades naturais.',
    essentialWords: [vocab('bottle', 'garrafa', 'a bottle of water'), vocab('can', 'lata', 'two cans of soda'), vocab('bag', 'saco/pacote', 'a bag of rice'), vocab('box', 'caixa', 'a box of cereal'), vocab('piece', 'pedaço', 'a piece of cake'), vocab('slice', 'fatia', 'a slice of bread'), vocab('cup', 'xícara/copo', 'a cup of coffee'), vocab('kilo', 'quilo', 'a kilo of apples'), vocab('rice', 'arroz', 'a bag of rice'), vocab('bread', 'pão', 'a slice of bread'), vocab('milk', 'leite', 'a bottle of milk'), vocab('cheese', 'queijo', 'a piece of cheese'), vocab('sugar', 'açúcar', 'a bag of sugar'), vocab('coffee', 'café', 'a cup of coffee')],
    chunks: [{ chunk: 'a bottle of water', translation: 'uma garrafa de água', example: 'We need a bottle of water.' }, { chunk: 'a bag of rice', translation: 'um saco/pacote de arroz', example: 'Do we have any rice?' }, { chunk: 'two cans of soda', translation: 'duas latas de refrigerante', example: 'I bought two cans of soda.' }, { chunk: 'a slice of bread', translation: 'uma fatia de pão', example: 'I need a slice of bread.' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Bottle costuma soar com t/d leve no inglês americano.', 'Piece soa como piiss.', 'Slice termina com som de S claro.'] },
    dangerousConfusions: [task('Cup pode ser xícara ou copo pequeno pelo contexto.'), task('Can como substantivo é lata; como verbo modal é poder.'), task('Piece é pedaço; peace é paz.'), task('Slice é fatia fina.')],
    collocations: [task('a bottle of water'), task('a can of soda'), task('a bag of rice'), task('a box of cereal'), task('a piece of cake'), task('a slice of bread'), task('a cup of coffee')],
    miniDialogues: [{ title: 'At the market', lines: ['A: Do we have any rice?', 'B: No, we don’t have any rice.', 'A: How much do we need?', 'B: A bag of rice and two bottles of water.'], focus: 'Some/any + containers.' }],
    examples: [ex('We don’t have any milk, so I am going to buy a bottle.', 'Não temos leite, então vou comprar uma garrafa.', 'Any + plano.'), ex('How many cans of soda do we need?', 'De quantas latas de refrigerante precisamos?', 'Many + cans.'), ex('There is a lot of food in the kitchen.', 'Há muita comida na cozinha.', 'A lot of + food.')],
    recognitionPractice: [{ question: 'Food quantities and containers — qual vocabulário desta aula significa "garrafa"?', options: ['bottle', 'can', 'bag'], answer: 'bottle', explanation: 'bottle = garrafa; vocabulário trabalhado nesta aula de Food quantities and containers.' }, task('Qual palavra é fatia?', 'slice'), task('Qual palavra é lata?', 'can'), task('Qual expressão é uma garrafa de água?', 'a bottle of water')],
    usagePractice: [task('Complete: a bottle ___ water', 'of'), task('Complete: two cans ___ soda', 'of'), task('Complete: a slice ___ bread', 'of')],
    productionTasks: [task('Crie uma lista de mercado com 10 itens usando containers.'), task('Escreva 6 perguntas com how much/how many.'), task('Crie diálogo de mercado com some/any.')],
    spacedReview: [task('Revise bottle/can/bag/box/piece/slice amanhã.'), task('Crie 3 frases com a lot of food/water/products.')],
    selfAssessment: [task('Consigo falar de recipientes?'), task('Consigo fazer lista de mercado?'), task('Consigo usar of corretamente?')],
    lessonRecap: ['Containers ajudam a contar comida e bebida.', 'Use container + of + noun.', 'How many combina com containers no plural.', 'Some/any e much/many ficam mais fáceis com unidade clara.'],
    nextLessonBridge: 'Agora você vai ler e ouvir textos com quantidades, sequência e planos.',
  }),

  createReadingLesson({
    ...common,
    id: 'A2-READING-017',
    order: 17,
    title: 'Reading for comparisons',
    objectives: ['Ler texto curto com quantidades e comparação.', 'Identificar itens, unidades, preço e escolha.', 'Reconhecer some/any, much/many e a lot of em contexto.', 'Responder com evidência textual.'],
    teacherOpening: 'Nesta leitura, você vai juntar quantidade e comparação. O texto fala de uma compra de mercado e escolha entre duas opções. Você vai localizar unidades, quantidades e motivo da decisão.',
    whyItMatters: 'A2.4 exige comparar opções e falar de quantidade em situações reais. Mercado, roupas e produtos são contextos perfeitos para isso.',
    realLifeUseCases: ['Ler lista de mercado.', 'Comparar duas opções de compra.', 'Decidir quantidade.', 'Entender preço e unidade.', 'Justificar escolha.'],
    conceptExplanation: 'Procure containers: bottle, bag, box, can. Procure quantifiers: some, any, many, much, a lot of. Procure comparação e decisão: cheaper, more expensive, better choice.',
    mentalModel: { title: 'read quantities + choice', summary: 'Leia lista, quantidade e motivo da escolha.', steps: ['items', 'containers', 'quantity', 'comparison', 'decision'] },
    stepByStep: [task('Marque os itens comprados.'), task('Marque recipientes/unidades.'), task('Marque quantificadores.'), task('Identifique comparação.'), task('Ache decisão final.')],
    portugueseContrast: [task('Any em pergunta/negativa.'), task('A lot of food é muita comida.'), task('Cheaper indica mais barato.'), task('Better choice indica melhor escolha.')],
    guidedDiscovery: [task('A bag of rice mostra unidade.'), task('Do we have any milk? mostra pergunta com any.'), task('The larger box is cheaper per kilo mostra comparação.')],
    guidedBeforeQuiz: [task('Procure bottles.'), task('Procure any.'), task('Procure cheaper.'), task('Use evidência.')],
    readingPurpose: 'Entender texto com lista de compras, quantidades e escolha.',
    preReadingVocabulary: [vocab('shopping list', 'lista de compras'), vocab('per kilo', 'por quilo'), vocab('larger', 'maior'), vocab('cheaper', 'mais barato'), vocab('container', 'recipiente')],
    readingStrategy: [task('Leia como lista + justificativa.'), task('Sublinhe números e unidades.'), task('Procure comparação por preço/quantidade.'), task('Responda com evidência.')],
    mainText: `We are going to cook dinner for six people tonight. We don't have any rice or milk, but we have some vegetables. We need a bag of rice, two bottles of water, a bottle of milk and three cans of soda. At the store, the small box of cereal is cheaper, but the large box has more cereal and is the better choice for the family.`,
    firstReadTask: task('Qual é o assunto geral?', 'Lista de compras para jantar e escolha de produto.'),
    secondReadTasks: [task('Para quantas pessoas será o jantar?', 'six people'), task('O que eles não têm?', 'rice or milk'), task('O que eles já têm?', 'some vegetables'), task('Qual caixa é melhor para a família?', 'large box')],
    evidenceQuestions: [q('What are they going to cook?', 'dinner', 'cook dinner for six people tonight', '', ['dinner','breakfast','lunch for two']), q('What don’t they have?', 'rice or milk', 'We don’t have any rice or milk', '', ['rice or milk','vegetables','soda']), q('How many bottles of water do they need?', 'two', 'two bottles of water', '', ['two','three','one']), q('Which cereal box is cheaper?', 'small box', 'the small box of cereal is cheaper', '', ['small box','large box','both']), q('Which box is the better choice for the family?', 'large box', 'the large box has more cereal and is the better choice', '', ['large box','small box','neither'])],
    contextVocabularyTasks: [task('For six people mostra quantidade de pessoas.'), task('More cereal mostra mais quantidade.'), task('Better choice mostra decisão prática.')],
    guidedSummary: task('Complete: They don’t have ___ rice or milk. They need two ___ of water. The large cereal box is the better ___ for the family.', '', 'any / bottles / choice'),
    connectedProduction: task('Escreva uma lista de mercado com 5 itens e uma escolha comparada.'),
    selfAssessment: [task('Consigo localizar quantidades?'), task('Consigo entender some/any no texto?'), task('Consigo identificar escolha final?')],
    lessonRecap: ['Reading for comparisons junta quantidade e decisão.', 'Containers indicam unidades.', 'Some/any aparecem em contexto real.', 'Better choice fecha a decisão.'],
    nextLessonBridge: 'Nas próximas escutas, você vai ouvir sequência e planos com quantidades.',
  }),

  createListeningLesson({
    ...common,
    id: 'A2-LISTENING-015',
    order: 15,
    title: 'Listening for sequence markers',
    objectives: ['Ouvir marcadores de sequência em compra e preparo.', 'Identificar first, then, after that e finally.', 'Reconhecer quantidades e recipientes em fala.', 'Praticar dictation e shadowing de sequência.'],
    teacherOpening: 'Nesta escuta, você vai ouvir uma sequência de compras/preparo. O foco é entender ordem: first, then, after that, finally. Isso ajuda a seguir instruções e planos.',
    whyItMatters: 'Sequência é importante para receitas, compras, tarefas de casa, planos e relatos. Você precisa entender o que vem primeiro e depois.',
    realLifeUseCases: ['Seguir instrução de mercado.', 'Preparar refeição simples.', 'Organizar tarefa doméstica.', 'Entender plano com etapas.', 'Ouvir lista de compras.'],
    conceptExplanation: 'Ouça marcadores: first, then, after that, finally. Eles organizam ações. Combine isso com quantidades: a bag of rice, two bottles of water, some vegetables.',
    mentalModel: { title: 'sequence = first → then → after that → finally', summary: 'Marcadores mostram ordem das ações.', steps: ['first', 'then', 'after that', 'finally'] },
    stepByStep: [task('Primeira escuta: assunto geral.'), task('Segunda escuta: ordem dos passos.'), task('Terceira etapa: quantidades.'), task('Leia transcript.'), task('Faça dictation.'), task('Faça shadowing.')],
    portugueseContrast: [task('First = primeiro.'), task('Then = então/depois.'), task('After that = depois disso.'), task('Finally = finalmente/por fim.')],
    guidedDiscovery: [task('First marca passo 1.'), task('Then marca passo 2.'), task('Finally marca último passo.'), task('Quantidades aparecem junto dos itens.')],
    guidedBeforeQuiz: [task('Primeira escuta: é sobre compra ou telefone?'), task('Segunda escuta: qual é o primeiro item?')],
    listeningPreparation: [task('Não leia transcript antes da primeira escuta.'), task('Prepare: first, then, after that, finally, rice, water, vegetables.'), task('Objetivo: ordem + quantidade.')],
    keyWordsToHear: [vocab('first','primeiro'), vocab('then','então/depois'), vocab('after that','depois disso'), vocab('finally','por fim'), vocab('a bag of rice','um pacote de arroz')],
    audioScript: `First, we need to buy a bag of rice and two bottles of water. Then, we need some vegetables and a bottle of milk. After that, we are going to compare the cereal boxes. The small box is cheaper, but the large box has more cereal. Finally, we are going to choose the large box.`,
    firstListenTasks: [task('Sem transcript: qual é o assunto?', 'shopping / buying food'), task('Sem transcript: eles vão comparar cereal?', 'yes')],
    secondListenTasks: [task('O que compram primeiro?', 'a bag of rice and two bottles of water'), task('O que compram depois?', 'some vegetables and a bottle of milk'), task('O que vão comparar?', 'cereal boxes'), task('Qual caixa escolhem?', 'large box')],
    transcript: `First, we need to buy a bag of rice and two bottles of water. Then, we need some vegetables and a bottle of milk. After that, we are going to compare the cereal boxes. The small box is cheaper, but the large box has more cereal. Finally, we are going to choose the large box.`,
    vocabulary: [vocab('compare', 'comparar'), vocab('choose', 'escolher'), vocab('large box', 'caixa grande'), vocab('small box', 'caixa pequena')],
    shadowing: [task('First, we need to buy a bag of rice.'), task('Then, we need some vegetables.'), task('After that, we are going to compare the cereal boxes.'), task('Finally, we are going to choose the large box.')],
    dictationTasks: [task('Digite: First, we need to buy a bag of rice.', 'First, we need to buy a bag of rice.'), task('Digite: Then, we need some vegetables.', 'Then, we need some vegetables.'), task('Digite: Finally, we are going to choose the large box.', 'Finally, we are going to choose the large box.')],
    pronunciationChunks: [task('first we need', 'Sequência + necessidade.'), task('after that we are going to', 'Sequência + plano.'), task('large box has more', 'Comparação de quantidade.')],
    listeningComprehension: [q('Áudio da aula — Listening for sequence markers — what do they need to buy first?', 'a bag of rice and two bottles of water', 'First, we need to buy...', '', ['rice and water','milk only','cereal first']), q('What do they need after that?', 'vegetables and milk', 'Then, we need some vegetables and a bottle of milk.', '', ['vegetables and milk','jackets','phone charger']), q('What are they going to compare?', 'cereal boxes', 'compare the cereal boxes', '', ['cereal boxes','jackets','phones']), q('Which box are they going to choose?', 'large box', 'choose the large box', '', ['large box','small box','no box'])],
    oralProduction: task('Repita a sequência usando first, then, after that e finally.'),
    selfAssessment: [task('Consegui ouvir ordem?'), task('Consegui ouvir quantidades?'), task('Consigo repetir marcadores de sequência?')],
    lessonRecap: ['Sequence markers organizam ações.', 'First/then/after that/finally mostram ordem.', 'Quantities aparecem com containers.', 'Going to pode aparecer em planos da sequência.'],
    nextLessonBridge: 'Na próxima escuta, você vai ouvir planos futuros com quantidades.',
  }),

  createListeningLesson({
    ...common,
    id: 'A2-LISTENING-016',
    order: 16,
    title: 'Listening for future plans',
    objectives: ['Ouvir planos futuros com going to.', 'Identificar compras, quantidades e motivo da escolha.', 'Reconhecer some/any, many/much e containers.', 'Praticar dictation e shadowing de planos.'],
    teacherOpening: 'Nesta escuta, você vai ouvir um plano futuro envolvendo compras. O foco é ouvir going to, itens, quantidades e o motivo da escolha.',
    whyItMatters: 'Planos e quantidades aparecem juntos na vida real: vou comprar, precisamos de, não temos, vamos escolher. Essa aula integra A2.3 e A2.4.',
    realLifeUseCases: ['Planejar mercado.', 'Combinar compras para jantar.', 'Decidir quantidade.', 'Comparar opções antes de comprar.', 'Falar de plano futuro com motivo.'],
    conceptExplanation: 'Ouça be going to + verb para plano. Ouça need/have para quantidade. Ouça some/any e containers como bottle, bag, can, box.',
    mentalModel: { title: 'future plan + shopping quantity', summary: 'Plano futuro com lista e razão.', steps: ['going to buy', 'need quantity', 'compare options', 'choose because'] },
    stepByStep: [task('Primeira escuta: plano geral.'), task('Segunda escuta: itens e quantidades.'), task('Terceira etapa: motivo da escolha.'), task('Leia transcript.'), task('Faça dictation.'), task('Faça shadowing.')],
    portugueseContrast: [task('We are going to buy = nós vamos comprar.'), task('Do we have any...? pergunta disponibilidade.'), task('We need some... fala necessidade indefinida.')],
    guidedDiscovery: [task('Going to buy mostra plano.'), task('Any aparece na pergunta.'), task('Some aparece em afirmação.'), task('Because explica escolha.')],
    guidedBeforeQuiz: [task('Primeira escuta: o plano é comprar comida?'), task('Segunda escuta: quantas garrafas?')],
    listeningPreparation: [task('Não leia transcript antes da primeira escuta.'), task('Prepare: going to buy, any rice, some vegetables, two bottles, better choice.'), task('Objetivo: plano + quantidade + motivo.')],
    keyWordsToHear: [vocab('going to buy','vai comprar'), vocab('do we have any','temos algum?'), vocab('some vegetables','alguns vegetais'), vocab('two bottles','duas garrafas'), vocab('better choice','melhor escolha')],
    audioScript: `A: What are we going to buy for dinner?
B: We need some vegetables and a bag of rice.
A: Do we have any milk?
B: No, we don't have any milk. We are going to buy one bottle.
A: How many cans of soda do we need?
B: Three cans. And let's choose the large cereal box because it has more cereal.`,
    firstListenTasks: [task('Sem transcript: eles estão planejando jantar?', 'yes'), task('Sem transcript: precisam comprar leite?', 'yes')],
    secondListenTasks: [task('O que precisam para o jantar?', 'vegetables and a bag of rice'), task('Quanto leite vão comprar?', 'one bottle'), task('Quantas latas de refrigerante?', 'three cans'), task('Qual caixa de cereal vão escolher?', 'large cereal box')],
    transcript: `A: What are we going to buy for dinner?
B: We need some vegetables and a bag of rice.
A: Do we have any milk?
B: No, we don't have any milk. We are going to buy one bottle.
A: How many cans of soda do we need?
B: Three cans. And let's choose the large cereal box because it has more cereal.`,
    vocabulary: [vocab('for dinner', 'para o jantar'), vocab('one bottle', 'uma garrafa'), vocab('three cans', 'três latas'), vocab('has more', 'tem mais')],
    shadowing: [task('What are we going to buy for dinner?'), task('We need some vegetables and a bag of rice.'), task('Do we have any milk?'), task('How many cans of soda do we need?'), task('Let’s choose the large cereal box.')],
    dictationTasks: [task('Digite: We need some vegetables.', 'We need some vegetables.'), task('Digite: We don’t have any milk.', 'We don’t have any milk.'), task('Digite: How many cans of soda do we need?', 'How many cans of soda do we need?')],
    pronunciationChunks: [task('going to buy for dinner', 'Plano + finalidade.'), task('do we have any milk', 'Pergunta com any.'), task('how many cans', 'Quantidade contável.')],
    listeningComprehension: [q('What are they going to buy for dinner?', 'vegetables and rice', 'We need some vegetables and a bag of rice.', '', ['vegetables and rice','jackets','phone charger']), q('Do they have any milk?', 'no', 'No, we don’t have any milk.', '', ['no','yes','not mentioned']), q('How many cans of soda do they need?', 'three', 'Three cans.', '', ['three','two','one']), q('Why will they choose the large cereal box?', 'it has more cereal', 'because it has more cereal', '', ['has more cereal','is smaller','is blue'])],
    oralProduction: task('Responda oralmente criando seu próprio plano de compra com going to, some/any e how much/how many.'),
    selfAssessment: [task('Consegui ouvir going to?'), task('Consegui ouvir some/any?'), task('Consegui ouvir quantidades?')],
    lessonRecap: ['Future plans podem incluir compras e quantidades.', 'Some/any aparecem naturalmente em listas.', 'How many pergunta quantidade contável.', 'Because explica escolha.'],
    nextLessonBridge: 'Na próxima parte do A2.4, você vai aprofundar comparatives, superlatives e personalidade/lugares.',
  }),
]);

export const A2_DEEP_COMPARISONS_NEEDS_PART2_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART2.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART2.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART2.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART2.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART2.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_COMPARISONS_NEEDS_PART2.filter((lesson) => lesson.pillar === 'writing')),
});
