import { createGrammarLesson, createVocabularyLesson, createReadingLesson, createListeningLesson, createSpeakingLesson, createWritingLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-2', 'past-stories', 'directions-health', 'closing', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function phrase(text, translation = '', note = '') { return { text, translation, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }
function q(question, answer, evidence = '', explanation = '', options = []) { return { question, answer, evidence, explanation, options }; }
function ex(text, translation, why = '', warning = '') { return { text, translation, why, warning }; }

export const A2_DEEP_PAST_STORIES_PART5 = Object.freeze([
  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-006',
    order: 6,
    title: 'Past time expressions',
    objectives: ['Usar expressões de tempo passado com segurança.', 'Diferenciar yesterday, last, ago, in e on.', 'Organizar histórias simples com tempo claro.', 'Evitar traduções literais como ago two days.'],
    teacherOpening: 'Nesta aula, você vai organizar o tempo das histórias. Past Simple fica muito mais claro quando você usa yesterday, last night, last week, two days ago, in 2023 e on Monday. O objetivo é dizer quando aconteceu sem confundir ordem das palavras.',
    whyItMatters: 'Sem tempo claro, uma história no passado fica vaga. Expressões de tempo ajudam listening, reading, speaking e writing, principalmente em viagens, compras, restaurante, farmácia e direções.',
    realLifeUseCases: ['Dizer quando viajou.', 'Contar quando comprou algo.', 'Explicar quando ficou doente.', 'Falar de um evento antigo.', 'Organizar uma história curta.'],
    conceptExplanation: 'Use yesterday para ontem. Use last + período: last night, last week, last month. Use quantidade + ago: two days ago, three weeks ago. Use in + ano/mês: in 2023, in July. Use on + dia/data: on Monday, on July 12.',
    mentalModel: { title: 'quando aconteceu?', summary: 'Past time expressions colocam a ação no calendário.', steps: ['yesterday', 'last + time', 'number + ago', 'in + month/year', 'on + day/date'] },
    stepByStep: [task('Escolha o tipo de tempo.'), task('Use last antes de períodos.'), task('Use ago depois da quantidade.'), task('Use in para mês/ano.'), task('Use on para dia/data.'), task('Coloque a expressão no começo ou fim da frase.')],
    portugueseContrast: [task('Two days ago = dois dias atrás; não ago two days.'), task('Last night = ontem à noite; não yesterday night.'), task('In July = em julho.'), task('On Monday = na segunda-feira.')],
    guidedDiscovery: [task('Yesterday indica ontem.'), task('Last week indica semana passada.'), task('Three days ago conta para trás.'), task('On Friday indica dia específico.')],
    guidedBeforeQuiz: [task('Corrija: ago two days.', 'two days ago'), task('Corrija: yesterday night.', 'last night'), task('Complete: ___ Monday', 'on'), task('Complete: ___ 2023', 'in')],
    grammarGoal: 'Localizar ações passadas no tempo com clareza.',
    formationGuide: [task('Yesterday + sentence', 'Yesterday, I bought a jacket.'), task('Last + period', 'I went to the hotel last week.'), task('Number + ago', 'She called me two days ago.'), task('In + month/year', 'I traveled in July.'), task('On + day/date', 'We met on Monday.')],
    whenToUse: [task('Para histórias no passado.'), task('Para perguntas e respostas sobre quando.'), task('Para organizar sequência de eventos.')],
    whenNotToUse: [task('Não use ago antes da quantidade.'), task('Não use last com datas completas.'), task('Não use in com dias da semana.'), task('Não misture today com Past Simple sem contexto.')],
    grammarTable: [
      { pattern: 'yesterday', example: 'I stayed home yesterday.', translation: 'Fiquei em casa ontem.' },
      { pattern: 'last + period', example: 'We traveled last month.', translation: 'Nós viajamos mês passado.' },
      { pattern: 'number + ago', example: 'She bought it two days ago.', translation: 'Ela comprou isso dois dias atrás.' },
      { pattern: 'in + month/year', example: 'I visited Curitiba in July.', translation: 'Visitei Curitiba em julho.' },
      { pattern: 'on + day/date', example: 'They arrived on Monday.', translation: 'Eles chegaram na segunda.' }
    ],
    teacherExamples: [
      { english: 'I went to the pharmacy yesterday.', translation: 'Fui à farmácia ontem.', why: 'Yesterday localiza o passado recente.' },
      { english: 'She bought the jacket two days ago.', translation: 'Ela comprou a jaqueta dois dias atrás.', why: 'Ago vem depois da quantidade.' },
      { english: 'We stayed at a hotel last weekend.', translation: 'Ficamos em um hotel fim de semana passado.', why: 'Last + weekend.' },
      { english: 'He traveled in 2023.', translation: 'Ele viajou em 2023.', why: 'In + ano.' }
    ],
    commonBrazilianMistakes: [mistake('ago two days', 'two days ago', 'Ago vem depois da quantidade.'), mistake('yesterday night', 'last night', 'O natural é last night.'), mistake('in Monday', 'on Monday', 'Dias usam on.'), mistake('on 2023', 'in 2023', 'Anos usam in.')],
    controlledPractice: [task('Complete: I bought it two days ___.', 'ago'), task('Complete: She called me ___ Monday.', 'on'), task('Complete: We traveled ___ July.', 'in'), task('Complete: I studied ___ night.', 'last')],
    errorCorrectionPractice: [task('Corrija: I went ago two days.', 'I went two days ago.'), task('Corrija: We met in Friday.', 'We met on Friday.'), task('Corrija: She traveled on 2022.', 'She traveled in 2022.')],
    transformationPractice: [task('Adicione ontem: I bought medicine.', 'I bought medicine yesterday.'), task('Adicione semana passada: We visited the city.', 'We visited the city last week.'), task('Adicione dois dias atrás: She called the hotel.', 'She called the hotel two days ago.')],
    translationPractice: [task('Eu fui à farmácia ontem.', 'I went to the pharmacy yesterday.'), task('Ela comprou isso dois dias atrás.', 'She bought it two days ago.'), task('Nós viajamos em julho.', 'We traveled in July.')],
    productionTasks: [task('Escreva 10 frases no passado usando yesterday/last/ago/in/on.'), task('Conte uma história com 4 expressões de tempo.'), task('Crie 5 perguntas com When did...?')],
    finalChecklist: [task('Usei a preposição certa?'), task('Ago veio depois da quantidade?'), task('Usei last night em vez de yesterday night?'), task('A frase está no Past Simple?')],
    selfAssessment: [task('Consigo dizer quando algo aconteceu?'), task('Consigo usar ago corretamente?'), task('Consigo diferenciar in/on/last?')],
    lessonRecap: ['Past time expressions organizam histórias.', 'Ago vem depois da quantidade.', 'Last night é o padrão para ontem à noite.', 'In é para mês/ano e on para dia/data.'],
    nextLessonBridge: 'Na próxima gramática, você vai descrever o que existia em lugares e situações com there was/there were.',
  }),

  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-007',
    order: 7,
    title: 'There was / there were',
    objectives: ['Usar there was e there were para falar do passado.', 'Descrever lugares, eventos e problemas passados.', 'Diferenciar singular e plural.', 'Criar frases sobre hotel, restaurante, loja e cidade.'],
    teacherOpening: 'There was e there were são usados para dizer que algo existia/acontecia em um lugar no passado. There was a problem. There were many people. Isso ajuda a descrever hotéis, restaurantes, lojas, ruas e eventos.',
    whyItMatters: 'No A2, você precisa descrever experiências: havia fila, havia desconto, havia farmácia perto, havia muitas pessoas. Essa estrutura deixa seus relatos mais ricos.',
    realLifeUseCases: ['Descrever hotel.', 'Falar de loja cheia.', 'Explicar problema em restaurante.', 'Dizer que havia uma farmácia perto.', 'Contar como estava uma cidade.'],
    conceptExplanation: 'Use there was para singular ou incontável: There was a problem. There was traffic. Use there were para plural: There were two pharmacies. There were many people.',
    mentalModel: { title: 'was singular / were plural', summary: 'Escolha pelo que vem depois.', steps: ['There was a problem.', 'There was traffic.', 'There were two stores.', 'There were many people.'] },
    stepByStep: [task('Veja o substantivo depois da estrutura.'), task('Se for singular/incontável, use there was.'), task('Se for plural, use there were.'), task('Adicione lugar/tempo.'), task('Use para descrever a cena passada.')],
    portugueseContrast: [task('Em português usamos “tinha/havia”; em inglês use there was/were.'), task('Não diga had many people para havia muitas pessoas.'), task('Use there were many people.'), task('Use there was traffic para havia trânsito.')],
    guidedDiscovery: [task('A problem é singular → there was.'), task('Two stores é plural → there were.'), task('Traffic é incontável → there was.')],
    guidedBeforeQuiz: [task('Complete: There ___ a problem.', 'was'), task('Complete: There ___ many people.', 'were'), task('Corrija: There was two stores.', 'There were two stores.')],
    grammarGoal: 'Descrever existência/situação passada com there was/were.',
    formationGuide: [task('There was + singular', 'There was a pharmacy near the hotel.'), task('There was + uncountable', 'There was traffic.'), task('There were + plural', 'There were two restaurants.'), task('Negative', 'There wasn’t a discount.'), task('Question', 'Was there a problem?')],
    whenToUse: [task('Descrever lugares no passado.'), task('Dizer que havia ou não havia algo.'), task('Falar de problemas, pessoas, serviços e objetos.')],
    whenNotToUse: [task('Não use para posse pessoal.'), task('Não use was com plural.'), task('Não use were com singular.'), task('Não traduza “tinha” sempre como had.')],
    grammarTable: [
      { pattern: 'There was + singular', example: 'There was a pharmacy near the hotel.', translation: 'Havia uma farmácia perto do hotel.' },
      { pattern: 'There was + uncountable', example: 'There was a lot of traffic.', translation: 'Havia muito trânsito.' },
      { pattern: 'There were + plural', example: 'There were many people in the store.', translation: 'Havia muitas pessoas na loja.' },
      { pattern: 'Was there...?', example: 'Was there a discount?', translation: 'Havia desconto?' }
    ],
    teacherExamples: [
      { english: 'There was a problem with my room.', translation: 'Havia um problema com meu quarto.', why: 'A problem é singular.' },
      { english: 'There were two restaurants near the hotel.', translation: 'Havia dois restaurantes perto do hotel.', why: 'Two restaurants é plural.' },
      { english: 'There wasn’t a pharmacy on this street.', translation: 'Não havia farmácia nesta rua.', why: 'Negativa singular.' },
      { english: 'There were many people at the station.', translation: 'Havia muitas pessoas na estação.', why: 'Many people é plural.' }
    ],
    commonBrazilianMistakes: [mistake('Had many people.', 'There were many people.', 'Para “havia”, use there were.'), mistake('There was two stores.', 'There were two stores.', 'Plural usa were.'), mistake('There were a problem.', 'There was a problem.', 'Singular usa was.'), mistake('Was a pharmacy near here.', 'There was a pharmacy near here.', 'Precisa de there.')],
    controlledPractice: [task('Complete: There ___ a restaurant.', 'was'), task('Complete: There ___ two stores.', 'were'), task('Complete: There ___ traffic.', 'was'), task('Complete: ___ there a pharmacy?', 'Was')],
    errorCorrectionPractice: [task('Corrija: There was many people.', 'There were many people.'), task('Corrija: Had a problem in the hotel.', 'There was a problem in the hotel.'), task('Corrija: There were a discount.', 'There was a discount.')],
    transformationPractice: [task('Transforme: A pharmacy existed near the hotel.', 'There was a pharmacy near the hotel.'), task('Transforme: Two restaurants existed near the station.', 'There were two restaurants near the station.'), task('Transforme em pergunta: There was a problem.', 'Was there a problem?')],
    translationPractice: [task('Havia uma farmácia perto.', 'There was a pharmacy nearby.'), task('Havia muitas pessoas na loja.', 'There were many people in the store.'), task('Havia desconto?', 'Was there a discount?')],
    productionTasks: [task('Descreva um hotel usando there was/were.'), task('Descreva uma loja usando there was/were.'), task('Escreva 5 perguntas com Was there/Were there?')],
    finalChecklist: [task('Olhei singular/plural?'), task('Usei there?'), task('Usei was para singular/incontável?'), task('Usei were para plural?')],
    selfAssessment: [task('Consigo usar there was/were?'), task('Consigo descrever lugares passados?'), task('Consigo evitar had many people?')],
    lessonRecap: ['There was/were descreve existência no passado.', 'Was é singular/incontável.', 'Were é plural.', 'Essa estrutura melhora relatos de viagem, cidade e problemas.'],
    nextLessonBridge: 'Agora você vai fechar o vocabulário de saúde e direções do A2.2.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-007',
    order: 7,
    title: 'Health and pharmacy',
    objectives: ['Aprender vocabulário de sintomas e farmácia.', 'Explicar problema de saúde simples.', 'Entender instruções básicas de remédio.', 'Pedir ajuda em farmácia com segurança A2.'],
    teacherOpening: 'Health and pharmacy fecha a parte de saúde do A2.2. Você vai aprender headache, fever, cough, sore throat, stomachache, medicine, pill, pharmacy, doctor, rest, water, worse e better. O foco é comunicação simples e cuidadosa.',
    whyItMatters: 'Saúde exige clareza. Mesmo no A2, você precisa explicar sintomas básicos e entender instruções simples, sem inventar informação complexa.',
    realLifeUseCases: ['Explicar dor de cabeça.', 'Comprar remédio básico.', 'Perguntar como tomar.', 'Dizer que está pior/melhor.', 'Procurar médico se necessário.'],
    conceptExplanation: 'Use I have + symptom: I have a headache. I have a cough. Use I feel + adjective: I feel tired. Para instruções, reconheça take medicine, drink water, rest, see a doctor.',
    mentalModel: { title: 'sintoma + pedido + instrução', summary: 'Diga o problema e entenda o que fazer.', steps: ['I have...', 'Can I have something for...?', 'Take this medicine...', 'See a doctor.'] },
    stepByStep: [task('Nomeie o sintoma.'), task('Use I have ou I feel.'), task('Pergunte por algo para o sintoma.'), task('Entenda quando tomar.'), task('Observe alerta de médico.')],
    portugueseContrast: [task('I have a headache = estou com dor de cabeça.'), task('I am with headache não é natural.'), task('Medicine é remédio.'), task('Pill é comprimido.')],
    guidedDiscovery: [task('Headache é sintoma.'), task('Pharmacy é lugar.'), task('Take medicine é instrução.'), task('Worse/better mostram evolução.')],
    guidedBeforeQuiz: [task('I have a headache.'), task('I have a sore throat.'), task('Can I have something for a cough?'), task('Take this medicine after lunch.')],
    topicContext: 'Você vai explicar sintomas simples e entender orientações de farmácia.',
    essentialWords: [vocab('headache', 'dor de cabeça', 'I have a headache.'), vocab('fever', 'febre', 'I have a fever.'), vocab('cough', 'tosse', 'I have a cough.'), vocab('sore throat', 'dor de garganta', 'I have a sore throat.'), vocab('stomachache', 'dor de estômago', 'I have a stomachache.'), vocab('medicine', 'remédio', 'Take this medicine.'), vocab('pill', 'comprimido', 'Take one pill.'), vocab('pharmacy', 'farmácia', 'I went to the pharmacy.'), vocab('doctor', 'médico', 'See a doctor.'), vocab('rest', 'descansar', 'You should rest.'), vocab('water', 'água', 'Drink water.'), vocab('worse', 'pior', 'I feel worse.'), vocab('better', 'melhor', 'I feel better.'), vocab('pain', 'dor', 'I have pain here.'), vocab('after lunch', 'depois do almoço', 'Take it after lunch.'), vocab('before bed', 'antes de dormir', 'Take it before bed.')],
    chunks: [{ chunk: 'I have a headache', translation: 'Estou com dor de cabeça', example: 'I have a headache.' }, { chunk: 'something for a cough', translation: 'algo para tosse', example: 'Can I have something for a cough?' }, { chunk: 'take one pill', translation: 'tomar um comprimido', example: 'Take one pill after lunch.' }, { chunk: 'see a doctor', translation: 'procurar um médico', example: 'See a doctor if you feel worse.' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Headache soa como HED-eik.', 'Cough não soa como “coug”; pratique devagar.', 'Sore throat tem th em throat.'] },
    dangerousConfusions: [task('Medicine é remédio; medication também existe, mas medicine é suficiente no A2.'), task('Pain é dor geral; headache/stomachache são dores específicas.'), task('Recipe não é receita médica; prescription é prescrição, mas fica para níveis posteriores.')],
    collocations: [task('have a headache'), task('have a fever'), task('take medicine'), task('drink water'), task('feel worse'), task('feel better'), task('see a doctor')],
    miniDialogues: [{ title: 'At the pharmacy', lines: ['A: How can I help you?', 'B: I have a cough.', 'A: Do you have a fever?', 'B: No, I don’t.', 'A: Take this medicine after lunch.'], focus: 'Sintoma e instrução.' }],
    examples: [ex('I didn’t go to work because I had a fever.', 'Não fui ao trabalho porque estava com febre.', 'Passado + saúde.'), ex('Can I have something for a headache?', 'Pode me dar algo para dor de cabeça?', 'Pedido em farmácia.'), ex('If you feel worse, see a doctor.', 'Se você se sentir pior, procure um médico.', 'Alerta simples.')],
    recognitionPractice: [task('Qual palavra é lugar?', 'pharmacy'), task('Qual palavra é sintoma?', 'headache/cough/fever'), task('Qual palavra é evolução?', 'worse/better')],
    usagePractice: [task('Complete: I have a ___.', 'headache/cough/fever'), task('Complete: Take this medicine ___ lunch.', 'after'), task('Complete: If you feel worse, see a ___.', 'doctor')],
    productionTasks: [task('Escreva 5 frases com sintomas.'), task('Crie 3 pedidos de farmácia.'), task('Crie um mini diálogo pharmacist/customer.')],
    spacedReview: [task('Revise headache/cough/fever/sore throat amanhã.'), task('Crie 3 frases com feel worse/better.')],
    selfAssessment: [task('Consigo explicar sintoma simples?'), task('Consigo pedir algo na farmácia?'), task('Consigo entender instruções básicas?')],
    lessonRecap: ['Health vocabulary precisa ser claro.', 'Use I have + symptom.', 'Take medicine e see a doctor são chunks essenciais.', 'Worse/better mostram evolução.'],
    nextLessonBridge: 'Agora você vai aprender direções e serviços da cidade para fechar o A2.2.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-008',
    order: 8,
    title: 'Directions and city services',
    objectives: ['Aprender vocabulário de direções e serviços da cidade.', 'Perguntar e dar direções simples.', 'Localizar farmácia, banco, mercado, hotel e estação.', 'Usar turn left/right, go straight e across from.'],
    teacherOpening: 'Directions and city services fecha o vocabulário prático do A2.2. Você vai aprender como perguntar onde fica um lugar e como entender respostas simples: Go straight, turn left, it is next to the bank, across from the pharmacy.',
    whyItMatters: 'Direções são essenciais em viagem, cidade, farmácia, hotel e transporte. Com poucas frases, você consegue se localizar e ajudar alguém.',
    realLifeUseCases: ['Perguntar onde fica a farmácia.', 'Entender caminho até estação.', 'Dar direção para hotel.', 'Localizar banco, mercado e restaurante.', 'Pedir ajuda na rua.'],
    conceptExplanation: 'Use Where is...? para perguntar. Para responder: go straight, turn left/right, walk two blocks, it is next to..., it is across from..., it is between... and....',
    mentalModel: { title: 'direção = ação + referência', summary: 'Diga para onde ir e use pontos de referência.', steps: ['go straight', 'turn left/right', 'next to', 'across from', 'between'] },
    stepByStep: [task('Pergunte Where is... ?'), task('Comece com go straight.'), task('Adicione turn left/right.'), task('Use referência: next to/across from.'), task('Confirme com thank you.')],
    portugueseContrast: [task('Go straight = siga em frente.'), task('Turn left/right = vire à esquerda/direita.'), task('Next to = ao lado de.'), task('Across from = em frente do outro lado.')],
    guidedDiscovery: [task('Pharmacy é serviço da cidade.'), task('Go straight é ação.'), task('Next to é localização.'), task('Block é quarteirão.')],
    guidedBeforeQuiz: [task('Where is the pharmacy?'), task('Go straight for two blocks.'), task('Turn left at the bank.'), task('It is next to the hotel.')],
    topicContext: 'Você vai perguntar e dar direções simples na cidade.',
    essentialWords: [vocab('pharmacy', 'farmácia', 'The pharmacy is near the hotel.'), vocab('bank', 'banco', 'Turn left at the bank.'), vocab('supermarket', 'supermercado', 'The supermarket is next to the pharmacy.'), vocab('station', 'estação', 'The station is two blocks away.'), vocab('hotel', 'hotel', 'The hotel is across from the bank.'), vocab('restaurant', 'restaurante', 'The restaurant is on this street.'), vocab('street', 'rua', 'Go down this street.'), vocab('block', 'quarteirão', 'Walk two blocks.'), vocab('corner', 'esquina', 'Turn right at the corner.'), vocab('traffic light', 'semáforo', 'Turn left at the traffic light.'), vocab('go straight', 'siga em frente', 'Go straight for two blocks.'), vocab('turn left', 'vire à esquerda', 'Turn left at the bank.'), vocab('turn right', 'vire à direita', 'Turn right at the corner.'), vocab('next to', 'ao lado de', 'It is next to the hotel.'), vocab('across from', 'em frente/do outro lado', 'It is across from the bank.'), vocab('between', 'entre', 'It is between the bank and the pharmacy.')],
    chunks: [{ chunk: 'Where is the pharmacy?', translation: 'Onde fica a farmácia?', example: 'Where is the pharmacy?' }, { chunk: 'go straight for two blocks', translation: 'siga em frente por dois quarteirões', example: 'Go straight for two blocks.' }, { chunk: 'turn left at the bank', translation: 'vire à esquerda no banco', example: 'Turn left at the bank.' }, { chunk: 'next to the hotel', translation: 'ao lado do hotel', example: 'It is next to the hotel.' }, { chunk: 'across from the station', translation: 'em frente à estação', example: 'It is across from the station.' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Straight tem som /str/.', 'Pharmacy começa com som de F.', 'Across from conecta as palavras.'] },
    dangerousConfusions: [task('Next to não é perto; é ao lado.'), task('Near é perto, menos específico.'), task('Across from é do outro lado/em frente.'), task('Corner é esquina; block é quarteirão.')],
    collocations: [task('turn left'), task('turn right'), task('go straight'), task('walk two blocks'), task('next to the bank'), task('across from the hotel'), task('at the corner')],
    miniDialogues: [{ title: 'Asking for directions', lines: ['A: Excuse me. Where is the pharmacy?', 'B: Go straight for two blocks and turn left.', 'A: Is it near the bank?', 'B: Yes. It is next to the bank.'], focus: 'Perguntar e entender direção.' }],
    examples: [ex('The pharmacy is next to the hotel.', 'A farmácia fica ao lado do hotel.', 'Localização simples.'), ex('Go straight and turn right at the traffic light.', 'Siga em frente e vire à direita no semáforo.', 'Direção em sequência.'), ex('There was a bank across from the station.', 'Havia um banco em frente à estação.', 'There was + directions.')],
    recognitionPractice: [task('Qual expressão significa siga em frente?', 'go straight'), task('Qual expressão significa ao lado de?', 'next to'), task('Qual palavra é quarteirão?', 'block')],
    usagePractice: [task('Complete: Turn ___ at the corner.', 'left/right'), task('Complete: It is next ___ the hotel.', 'to'), task('Complete: Go straight for two ___.', 'blocks')],
    productionTasks: [task('Escreva 5 perguntas com Where is...?'), task('Escreva 5 direções simples.'), task('Crie um mini diálogo pedindo caminho para a farmácia.')],
    spacedReview: [task('Revise next to/across from/between amanhã.'), task('Crie 3 direções usando go straight e turn left/right.')],
    selfAssessment: [task('Consigo pedir direções?'), task('Consigo dar direção simples?'), task('Consigo usar pontos de referência?')],
    lessonRecap: ['Direções combinam ação e referência.', 'Where is...? pergunta lugar.', 'Go straight/turn left/right orientam caminho.', 'Next to/across from/between localizam serviços.'],
    nextLessonBridge: 'Na Reading e Listening, você vai aplicar direções em textos e diálogos da cidade.',
  }),

  createReadingLesson({
    ...common,
    id: 'A2-READING-007',
    order: 7,
    title: 'A city directions text',
    objectives: ['Ler um texto simples de direções na cidade.', 'Identificar caminho, serviços e pontos de referência.', 'Reconhecer there was/were em contexto.', 'Responder com evidência textual.'],
    teacherOpening: 'Nesta leitura, você vai ler direções na cidade. O objetivo é seguir o caminho mentalmente: sair do hotel, seguir em frente, virar, localizar farmácia, banco e estação.',
    whyItMatters: 'Direções unem vocabulário prático, preposições e compreensão de sequência. É uma habilidade real de viagem e cidade.',
    realLifeUseCases: ['Ler instruções para chegar à farmácia.', 'Entender caminho para estação.', 'Localizar serviços perto do hotel.', 'Seguir orientação escrita.'],
    conceptExplanation: 'Textos de direção têm sequência: start point, actions, landmarks e destination. Procure go straight, turn left, next to, across from, between e blocks.',
    mentalModel: { title: 'direção escrita = ponto inicial + passos + destino', summary: 'Leia como mapa, não como história comum.', steps: ['start', 'go straight', 'turn', 'landmark', 'destination'] },
    stepByStep: [task('Ache o ponto inicial.'), task('Marque cada ação.'), task('Marque pontos de referência.'), task('Identifique o destino final.'), task('Responda com evidência.')],
    portugueseContrast: [task('Go past = passar por.'), task('On your left/right = à sua esquerda/direita.'), task('Across from = em frente do outro lado.')],
    guidedDiscovery: [task('Start at the hotel indica início.'), task('Turn right at the bank indica ação + referência.'), task('The pharmacy is next to the supermarket indica destino.')],
    guidedBeforeQuiz: [task('Procure start point.'), task('Procure turn left/right.'), task('Procure final place.'), task('Use evidência.')],
    readingPurpose: 'Entender direções escritas simples.',
    preReadingVocabulary: [vocab('start', 'começar'), vocab('go straight', 'seguir em frente'), vocab('turn right', 'virar à direita'), vocab('block', 'quarteirão'), vocab('next to', 'ao lado de'), vocab('across from', 'em frente')],
    readingStrategy: [task('Transforme texto em passos.'), task('Não traduza tudo; siga as ações.'), task('Marque landmarks.'), task('Confirme destino final.')],
    mainText: `Start at the hotel. Go straight for two blocks and turn right at the bank. Walk past the restaurant. There was a pharmacy next to the supermarket, but now it is across from the station. The station is on your left. The pharmacy is small, but easy to find.`,
    firstReadTask: task('Qual é o objetivo do texto?', 'Dar direções para encontrar a farmácia.'),
    secondReadTasks: [task('Onde começa?', 'at the hotel'), task('Onde vira à direita?', 'at the bank'), task('Por onde passa?', 'past the restaurant'), task('Onde fica a farmácia agora?', 'across from the station')],
    evidenceQuestions: [q('Where do you start?', 'at the hotel', 'Start at the hotel.', '', ['at the hotel','at the station','at the bank']), q('How many blocks do you go straight?', 'two blocks', 'Go straight for two blocks', '', ['two','three','one']), q('Where do you turn right?', 'at the bank', 'turn right at the bank', '', ['at the bank','at the restaurant','at the pharmacy']), q('Where is the pharmacy now?', 'across from the station', 'now it is across from the station', '', ['across from the station','next to the hotel','between two banks']), q('What is on your left?', 'the station', 'The station is on your left.', '', ['the station','the supermarket','the hotel'])],
    contextVocabularyTasks: [task('Walk past significa passar por.'), task('Now contrasta com there was no passado.'), task('Easy to find significa fácil de encontrar.')],
    guidedSummary: task('Complete: Start at the ___. Go straight for ___ blocks, turn right at the ___ and find the pharmacy across from the ___.', '', 'hotel / two / bank / station'),
    connectedProduction: task('Escreva 4 passos para chegar da sua casa a uma farmácia ou mercado.'),
    selfAssessment: [task('Consigo seguir direções escritas?'), task('Consigo identificar landmarks?'), task('Consigo responder com evidência?')],
    lessonRecap: ['Direções escritas são sequência de passos.', 'Start point e destination são essenciais.', 'Landmarks ajudam localização.', 'There was/were pode comparar passado e presente.'],
    nextLessonBridge: 'No Listening, você vai ouvir alguém pedindo direções.',
  }),

  createListeningLesson({
    ...common,
    id: 'A2-LISTENING-007',
    order: 7,
    title: 'Asking for directions',
    objectives: ['Ouvir diálogo pedindo direções.', 'Identificar destino, passos e pontos de referência.', 'Reconhecer go straight, turn left/right e next to.', 'Praticar dictation e shadowing de direções.'],
    teacherOpening: 'Nesta escuta, você vai ouvir uma pessoa perguntando onde fica a farmácia. Primeiro entenda o destino. Depois, siga os passos: go straight, turn left, next to the bank.',
    whyItMatters: 'Pedir direções é uma situação comum em viagem. Você precisa entender respostas rápidas e confirmar se está perto ou longe.',
    realLifeUseCases: ['Perguntar caminho na rua.', 'Entender rota até farmácia.', 'Localizar hotel ou estação.', 'Confirmar se é perto.'],
    conceptExplanation: 'Ouça por blocos de movimento e referência: go straight, turn left, at the traffic light, next to the bank, across from the station. Repita em shadowing para automatizar.',
    mentalModel: { title: 'listen for path steps', summary: 'Destino primeiro, passos depois.', steps: ['destination', 'go straight', 'turn', 'landmark', 'final location'] },
    stepByStep: [task('Primeira escuta: destino.'), task('Segunda escuta: passos.'), task('Terceira etapa: referência final.'), task('Leia transcript.'), task('Faça dictation.'), task('Faça shadowing.')],
    portugueseContrast: [task('Excuse me abre pedido educado.'), task('Is it far? pergunta se é longe.'), task('It is on your right = fica à sua direita.')],
    guidedDiscovery: [task('Where is the pharmacy? mostra destino.'), task('Turn left at the traffic light mostra ação e referência.'), task('On your right mostra posição final.')],
    guidedBeforeQuiz: [task('Primeira escuta: para onde a pessoa quer ir?'), task('Segunda escuta: ela vira à esquerda ou direita?')],
    listeningPreparation: [task('Não leia transcript antes da primeira escuta.'), task('Prepare: pharmacy, straight, left, traffic light, bank, right.'), task('Objetivo: destino + passos.')],
    keyWordsToHear: [vocab('excuse me','com licença'), vocab('pharmacy','farmácia'), vocab('go straight','siga em frente'), vocab('turn left','vire à esquerda'), vocab('traffic light','semáforo'), vocab('on your right','à sua direita')],
    audioScript: `A: Excuse me. Where is the pharmacy?
B: Go straight for two blocks and turn left at the traffic light.
A: Is it far?
B: No, it isn't. Walk past the bank. The pharmacy is on your right, next to the supermarket.
A: Thank you!
B: You're welcome.`,
    firstListenTasks: [task('Sem transcript: qual é o destino?', 'pharmacy'), task('Sem transcript: é longe?', 'no')],
    secondListenTasks: [task('Quantos quarteirões?', 'two blocks'), task('Onde vira à esquerda?', 'at the traffic light'), task('Por onde passa?', 'past the bank'), task('Onde fica a farmácia?', 'on your right, next to the supermarket')],
    transcript: `A: Excuse me. Where is the pharmacy?
B: Go straight for two blocks and turn left at the traffic light.
A: Is it far?
B: No, it isn't. Walk past the bank. The pharmacy is on your right, next to the supermarket.
A: Thank you!
B: You're welcome.`,
    vocabulary: [vocab('is it far?', 'é longe?'), vocab('walk past', 'passar por'), vocab('you’re welcome', 'de nada'), vocab('on your right', 'à sua direita')],
    shadowing: [task('Excuse me. Where is the pharmacy?'), task('Go straight for two blocks.'), task('Turn left at the traffic light.'), task('Is it far?'), task('The pharmacy is on your right.')],
    dictationTasks: [task('Digite: Where is the pharmacy?', 'Where is the pharmacy?'), task('Digite: Go straight for two blocks.', 'Go straight for two blocks.'), task('Digite: The pharmacy is on your right.', 'The pharmacy is on your right.')],
    pronunciationChunks: [task('Excuse me', 'Abertura educada.'), task('go straight for', 'Conecte o bloco.'), task('turn left at', 'Ação + referência.')],
    listeningComprehension: [q('Where does the person want to go?', 'the pharmacy', 'Where is the pharmacy?', '', ['the pharmacy','the hotel','the station']), q('How many blocks should the person go straight?', 'two blocks', 'Go straight for two blocks.', '', ['two','one','three']), q('Where should the person turn left?', 'at the traffic light', 'turn left at the traffic light', '', ['at the traffic light','at the bank','at the supermarket']), q('Where is the pharmacy?', 'on your right, next to the supermarket', 'The pharmacy is on your right, next to the supermarket.', '', ['on your right next to the supermarket','across from the hotel','behind the bank'])],
    oralProduction: task('Pratique pedir e dar direções para pharmacy, bank e station.'),
    selfAssessment: [task('Consegui ouvir destino?'), task('Consegui seguir passos?'), task('Consigo repetir direções?')],
    lessonRecap: ['Listening de direções exige ouvir passos.', 'Go straight e turn left/right são centrais.', 'Landmarks confirmam destino.', 'Shadowing ajuda a responder na rua.'],
    nextLessonBridge: 'Agora você vai falar sobre saúde e direções para fechar o A2.2.',
  }),

  createSpeakingLesson({
    ...common,
    id: 'A2-SPEAKING-007',
    order: 7,
    title: 'Explain a simple health problem',
    objectives: ['Explicar sintoma simples em inglês.', 'Responder perguntas básicas de farmácia.', 'Pedir algo para dor/tosse/febre.', 'Gravar diálogo curto na farmácia.'],
    teacherOpening: 'Nesta fala, você vai explicar um problema de saúde simples. Use I have a headache, I have a cough, I feel tired, Can I have something for...? O objetivo é ser claro e cuidadoso.',
    whyItMatters: 'Saúde é uma área em que clareza importa. No A2, você não vai explicar diagnóstico; vai comunicar sintomas básicos e entender orientação simples.',
    realLifeUseCases: ['Pedir remédio na farmácia.', 'Dizer que está com dor de cabeça.', 'Responder se tem febre.', 'Perguntar preço e instrução.', 'Dizer se melhorou/piorou.'],
    conceptExplanation: 'Use I have + symptom para sintomas. Use I feel + adjective para estado. Para pedir ajuda: Can I have something for a headache? Para responder: No, I don’t have a fever.',
    mentalModel: { title: 'symptom + request + instruction', summary: 'Diga o sintoma e peça ajuda.', steps: ['I have...', 'Do you have fever?', 'Can I have something for...?', 'Take it after lunch.'] },
    stepByStep: [task('Diga o sintoma.'), task('Diga se tem febre ou não.'), task('Peça algo para o sintoma.'), task('Pergunte como tomar.'), task('Pergunte preço se necessário.'), task('Agradeça.')],
    portugueseContrast: [task('Não diga I am with headache.'), task('Use I have a headache.'), task('Use something for + sintoma.'), task('Use How should I take it? para instrução.')],
    guidedDiscovery: [task('I have a cough é sintoma.'), task('Can I have something for...? é pedido.'), task('How should I take it? pergunta instrução.')],
    guidedBeforeQuiz: [task('Repita: I have a headache.'), task('Repita: I have a cough.'), task('Repita: Can I have something for a sore throat?'), task('Repita: How should I take it?')],
    speakingSituation: 'Você está na farmácia e precisa explicar um sintoma simples.',
    modelPhrases: [phrase('I have a headache.', 'Estou com dor de cabeça.'), phrase('I have a cough.', 'Estou com tosse.'), phrase('I don’t have a fever.', 'Não estou com febre.'), phrase('Can I have something for a sore throat?', 'Pode me dar algo para dor de garganta?'), phrase('How should I take it?', 'Como devo tomar?')],
    pronunciationChunks: [task('I have a', 'Bloco para sintomas.'), task('something for a', 'Pedido em bloco.'), task('How should I take it', 'Pergunta útil.')],
    repeatAfterMe: [task('I have a headache.'), task('I have a sore throat.'), task('Do you have a fever?'), task('No, I don’t.'), task('Can I have something for a cough?'), task('How should I take it?')],
    substitutionDrills: [task('headache → stomachache', 'I have a stomachache.'), task('cough → sore throat', 'Can I have something for a sore throat?'), task('after lunch → before bed', 'Take it before bed.')],
    guidedSpeaking: [task('Explique um sintoma.'), task('Responda se tem febre.'), task('Peça algo para o sintoma.'), task('Pergunte como tomar.'), task('Pergunte preço.')],
    recordingTasks: [task('Grave 5 sintomas simples.'), task('Grave diálogo na farmácia de 8 linhas.'), task('Grave versão final com sintoma, pedido e instrução.')],
    freeSpeaking: task('Simule uma conversa na farmácia por até 60 segundos.'),
    feedbackChecklist: [task('Usei I have + symptom?'), task('Pedi ajuda com Can I have something for...?'), task('Perguntei instrução?'), task('Usei please/thank you?'), task('Fui claro?')],
    selfAssessment: [task('Consigo explicar sintoma?'), task('Consigo pedir ajuda na farmácia?'), task('Consigo perguntar como tomar?')],
    lessonRecap: ['Health speaking precisa ser simples e claro.', 'I have + symptom é estrutura central.', 'Something for... ajuda a pedir remédio.', 'Não invente detalhes médicos complexos no A2.'],
    nextLessonBridge: 'Na próxima fala, você vai pedir e dar direções na cidade.',
  }),

  createSpeakingLesson({
    ...common,
    id: 'A2-SPEAKING-008',
    order: 8,
    title: 'Ask and give directions',
    objectives: ['Pedir direções de forma educada.', 'Dar direções simples com passos e referências.', 'Usar Where is, go straight, turn left/right e next to.', 'Gravar diálogo curto de direções.'],
    teacherOpening: 'Agora você vai praticar pedir e dar direções. Use Excuse me, where is the pharmacy? Go straight for two blocks. Turn left at the bank. It is next to the supermarket.',
    whyItMatters: 'Direções fecham o A2.2 porque juntam cidade, serviços, perguntas, preposições e fala funcional real.',
    realLifeUseCases: ['Pedir caminho para farmácia.', 'Ajudar alguém a achar estação.', 'Localizar hotel ou mercado.', 'Confirmar se é longe.', 'Dar passos simples.'],
    conceptExplanation: 'Comece educado: Excuse me. Pergunte: Where is...? Responda com ações: go straight, turn left/right. Termine com referência: next to, across from, on your right/left.',
    mentalModel: { title: 'ask politely + give steps', summary: 'Direção boa tem passos curtos e referência final.', steps: ['Excuse me', 'Where is...?', 'Go straight', 'Turn...', 'It is next to...'] },
    stepByStep: [task('Abra com Excuse me.'), task('Pergunte Where is...?'), task('Dê 2 ou 3 passos.'), task('Use landmark.'), task('Confirme se é perto/longe.'), task('Agradeça.')],
    portugueseContrast: [task('Where is...? é suficiente para onde fica.'), task('On your right/left depende da direção da pessoa.'), task('Near é perto; next to é ao lado.')],
    guidedDiscovery: [task('Excuse me torna educado.'), task('Go straight dá ação.'), task('At the traffic light dá referência.'), task('Next to the bank dá localização final.')],
    guidedBeforeQuiz: [task('Repita: Excuse me. Where is the pharmacy?'), task('Repita: Go straight for two blocks.'), task('Repita: Turn left at the bank.'), task('Repita: It is on your right.')],
    speakingSituation: 'Você está na rua e precisa pedir ou dar uma direção simples.',
    modelPhrases: [phrase('Excuse me. Where is the pharmacy?', 'Com licença. Onde fica a farmácia?'), phrase('Go straight for two blocks.', 'Siga em frente por dois quarteirões.'), phrase('Turn left at the traffic light.', 'Vire à esquerda no semáforo.'), phrase('It is next to the bank.', 'Fica ao lado do banco.'), phrase('Is it far?', 'É longe?')],
    pronunciationChunks: [task('Excuse me where is', 'Abertura conectada.'), task('go straight for', 'Bloco de direção.'), task('turn left at', 'Ação + referência.')],
    repeatAfterMe: [task('Excuse me. Where is the station?'), task('Go straight for one block.'), task('Turn right at the corner.'), task('It is across from the hotel.'), task('You’re welcome.')],
    substitutionDrills: [task('pharmacy → station', 'Where is the station?'), task('turn left → turn right', 'Turn right at the bank.'), task('next to → across from', 'It is across from the supermarket.')],
    guidedSpeaking: [task('Peça caminho para farmácia.'), task('Dê caminho para estação.'), task('Use go straight e turn right.'), task('Use next to ou across from.'), task('Feche com thank you/you’re welcome.')],
    recordingTasks: [task('Grave 5 frases de direções.'), task('Grave diálogo de 8 linhas pedindo caminho.'), task('Grave versão final com 3 passos e referência final.')],
    freeSpeaking: task('Simule uma conversa de direções por até 60 segundos.'),
    feedbackChecklist: [task('Usei Excuse me?'), task('Perguntei Where is...?'), task('Dei passos claros?'), task('Usei landmarks?'), task('Usei thank you/you’re welcome?')],
    selfAssessment: [task('Consigo pedir direções?'), task('Consigo dar 2–3 passos?'), task('Consigo usar next to/across from?')],
    lessonRecap: ['Direções A2 usam perguntas curtas.', 'Go straight/turn left/right são centrais.', 'Landmarks ajudam clareza.', 'Educação importa na rua.'],
    nextLessonBridge: 'Na escrita, você vai fechar o A2.2 escrevendo sobre saúde e direções.',
  }),

  createWritingLesson({
    ...common,
    id: 'A2-WRITING-007',
    order: 7,
    title: 'Write about a health problem',
    objectives: ['Escrever mensagem curta sobre problema de saúde.', 'Explicar sintoma, tempo e pedido de ajuda.', 'Usar should/can e vocabulário de farmácia.', 'Revisar clareza e tom cuidadoso.'],
    teacherOpening: 'Nesta escrita, você vai escrever uma mensagem simples sobre saúde. O foco é comunicar sintoma e pedir orientação básica: I have a headache and a cough. Can I take this medicine after lunch?',
    whyItMatters: 'Mensagens de saúde precisam ser claras. No A2, você deve escrever sintomas básicos, tempo e pedido sem exagerar no detalhe médico.',
    realLifeUseCases: ['Mandar mensagem para farmácia/hotel/família.', 'Explicar que não foi a uma aula por estar doente.', 'Pedir orientação simples.', 'Registrar sintomas básicos.'],
    conceptExplanation: 'Use 4 partes: greeting, symptom, time/context, request. Exemplo: Hello, I have a headache and a cough. I felt worse last night. Can I take this medicine after lunch? Thank you.',
    mentalModel: { title: 'health message = symptom + context + request', summary: 'Explique o problema e peça orientação.', steps: ['Hello', 'I have...', 'Since/last night', 'Can I...?', 'Thank you'] },
    stepByStep: [task('Comece com Hello.'), task('Diga o sintoma.'), task('Diga quando começou ou contexto.'), task('Faça pergunta/pedido.'), task('Agradeça.'), task('Revise pontuação.')],
    portugueseContrast: [task('Não use I am with headache.'), task('Use I have a headache.'), task('Use felt worse para passado.'), task('Use Can I take...? para perguntar sobre remédio.')],
    guidedDiscovery: [task('I have a headache comunica sintoma.'), task('Last night dá tempo.'), task('Can I take...? faz pergunta de orientação.')],
    guidedBeforeQuiz: [task('Modelo: Hello, I have a headache.'), task('Modelo: I felt worse last night.'), task('Modelo: Can I take this medicine after lunch?'), task('Modelo: Thank you.')],
    writingPurpose: 'Escrever mensagem curta sobre sintoma e pedido de orientação.',
    modelText: `Hello, I have a headache and a cough. I felt worse last night, but I don't have a fever. Can I take this medicine after lunch? Should I see a doctor if I feel worse tomorrow? Thank you.`,
    writingBlocks: [task('Greeting', 'Hello,'), task('Symptoms', 'I have a headache and a cough.'), task('Time/context', 'I felt worse last night.'), task('Medicine question', 'Can I take this medicine after lunch?'), task('Warning question', 'Should I see a doctor if I feel worse tomorrow?'), task('Closing', 'Thank you.')],
    guidedSubstitution: [task('Troque headache por sore throat.'), task('Troque cough por stomachache.'), task('Troque after lunch por before bed.'), task('Troque feel worse por feel better.')],
    grammarForWriting: [task('Use I have + symptom.'), task('Use Past Simple para felt.'), task('Use Can I...? para pergunta.'), task('Use if para condição/alerta.'), task('Use ? em perguntas.')],
    checklist: [task('Expliquei sintoma?'), task('Incluí tempo/contexto?'), task('Fiz pergunta clara?'), task('Usei pontuação correta?'), task('Mantive tom cuidadoso?')],
    draftTask: task('Escreva uma mensagem de 4 a 6 frases explicando um problema simples de saúde.'),
    revisionTask: task('Revise sintoma, tempo, pedido e pontuação.'),
    commonMistakes: [mistake('I am with cough.', 'I have a cough.', 'Sintoma usa I have.'), mistake('I feel worse yesterday.', 'I felt worse yesterday.', 'Passado de feel é felt.'), mistake('Can I take this medicine.', 'Can I take this medicine?', 'Pergunta precisa de ?')],
    productionTasks: [task('Escreva mensagem para dor de cabeça.'), task('Escreva mensagem para tosse.'), task('Reescreva com if e should.')],
    selfAssessment: [task('Consigo escrever sintoma simples?'), task('Consigo pedir orientação?'), task('Consigo revisar tom e pontuação?')],
    lessonRecap: ['Health writing precisa de clareza.', 'I have + symptom é estrutura central.', 'Can I/Should I ajudam pedidos.', 'Evite detalhes médicos complexos no A2.'],
    nextLessonBridge: 'Na última escrita do A2.2, você vai escrever direções simples.',
  }),

  createWritingLesson({
    ...common,
    id: 'A2-WRITING-008',
    order: 8,
    title: 'Write directions',
    objectives: ['Escrever direções simples em inglês.', 'Usar sequência de passos e pontos de referência.', 'Incluir origem, destino e orientação final.', 'Revisar clareza, ordem e preposições.'],
    teacherOpening: 'Esta aula fecha o A2.2. Você vai escrever direções simples: Start at the hotel. Go straight for two blocks. Turn left at the bank. The pharmacy is next to the supermarket.',
    whyItMatters: 'Escrever direções mostra que você consegue organizar sequência, cidade, serviços e preposições de lugar. É uma habilidade prática e um bom fechamento do pacote.',
    realLifeUseCases: ['Mandar caminho para alguém.', 'Explicar onde fica farmácia/mercado.', 'Escrever orientação para hotel ou estação.', 'Criar instruções simples de cidade.'],
    conceptExplanation: 'Direções escritas precisam ser claras e em passos curtos. Use imperativos: Start, go, turn, walk. Use referências: at the bank, next to the supermarket, across from the station.',
    mentalModel: { title: 'directions = start + steps + destination', summary: 'Escreva como se fossem instruções de mapa.', steps: ['Start at...', 'Go straight...', 'Turn...', 'It is next to...'] },
    stepByStep: [task('Diga onde começa.'), task('Escreva o primeiro passo.'), task('Adicione virada ou referência.'), task('Diga onde fica o destino.'), task('Revise ordem e preposições.'), task('Leia como mapa.')],
    portugueseContrast: [task('Use imperativos simples: Go, Turn, Walk.'), task('Não escreva frases longas demais.'), task('Use at para ponto de referência: at the bank.'), task('Use next to/across from para localização final.')],
    guidedDiscovery: [task('Start at the hotel indica origem.'), task('Go straight for two blocks é passo.'), task('Turn left at the bank é passo + referência.'), task('It is next to the supermarket é destino.')],
    guidedBeforeQuiz: [task('Modelo: Start at the hotel.'), task('Modelo: Go straight for two blocks.'), task('Modelo: Turn right at the corner.'), task('Modelo: It is across from the station.')],
    writingPurpose: 'Escrever direções simples e úteis.',
    modelText: `Start at the hotel. Go straight for two blocks and turn left at the bank. Walk past the restaurant. The pharmacy is on your right, next to the supermarket. It is small, but easy to find.`,
    writingBlocks: [task('Start', 'Start at the hotel.'), task('First step', 'Go straight for two blocks.'), task('Turn', 'Turn left at the bank.'), task('Landmark', 'Walk past the restaurant.'), task('Final place', 'The pharmacy is on your right, next to the supermarket.'), task('Extra detail', 'It is easy to find.')],
    guidedSubstitution: [task('Troque hotel por station.'), task('Troque pharmacy por bank.'), task('Troque left por right.'), task('Troque next to por across from.')],
    grammarForWriting: [task('Use imperativos sem sujeito: Go/Turn/Walk.'), task('Use for + distância: for two blocks.'), task('Use at + landmark.'), task('Use next to/across from para localização.'), task('Use ponto final em cada passo.')],
    checklist: [task('Incluí ponto inicial?'), task('Incluí 2 ou 3 passos?'), task('Usei landmark?'), task('Digo onde fica o destino?'), task('Frases estão curtas?')],
    draftTask: task('Escreva direções para uma farmácia, mercado, estação ou banco.'),
    revisionTask: task('Revise ordem, preposições, landmarks e pontuação.'),
    commonMistakes: [mistake('Go straight two blocks.', 'Go straight for two blocks.', 'Use for com distância.'), mistake('Turn left in the bank.', 'Turn left at the bank.', 'Use at para ponto de referência.'), mistake('It is side the hotel.', 'It is next to the hotel.', 'Use next to.')],
    productionTasks: [task('Escreva direções para a farmácia.'), task('Escreva direções para a estação.'), task('Reescreva usando across from e next to.')],
    selfAssessment: [task('Consigo escrever direções simples?'), task('Consigo usar imperativos?'), task('Consigo revisar preposições?')],
    lessonRecap: ['Direções escritas fecham o A2.2.', 'Use start + steps + destination.', 'Imperativos deixam instruções claras.', 'Landmarks ajudam o leitor.'],
    nextLessonBridge: 'A2.2 está fechado. O próximo pacote correto é A2.3 Plans, routines and comparisons.',
  }),
]);

export const A2_DEEP_PAST_STORIES_PART5_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_PAST_STORIES_PART5.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_PAST_STORIES_PART5.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_PAST_STORIES_PART5.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_PAST_STORIES_PART5.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_PAST_STORIES_PART5.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_PAST_STORIES_PART5.filter((lesson) => lesson.pillar === 'writing')),
});
