import { createSpeakingLesson, createWritingLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-6', 'reviews-checkpoints', 'speaking', 'writing', 'checkpoint', 'a2-closing', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function phrase(text, translation = '', note = '') { return { text, translation, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }

export const A2_DEEP_REVIEWS_CHECKPOINTS_PART3 = Object.freeze([
  createSpeakingLesson({
    ...common,
    id: 'A2-SPEAKING-017',
    order: 17,
    title: 'Speak for 60 seconds about your week',
    checkpoint: 'speaking-review',
    objectives: ['Falar por 60 segundos sobre a semana.', 'Integrar passado, presente, planos, obrigações, conselhos e opinião.', 'Usar conectores simples para organizar fala.', 'Preparar o Speaking Checkpoint A2.'],
    teacherOpening: 'Esta é a revisão oral final antes do checkpoint. Você vai falar por 60 segundos sobre sua semana usando estruturas A2: what you did, what you are doing, what you are going to do, what you have to do and how you feel.',
    whyItMatters: 'No A2, você precisa sustentar uma fala curta, simples e organizada sobre sua vida. Não precisa ser perfeito; precisa ser claro, funcional e compreensível.',
    realLifeUseCases: ['Falar sobre a semana para professor ou colega.', 'Responder perguntas em entrevista simples.', 'Explicar rotina, planos e obrigações.', 'Falar de sentimentos e conselhos.', 'Preparar transição para B1.'],
    conceptExplanation: 'Organize sua fala em blocos: passado, agora, planos, obrigações, sentimentos e fechamento. Use frases curtas e conectores como and, but, because e so.',
    mentalModel: { title: '60-second A2 speaking frame', summary: 'Past + now + plan + obligation + feeling + closing.', steps: ['Last week...', 'Now...', 'This week I’m going to...', 'I have to...', 'I feel...', 'So...'] },
    stepByStep: [task('Comece com uma frase geral sobre sua semana.'), task('Diga 2 coisas que fez no passado.'), task('Diga o que está fazendo agora.'), task('Diga 2 planos com going to.'), task('Diga 1 obrigação com have to.'), task('Diga como se sente e dê motivo.'), task('Feche com uma frase simples.')],
    portugueseContrast: [task('Fale simples; não tente frases gigantes.'), task('Use did/past para passado e be + ing para agora.'), task('Use going to para plano.'), task('Use because para justificar sentimento ou escolha.')],
    guidedDiscovery: [task('Last weekend, I worked and watched a movie.'), task('Now, I’m studying English.'), task('This week, I’m going to visit my family.'), task('I have to wake up early tomorrow.'), task('I feel tired, but I’m happy.')],
    guidedBeforeQuiz: [task('Repita: Last weekend, I stayed home.'), task('Repita: Now I’m studying English.'), task('Repita: I’m going to work tomorrow.'), task('Repita: I have to wake up early.'), task('Repita: I feel tired, but I’m okay.')],
    speakingSituation: 'Você vai gravar uma fala de 60 segundos sobre sua semana.',
    modelPhrases: [phrase('Last weekend, I worked and stayed home.', 'No fim de semana passado, trabalhei e fiquei em casa.'), phrase('Now I’m studying English.', 'Agora estou estudando inglês.'), phrase('This week, I’m going to organize my schedule.', 'Esta semana, vou organizar minha agenda.'), phrase('I have to wake up early tomorrow.', 'Tenho que acordar cedo amanhã.'), phrase('I feel tired, but I’m motivated.', 'Eu me sinto cansado, mas estou motivado.')],
    pronunciationChunks: [task('last weekend I worked', 'Passado em bloco.'), task('now I’m studying', 'Agora em bloco.'), task('I’m going to organize', 'Plano em bloco.'), task('I have to wake up early', 'Obrigação em bloco.')],
    repeatAfterMe: [task('Last weekend, I worked a lot.'), task('I didn’t go out because I was tired.'), task('Now, I’m studying English.'), task('This week, I’m going to rest more.'), task('I have to finish some important things.')],
    substitutionDrills: [task('worked → studied', 'Last weekend, I studied a lot.'), task('rest more → save money', 'This week, I’m going to save money.'), task('wake up early → call my manager', 'I have to call my manager tomorrow.'), task('tired → worried', 'I feel worried, but I’m okay.')],
    guidedSpeaking: [task('Fale 15 segundos só sobre o passado.'), task('Fale 15 segundos sobre agora e rotina.'), task('Fale 15 segundos sobre planos.'), task('Fale 15 segundos sobre obrigações e sentimentos.')],
    recordingTasks: [task('Grave uma primeira versão de 30 segundos.'), task('Grave uma versão de 60 segundos usando pelo menos 6 estruturas A2.'), task('Ouça e marque erros de verbo.'), task('Regrave corrigindo pausas e conectores.')],
    freeSpeaking: task('Fale por 60 segundos sobre sua semana usando: Past Simple, Present Continuous, going to, have to, should, because, but e and.'),
    feedbackChecklist: [task('Falei por pelo menos 45–60 segundos?'), task('Usei passado corretamente?'), task('Usei now + be + ing?'), task('Usei going to?'), task('Usei have to?'), task('Usei conectores?'), task('Minha fala ficou compreensível?')],
    selfAssessment: [task('Consigo sustentar fala A2 curta?'), task('Consigo organizar ideias em sequência?'), task('Consigo corrigir meus erros principais?')],
    lessonRecap: ['Speaking A2 precisa de clareza e organização.', 'Fale por blocos, não por tradução palavra por palavra.', 'Use estruturas A2 de forma funcional.', 'Regravar faz parte do treino.'],
    nextLessonBridge: 'Agora você vai fazer o Speaking Checkpoint A2.',
  }),

  createSpeakingLesson({
    ...common,
    id: 'A2-SPEAKING-018',
    order: 18,
    title: 'Speaking Checkpoint A2',
    checkpoint: 'speaking-checkpoint',
    objectives: ['Avaliar fala A2 final.', 'Responder prompts funcionais com clareza.', 'Usar passado, presente, plano, obrigação, conselho e pedido.', 'Confirmar prontidão oral para avançar depois do A2.'],
    teacherOpening: 'Este checkpoint confirma se você consegue falar em nível A2 de forma funcional. O objetivo não é soar nativo; é conseguir se comunicar, responder, pedir, explicar e organizar ideias simples.',
    whyItMatters: 'Speaking é o ponto onde você transforma conhecimento em comunicação. Antes do B1, você precisa falar sobre si, sua rotina, planos, problemas e pedidos simples.',
    realLifeUseCases: ['Apresentação pessoal simples.', 'Responder pergunta sobre rotina e semana.', 'Pedir ajuda ou informação.', 'Explicar obrigação e plano.', 'Dar conselho simples.'],
    conceptExplanation: 'Você vai responder a prompts. Cada resposta deve ser curta, clara e completa. Use frases simples, conectores e pelo menos uma estrutura alvo por resposta.',
    mentalModel: { title: 'A2 speaking checkpoint', summary: 'Answer clearly, add detail, connect ideas.', steps: ['answer', 'detail', 'reason', 'next idea', 'close'] },
    stepByStep: [task('Leia/escute o prompt.'), task('Responda diretamente.'), task('Adicione um detalhe.'), task('Use because, but, so ou and.'), task('Mantenha frase curta.'), task('Corrija e regrave se travar.')],
    portugueseContrast: [task('Evite montar frase longa em português e traduzir.'), task('Comece simples e adicione detalhe.'), task('Pausas são aceitáveis; frases incompletas demais precisam revisão.')],
    guidedDiscovery: [task('Prompt: What did you do yesterday? → I worked and studied English.'), task('Prompt: What are you doing now? → I’m practicing speaking.'), task('Prompt: What are you going to do tomorrow? → I’m going to work and rest.'), task('Prompt: Could you ask for help? → Could you help me with this, please?')],
    guidedBeforeQuiz: [task('Responda em 2 frases, não só 1 palavra.'), task('Inclua ao menos um motivo com because em 2 respostas.'), task('Use uma pergunta com could you.')],
    speakingSituation: 'Checkpoint oral A2 com prompts funcionais.',
    modelPhrases: [phrase('Yesterday, I worked and studied English because I had time.', 'Ontem trabalhei e estudei inglês porque tive tempo.'), phrase('Now, I’m practicing speaking, and I’m trying to speak clearly.', 'Agora estou praticando fala e tentando falar claramente.'), phrase('Tomorrow, I’m going to organize my day.', 'Amanhã vou organizar meu dia.'), phrase('Could you repeat that, please?', 'Você poderia repetir, por favor?'), phrase('I think you should rest because you look tired.', 'Acho que você deveria descansar porque parece cansado.')],
    pronunciationChunks: [task('worked and studied', 'Sequência no passado.'), task('trying to speak clearly', 'Fala com advérbio.'), task('could you repeat that please', 'Pedido educado.'), task('I think you should rest', 'Conselho em bloco.')],
    repeatAfterMe: [task('Yesterday, I worked and studied English.'), task('Now, I’m practicing speaking.'), task('Tomorrow, I’m going to organize my day.'), task('I have to wake up early.'), task('Could you repeat that, please?')],
    substitutionDrills: [task('worked and studied → cooked and cleaned', 'Yesterday, I cooked and cleaned.'), task('organize my day → visit my family', 'Tomorrow, I’m going to visit my family.'), task('wake up early → finish a report', 'I have to finish a report.'), task('repeat that → speak slowly', 'Could you speak slowly, please?')],
    guidedSpeaking: [task('Prompt 1: What did you do yesterday?'), task('Prompt 2: What are you doing now?'), task('Prompt 3: What are you going to do this week?'), task('Prompt 4: What do you have to do tomorrow?'), task('Prompt 5: Ask for help politely.'), task('Prompt 6: Give advice to a tired friend.')],
    recordingTasks: [task('Grave cada prompt separadamente.'), task('Depois grave todos em sequência.'), task('Marque erros de tempo verbal.'), task('Regrave a versão final com pausas menores.')],
    freeSpeaking: task('Grave uma resposta final de 90 segundos: apresentação curta, semana passada, agora, planos, obrigações, conselho e pedido educado.'),
    feedbackChecklist: [task('Respondi todos os prompts?'), task('Usei pelo menos 6 estruturas A2?'), task('Minha pronúncia ficou compreensível?'), task('Evitei should to/could to/did went?'), task('Usei conectores?')],
    selfAssessment: [task('Consigo falar sobre passado?'), task('Consigo falar sobre agora?'), task('Consigo falar sobre planos?'), task('Consigo pedir ajuda e dar conselho?')],
    lessonRecap: ['Speaking Checkpoint confirma comunicação oral A2.', 'Clareza é mais importante que perfeição.', 'Use respostas curtas com detalhes.', 'A próxima etapa fecha Writing A2.'],
    nextLessonBridge: 'Agora você vai revisar Writing A2.',
  }),

  createWritingLesson({
    ...common,
    id: 'A2-WRITING-017',
    order: 17,
    title: 'Writing Review A2',
    checkpoint: 'writing-review',
    objectives: ['Revisar escrita funcional A2.', 'Escrever mensagens, convites, respostas, conselhos e instruções simples.', 'Organizar texto com começo, detalhes e fechamento.', 'Usar conectores e revisar erros centrais.'],
    teacherOpening: 'Writing Review A2 junta os formatos que você precisa dominar: mensagem curta, convite e resposta, relato passado, plano futuro, conselho e instrução com obrigação.',
    whyItMatters: 'No A2, você deve conseguir escrever mensagens úteis para vida real: combinar algo, explicar problema, pedir ajuda, dar instruções e contar algo simples.',
    realLifeUseCases: ['Escrever convite e resposta.', 'Mandar mensagem explicando atraso.', 'Escrever conselho para amigo.', 'Dar instruções de trabalho.', 'Contar o que aconteceu ontem.'],
    conceptExplanation: 'Um bom texto A2 é curto, claro e organizado. Use frases simples, conectores básicos e revise verbos centrais: did, be + ing, going to, should, have to e can/could.',
    mentalModel: { title: 'A2 writing frame', summary: 'Context + details + action + closing.', steps: ['Hi...', 'context', 'details', 'reason/action', 'closing'] },
    stepByStep: [task('Defina o tipo de texto.'), task('Escreva uma frase de contexto.'), task('Adicione 2–4 detalhes.'), task('Inclua motivo ou contraste.'), task('Feche com ação clara.'), task('Revise gramática alvo.')],
    portugueseContrast: [task('Não traduza texto longo do português.'), task('Use frases curtas em inglês.'), task('Revise preposições de tempo: on Monday, at 8, in the morning.'), task('Revise object pronouns: to me, with her, for us.')],
    guidedDiscovery: [task('Invitation: Would you like to...?'), task('Advice: I think you should...'), task('Obligation: You have to... / You don’t have to...'), task('Past story: Yesterday, I went...'), task('Plan: I’m going to...')],
    guidedBeforeQuiz: [task('Modelo convite: Would you like to have lunch on Sunday?'), task('Modelo resposta: That sounds good, but I have to work.'), task('Modelo conselho: You should rest because you look tired.'), task('Modelo instrução: You have to arrive at 8.')],
    writingPurpose: 'Revisar escrita funcional A2 antes do checkpoint final.',
    modelText: `Hi Marcos, I’m sorry I can’t meet you today because I have to finish a report. I worked late yesterday, and now I’m feeling tired. Can we meet on Sunday afternoon? There is a new café near the station. It is cheaper than the restaurant we visited last week, and the service is good. Let me know if Sunday works for you.`,
    writingBlocks: [task('Greeting', 'Hi Marcos,'), task('Reason/problem', 'I can’t meet you today because...'), task('Past detail', 'I worked late yesterday.'), task('New plan', 'Can we meet on Sunday afternoon?'), task('Comparison/opinion', 'It is cheaper... and the service is good.'), task('Closing', 'Let me know if Sunday works for you.')],
    guidedSubstitution: [task('Troque report por appointment.'), task('Troque Sunday afternoon por Saturday morning.'), task('Troque café por restaurant.'), task('Troque cheaper por more comfortable.')],
    grammarForWriting: [task('Past Simple para relato passado.'), task('Present Continuous para estado agora.'), task('Going to para plano.'), task('Should para conselho.'), task('Have to para obrigação.'), task('Can/Could para pedido.'), task('Because/so/but/and para conexão.')],
    checklist: [task('O texto tem contexto?'), task('Tem detalhes suficientes?'), task('Tem conectores?'), task('Tem ação ou pedido final?'), task('Revisei verbos e pronomes?')],
    draftTask: task('Escreva uma mensagem de 7 a 9 frases explicando que você não pode ir hoje, dando motivo, sugerindo outro dia e comparando duas opções.'),
    revisionTask: task('Revise: did + base verb, be + ing, going to, should/could + base verb, have to, object pronouns e conectores.'),
    commonMistakes: [mistake('I can’t meet you because I worked late and now I tired.', 'I can’t meet you because I worked late, and now I’m tired.', 'Tired precisa de be.'), mistake('Can we to meet Sunday?', 'Can we meet on Sunday?', 'Can + base verb; dia usa on.'), mistake('I didn’t went.', 'I didn’t go.', 'Didn’t + base verb.'), mistake('This restaurant is more cheap.', 'This restaurant is cheaper.', 'Cheap usa -er.')],
    productionTasks: [task('Escreva um convite e uma resposta.'), task('Escreva um conselho para alguém cansado.'), task('Escreva instruções para uma reunião.'), task('Escreva um relato curto sobre ontem.'), task('Escreva uma mensagem com plano futuro.')],
    selfAssessment: [task('Consigo escrever mensagem funcional?'), task('Consigo organizar começo, detalhes e fechamento?'), task('Consigo revisar meus erros centrais?')],
    lessonRecap: ['Writing A2 é funcional e organizado.', 'Frases curtas vencem frases longas confusas.', 'Conectores dão lógica.', 'Revisão final prepara o checkpoint.'],
    nextLessonBridge: 'Agora você vai fazer o Writing Checkpoint A2.',
  }),

  createWritingLesson({
    ...common,
    id: 'A2-WRITING-018',
    order: 18,
    title: 'Writing Checkpoint A2',
    checkpoint: 'writing-checkpoint',
    objectives: ['Avaliar escrita A2 final.', 'Produzir texto funcional completo.', 'Usar múltiplas estruturas A2 com clareza.', 'Confirmar fechamento do A2 antes do próximo nível.'],
    teacherOpening: 'Este é o checkpoint final de Writing A2. Você vai escrever uma mensagem funcional completa. O objetivo é mostrar que consegue explicar situação, dar detalhes, justificar, sugerir e fechar com clareza.',
    whyItMatters: 'Escrita A2 mostra se você consegue usar inglês para resolver situações reais: cancelar, reagendar, pedir ajuda, dar instruções e explicar motivos.',
    realLifeUseCases: ['Reagendar compromisso.', 'Explicar atraso.', 'Pedir ajuda ou informação.', 'Comparar opções.', 'Dar conselho ou instrução simples.'],
    conceptExplanation: 'Seu texto final deve ter: saudação, contexto, detalhe passado, situação atual, plano futuro, obrigação/conselho, pedido ou fechamento. Use conectores básicos.',
    mentalModel: { title: 'final A2 writing checkpoint', summary: 'Context + past + now + plan + reason + request + closing.', steps: ['Hi...', 'I’m sorry...', 'Yesterday...', 'Now...', 'I’m going to...', 'Could you...?', 'Thanks...'] },
    stepByStep: [task('Leia o prompt.'), task('Planeje 5 blocos.'), task('Escreva frases curtas.'), task('Inclua pelo menos 5 estruturas A2.'), task('Revise erros centrais.'), task('Faça versão final limpa.')],
    portugueseContrast: [task('Não escreva como redação longa em português.'), task('Use mensagem clara e prática.'), task('Evite excesso de conectores.'), task('Priorize precisão em estruturas A2.')],
    guidedDiscovery: [task('Past: I worked late yesterday.'), task('Now: I’m feeling tired now.'), task('Plan: I’m going to rest tonight.'), task('Obligation: I have to wake up early.'), task('Request: Could you send me the address?')],
    guidedBeforeQuiz: [task('Planeje antes: contexto, motivo, plano, pedido, fechamento.'), task('Revise antes de enviar: did, be, going to, should, have to, could.')],
    writingPurpose: 'Checkpoint final de escrita A2.',
    modelText: `Hi Ana, I’m sorry, but I can’t go to the meeting today because I have to work late. Yesterday, I finished a big report, and now I’m very tired. I’m going to rest tonight, but I can meet you on Sunday afternoon. There is a café near the station. It is quieter than the restaurant, and the coffee is cheaper. Could you send me the time again, please? Thanks, and see you soon.`,
    writingBlocks: [task('Greeting + apology', 'Hi Ana, I’m sorry, but...'), task('Reason/obligation', 'because I have to work late.'), task('Past detail', 'Yesterday, I finished a big report.'), task('Current feeling', 'Now I’m very tired.'), task('Future plan', 'I’m going to rest tonight.'), task('Comparison', 'It is quieter than the restaurant.'), task('Request', 'Could you send me the time again?'), task('Closing', 'Thanks, and see you soon.')],
    guidedSubstitution: [task('Troque meeting por appointment.'), task('Troque work late por study for a test.'), task('Troque Sunday afternoon por Monday morning.'), task('Troque café por library.'), task('Troque quieter por more comfortable.')],
    grammarForWriting: [task('Use Past Simple para yesterday/last week.'), task('Use Present Continuous para now.'), task('Use going to para plano.'), task('Use have to para obrigação.'), task('Use could para pedido educado.'), task('Use comparative para comparar.'), task('Use because/but/and para lógica.')],
    checklist: [task('Incluí saudação?'), task('Expliquei o problema?'), task('Usei motivo com because?'), task('Incluí detalhe passado?'), task('Incluí situação atual?'), task('Incluí plano futuro?'), task('Incluí pedido ou fechamento?'), task('Revisei erros centrais?')],
    draftTask: task('Checkpoint: escreva uma mensagem de 8 a 10 frases reagendando um compromisso. Inclua motivo, detalhe passado, situação atual, plano futuro, comparação entre duas opções e um pedido educado.'),
    revisionTask: task('Revise com foco em: did/didn’t + base verb, be + ing, going to, have to, could + base verb, comparatives, object pronouns, because/so/but/and.'),
    commonMistakes: [mistake('I can’t go because I have work late.', 'I can’t go because I have to work late.', 'Obrigação usa have to.'), mistake('Yesterday I finish.', 'Yesterday I finished.', 'Past Simple precisa de passado.'), mistake('I going to rest.', 'I’m going to rest.', 'Going to precisa de be.'), mistake('Could you to send me?', 'Could you send me?', 'Could + base verb.'), mistake('More cheaper', 'Cheaper', 'Não use more com adjetivo curto em -er.')],
    productionTasks: [task('Escreva a versão final do checkpoint.'), task('Sublinhe todas as estruturas A2 usadas.'), task('Corrija 5 possíveis erros.'), task('Reescreva a mensagem de forma mais clara.')],
    selfAssessment: [task('Consigo escrever uma mensagem funcional A2 sem modelo?'), task('Consigo usar pelo menos 5 estruturas A2?'), task('Consigo revisar erros principais?'), task('Consigo explicar uma situação real por escrito?')],
    lessonRecap: ['Writing Checkpoint fecha a produção escrita A2.', 'Mensagem funcional precisa de contexto, motivo, plano e fechamento.', 'Use estruturas A2 com precisão suficiente.', 'A2 está completo em conteúdo profundo premium nesta fase.'],
    nextLessonBridge: 'A2 completo. O próximo passo correto será iniciar B1 ou executar a revisão premium restante do A1 conforme a prioridade definida.',
  }),
]);

export const A2_DEEP_REVIEWS_CHECKPOINTS_PART3_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_REVIEWS_CHECKPOINTS_PART3.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_REVIEWS_CHECKPOINTS_PART3.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_REVIEWS_CHECKPOINTS_PART3.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_REVIEWS_CHECKPOINTS_PART3.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_REVIEWS_CHECKPOINTS_PART3.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_REVIEWS_CHECKPOINTS_PART3.filter((lesson) => lesson.pillar === 'writing')),
});
