import { createGrammarLesson, createReadingLesson, createSpeakingLesson, createWritingLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-5', 'communication-tasks', 'obligations', 'have-to', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function phrase(text, translation = '', note = '') { return { text, translation, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }
function q(question, answer, evidence = '', explanation = '', options = []) { return { question, answer, evidence, explanation, options }; }

export const A2_DEEP_COMMUNICATION_TASKS_PART3 = Object.freeze([
  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-020',
    order: 20,
    title: 'Have to / don’t have to',
    objectives: ['Usar have to para obrigação prática.', 'Usar don’t have to para ausência de obrigação.', 'Formar perguntas com Do I have to...? / Does she have to...?', 'Diferenciar conselho com should e obrigação com have to.'],
    teacherOpening: 'Have to fala de obrigação real: I have to work. She has to study. Don’t have to não significa proibição; significa que não é necessário: You don’t have to come early.',
    whyItMatters: 'Você usa have to para regras, trabalho, escola, rotina, compromissos, prazos, viagens e responsabilidades.',
    realLifeUseCases: ['Falar de obrigação no trabalho.', 'Explicar regras simples.', 'Perguntar se algo é necessário.', 'Dizer que não precisa fazer algo.', 'Comparar conselho e obrigação.'],
    conceptExplanation: 'Use subject + have to + base verb. Com he/she/it, use has to. Na negativa, don’t/doesn’t have to. Na pergunta, Do/Does + subject + have to + verb? Exemplo: Do you have to work tomorrow?',
    mentalModel: { title: 'have to = obrigação externa/prática', summary: 'Use have to quando algo é necessário por regra, trabalho, compromisso ou situação.', steps: ['I have to work.', 'She has to study.', 'You don’t have to pay now.', 'Do we have to leave?'] },
    stepByStep: [task('Identifique se é obrigação ou conselho.'), task('Obrigação: have to.'), task('He/she/it: has to.'), task('Negativa: don’t/doesn’t have to.'), task('Pergunta: Do/Does + subject + have to?')],
    portugueseContrast: [task('Don’t have to = não precisa, não é “não deve”.'), task('Should = conselho; have to = obrigação.'), task('She has to, não she have to.'), task('Does she have to, não does she has to.')],
    guidedDiscovery: [task('I have to work tomorrow = obrigação.'), task('You should rest = conselho.'), task('You don’t have to come = não precisa vir.'), task('Do I have to pay now? = preciso pagar agora?')],
    guidedBeforeQuiz: [task('Complete: I ___ to work today.', 'have'), task('Complete: She ___ to study tonight.', 'has'), task('Complete: You ___ have to come early.', 'don’t'), task('Corrija: Does she has to go?', 'Does she have to go?')],
    grammarGoal: 'Falar de obrigações e ausência de obrigação em situações cotidianas.',
    formationGuide: [task('Affirmative', 'I have to work tomorrow.'), task('He/she/it', 'She has to study tonight.'), task('Negative', 'You don’t have to bring food.'), task('Question', 'Do we have to arrive early?'), task('He/she question', 'Does he have to call the manager?')],
    whenToUse: [task('Obrigação de trabalho/escola.'), task('Regra simples.'), task('Necessidade por compromisso.'), task('Perguntar se algo é obrigatório.')],
    whenNotToUse: [task('Não use don’t have to para proibição; isso é mustn’t/can’t, fora do foco aqui.'), task('Não use has depois de does.'), task('Não confunda should com have to.')],
    grammarTable: [
      { pattern: 'I/you/we/they have to + verb', example: 'We have to leave at six.', translation: 'Temos que sair às seis.' },
      { pattern: 'he/she/it has to + verb', example: 'She has to work on Saturday.', translation: 'Ela tem que trabalhar no sábado.' },
      { pattern: 'don’t have to + verb', example: 'You don’t have to pay today.', translation: 'Você não precisa pagar hoje.' },
      { pattern: 'Do/Does + subject + have to?', example: 'Does he have to wear a uniform?', translation: 'Ele precisa usar uniforme?' }
    ],
    teacherExamples: [
      { english: 'I have to finish this report today.', translation: 'Tenho que terminar este relatório hoje.', why: 'Obrigação por prazo.' },
      { english: 'You don’t have to answer now.', translation: 'Você não precisa responder agora.', why: 'Ausência de obrigação.' },
      { english: 'Does she have to work late?', translation: 'Ela precisa trabalhar até tarde?', why: 'Pergunta com does + have.' }
    ],
    commonBrazilianMistakes: [mistake('She have to work.', 'She has to work.', 'He/she/it usa has to.'), mistake('Does she has to go?', 'Does she have to go?', 'Com does, volte para have.'), mistake('You don’t have to smoke here.', 'You can’t smoke here. / You mustn’t smoke here.', 'Don’t have to não é proibição.'), mistake('I have to can go.', 'I have to go.', 'Depois de have to, use verbo base.')],
    controlledPractice: [task('Complete: I ___ to wake up early.', 'have'), task('Complete: He ___ to call his boss.', 'has'), task('Complete: We ___ have to pay today.', 'don’t'), task('Complete: ___ you have to work tomorrow?', 'Do')],
    errorCorrectionPractice: [task('Corrija: She have to study.', 'She has to study.'), task('Corrija: Does he has to leave?', 'Does he have to leave?'), task('Corrija: I don’t have to go means I must not go.', 'I don’t have to go means it is not necessary.')],
    transformationPractice: [task('Obrigação: work tomorrow', 'I have to work tomorrow.'), task('Ela: study tonight', 'She has to study tonight.'), task('Não precisa: come early', 'You don’t have to come early.'), task('Pergunta: pay now', 'Do I have to pay now?')],
    translationPractice: [task('Eu tenho que trabalhar amanhã.', 'I have to work tomorrow.'), task('Ela tem que estudar hoje.', 'She has to study today.'), task('Você não precisa vir cedo.', 'You don’t have to come early.'), task('Eu preciso pagar agora?', 'Do I have to pay now?')],
    productionTasks: [task('Escreva 8 obrigações da sua rotina.'), task('Escreva 5 coisas que você não precisa fazer hoje.'), task('Crie 5 perguntas com Do/Does have to.')],
    finalChecklist: [task('É obrigação real?'), task('Usei has to com he/she?'), task('Usei don’t have to como “não precisa”?'), task('Na pergunta com does, usei have?')],
    selfAssessment: [task('Consigo falar de obrigação?'), task('Consigo dizer que não precisa?'), task('Consigo diferenciar should e have to?')],
    lessonRecap: ['Have to fala de obrigação.', 'Has to com he/she/it.', 'Don’t have to = não precisa.', 'Does she have to usa have, não has.'],
    nextLessonBridge: 'Agora você vai ler um texto com conselhos e obrigações juntos.',
  }),

  createReadingLesson({
    ...common,
    id: 'A2-READING-018',
    order: 18,
    title: 'Reading for advice and obligation',
    objectives: ['Ler texto com conselho e obrigação.', 'Diferenciar should e have to no contexto.', 'Identificar motivo com because.', 'Responder perguntas com evidência textual.'],
    teacherOpening: 'Nesta leitura, o foco é separar conselho de obrigação. Should mostra sugestão. Have to mostra algo necessário por regra, prazo ou situação.',
    whyItMatters: 'Muitos textos misturam recomendação e obrigação: trabalho, escola, saúde, viagem, hotel e eventos. Você precisa saber o que é obrigatório e o que é apenas conselho.',
    realLifeUseCases: ['Ler instruções de trabalho.', 'Entender regras de curso.', 'Ler conselho de saúde.', 'Separar obrigação de sugestão.', 'Responder com evidência.'],
    conceptExplanation: 'Procure should/shouldn’t para conselho e have to/has to/don’t have to para obrigação ou ausência dela. Because explica o motivo.',
    mentalModel: { title: 'advice vs obligation', summary: 'Should aconselha; have to obriga; don’t have to libera.', steps: ['find problem', 'find should', 'find have to', 'find because'] },
    stepByStep: [task('Leia o texto uma vez para o tema.'), task('Sublinhe should/shouldn’t.'), task('Circule have to/has to/don’t have to.'), task('Marque motivos com because.'), task('Responda copiando evidência.')],
    portugueseContrast: [task('Should não é obrigação forte.'), task('Have to é mais forte/prático.'), task('Don’t have to significa não precisa.'), task('Because dá a razão.')],
    guidedDiscovery: [task('You should rest = conselho.'), task('You have to arrive at 8 = obrigação.'), task('You don’t have to bring food = não precisa.'), task('Because liga motivo.')],
    guidedBeforeQuiz: [task('Procure should.'), task('Procure have to.'), task('Procure don’t have to.'), task('Procure because.')],
    readingPurpose: 'Entender conselhos e obrigações em um texto funcional A2.',
    preReadingVocabulary: [vocab('rule', 'regra'), vocab('deadline', 'prazo'), vocab('bring', 'trazer'), vocab('uniform', 'uniforme'), vocab('rest', 'descansar'), vocab('meeting', 'reunião')],
    readingStrategy: [task('Crie duas colunas: advice e obligation.'), task('Coloque should na coluna advice.'), task('Coloque have to na coluna obligation.'), task('Use evidência textual.')],
    mainText: `Hi team, tomorrow we have an important meeting with a new client. Everyone has to arrive at 8:30 because the meeting starts at 9. You have to bring your notebook and your ID card. You don’t have to wear a uniform, but you should wear comfortable clothes. Please don’t be late. If you feel tired tonight, you should sleep early and you shouldn’t study all night.`,
    firstReadTask: task('Qual é o assunto geral?', 'Instruções para reunião importante com cliente novo.'),
    secondReadTasks: [task('Que horas todos precisam chegar?', '8:30'), task('O que precisam trazer?', 'notebook and ID card'), task('Precisam usar uniforme?', 'no'), task('Que conselho aparece para quem está cansado?', 'sleep early / not study all night')],
    evidenceQuestions: [q('Why does everyone have to arrive at 8:30?', 'because the meeting starts at 9', 'because the meeting starts at 9', '', ['meeting starts at 9','client arrives at 8','uniform is required']), q('What do they have to bring?', 'notebook and ID card', 'bring your notebook and your ID card', '', ['notebook and ID card','food','uniform']), q('Do they have to wear a uniform?', 'no', 'You don’t have to wear a uniform', '', ['no','yes','only managers']), q('What should they wear?', 'comfortable clothes', 'you should wear comfortable clothes', '', ['comfortable clothes','a uniform','formal shoes']), q('What shouldn’t they do if tired?', 'study all night', 'you shouldn’t study all night', '', ['study all night','sleep early','bring ID'])],
    contextVocabularyTasks: [task('Client significa cliente.'), task('ID card significa documento/crachá.'), task('Comfortable clothes são roupas confortáveis.'), task('Don’t be late é não se atrase.')],
    guidedSummary: task('Complete: Everyone has to arrive at ___. They have to bring their ___ and ___. They don’t have to wear a ___. If they are tired, they should ___.', '', '8:30 / notebook / ID card / uniform / sleep early'),
    connectedProduction: task('Escreva 5 regras e 3 conselhos para um dia de trabalho importante.'),
    selfAssessment: [task('Consigo separar conselho de obrigação?'), task('Consigo encontrar evidência?'), task('Consigo entender don’t have to?')],
    lessonRecap: ['Should mostra conselho.', 'Have to mostra obrigação.', 'Don’t have to mostra ausência de obrigação.', 'Because explica razão.'],
    nextLessonBridge: 'Agora você vai falar sobre obrigações da sua rotina.',
  }),

  createSpeakingLesson({
    ...common,
    id: 'A2-SPEAKING-016',
    order: 16,
    title: 'Talk about obligations',
    objectives: ['Falar sobre obrigações da rotina.', 'Usar have to, has to e don’t have to oralmente.', 'Perguntar sobre obrigação com Do you have to...?', 'Comparar obrigação e conselho em fala curta.'],
    teacherOpening: 'Agora você vai falar sobre responsabilidades: I have to work. I have to wake up early. I don’t have to work on Sunday. My wife has to study. Do you have to wear a uniform?',
    whyItMatters: 'Falar de obrigações é essencial para trabalho, estudo, família, viagens e compromissos.',
    realLifeUseCases: ['Explicar rotina de trabalho.', 'Perguntar sobre regras.', 'Dizer que não precisa fazer algo.', 'Falar de obrigações de outra pessoa.', 'Dar conselho e obrigação juntos.'],
    conceptExplanation: 'Use frases curtas. Para você: I have to... Para outra pessoa: He/She has to... Para ausência de obrigação: I don’t have to... Para pergunta: Do you have to...?',
    mentalModel: { title: 'obligation speaking', summary: 'Fale obrigação, pessoa, tempo e motivo.', steps: ['I have to...', 'She has to...', 'I don’t have to...', 'Do you have to...?'] },
    stepByStep: [task('Escolha pessoa.'), task('Escolha obrigação.'), task('Use have to ou has to.'), task('Adicione tempo: today, tomorrow, on Saturday.'), task('Crie uma negativa com don’t have to.'), task('Faça uma pergunta.')],
    portugueseContrast: [task('I have to é “tenho que/preciso”.'), task('Don’t have to é “não preciso”.'), task('She has to, não she have to.'), task('Do you have to...? é pergunta natural.')],
    guidedDiscovery: [task('I have to work today.'), task('She has to study tonight.'), task('We don’t have to leave now.'), task('Do you have to wake up early?')],
    guidedBeforeQuiz: [task('Repita: I have to work tomorrow.'), task('Repita: She has to study tonight.'), task('Repita: I don’t have to go today.'), task('Repita: Do you have to wear a uniform?')],
    speakingSituation: 'Você vai explicar sua rotina e perguntar sobre obrigações de outra pessoa.',
    modelPhrases: [phrase('I have to wake up early.', 'Tenho que acordar cedo.'), phrase('I don’t have to work on Sunday.', 'Não preciso trabalhar no domingo.'), phrase('She has to study tonight.', 'Ela tem que estudar hoje à noite.'), phrase('Do you have to wear a uniform?', 'Você precisa usar uniforme?'), phrase('We have to arrive at eight.', 'Temos que chegar às oito.')],
    pronunciationChunks: [task('have to wake up early', 'Obrigação da rotina.'), task('don’t have to work', 'Não precisa trabalhar.'), task('does she have to', 'Pergunta com does + have.')],
    repeatAfterMe: [task('I have to work today.'), task('I have to wake up early.'), task('I don’t have to cook tonight.'), task('She has to call her boss.'), task('Do you have to leave now?')],
    substitutionDrills: [task('work → study', 'I have to study today.'), task('Sunday → Saturday', 'I don’t have to work on Saturday.'), task('she → he', 'He has to call his boss.'), task('leave now → pay today', 'Do you have to pay today?')],
    guidedSpeaking: [task('Diga 5 obrigações suas.'), task('Diga 3 coisas que você não precisa fazer hoje.'), task('Fale 3 obrigações de outra pessoa.'), task('Faça 5 perguntas com Do you have to...?')],
    recordingTasks: [task('Grave 8 frases com have to.'), task('Grave 5 frases com don’t have to.'), task('Grave diálogo curto perguntando sobre obrigações.'), task('Grave fala de 60 segundos sobre sua semana.')],
    freeSpeaking: task('Fale por até 60 segundos sobre suas obrigações esta semana e uma coisa que você não precisa fazer.'),
    feedbackChecklist: [task('Usei have to/has to corretamente?'), task('Usei don’t have to como “não precisa”?'), task('Usei tempo claro?'), task('Fiz pelo menos uma pergunta?')],
    selfAssessment: [task('Consigo falar obrigações?'), task('Consigo fazer perguntas?'), task('Consigo diferenciar conselho e obrigação?')],
    lessonRecap: ['Have to fala de obrigação.', 'Has to com he/she.', 'Don’t have to é não precisa.', 'Do you have to...? pergunta obrigação.'],
    nextLessonBridge: 'Agora você vai escrever sobre obrigações em uma mensagem clara.',
  }),

  createWritingLesson({
    ...common,
    id: 'A2-WRITING-016',
    order: 16,
    title: 'Write about obligations',
    objectives: ['Escrever sobre obrigações da rotina.', 'Usar have to, has to e don’t have to em mensagem curta.', 'Explicar motivo com because.', 'Combinar obrigação com conselho simples quando necessário.'],
    teacherOpening: 'Nesta escrita, você vai criar uma mensagem sobre obrigações: I have to work tomorrow. I don’t have to go early. My brother has to bring his ID card. You should arrive on time.',
    whyItMatters: 'Mensagens sobre obrigação aparecem em trabalho, estudo, família e compromissos. Você precisa explicar o que é necessário, o que não é e por quê.',
    realLifeUseCases: ['Mandar instruções de trabalho.', 'Explicar rotina da semana.', 'Combinar regras simples.', 'Avisar o que alguém precisa trazer.', 'Dizer que algo não é necessário.'],
    conceptExplanation: 'Organize a mensagem em: contexto, obrigações, coisas não necessárias, conselho final. Use have to para obrigação e don’t have to para não necessidade.',
    mentalModel: { title: 'obligation message', summary: 'Contexto + obrigação + não obrigação + conselho.', steps: ['Tomorrow...', 'We have to...', 'We don’t have to...', 'You should...'] },
    stepByStep: [task('Comece com contexto.'), task('Liste obrigações com have to.'), task('Liste o que não precisa com don’t have to.'), task('Dê motivo com because.'), task('Feche com conselho usando should.')],
    portugueseContrast: [task('Don’t have to = não precisa.'), task('Não use doesn’t has to.'), task('Use on para dias: on Monday.'), task('Use at para horas: at 8.')],
    guidedDiscovery: [task('We have to arrive at 8.'), task('You don’t have to bring food.'), task('She has to call the manager.'), task('You should sleep early.')],
    guidedBeforeQuiz: [task('Modelo: We have to arrive at 8.'), task('Modelo: You don’t have to wear a uniform.'), task('Modelo: She has to bring her ID card.'), task('Modelo: You should not be late.')],
    writingPurpose: 'Escrever mensagem funcional sobre obrigações e instruções simples.',
    modelText: `Hi team, tomorrow we have an important meeting. We have to arrive at 8:30 because the client arrives at 9. You have to bring your notebook and your ID card. You don’t have to wear a uniform, but you should wear comfortable clothes. Please don’t be late.`,
    writingBlocks: [task('Context', 'Tomorrow we have an important meeting.'), task('Obligation', 'We have to arrive at 8:30.'), task('Reason', 'because the client arrives at 9.'), task('No obligation', 'You don’t have to wear a uniform.'), task('Advice', 'You should wear comfortable clothes.')],
    guidedSubstitution: [task('Troque meeting por class.'), task('Troque 8:30 por 7:45.'), task('Troque notebook por phone charger.'), task('Troque uniform por formal clothes.')],
    grammarForWriting: [task('Use have to + base verb.'), task('Use has to com he/she.'), task('Use don’t have to para não precisa.'), task('Use because para motivo.'), task('Use should para conselho final.')],
    checklist: [task('Expliquei o contexto?'), task('Incluí pelo menos 2 obrigações?'), task('Incluí uma coisa que não precisa?'), task('Expliquei motivo com because?'), task('Usei should para conselho?')],
    draftTask: task('Escreva uma mensagem de 5 a 7 frases com instruções para um dia importante.'),
    revisionTask: task('Revise have/has, don’t/doesn’t have to, preposições de tempo e clareza.'),
    commonMistakes: [mistake('She have to bring ID.', 'She has to bring ID.', 'He/she usa has to.'), mistake('You don’t have to be late.', 'You shouldn’t be late. / Please don’t be late.', 'Don’t have to não significa não deve.'), mistake('Does he has to call?', 'Does he have to call?', 'Com does, use have.'), mistake('In Monday', 'On Monday', 'Dias usam on.')],
    productionTasks: [task('Escreva instruções para uma reunião.'), task('Escreva obrigações de uma viagem.'), task('Escreva mensagem para colega explicando o que precisa trazer.'), task('Reescreva usando pelo menos um should.')],
    selfAssessment: [task('Consigo escrever obrigações?'), task('Consigo dizer o que não precisa?'), task('Consigo explicar motivo e conselho?')],
    lessonRecap: ['Have to escreve obrigações.', 'Don’t have to escreve ausência de obrigação.', 'Because explica razão.', 'Should fecha com conselho.'],
    nextLessonBridge: 'A próxima parte do A2.5 vai trabalhar pedidos educados com can/could e pronomes objeto.',
  }),
]);

export const A2_DEEP_COMMUNICATION_TASKS_PART3_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART3.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART3.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART3.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART3.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART3.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART3.filter((lesson) => lesson.pillar === 'writing')),
});
