import { createGrammarLesson, createVocabularyLesson, createReadingLesson, createListeningLesson, createSpeakingLesson, createWritingLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-3', 'plans-and-now', 'present-continuous', 'work-study', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function phrase(text, translation = '', note = '') { return { text, translation, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }
function q(question, answer, evidence = '', explanation = '', options = []) { return { question, answer, evidence, explanation, options }; }
function ex(text, translation, why = '', warning = '') { return { text, translation, why, warning }; }

export const A2_DEEP_PLANS_AND_NOW = Object.freeze([
  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-008',
    order: 8,
    title: 'Present Continuous — actions now',
    objectives: ['Formar Present Continuous para ações acontecendo agora.', 'Usar am/is/are + verb-ing corretamente.', 'Diferenciar ação agora de rotina geral.', 'Criar frases sobre trabalho, estudo, casa e telefone.'],
    teacherOpening: 'Agora o A2 muda do passado para o presente em andamento. Present Continuous fala do que está acontecendo agora: I am studying. She is working. They are waiting. A chave é be + verb-ing.',
    whyItMatters: 'Você usa Present Continuous para explicar o que está fazendo agora, o que alguém está fazendo, por que não pode responder, ou o que está acontecendo em uma situação real.',
    realLifeUseCases: ['Dizer que está trabalhando agora.', 'Explicar que está estudando.', 'Falar que alguém está esperando.', 'Descrever problema acontecendo no telefone.', 'Responder What are you doing?'],
    conceptExplanation: 'Use subject + am/is/are + verb-ing. I am working. You are studying. He is calling. We are waiting. O verbo be muda com o sujeito; o verbo principal ganha -ing.',
    mentalModel: { title: 'be + verb-ing = acontecendo agora', summary: 'O be mostra o sujeito; o -ing mostra ação em andamento.', steps: ['I am working.', 'She is studying.', 'They are waiting.'] },
    stepByStep: [task('Escolha o sujeito.'), task('Use am/is/are.'), task('Adicione verbo com -ing.'), task('Complete com agora/lugar.'), task('Revise se não esqueceu o be.')],
    portugueseContrast: [task('Português usa estou trabalhando; inglês precisa I am working.'), task('Não diga I working.'), task('Não diga She are studying.'), task('Não use Present Continuous para toda rotina permanente.')],
    guidedDiscovery: [task('Am combina com I.'), task('Is combina com he/she/it.'), task('Are combina com you/we/they.'), task('Working mostra ação em andamento.')],
    guidedBeforeQuiz: [task('Complete: I ___ studying.', 'am'), task('Complete: She ___ working.', 'is'), task('Complete: They ___ waiting.', 'are'), task('Corrija: I working now.', 'I am working now.')],
    grammarGoal: 'Descrever ações acontecendo agora com am/is/are + verb-ing.',
    formationGuide: [task('I + am + verb-ing', 'I am studying now.'), task('He/She/It + is + verb-ing', 'She is working.'), task('You/We/They + are + verb-ing', 'They are waiting.'), task('Negative', 'I am not working now.'), task('Question', 'Are you studying?')],
    whenToUse: [task('Ações acontecendo agora.'), task('Situações temporárias em andamento.'), task('Fotos, chamadas, mensagens e cenas atuais.')],
    whenNotToUse: [task('Não use para hábitos gerais sem contexto temporário.'), task('Não esqueça am/is/are.'), task('Não use do/does junto com be no afirmativo.')],
    grammarTable: [
      { pattern: 'I am + ing', example: 'I am studying English now.', translation: 'Estou estudando inglês agora.' },
      { pattern: 'She is + ing', example: 'She is working today.', translation: 'Ela está trabalhando hoje.' },
      { pattern: 'They are + ing', example: 'They are waiting at the station.', translation: 'Eles estão esperando na estação.' },
      { pattern: 'Are you + ing?', example: 'Are you working now?', translation: 'Você está trabalhando agora?' }
    ],
    teacherExamples: [
      { english: 'I am writing a message.', translation: 'Estou escrevendo uma mensagem.', why: 'Ação em andamento agora.' },
      { english: 'He is fixing his phone.', translation: 'Ele está consertando o telefone.', why: 'Problema acontecendo agora.' },
      { english: 'We are studying for a test.', translation: 'Estamos estudando para uma prova.', why: 'Ação atual/temporária.' },
      { english: 'They are having lunch.', translation: 'Eles estão almoçando.', why: 'Atividade em andamento.' }
    ],
    commonBrazilianMistakes: [mistake('I working now.', 'I am working now.', 'Present Continuous precisa de be.'), mistake('She are studying.', 'She is studying.', 'She usa is.'), mistake('They is waiting.', 'They are waiting.', 'They usa are.'), mistake('I am work now.', 'I am working now.', 'Verbo principal ganha -ing.')],
    controlledPractice: [task('Complete: I ___ cooking.', 'am'), task('Complete: He ___ calling.', 'is'), task('Complete: We ___ waiting.', 'are'), task('Complete: She is ___ a message. (write)', 'writing')],
    errorCorrectionPractice: [task('Corrija: I studying.', 'I am studying.'), task('Corrija: You is working.', 'You are working.'), task('Corrija: He is call me.', 'He is calling me.')],
    transformationPractice: [task('Transforme: I study English. (now)', 'I am studying English now.'), task('Transforme: She works. (right now)', 'She is working right now.'), task('Transforme: They wait. (at the station)', 'They are waiting at the station.')],
    translationPractice: [task('Estou estudando agora.', 'I am studying now.'), task('Ela está trabalhando hoje.', 'She is working today.'), task('Eles estão esperando.', 'They are waiting.')],
    productionTasks: [task('Escreva 8 frases sobre o que pessoas estão fazendo agora.'), task('Descreva sua situação atual em 5 frases.'), task('Crie 5 perguntas com Are you...?')],
    finalChecklist: [task('Usei am/is/are?'), task('O verbo tem -ing?'), task('O contexto é agora/temporário?'), task('Concordei be com o sujeito?')],
    selfAssessment: [task('Consigo dizer o que estou fazendo agora?'), task('Consigo formar pergunta?'), task('Consigo evitar I working?')],
    lessonRecap: ['Present Continuous fala de ação em andamento.', 'A forma é be + verb-ing.', 'I usa am, he/she/it usa is, you/we/they usa are.', 'Não esqueça o be.'],
    nextLessonBridge: 'Na próxima aula de vocabulário, você vai falar de tarefas e horários de trabalho usando ações atuais e agenda.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-009',
    order: 9,
    title: 'Work tasks and schedules',
    objectives: ['Aprender vocabulário de tarefas e horários de trabalho.', 'Falar de agenda, turno, reunião, prazo e tarefa.', 'Usar Present Continuous para ações de trabalho atuais.', 'Preparar mensagens sobre mudança de horário.'],
    teacherOpening: 'Work tasks and schedules abre o A2.3 no vocabulário. Você vai falar de tarefas, horários, reuniões e mudanças: task, schedule, shift, meeting, deadline, report, call, break, busy, available, working, waiting.',
    whyItMatters: 'Trabalho e agenda são temas reais do A2. Você precisa dizer o que está fazendo, quando tem reunião, se está disponível e se o horário mudou.',
    realLifeUseCases: ['Falar que está ocupado.', 'Explicar uma mudança de horário.', 'Marcar reunião simples.', 'Dizer que está trabalhando em uma tarefa.', 'Falar de prazo e pausa.'],
    conceptExplanation: 'Organize o vocabulário por tempo e tarefa. Schedule é agenda/horário. Shift é turno. Task é tarefa. Deadline é prazo. Available é disponível. Use: I am working on a report. I have a meeting at 3. My shift starts at 8.',
    mentalModel: { title: 'work = task + time + availability', summary: 'Diga o que está fazendo, quando e se pode.', steps: ['task', 'schedule', 'meeting', 'deadline', 'available'] },
    stepByStep: [task('Aprenda tarefas comuns.'), task('Aprenda palavras de agenda.'), task('Monte frases com horário.'), task('Use Present Continuous para agora.'), task('Use available/busy para disponibilidade.')],
    portugueseContrast: [task('Schedule é agenda/cronograma, não escola.'), task('Shift é turno.'), task('Deadline é prazo final.'), task('Available significa disponível.')],
    guidedDiscovery: [task('Meeting é evento de trabalho.'), task('Deadline indica prazo.'), task('I am working on... indica tarefa atual.')],
    guidedBeforeQuiz: [task('I am working on a report.'), task('My meeting is at 3.'), task('My shift starts at 8.'), task('I am not available now.')],
    topicContext: 'Você vai falar de trabalho, tarefas, horários e disponibilidade.',
    essentialWords: [vocab('task', 'tarefa', 'This task is important.'), vocab('schedule', 'agenda/horário', 'My schedule changed.'), vocab('shift', 'turno', 'My shift starts at 8.'), vocab('meeting', 'reunião', 'I have a meeting at 3.'), vocab('deadline', 'prazo', 'The deadline is tomorrow.'), vocab('report', 'relatório', 'I am writing a report.'), vocab('call', 'ligação/chamada', 'I have a call at 2.'), vocab('break', 'pausa', 'I am taking a break.'), vocab('busy', 'ocupado', 'I am busy now.'), vocab('available', 'disponível', 'I am available after lunch.'), vocab('late', 'atrasado', 'I am running late.'), vocab('early', 'cedo/adiantado', 'The meeting is early.'), vocab('start', 'começar', 'The shift starts at 8.'), vocab('finish', 'terminar', 'I finish work at 5.'), vocab('change', 'mudar', 'The schedule changed.'), vocab('cancel', 'cancelar', 'They canceled the meeting.')],
    chunks: [{ chunk: 'working on a task', translation: 'trabalhando em uma tarefa', example: 'I am working on a task.' }, { chunk: 'my schedule changed', translation: 'meu horário mudou', example: 'My schedule changed.' }, { chunk: 'I have a meeting', translation: 'tenho uma reunião', example: 'I have a meeting at 3.' }, { chunk: 'I am available after lunch', translation: 'estou disponível depois do almoço', example: 'I am available after lunch.' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Schedule pode soar diferente em inglês americano/britânico.', 'Deadline tem stress em DEAD.', 'Available tem stress em VAI.'] },
    dangerousConfusions: [task('Busy = ocupado; business = negócio/empresa.'), task('Meeting não é “metting”.'), task('Deadline não é linha morta; é prazo.'), task('Available não é avaliado.')],
    collocations: [task('have a meeting'), task('write a report'), task('take a break'), task('work on a task'), task('change the schedule'), task('meet a deadline'), task('be available')],
    miniDialogues: [{ title: 'Schedule update', lines: ['A: Are you available now?', 'B: No, I am working on a report.', 'A: What time is your meeting?', 'B: At 3. I am available after lunch.'], focus: 'Disponibilidade e tarefa atual.' }],
    examples: [ex('I am working on a report right now.', 'Estou trabalhando em um relatório agora.', 'Present Continuous + work task.'), ex('My schedule changed yesterday.', 'Meu horário mudou ontem.', 'Passado de change.'), ex('I am available after the meeting.', 'Estou disponível depois da reunião.', 'Disponibilidade.')],
    recognitionPractice: [task('Qual palavra significa prazo?', 'deadline'), task('Qual palavra significa turno?', 'shift'), task('Qual palavra significa disponível?', 'available')],
    usagePractice: [task('Complete: I am working ___ a report.', 'on'), task('Complete: I have a meeting ___ 3.', 'at'), task('Complete: I am available ___ lunch.', 'after')],
    productionTasks: [task('Escreva 6 frases sobre sua rotina de trabalho/estudo.'), task('Crie 3 mensagens de mudança de horário.'), task('Crie um mini diálogo sobre disponibilidade.')],
    spacedReview: [task('Revise task/schedule/shift/deadline amanhã.'), task('Crie 3 frases com available/busy.')],
    selfAssessment: [task('Consigo falar de tarefas?'), task('Consigo falar de horário/reunião?'), task('Consigo dizer disponibilidade?')],
    lessonRecap: ['Work vocabulary combina tarefa e tempo.', 'Schedule, shift e deadline são essenciais.', 'Available/busy resolvem disponibilidade.', 'Present Continuous mostra tarefa atual.'],
    nextLessonBridge: 'Na Reading, você vai ler uma atualização de horário de trabalho.',
  }),

  createReadingLesson({
    ...common,
    id: 'A2-READING-008',
    order: 8,
    title: 'A work schedule update',
    objectives: ['Ler uma atualização simples de horário de trabalho.', 'Identificar mudança de turno, reunião e disponibilidade.', 'Reconhecer now, today, tomorrow e after lunch.', 'Responder com evidência textual.'],
    teacherOpening: 'Nesta leitura, você vai ler uma mensagem de atualização de horário. O objetivo é entender o que mudou, quando acontece e quem está disponível.',
    whyItMatters: 'Mensagens de trabalho/agenda são comuns. No A2, você precisa entender mudança de horário, reunião, turno e disponibilidade sem se perder nos detalhes.',
    realLifeUseCases: ['Ler mensagem de trabalho.', 'Entender mudança de reunião.', 'Saber quando alguém está disponível.', 'Responder sobre agenda.', 'Planejar estudo ou tarefa.'],
    conceptExplanation: 'Procure time words: today, tomorrow, after lunch, at 3. Procure actions: working, meeting, changed, canceled. Procure availability: available, busy.',
    mentalModel: { title: 'schedule update = mudança + horário + disponibilidade', summary: 'Leia para descobrir o que mudou e quando.', steps: ['what changed', 'when', 'who is busy', 'who is available'] },
    stepByStep: [task('Leia para achar a mudança principal.'), task('Marque horários.'), task('Marque reunião/tarefa.'), task('Procure available/busy.'), task('Responda com evidência.')],
    portugueseContrast: [task('Update = atualização.'), task('After lunch = depois do almoço.'), task('Available = disponível.'), task('Busy = ocupado.')],
    guidedDiscovery: [task('Changed mostra mudança.'), task('Tomorrow mostra futuro próximo.'), task('I am working now mostra ação atual.')],
    guidedBeforeQuiz: [task('Procure changed.'), task('Procure meeting.'), task('Procure available.'), task('Use evidência.')],
    readingPurpose: 'Entender atualização curta de agenda/trabalho.',
    preReadingVocabulary: [vocab('schedule', 'agenda/horário'), vocab('meeting', 'reunião'), vocab('available', 'disponível'), vocab('busy', 'ocupado'), vocab('after lunch', 'depois do almoço')],
    readingStrategy: [task('Use scanning para horários.'), task('Procure quem está fazendo o quê.'), task('Separe hoje e amanhã.'), task('Copie evidência.')],
    mainText: `Hi, team. My schedule changed today. I am working on the report this morning, so I am not available now. The meeting at 10 was canceled. We are having a new meeting tomorrow at 3. I am available after lunch today if you need help with the task.`,
    firstReadTask: task('Qual é o assunto geral?', 'Uma atualização de horário de trabalho.'),
    secondReadTasks: [task('O que mudou?', 'the schedule changed / meeting at 10 was canceled'), task('Em que a pessoa está trabalhando?', 'the report'), task('Quando será a nova reunião?', 'tomorrow at 3'), task('Quando a pessoa está disponível?', 'after lunch today')],
    evidenceQuestions: [q('What changed today?', 'the schedule', 'My schedule changed today.', '', ['the schedule','the hotel','the price']), q('What is the person working on?', 'the report', 'I am working on the report this morning', '', ['the report','a phone','a lesson']), q('What happened to the meeting at 10?', 'it was canceled', 'The meeting at 10 was canceled.', '', ['canceled','moved to 9','finished']), q('When is the new meeting?', 'tomorrow at 3', 'a new meeting tomorrow at 3', '', ['tomorrow at 3','today at 10','after lunch today']), q('When is the person available?', 'after lunch today', 'I am available after lunch today', '', ['after lunch today','now','tomorrow morning'])],
    contextVocabularyTasks: [task('Canceled significa cancelada.'), task('Need help with the task mostra oferta de ajuda.'), task('Now contrasta com after lunch.')],
    guidedSummary: task('Complete: The schedule changed. The 10 o’clock meeting was ___. The new meeting is tomorrow at ___. The person is available after ___.', '', 'canceled / 3 / lunch'),
    connectedProduction: task('Escreva 3 frases sobre uma mudança de horário no trabalho ou estudo.'),
    selfAssessment: [task('Consigo entender mudança de agenda?'), task('Consigo identificar disponibilidade?'), task('Consigo responder com evidência?')],
    lessonRecap: ['Schedule updates mostram mudança, horário e disponibilidade.', 'Today/tomorrow/after lunch orientam o tempo.', 'Canceled indica cancelamento.', 'Available/busy são essenciais.'],
    nextLessonBridge: 'No Listening, você vai ouvir mudanças de horário de trabalho.',
  }),

  createListeningLesson({
    ...common,
    id: 'A2-LISTENING-008',
    order: 8,
    title: 'Work schedule changes',
    objectives: ['Ouvir diálogo sobre mudança de horário de trabalho.', 'Identificar reunião, novo horário e disponibilidade.', 'Reconhecer now, today, tomorrow e after lunch.', 'Praticar dictation e shadowing de agenda.'],
    teacherOpening: 'Nesta escuta, você vai ouvir uma conversa sobre agenda. Primeiro entenda o que mudou. Depois, identifique o novo horário e quando a pessoa está disponível.',
    whyItMatters: 'Mudança de agenda é comum em trabalho e estudo. Você precisa entender horários rapidamente e responder se está disponível.',
    realLifeUseCases: ['Entender reunião remarcada.', 'Dizer que está ocupado agora.', 'Confirmar disponibilidade.', 'Combinar novo horário.', 'Ouvir tarefa atual.'],
    conceptExplanation: 'Ouça por blocos: I am working now, the meeting was canceled, tomorrow at 3, are you available after lunch? Esses blocos mostram ação atual e agenda.',
    mentalModel: { title: 'listen for schedule changes', summary: 'Mudança, novo horário e disponibilidade.', steps: ['current task', 'canceled/moved', 'new time', 'available?'] },
    stepByStep: [task('Primeira escuta: o que mudou?'), task('Segunda escuta: novo horário.'), task('Terceira etapa: disponibilidade.'), task('Leia transcript.'), task('Faça dictation.'), task('Faça shadowing.')],
    portugueseContrast: [task('Are you available? = você está disponível?'), task('Moved = movida/remarcada.'), task('Canceled = cancelada.'), task('After lunch = depois do almoço.')],
    guidedDiscovery: [task('I am working now indica ação atual.'), task('Meeting moved indica mudança.'), task('Available after lunch indica disponibilidade.')],
    guidedBeforeQuiz: [task('Primeira escuta: reunião foi cancelada ou remarcada?'), task('Segunda escuta: para quando?')],
    listeningPreparation: [task('Não leia transcript antes da primeira escuta.'), task('Prepare: meeting, moved, canceled, available, after lunch, tomorrow.'), task('Objetivo: mudança + novo horário.')],
    keyWordsToHear: [vocab('meeting','reunião'), vocab('moved','remarcada/movida'), vocab('available','disponível'), vocab('busy','ocupado'), vocab('after lunch','depois do almoço')],
    audioScript: `A: Are you available now?
B: Not now. I am working on a report.
A: Okay. The meeting was moved to tomorrow at three.
B: Tomorrow at three is fine.
A: Great. Are you available after lunch today?
B: Yes, I am. I can help with the task after lunch.`,
    firstListenTasks: [task('Sem transcript: a pessoa está disponível agora?', 'no'), task('Sem transcript: a reunião foi para amanhã?', 'yes')],
    secondListenTasks: [task('Em que a pessoa está trabalhando?', 'a report'), task('Para quando a reunião foi movida?', 'tomorrow at three'), task('Quando ela pode ajudar?', 'after lunch today')],
    transcript: `A: Are you available now?
B: Not now. I am working on a report.
A: Okay. The meeting was moved to tomorrow at three.
B: Tomorrow at three is fine.
A: Great. Are you available after lunch today?
B: Yes, I am. I can help with the task after lunch.`,
    vocabulary: [vocab('not now', 'agora não'), vocab('is fine', 'está bom'), vocab('help with the task', 'ajudar com a tarefa')],
    shadowing: [task('Are you available now?'), task('I am working on a report.'), task('The meeting was moved to tomorrow at three.'), task('Tomorrow at three is fine.'), task('I can help with the task after lunch.')],
    dictationTasks: [task('Digite: Are you available now?', 'Are you available now?'), task('Digite: I am working on a report.', 'I am working on a report.'), task('Digite: The meeting was moved to tomorrow at three.', 'The meeting was moved to tomorrow at three.')],
    pronunciationChunks: [task('available now', 'Conecte final/início.'), task('working on a report', 'Bloco de tarefa.'), task('tomorrow at three', 'Tempo em bloco.')],
    listeningComprehension: [q('Is the person available now?', 'no', 'Not now. I am working on a report.', '', ['no','yes','not mentioned']), q('What is the person working on?', 'a report', 'I am working on a report.', '', ['a report','a phone','a meeting']), q('When is the meeting?', 'tomorrow at three', 'moved to tomorrow at three', '', ['tomorrow at three','today at ten','after lunch']), q('When can the person help?', 'after lunch', 'I can help with the task after lunch.', '', ['after lunch','now','tomorrow night'])],
    oralProduction: task('Pratique dizer se está disponível agora e quando pode ajudar.'),
    selfAssessment: [task('Consegui ouvir disponibilidade?'), task('Consegui ouvir novo horário?'), task('Consigo repetir frases de agenda?')],
    lessonRecap: ['Schedule listening foca mudança e disponibilidade.', 'Present Continuous mostra tarefa atual.', 'Moved/canceled indicam alteração.', 'After lunch/tomorrow at three dão tempo.'],
    nextLessonBridge: 'No Speaking, você vai falar sobre sua agenda de trabalho.',
  }),

  createSpeakingLesson({
    ...common,
    id: 'A2-SPEAKING-009',
    order: 9,
    title: 'Talk about work schedule',
    objectives: ['Falar sobre agenda de trabalho ou estudo.', 'Dizer o que está fazendo agora.', 'Dizer quando está disponível.', 'Gravar fala curta sobre horário, reunião e tarefa.'],
    teacherOpening: 'Nesta fala, você vai explicar sua agenda: I am working now. I have a meeting at 3. I am available after lunch. My shift starts at 8. O foco é falar de horário real com frases simples.',
    whyItMatters: 'Falar de agenda é útil para trabalho, estudo e compromissos. Você precisa explicar disponibilidade sem frases longas.',
    realLifeUseCases: ['Dizer que está ocupado.', 'Marcar reunião.', 'Explicar turno.', 'Oferecer ajuda depois.', 'Responder se está disponível.'],
    conceptExplanation: 'Use Present Continuous para agora: I am working now. Use have para compromisso: I have a meeting at 3. Use available/busy para disponibilidade. Use starts/finishes para turno.',
    mentalModel: { title: 'agenda em 4 frases', summary: 'Agora, compromisso, disponibilidade e turno.', steps: ['I am working now.', 'I have a meeting at 3.', 'I am available after lunch.', 'My shift starts at 8.'] },
    stepByStep: [task('Diga o que está fazendo agora.'), task('Diga um compromisso.'), task('Diga disponibilidade.'), task('Diga horário de início/fim.'), task('Grave versão final.')],
    portugueseContrast: [task('I am available = estou disponível.'), task('I have a meeting = tenho uma reunião.'), task('My shift starts at... = meu turno começa às...')],
    guidedDiscovery: [task('Are you available now? pede disponibilidade.'), task('I am working now explica indisponibilidade.'), task('After lunch oferece alternativa.')],
    guidedBeforeQuiz: [task('Repita: I am working now.'), task('Repita: I have a meeting at 3.'), task('Repita: I am available after lunch.'), task('Repita: My shift starts at 8.')],
    speakingSituation: 'Você precisa explicar sua agenda e disponibilidade para alguém.',
    modelPhrases: [phrase('I am working now.', 'Estou trabalhando agora.'), phrase('I have a meeting at 3.', 'Tenho uma reunião às 3.'), phrase('I am available after lunch.', 'Estou disponível depois do almoço.'), phrase('My shift starts at 8.', 'Meu turno começa às 8.'), phrase('I can help with the task later.', 'Posso ajudar com a tarefa mais tarde.')],
    pronunciationChunks: [task('I am working now', 'Bloco de estado atual.'), task('available after lunch', 'Disponibilidade em bloco.'), task('meeting at three', 'Conecte meeting-at-three.')],
    repeatAfterMe: [task('Are you available now?'), task('Not now. I am working.'), task('I have a meeting at 3.'), task('I am available after lunch.'), task('I can help later.')],
    substitutionDrills: [task('meeting → call', 'I have a call at 3.'), task('after lunch → tomorrow morning', 'I am available tomorrow morning.'), task('working → studying', 'I am studying now.')],
    guidedSpeaking: [task('Responda: Are you available now?'), task('Diga uma tarefa atual.'), task('Diga um compromisso.'), task('Diga quando pode ajudar.')],
    recordingTasks: [task('Grave 5 frases sobre agenda.'), task('Grave diálogo de disponibilidade.'), task('Grave fala de 45 segundos sobre seu dia de trabalho/estudo.')],
    freeSpeaking: task('Fale por até 60 segundos sobre sua agenda de hoje, usando now, at, after lunch e tomorrow.'),
    feedbackChecklist: [task('Usei Present Continuous para agora?'), task('Usei meeting/call/task?'), task('Disse disponibilidade?'), task('Usei horários claros?')],
    selfAssessment: [task('Consigo falar de agenda?'), task('Consigo dizer que estou ocupado?'), task('Consigo oferecer horário alternativo?')],
    lessonRecap: ['Agenda combina tarefa, compromisso e disponibilidade.', 'Present Continuous explica o agora.', 'Available/busy resolvem comunicação prática.', 'Horários deixam a fala clara.'],
    nextLessonBridge: 'Na Writing, você vai escrever uma mensagem de mudança de horário de trabalho.',
  }),

  createWritingLesson({
    ...common,
    id: 'A2-WRITING-009',
    order: 9,
    title: 'Write a work schedule message',
    objectives: ['Escrever mensagem curta sobre agenda de trabalho/estudo.', 'Explicar mudança de horário ou reunião.', 'Dizer disponibilidade com clareza.', 'Revisar tom profissional simples.'],
    teacherOpening: 'Nesta escrita, você vai escrever uma mensagem curta sobre agenda. Exemplo: Hi, my schedule changed today. I am working on a report now. I am available after lunch. Can we meet tomorrow at 3?',
    whyItMatters: 'Mensagens de agenda são comuns no trabalho e nos estudos. Você precisa escrever com clareza, sem texto longo, dizendo o que mudou e quando está disponível.',
    realLifeUseCases: ['Avisar mudança de horário.', 'Remarcar reunião.', 'Dizer que está ocupado agora.', 'Oferecer novo horário.', 'Pedir ajuda com tarefa.'],
    conceptExplanation: 'Uma work schedule message tem 4 partes: greeting, context/change, current task, availability/request. Use today, now, after lunch, tomorrow at 3.',
    mentalModel: { title: 'schedule message = mudança + agora + disponibilidade', summary: 'Explique o que mudou e ofereça solução.', steps: ['Hi', 'My schedule changed', 'I am working now', 'I am available...', 'Can we...?'] },
    stepByStep: [task('Comece com Hi/Hello.'), task('Explique a mudança.'), task('Diga o que está fazendo agora.'), task('Diga quando está disponível.'), task('Faça pedido ou proposta.'), task('Feche com thanks.')],
    portugueseContrast: [task('Não escreva texto longo demais.'), task('Use available, não “disposed”.'), task('Use Can we meet...? para propor reunião.'), task('Use at para horário.')],
    guidedDiscovery: [task('My schedule changed dá contexto.'), task('I am working now mostra o agora.'), task('Can we meet tomorrow at 3? propõe solução.')],
    guidedBeforeQuiz: [task('Modelo: Hi, my schedule changed today.'), task('Modelo: I am working on a report now.'), task('Modelo: I am available after lunch.'), task('Modelo: Can we meet tomorrow at 3?')],
    writingPurpose: 'Escrever mensagem curta de agenda/trabalho.',
    modelText: `Hi, my schedule changed today. I am working on a report now, so I am not available this morning. I am available after lunch. Can we meet tomorrow at 3? Thank you.`,
    writingBlocks: [task('Greeting', 'Hi,'), task('Change', 'My schedule changed today.'), task('Current task', 'I am working on a report now.'), task('Availability', 'I am available after lunch.'), task('Request', 'Can we meet tomorrow at 3?'), task('Closing', 'Thank you.')],
    guidedSubstitution: [task('Troque report por task/call.'), task('Troque after lunch por tomorrow morning.'), task('Troque meet tomorrow at 3 por talk at 4.'), task('Troque schedule changed por meeting was canceled.')],
    grammarForWriting: [task('Use Present Continuous para agora.'), task('Use Past Simple para changed/canceled.'), task('Use at para horário.'), task('Use after para período posterior.'), task('Use ? em proposta/pergunta.')],
    checklist: [task('Expliquei a mudança?'), task('Disse o que estou fazendo agora?'), task('Disse disponibilidade?'), task('Propus horário claro?'), task('Usei tom educado?')],
    draftTask: task('Escreva uma mensagem de 4 a 6 frases avisando mudança de agenda.'),
    revisionTask: task('Revise tempo, disponibilidade, pedido e pontuação.'),
    commonMistakes: [mistake('I am available in 3.', 'I am available at 3.', 'Use at para horário.'), mistake('I working now.', 'I am working now.', 'Present Continuous precisa de be.'), mistake('Can we meet tomorrow at 3.', 'Can we meet tomorrow at 3?', 'Pergunta precisa de ?')],
    productionTasks: [task('Escreva mensagem remarcando reunião.'), task('Escreva mensagem dizendo que está ocupado agora.'), task('Reescreva com nova disponibilidade.')],
    selfAssessment: [task('Consigo escrever mensagem de agenda?'), task('Consigo propor novo horário?'), task('Consigo revisar tom profissional simples?')],
    lessonRecap: ['Schedule message deve ser curta e clara.', 'Diga mudança, tarefa atual e disponibilidade.', 'Use horários específicos.', 'Tom educado ajuda comunicação real.'],
    nextLessonBridge: 'Na próxima parte do A2.3, você vai aprofundar estudo, tecnologia, casa e planos com going to.',
  }),
]);

export const A2_DEEP_PLANS_AND_NOW_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_PLANS_AND_NOW.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_PLANS_AND_NOW.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_PLANS_AND_NOW.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_PLANS_AND_NOW.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_PLANS_AND_NOW.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_PLANS_AND_NOW.filter((lesson) => lesson.pillar === 'writing')),
});
