import { createGrammarLesson, createVocabularyLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-5', 'communication-tasks', 'requests', 'pronouns', 'adverbs', 'connectors', 'closing', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }
function ex(text, translation, why = '', warning = '') { return { text, translation, why, warning }; }

export const A2_DEEP_COMMUNICATION_TASKS_PART4 = Object.freeze([
  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-021',
    order: 21,
    title: 'Can / could for requests',
    objectives: ['Fazer pedidos com can e could.', 'Diferenciar pedido direto e pedido mais educado.', 'Usar Can you...? Could you...? Can I...? Could I...?', 'Responder pedidos com yes, sure, sorry e motivo simples.'],
    teacherOpening: 'Can e could são essenciais para pedidos. Can you help me? é natural. Could you help me? é mais educado. Can I sit here? pede permissão. Could I ask a question? soa mais formal.',
    whyItMatters: 'Você usa can/could em loja, trabalho, escola, viagem, hotel, restaurante, atendimento e mensagens.',
    realLifeUseCases: ['Pedir ajuda.', 'Pedir permissão.', 'Pedir informação.', 'Pedir para alguém repetir.', 'Responder pedidos educadamente.'],
    conceptExplanation: 'Use Can you/Could you + base verb para pedir que alguém faça algo. Use Can I/Could I + base verb para pedir permissão. Could é mais educado/formal que can.',
    mentalModel: { title: 'request = can/could + subject + verb', summary: 'Can é natural; could é mais educado.', steps: ['Can you help me?', 'Could you repeat that?', 'Can I sit here?', 'Could I ask a question?'] },
    stepByStep: [task('Decida se você quer pedir ajuda ou permissão.'), task('Ajuda: Can/Could you + verb?'), task('Permissão: Can/Could I + verb?'), task('Use please para suavizar.'), task('Responda com Sure ou Sorry.')],
    portugueseContrast: [task('Could não é só passado; aqui é pedido educado.'), task('Depois de can/could use verbo base.'), task('Não use to depois de can/could.'), task('Please ajuda, mas não substitui estrutura correta.')],
    guidedDiscovery: [task('Can you help me? = pedido comum.'), task('Could you help me? = pedido mais educado.'), task('Can I use your phone? = permissão.'), task('Could I ask a question? = permissão educada.')],
    guidedBeforeQuiz: [task('Complete: ___ you help me, please?', 'Can/Could'), task('Complete: Could you ___ that?', 'repeat'), task('Corrija: Can you to call me?', 'Can you call me?')],
    grammarGoal: 'Fazer pedidos e pedir permissão de forma educada.',
    formationGuide: [task('Can you + verb?', 'Can you help me?'), task('Could you + verb?', 'Could you repeat that, please?'), task('Can I + verb?', 'Can I sit here?'), task('Could I + verb?', 'Could I ask a question?')],
    whenToUse: [task('Pedidos do dia a dia.'), task('Permissão em lugares públicos.'), task('Atendimento e trabalho.'), task('Quando precisa soar educado.')],
    whenNotToUse: [task('Não use can to/could to.'), task('Não confunda Could you...? com passado neste contexto.'), task('Não diga You can help me? como pedido padrão; use Can you help me?')],
    grammarTable: [
      { pattern: 'Can you + verb?', example: 'Can you help me?', translation: 'Você pode me ajudar?' },
      { pattern: 'Could you + verb?', example: 'Could you send me the address?', translation: 'Você poderia me enviar o endereço?' },
      { pattern: 'Can I + verb?', example: 'Can I use this chair?', translation: 'Posso usar esta cadeira?' },
      { pattern: 'Could I + verb?', example: 'Could I ask a question?', translation: 'Eu poderia fazer uma pergunta?' }
    ],
    teacherExamples: [
      { english: 'Could you speak more slowly, please?', translation: 'Você poderia falar mais devagar, por favor?', why: 'Pedido educado + advérbio.' },
      { english: 'Can I pay by card?', translation: 'Posso pagar no cartão?', why: 'Permissão/prática de atendimento.' },
      { english: 'Sorry, I can’t help you right now because I’m busy.', translation: 'Desculpa, não posso te ajudar agora porque estou ocupado.', why: 'Resposta negativa com motivo.' }
    ],
    commonBrazilianMistakes: [mistake('Can you to help me?', 'Can you help me?', 'Sem to depois de can.'), mistake('You can help me?', 'Can you help me?', 'Pergunta precisa inverter can + subject.'), mistake('Could you helps me?', 'Could you help me?', 'Verbo base depois de could.'), mistake('Can I to use this?', 'Can I use this?', 'Sem to depois de can.')],
    controlledPractice: [task('Complete: Can you ___ me?', 'help'), task('Complete: Could you ___ that?', 'repeat'), task('Complete: Can I ___ here?', 'sit'), task('Complete: Could I ___ a question?', 'ask: verbo para fazer uma pergunta.')],
    errorCorrectionPractice: [task('Corrija: Could you to call me?', 'Could you call me?'), task('Corrija: You can repeat?', 'Can you repeat?'), task('Corrija: Can I to pay now?', 'Can I pay now?')],
    transformationPractice: [task('Mais educado: Can you help me?', 'Could you help me?'), task('Permissão: I use your charger?', 'Can I use your charger?'), task('Pedido: repeat that', 'Could you repeat that, please?')],
    translationPractice: [task('Você poderia me ajudar?', 'Could you help me?'), task('Posso sentar aqui?', 'Can I sit here?'), task('Você pode repetir, por favor?', 'Can you repeat that, please?')],
    productionTasks: [task('Escreva 8 pedidos com can/could.'), task('Escreva 5 pedidos de permissão.'), task('Crie 5 respostas positivas e 5 negativas com motivo.')],
    finalChecklist: [task('Usei verbo base depois de can/could?'), task('Inverteu Can/Could + subject?'), task('Usei could para mais educação?'), task('Incluí please quando natural?')],
    selfAssessment: [task('Consigo pedir ajuda?'), task('Consigo pedir permissão?'), task('Consigo responder pedidos?')],
    lessonRecap: ['Can e could fazem pedidos.', 'Could é mais educado.', 'Depois de can/could, verbo base.', 'Can I/Could I pedem permissão.'],
    nextLessonBridge: 'Agora você vai revisar object pronouns para deixar pedidos e respostas mais naturais.',
  }),

  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-022',
    order: 22,
    title: 'Object pronouns review and expansion',
    objectives: ['Revisar object pronouns: me, you, him, her, it, us, them.', 'Usar object pronouns depois de verbos e preposições.', 'Evitar repetição em pedidos, conselhos e mensagens.', 'Corrigir confusões entre subject e object pronouns.'],
    teacherOpening: 'Subject pronouns fazem a ação: I, he, she, they. Object pronouns recebem a ação: me, him, her, them. Diga: Can you help me? I called him. She sent it to us.',
    whyItMatters: 'Sem object pronouns, sua fala fica repetitiva e confusa. Eles aparecem em pedidos, convites, mensagens, conselhos e obrigações.',
    realLifeUseCases: ['Pedir ajuda: help me.', 'Falar de pessoas: call him/her.', 'Enviar algo: send it to me.', 'Convidar grupo: join us.', 'Falar de produtos: buy them.'],
    conceptExplanation: 'Use object pronouns depois de verbos: help me, call her, invite them. Use também depois de preposições: with me, for him, to us, about it.',
    mentalModel: { title: 'subject faz / object recebe', summary: 'I help him. She calls me. They invite us.', steps: ['I → me', 'he → him', 'she → her', 'we → us', 'they → them'] },
    stepByStep: [task('Identifique quem faz a ação.'), task('Identifique quem recebe a ação.'), task('Use subject para quem faz.'), task('Use object para quem recebe.'), task('Depois de preposição, use object pronoun.')],
    portugueseContrast: [task('Depois de preposição em inglês use me, não I: with me.'), task('Him = ele como objeto; her = ela como objeto.'), task('It substitui coisa/animal/ideia singular.'), task('Them substitui plural.')],
    guidedDiscovery: [task('Can you help Luis? → Can you help him?'), task('I invited Ana. → I invited her.'), task('Send the message to us. → Send it to us.'), task('Come with me, não come with I.')],
    guidedBeforeQuiz: [task('Complete: Can you help ___? (I)', 'me'), task('Complete: I called ___. (he)', 'him'), task('Complete: She invited ___. (we)', 'us')],
    grammarGoal: 'Usar pronomes objeto em comunicação real.',
    formationGuide: [task('After verb', 'Please help me.'), task('After verb', 'I called her yesterday.'), task('After preposition', 'Come with us.'), task('Thing/object', 'Can you send it to me?')],
    whenToUse: [task('Depois de verbos.'), task('Depois de preposições.'), task('Para evitar repetir nomes/coisas.'), task('Em pedidos e mensagens.')],
    whenNotToUse: [task('Não use object pronoun como sujeito: Me am tired errado.'), task('Não use I depois de with/to/for.'), task('Não confunda his com him.')],
    grammarTable: [
      { pattern: 'I → me', example: 'Can you help me?', translation: 'Você pode me ajudar?' },
      { pattern: 'he → him', example: 'I called him.', translation: 'Eu liguei para ele.' },
      { pattern: 'she → her', example: 'We invited her.', translation: 'Nós convidamos ela.' },
      { pattern: 'we → us', example: 'Join us.', translation: 'Junte-se a nós.' },
      { pattern: 'they → them', example: 'I bought them yesterday.', translation: 'Eu comprei eles ontem.' }
    ],
    teacherExamples: [
      { english: 'Could you send it to me?', translation: 'Você poderia enviar isso para mim?', why: 'It substitui objeto; me depois de to.' },
      { english: 'I think you should talk to her.', translation: 'Acho que você deveria falar com ela.', why: 'Her depois de preposição to.' },
      { english: 'Would you like to join us?', translation: 'Você gostaria de se juntar a nós?', why: 'Us depois de join.' }
    ],
    commonBrazilianMistakes: [mistake('Can you help I?', 'Can you help me?', 'Depois de verbo, use me.'), mistake('Come with I.', 'Come with me.', 'Depois de preposição, use object pronoun.'), mistake('I called he.', 'I called him.', 'He vira him como objeto.'), mistake('Send me it.', 'Send it to me.', 'No A2, prefira send it to me.')],
    controlledPractice: [task('I → ___', 'me'), task('he → ___', 'him'), task('she → ___', 'her'), task('we → ___', 'us'), task('they → ___', 'them')],
    errorCorrectionPractice: [task('Corrija: Help I.', 'Help me.'), task('Corrija: Talk to she.', 'Talk to her.'), task('Corrija: I invited they.', 'I invited them.')],
    transformationPractice: [task('Replace Ana: I invited Ana.', 'I invited her.'), task('Replace my brother: Call my brother.', 'Call him.'), task('Replace the documents: Send the documents to me.', 'Send them to me.')],
    translationPractice: [task('Você pode me ajudar?', 'Can you help me?'), task('Eu liguei para ele.', 'I called him.'), task('Fale com ela.', 'Talk to her.'), task('Junte-se a nós.', 'Join us.')],
    productionTasks: [task('Escreva 10 frases com object pronouns.'), task('Crie 5 pedidos com help me/send it to me.'), task('Crie 5 conselhos usando talk to him/her/them.')],
    finalChecklist: [task('O pronome está depois de verbo?'), task('Está depois de preposição?'), task('Usei me/him/her/us/them?'), task('Evitei help I / with I?')],
    selfAssessment: [task('Consigo usar me/him/her?'), task('Consigo usar us/them?'), task('Consigo evitar repetição?')],
    lessonRecap: ['Object pronouns recebem a ação.', 'Use depois de verbos e preposições.', 'Me/him/her/us/them são essenciais no A2.', 'Can you help me? é frase-chave.'],
    nextLessonBridge: 'Agora você vai aprender chunks comuns que conectam pedidos, respostas e problemas.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-019',
    order: 19,
    title: 'Common phrasal chunks A2',
    objectives: ['Aprender chunks comuns de comunicação A2.', 'Usar expressões prontas para pedir, responder, confirmar e resolver problemas.', 'Combinar chunks com can/could, should e have to.', 'Melhorar naturalidade em diálogos e mensagens.'],
    teacherOpening: 'Chunks são blocos prontos de fala. Em vez de montar palavra por palavra, você usa blocos como: Could you help me?, I’m not sure, No problem, Let me check, I’ll be there, That sounds good.',
    whyItMatters: 'Chunks aceleram sua fala e deixam o inglês mais natural em situações reais.',
    realLifeUseCases: ['Responder convite.', 'Pedir ajuda.', 'Ganhar tempo para pensar.', 'Confirmar informação.', 'Resolver problema simples.'],
    conceptExplanation: 'Memorize blocos úteis por função: pedir, confirmar, recusar, explicar, pedir repetição, sugerir. Depois troque partes pequenas.',
    mentalModel: { title: 'chunk = bloco pronto', summary: 'Use blocos prontos e personalize detalhes.', steps: ['Could you help me?', 'Let me check.', 'I’m not sure.', 'That sounds good.', 'Maybe another time.'] },
    stepByStep: [task('Escolha a função comunicativa.'), task('Use o chunk pronto.'), task('Troque detalhe se necessário.'), task('Pratique como frase inteira.'), task('Use em diálogo curto.')],
    portugueseContrast: [task('Let me check = deixa eu verificar.'), task('That sounds good = parece bom/legal.'), task('I’m not sure = não tenho certeza.'), task('No problem = sem problema.')],
    guidedDiscovery: [task('Could you help me? é pedido.'), task('Let me check ganha tempo.'), task('That sounds good aceita sugestão.'), task('Maybe another time recusa suavemente.')],
    guidedBeforeQuiz: [task('Could you help me?'), task('Let me check.'), task('I’m not sure.'), task('That sounds good.'), task('No problem.')],
    topicContext: 'Você vai ganhar naturalidade em comunicação cotidiana.',
    essentialWords: [vocab('Let me check', 'deixa eu verificar', 'Let me check my schedule.'), vocab('I’m not sure', 'não tenho certeza', 'I’m not sure about Friday.'), vocab('No problem', 'sem problema', 'No problem, we can meet later.'), vocab('That sounds good', 'parece bom/legal', 'That sounds good to me.'), vocab('I’ll be there', 'estarei lá', 'I’ll be there at 7.'), vocab('Can you help me?', 'você pode me ajudar?', 'Can you help me with this?'), vocab('Could you repeat that?', 'você poderia repetir?', 'Could you repeat that, please?'), vocab('Just a moment', 'só um momento', 'Just a moment, please.'), vocab('I have to go', 'tenho que ir', 'I have to go now.'), vocab('Maybe another time', 'talvez outra hora', 'Maybe another time, thanks.'), vocab('What should I do?', 'o que devo fazer?', 'What should I do now?'), vocab('I think so', 'acho que sim', 'I think so.'), vocab('I don’t think so', 'acho que não', 'I don’t think so.'), vocab('It depends', 'depende', 'It depends on the price.')],
    chunks: [{ chunk: 'Let me check my schedule', translation: 'deixa eu verificar minha agenda', example: 'Let me check my schedule first.' }, { chunk: 'That sounds good to me', translation: 'isso parece bom para mim', example: 'Sunday sounds good to me.' }, { chunk: 'Could you repeat that, please?', translation: 'você poderia repetir, por favor?', example: 'Sorry, could you repeat that, please?' }, { chunk: 'I have to go now', translation: 'tenho que ir agora', example: 'Sorry, I have to go now.' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Could you soa como bloco.', 'Let me pode soar lemi.', 'I’ll be there soa ail bi dher.'] },
    dangerousConfusions: [task('I think so = acho que sim; I don’t think so = acho que não.'), task('It depends precisa de on quando tiver complemento: depends on the price.'), task('Actually = na verdade, não atualmente.'), task('No problem não é sempre resposta para desculpa; também aceita pedidos.')],
    collocations: [task('check my schedule'), task('repeat that'), task('sounds good'), task('be there at'), task('depends on'), task('help me with')],
    miniDialogues: [{ title: 'Making a plan', lines: ['A: Are you free on Sunday?', 'B: I’m not sure. Let me check my schedule.', 'A: No problem.', 'B: Sunday afternoon sounds good to me. I’ll be there at 4.'], focus: 'Chunks para combinar plano.' }, { title: 'Asking for help', lines: ['A: Could you help me with this?', 'B: Sure. What do you need?', 'A: Could you repeat that part, please?', 'B: Of course.'], focus: 'Chunks de pedido.' }],
    examples: [ex('Let me check my schedule first.', 'Deixa eu verificar minha agenda primeiro.', 'Ganha tempo em conversa.'), ex('That sounds good to me.', 'Isso parece bom para mim.', 'Aceita uma sugestão.'), ex('It depends on the price.', 'Depende do preço.', 'Resposta natural com depends on.')],
    recognitionPractice: [task('Qual chunk significa “não tenho certeza”?', 'I’m not sure.'), task('Qual chunk pede repetição?', 'Could you repeat that, please?'), task('Qual chunk aceita sugestão?', 'That sounds good.')],
    usagePractice: [task('Complete: Let me check my ___.', 'schedule'), task('Complete: It depends ___ the price.', 'on'), task('Complete: That ___ good to me.', 'sounds')],
    productionTasks: [task('Escreva diálogo usando 8 chunks.'), task('Crie 5 respostas para convite usando chunks.'), task('Crie 5 pedidos de ajuda usando chunks.')],
    spacedReview: [task('Revise 5 chunks por dia.'), task('Grave todos os chunks como frases inteiras.')],
    selfAssessment: [task('Consigo usar chunks sem traduzir palavra por palavra?'), task('Consigo responder convites com chunks?'), task('Consigo pedir ajuda com naturalidade?')],
    lessonRecap: ['Chunks são blocos prontos.', 'Eles aceleram fala e escrita.', 'Use por função comunicativa.', 'Pratique como frase inteira.'],
    nextLessonBridge: 'Agora você vai ver advérbios de modo para explicar como ações acontecem.',
  }),

  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-024',
    order: 24,
    title: 'Adverbs of manner',
    objectives: ['Usar advérbios de modo para dizer como uma ação acontece.', 'Formar advérbios comuns com -ly.', 'Reconhecer irregular well.', 'Aplicar slowly, carefully, quickly, clearly, politely e well em comunicação.'],
    teacherOpening: 'Adverbs of manner respondem “como?”. Speak slowly. Drive carefully. Explain clearly. Ask politely. Good é adjetivo; well é advérbio: She speaks English well.',
    whyItMatters: 'Você usa advérbios para pedir que alguém fale devagar, explicar como fazer algo, dar conselhos e descrever ações.',
    realLifeUseCases: ['Pedir para alguém falar devagar.', 'Dar instrução de trabalho.', 'Descrever atendimento.', 'Dar conselho de segurança.', 'Falar de desempenho.'],
    conceptExplanation: 'Muitos advérbios vêm de adjective + ly: slow → slowly, careful → carefully, quick → quickly, clear → clearly, polite → politely. Irregular importante: good → well.',
    mentalModel: { title: 'verb + how?', summary: 'Depois da ação, diga como ela acontece.', steps: ['speak slowly', 'drive carefully', 'explain clearly', 'work quickly', 'speak well'] },
    stepByStep: [task('Identifique o verbo.'), task('Pergunte “como?”'), task('Escolha o advérbio.'), task('Coloque geralmente depois do verbo/objeto.'), task('Use well, não good, para ação.')],
    portugueseContrast: [task('Good descreve coisa/pessoa; well descreve ação.'), task('Slowly = devagar; slow pode ser adjetivo.'), task('Carefully = cuidadosamente/com cuidado.'), task('Politely = educadamente.')],
    guidedDiscovery: [task('Speak slowly = fale devagar.'), task('Drive carefully = dirija com cuidado.'), task('Explain clearly = explique claramente.'), task('She speaks well = ela fala bem.')],
    guidedBeforeQuiz: [task('Complete: Please speak ___.', 'slowly'), task('Complete: Drive ___.', 'carefully'), task('Corrija: She speaks good.', 'She speaks well.')],
    grammarGoal: 'Descrever como ações acontecem usando advérbios de modo.',
    formationGuide: [task('adjective + ly', 'slow → slowly'), task('adjective ending in y', 'easy → easily'), task('irregular', 'good → well'), task('placement', 'Please speak slowly.')],
    whenToUse: [task('Para descrever modo da ação.'), task('Em pedidos e instruções.'), task('Em conselhos.'), task('Em descrições de desempenho.')],
    whenNotToUse: [task('Não use well antes de substantivo como adjetivo.'), task('Não use good para descrever verbo.'), task('Não coloque -ly em well.')],
    grammarTable: [
      { pattern: 'slow → slowly', example: 'Could you speak slowly?', translation: 'Você poderia falar devagar?' },
      { pattern: 'careful → carefully', example: 'You should drive carefully.', translation: 'Você deveria dirigir com cuidado.' },
      { pattern: 'clear → clearly', example: 'Please explain it clearly.', translation: 'Por favor, explique claramente.' },
      { pattern: 'good → well', example: 'She writes well.', translation: 'Ela escreve bem.' }
    ],
    teacherExamples: [
      { english: 'Could you speak more slowly, please?', translation: 'Você poderia falar mais devagar, por favor?', why: 'Pedido educado + advérbio.' },
      { english: 'You should read the instructions carefully.', translation: 'Você deveria ler as instruções com cuidado.', why: 'Conselho + advérbio.' },
      { english: 'He works quickly, but he doesn’t work carefully.', translation: 'Ele trabalha rápido, mas não trabalha com cuidado.', why: 'Contraste com but.' }
    ],
    commonBrazilianMistakes: [mistake('She speaks English good.', 'She speaks English well.', 'Ação usa well.'), mistake('Drive careful.', 'Drive carefully.', 'Advérbio com -ly.'), mistake('Explain clear.', 'Explain clearly.', 'Clear vira clearly.'), mistake('Well job.', 'Good job.', 'Good descreve substantivo.')],
    controlledPractice: [task('slow → ___', 'slowly'), task('careful → ___', 'carefully'), task('quick → ___', 'quickly'), task('good → ___', 'well')],
    errorCorrectionPractice: [task('Corrija: Please speak slow.', 'Please speak slowly.'), task('Corrija: He works good.', 'He works well.'), task('Corrija: Read careful.', 'Read carefully.')],
    transformationPractice: [task('Pedido: speak / slow', 'Could you speak slowly?'), task('Conselho: drive / careful', 'You should drive carefully.'), task('Descrição: she / write / good', 'She writes well.')],
    translationPractice: [task('Fale devagar, por favor.', 'Speak slowly, please.'), task('Você deveria dirigir com cuidado.', 'You should drive carefully.'), task('Ela canta bem.', 'She sings well.')],
    productionTasks: [task('Escreva 8 frases com advérbios de modo.'), task('Crie 5 pedidos com slowly/clearly/politely.'), task('Crie 5 conselhos com carefully/well.')],
    finalChecklist: [task('Estou descrevendo uma ação?'), task('Usei advérbio, não adjetivo?'), task('Usei well para ação boa?'), task('Coloquei advérbio em posição natural?')],
    selfAssessment: [task('Consigo usar slowly/carefully?'), task('Consigo usar well corretamente?'), task('Consigo pedir que alguém fale claramente/devagar?')],
    lessonRecap: ['Adverbs of manner respondem como.', 'Muitos terminam em -ly.', 'Good vira well como advérbio.', 'São úteis em pedidos e conselhos.'],
    nextLessonBridge: 'Agora você vai fechar o A2.5 com conectores para organizar mensagens e explicações.',
  }),

  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-025',
    order: 25,
    title: 'Because / so / but / and review',
    objectives: ['Revisar conectores básicos de comunicação.', 'Usar because para motivo, so para consequência, but para contraste e and para soma.', 'Conectar pedidos, conselhos, obrigações e opiniões.', 'Evitar frases longas confusas.'],
    teacherOpening: 'Conectores fazem sua comunicação ficar lógica. Because explica motivo. So mostra resultado. But mostra contraste. And adiciona ideia. Exemplo: I’m tired, so I should rest. I want to go, but I have to work.',
    whyItMatters: 'Sem conectores, você fala frases soltas. Com eles, você explica problemas, pedidos, conselhos, recusas e obrigações com clareza.',
    realLifeUseCases: ['Explicar recusa de convite.', 'Justificar conselho.', 'Conectar obrigação e motivo.', 'Comparar opções.', 'Escrever mensagens mais claras.'],
    conceptExplanation: 'Use because para responder por quê. Use so para consequência. Use but para contraste. Use and para adicionar informação. No A2, prefira frases curtas e conectores simples.',
    mentalModel: { title: 'connector = logic', summary: 'Cada conector cria uma relação lógica.', steps: ['because = reason', 'so = result', 'but = contrast', 'and = addition'] },
    stepByStep: [task('Decida a relação entre ideias.'), task('Motivo: because.'), task('Resultado: so.'), task('Contraste: but.'), task('Adição: and.'), task('Revise se a frase ficou clara.')],
    portugueseContrast: [task('Because = porque de motivo.'), task('So = então/por isso.'), task('But = mas.'), task('And = e.')],
    guidedDiscovery: [task('I’m tired because I worked a lot.'), task('I’m tired, so I should rest.'), task('I want to go, but I have to work.'), task('I need my notebook and my ID card.')],
    guidedBeforeQuiz: [task('Complete: I’m tired ___ I worked a lot.', 'because'), task('Complete: I’m tired, ___ I should rest.', 'so'), task('Complete: I want to go, ___ I’m busy.', 'but')],
    grammarGoal: 'Conectar ideias simples com lógica clara em comunicação A2.',
    formationGuide: [task('Reason', 'I can’t go because I have to work.'), task('Result', 'I have to work, so I can’t go.'), task('Contrast', 'I want to go, but I’m busy.'), task('Addition', 'Bring your notebook and your ID card.')],
    whenToUse: [task('Because para explicar motivo.'), task('So para consequência.'), task('But para contraste.'), task('And para adicionar informação.')],
    whenNotToUse: [task('Não use because e so juntos na mesma relação simples.'), task('Não crie frase gigante com muitos and.'), task('Não use but quando não há contraste.')],
    grammarTable: [
      { pattern: 'because = reason', example: 'I can’t come because I’m busy.', translation: 'Não posso ir porque estou ocupado.' },
      { pattern: 'so = result', example: 'I’m busy, so I can’t come.', translation: 'Estou ocupado, então não posso ir.' },
      { pattern: 'but = contrast', example: 'I want to come, but I have to work.', translation: 'Quero ir, mas tenho que trabalhar.' },
      { pattern: 'and = addition', example: 'Please bring your notebook and your ID card.', translation: 'Por favor, traga seu caderno e seu documento.' }
    ],
    teacherExamples: [
      { english: 'I’m worried about the test, so I should study tonight.', translation: 'Estou preocupado com a prova, então deveria estudar hoje à noite.', why: 'Sentimento → consequência.' },
      { english: 'I would like to join you, but I have to work.', translation: 'Gostaria de ir com vocês, mas tenho que trabalhar.', why: 'Desejo + contraste.' },
      { english: 'Could you speak slowly because I’m still learning?', translation: 'Você poderia falar devagar porque ainda estou aprendendo?', why: 'Pedido + motivo.' }
    ],
    commonBrazilianMistakes: [mistake('Because I’m tired, so I will rest.', 'I’m tired, so I will rest. / I will rest because I’m tired.', 'Evite because e so duplicando a mesma lógica.'), mistake('I want go but I can.', 'I want to go, but I can’t.', 'Verbo e negativa precisam estar completos.'), mistake('I have to work because I can’t go.', 'I can’t go because I have to work.', 'Motivo correto vem depois de because.')],
    guidedPractice: [{ question: 'Qual frase conecta ideias corretamente com so?', answer: 'I’m worried about the test, so I should study tonight.', evidence: '', explanation: 'So indica consequência: preocupação → estudar.', options: ['I’m worried about the test, so I should study tonight.', 'I’m worried about the test, because I should study.', 'I’m worried about the test, but I should study tonight.'] }, { question: 'Qual alternativa usa but para contraste?', answer: 'I would like to join you, but I have to work tonight.', evidence: '', explanation: 'But conecta ideias opostas: desejo vs obrigação.', options: ['I would like to join you, but I have to work tonight.', 'I would like to join you, so I have to work tonight.', 'I would like to join you, because I have to work tonight.'] }],
    controlledPractice: [task('Motivo: ___', 'because'), task('Resultado: ___', 'so'), task('Contraste: ___', 'but'), task('Adição: ___', 'and')],
    errorCorrectionPractice: [task('Corrija: I’m tired because I will sleep.', 'I will sleep because I’m tired. / I’m tired, so I will sleep.'), task('Corrija: I want to go and I am busy.', 'I want to go, but I am busy.'), task('Corrija: Bring notebook but ID card.', 'Bring your notebook and your ID card.')],
    transformationPractice: [task('Use because: I can’t go. I have to work.', 'I can’t go because I have to work.'), task('Use so: I am tired. I should rest.', 'I am tired, so I should rest.'), task('Use but: I want to go. I am busy.', 'I want to go, but I am busy.')],
    translationPractice: [task('Não posso ir porque tenho que trabalhar.', 'I can’t go because I have to work.'), task('Estou cansado, então devo descansar.', 'I’m tired, so I should rest.'), task('Quero ir, mas estou ocupado.', 'I want to go, but I’m busy.')],
    productionTasks: [task('Escreva 5 frases com because.'), task('Escreva 5 frases com so.'), task('Escreva 5 frases com but.'), task('Escreva uma mensagem curta usando because, so, but e and.')],
    finalChecklist: [task('A relação é motivo, resultado, contraste ou soma?'), task('Usei o conector certo?'), task('A frase está curta e clara?'), task('Evitei because + so duplicado?')],
    selfAssessment: [task('Consigo explicar motivo?'), task('Consigo mostrar consequência?'), task('Consigo contrastar ideias?'), task('Consigo escrever mensagem clara?')],
    lessonRecap: ['Because explica motivo.', 'So mostra consequência.', 'But mostra contraste.', 'And adiciona informação.'],
    nextLessonBridge: 'A2.5 está fechado. O próximo pacote correto será A2.6 Reviews and checkpoints.',
  }),
]);

export const A2_DEEP_COMMUNICATION_TASKS_PART4_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART4.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART4.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART4.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART4.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART4.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_COMMUNICATION_TASKS_PART4.filter((lesson) => lesson.pillar === 'writing')),
});
