import { createGrammarLesson, createVocabularyLesson, createReadingLesson, createListeningLesson, createSpeakingLesson, createWritingLesson } from '../../../schemas/index.js';

const level = 'A2';
const status = 'ready';
const common = { level, status, estimatedMinutes: 60, tags: ['a2-3', 'plans-and-now', 'going-to', 'household-problems', 'closing', 'deep-approved-target'] };

function task(instruction, note = '', expected = '') { return { instruction, note, expected }; }
function vocab(word, meaning, example = '', note = '') { return { word, meaning, example, note }; }
function phrase(text, translation = '', note = '') { return { text, translation, note }; }
function mistake(wrong, right, why = '') { return { wrong, right, why }; }
function q(question, answer, evidence = '', explanation = '', options = []) { return { question, answer, evidence, explanation, options }; }
function ex(text, translation, why = '', warning = '') { return { text, translation, why, warning }; }

export const A2_DEEP_PLANS_AND_NOW_PART4 = Object.freeze([
  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-011',
    order: 11,
    title: 'Future with going to — plans',
    objectives: ['Formar futuro com going to para planos.', 'Falar de planos de fim de semana, estudo, casa e tecnologia.', 'Criar perguntas e negativas com be going to.', 'Evitar erros como I going to e I am go to.'],
    teacherOpening: 'Agora você vai falar de planos futuros com going to. Use be + going to + base verb: I am going to study tonight. She is going to call support. We are going to clean the house. O be muda com o sujeito; o verbo principal fica na base.',
    whyItMatters: 'A2 precisa permitir que você fale do próximo passo: o que vai fazer no fim de semana, como vai resolver um problema, que plano de estudo vai seguir e com quem vai falar.',
    realLifeUseCases: ['Falar de planos de fim de semana.', 'Combinar horário com amigo.', 'Dizer o que vai estudar.', 'Explicar como vai resolver problema de casa.', 'Planejar suporte para telefone/app.'],
    conceptExplanation: 'Use subject + am/is/are + going to + base verb. I am going to study. He is going to fix the sink. They are going to visit us. Para perguntas: Are you going to study? Para negativas: I am not going to travel.',
    mentalModel: { title: 'be + going to + verbo base', summary: 'O be concorda com o sujeito; o verbo depois de to fica base.', steps: ['I am going to study.', 'She is going to call.', 'They are going to clean.'] },
    stepByStep: [task('Escolha o sujeito.'), task('Use am/is/are.'), task('Adicione going to.'), task('Use verbo base.'), task('Complete com tempo/lugar.'), task('Revise se não esqueceu o be.')],
    portugueseContrast: [task('Não diga I going to study.'), task('Não diga I am going to studying.'), task('Depois de going to, use verbo base.'), task('Going to fala de plano/intenção futura.')],
    guidedDiscovery: [task('Am/is/are carrega o sujeito.'), task('Going to mostra plano.'), task('Study/call/fix ficam na base.')],
    guidedBeforeQuiz: [task('Complete: I ___ going to study.', 'am'), task('Complete: She is going to ___. (call)', 'call'), task('Corrija: I going to clean.', 'I am going to clean.')],
    grammarGoal: 'Falar de planos futuros com be going to + verbo base.',
    formationGuide: [task('Affirmative', 'I am going to study tonight.'), task('Negative', 'She is not going to travel.'), task('Yes/no question', 'Are you going to work tomorrow?'), task('Wh-question', 'What are you going to do this weekend?')],
    whenToUse: [task('Planos e intenções futuras.'), task('Decisões já pensadas.'), task('Combinar fim de semana, estudo, casa e suporte.')],
    whenNotToUse: [task('Não use para rotina geral.'), task('Não use com verbo em -ing depois de to.'), task('Não esqueça am/is/are.')],
    grammarTable: [
      { pattern: 'I am going to + verb', example: 'I am going to study tonight.', translation: 'Vou estudar hoje à noite.' },
      { pattern: 'She is going to + verb', example: 'She is going to call support.', translation: 'Ela vai ligar para o suporte.' },
      { pattern: 'We are going to + verb', example: 'We are going to clean the house.', translation: 'Nós vamos limpar a casa.' },
      { pattern: 'Question', example: 'What are you going to do?', translation: 'O que você vai fazer?' }
    ],
    teacherExamples: [
      { english: 'I am going to review my mistakes tonight.', translation: 'Vou revisar meus erros hoje à noite.', why: 'Plano de estudo.' },
      { english: 'He is going to fix the Wi-Fi tomorrow.', translation: 'Ele vai consertar o Wi-Fi amanhã.', why: 'Plano para resolver problema.' },
      { english: 'We are going to visit my family this weekend.', translation: 'Vamos visitar minha família este fim de semana.', why: 'Plano de fim de semana.' }
    ],
    commonBrazilianMistakes: [mistake('I going to study.', 'I am going to study.', 'Falta be.'), mistake('She is going to studying.', 'She is going to study.', 'Depois de to, verbo base.'), mistake('They is going to clean.', 'They are going to clean.', 'They usa are.'), mistake('What you are going to do?', 'What are you going to do?', 'Pergunta inverte be e sujeito.')],
    controlledPractice: [task('Complete: I ___ going to call support.', 'am'), task('Complete: He ___ going to fix it.', 'is'), task('Complete: They ___ going to visit us.', 'are'), task('Complete: What are you going to ___?', 'do')],
    errorCorrectionPractice: [task('Corrija: I going to travel.', 'I am going to travel.'), task('Corrija: She is going to calls.', 'She is going to call.'), task('Corrija: Are you going to studying?', 'Are you going to study?')],
    transformationPractice: [task('Transforme em plano: I study tonight.', 'I am going to study tonight.'), task('Transforme em pergunta: You are going to travel.', 'Are you going to travel?'), task('Transforme em negativa: She is going to work.', 'She is not going to work.')],
    translationPractice: [task('Vou estudar hoje à noite.', 'I am going to study tonight.'), task('Ela vai ligar para o suporte.', 'She is going to call support.'), task('O que você vai fazer no fim de semana?', 'What are you going to do this weekend?')],
    productionTasks: [task('Escreva 8 planos com going to.'), task('Crie 5 perguntas sobre planos de fim de semana.'), task('Fale 60 segundos sobre seus planos de estudo usando going to.')],
    finalChecklist: [task('Usei am/is/are?'), task('Usei going to?'), task('Depois de to, usei verbo base?'), task('Meu contexto é futuro/plano?')],
    selfAssessment: [task('Consigo falar de planos?'), task('Consigo fazer perguntas com going to?'), task('Consigo evitar I going to?')],
    lessonRecap: ['Going to fala de planos futuros.', 'A forma é be + going to + verbo base.', 'Perguntas invertem o be.', 'Planos de estudo, casa e fim de semana ficam claros com essa estrutura.'],
    nextLessonBridge: 'Na próxima gramática, você vai usar going to para previsões com evidência.',
  }),

  createGrammarLesson({
    ...common,
    id: 'A2-GRAMMAR-012',
    order: 12,
    title: 'Future with going to — predictions from evidence',
    objectives: ['Usar going to para previsões baseadas em evidência.', 'Diferenciar plano e previsão visual/evidente.', 'Criar frases com look, because e evidence.', 'Aplicar previsões a clima, casa, telefone e situações do dia a dia.'],
    teacherOpening: 'Going to também serve para previsões quando existe evidência agora. Look at those clouds. It is going to rain. The battery is at 1%. The phone is going to turn off. A previsão não é chute; há sinal visível.',
    whyItMatters: 'Você precisa prever consequências simples: vai chover, o celular vai desligar, a pia vai vazar, a reunião vai atrasar. Isso deixa sua fala mais natural.',
    realLifeUseCases: ['Prever chuva olhando o céu.', 'Dizer que a bateria vai acabar.', 'Avisar que algo vai quebrar/vazar.', 'Falar que alguém vai se atrasar.', 'Explicar evidência de um problema.'],
    conceptExplanation: 'Use be going to + base verb para previsão com evidência atual. It is going to rain because the sky is dark. The app is going to crash because it is freezing. The sink is going to leak again because the pipe is loose.',
    mentalModel: { title: 'evidence now → future result', summary: 'Existe sinal agora; você prevê o resultado.', steps: ['dark clouds → rain', 'low battery → phone turns off', 'loose pipe → leak'] },
    stepByStep: [task('Observe a evidência.'), task('Diga a previsão com be going to.'), task('Use verbo base.'), task('Explique com because se necessário.'), task('Revise am/is/are.')],
    portugueseContrast: [task('Em português “vai chover” pode ser plano? não. Em inglês, going to também faz previsão.'), task('Use It is going to rain, não It going to rain.'), task('Because conecta evidência.')],
    guidedDiscovery: [task('Look! chama atenção para evidência.'), task('Because explica motivo.'), task('Going to indica resultado provável.')],
    guidedBeforeQuiz: [task('Complete: It ___ going to rain.', 'is'), task('Complete: The phone is going to ___. (turn off)', 'turn off'), task('Corrija: It going to break.', 'It is going to break.')],
    grammarGoal: 'Fazer previsões simples com going to a partir de evidência atual.',
    formationGuide: [task('Evidence + prediction', 'The sky is dark. It is going to rain.'), task('Device evidence', 'The battery is low. The phone is going to turn off.'), task('Household evidence', 'The pipe is loose. It is going to leak.')],
    whenToUse: [task('Há evidência no presente.'), task('Você prevê consequência próxima.'), task('Clima, telefone, casa, atraso e problemas visíveis.')],
    whenNotToUse: [task('Não use como chute sem evidência quando quiser ser preciso.'), task('Não confunda com plano intencional.'), task('Não esqueça be.')],
    grammarTable: [
      { pattern: 'It is going to rain', example: 'Look at the clouds. It is going to rain.', translation: 'Olhe as nuvens. Vai chover.' },
      { pattern: 'The phone is going to turn off', example: 'The battery is at 1%. The phone is going to turn off.', translation: 'A bateria está em 1%. O celular vai desligar.' },
      { pattern: 'The sink is going to leak', example: 'The pipe is loose. The sink is going to leak.', translation: 'O cano está solto. A pia vai vazar.' }
    ],
    teacherExamples: [
      { english: 'The app is freezing again. It is going to crash.', translation: 'O app está travando de novo. Ele vai fechar/travar.', why: 'Evidência técnica.' },
      { english: 'The sky is very dark. It is going to rain soon.', translation: 'O céu está muito escuro. Vai chover em breve.', why: 'Evidência visual.' },
      { english: 'The shelf is not stable. It is going to fall.', translation: 'A prateleira não está firme. Ela vai cair.', why: 'Evidência física.' }
    ],
    commonBrazilianMistakes: [mistake('It going to rain.', 'It is going to rain.', 'Falta is.'), mistake('The phone is going to turns off.', 'The phone is going to turn off.', 'Depois de to, verbo base.'), mistake('She is going to late.', 'She is going to be late.', 'Late é adjetivo; precisa be.')],
    controlledPractice: [task('Complete: The sky is dark. It ___ going to rain.', 'is'), task('Complete: The battery is low. The phone is going to ___.', 'turn off'), task('Complete: The shelf is unstable. It is going to ___.', 'fall')],
    errorCorrectionPractice: [task('Corrija: It going to rain.', 'It is going to rain.'), task('Corrija: The app is going to crashes.', 'The app is going to crash.'), task('Corrija: He is going to late.', 'He is going to be late.')],
    transformationPractice: [task('Crie previsão: dark clouds → rain', 'It is going to rain.'), task('Crie previsão: low battery → turn off', 'The phone is going to turn off.'), task('Crie previsão: loose pipe → leak', 'The pipe is going to leak.')],
    translationPractice: [task('Vai chover.', 'It is going to rain.'), task('O celular vai desligar.', 'The phone is going to turn off.'), task('A pia vai vazar.', 'The sink is going to leak.')],
    productionTasks: [task('Escreva 8 previsões com evidência.'), task('Crie 4 frases com because.'), task('Fale sobre 3 problemas visíveis em casa/telefone usando going to.')],
    finalChecklist: [task('Existe evidência atual?'), task('Usei be going to?'), task('Depois de to, verbo base?'), task('Expliquei com because quando útil?')],
    selfAssessment: [task('Consigo usar going to para previsão?'), task('Consigo explicar evidência?'), task('Consigo diferenciar plano e previsão?')],
    lessonRecap: ['Going to também faz previsões com evidência.', 'Evidência agora aponta resultado futuro.', 'Because ajuda a justificar.', 'Use be + going to + verbo base.'],
    nextLessonBridge: 'Agora você vai aprender problemas de casa para aplicar planos e previsões.',
  }),

  createVocabularyLesson({
    ...common,
    id: 'A2-VOCABULARY-012',
    order: 12,
    title: 'Household problems',
    objectives: ['Aprender vocabulário de problemas domésticos.', 'Explicar problemas simples em casa.', 'Falar de consertos, vazamentos, luz, porta e limpeza.', 'Usar going to para planos de solução.'],
    teacherOpening: 'Household problems fecha o vocabulário do A2.3. Você vai aprender leak, sink, pipe, light, door, key, window, broken, dirty, clean, repair, fix, call a technician, electricity e water.',
    whyItMatters: 'Problemas em casa são muito comuns: pia vazando, luz queimada, porta quebrada, internet ruim, janela aberta. Você precisa explicar o problema e dizer o que vai fazer.',
    realLifeUseCases: ['Falar que a pia está vazando.', 'Pedir conserto.', 'Dizer que vai limpar/arrumar.', 'Explicar problema em hotel/casa.', 'Combinar visita de técnico.'],
    conceptExplanation: 'Organize por área: water, electricity, furniture, cleaning e repair. Use The sink is leaking. The light is not working. The door is broken. I am going to call a technician.',
    mentalModel: { title: 'house problem = object + issue + plan', summary: 'Diga objeto, problema e solução.', steps: ['sink → leaking', 'light → not working', 'door → broken', 'plan → call/fix/clean'] },
    stepByStep: [task('Nomeie o objeto.'), task('Diga o problema.'), task('Diga se está acontecendo agora.'), task('Diga o plano com going to.'), task('Peça ajuda se necessário.')],
    portugueseContrast: [task('Leak = vazamento/vazar.'), task('Sink = pia.'), task('Pipe = cano.'), task('Fix/repair = consertar.')],
    guidedDiscovery: [task('Sink é objeto.'), task('Leaking é problema acontecendo.'), task('Technician é pessoa que resolve.'), task('Going to mostra plano de solução.')],
    guidedBeforeQuiz: [task('The sink is leaking.'), task('The light is not working.'), task('The door is broken.'), task('I am going to call a technician.')],
    topicContext: 'Você vai explicar problemas simples em casa e planos para resolver.',
    essentialWords: [vocab('leak', 'vazar/vazamento', 'The sink is leaking.'), vocab('sink', 'pia', 'The sink is dirty.'), vocab('pipe', 'cano', 'The pipe is loose.'), vocab('light', 'luz', 'The light is not working.'), vocab('door', 'porta', 'The door is broken.'), vocab('key', 'chave', 'I lost my key.'), vocab('window', 'janela', 'The window is open.'), vocab('broken', 'quebrado', 'The chair is broken.'), vocab('dirty', 'sujo', 'The kitchen is dirty.'), vocab('clean', 'limpar/limpo', 'I am going to clean the kitchen.'), vocab('repair', 'consertar', 'We need to repair the door.'), vocab('fix', 'consertar', 'I am going to fix it.'), vocab('technician', 'técnico', 'I am going to call a technician.'), vocab('electricity', 'eletricidade', 'There is no electricity.'), vocab('water', 'água', 'There is no water.')],
    chunks: [{ chunk: 'the sink is leaking', translation: 'a pia está vazando', example: 'The sink is leaking.' }, { chunk: 'the light is not working', translation: 'a luz não está funcionando', example: 'The light is not working.' }, { chunk: 'call a technician', translation: 'chamar um técnico', example: 'I am going to call a technician.' }, { chunk: 'fix the problem', translation: 'resolver/consertar o problema', example: 'We are going to fix the problem.' }],
    pronunciationFocus: { title: 'Foco sonoro', tips: ['Leak soa como liik.', 'Sink tem som nasal final.', 'Technician tem stress em NI: tech-NI-cian.'] },
    dangerousConfusions: [task('Sink = pia; think = pensar.'), task('Light pode ser luz ou leve pelo contexto.'), task('Fix é mais comum em fala; repair é um pouco mais formal.'), task('There is no water = não há água.')],
    collocations: [task('the sink is leaking'), task('the light is not working'), task('the door is broken'), task('call a technician'), task('fix the problem'), task('clean the kitchen')],
    miniDialogues: [{ title: 'House problem', lines: ['A: Áudio da aula — what is the problem?', 'B: The sink is leaking.', 'A: Are you going to fix it?', 'B: No. I am going to call a technician.'], focus: 'Problema + plano.' }],
    examples: [ex('The pipe is loose, so the sink is going to leak again.', 'O cano está solto, então a pia vai vazar de novo.', 'Previsão com evidência.'), ex('The light is not working. I am going to buy a new one.', 'A luz não está funcionando. Vou comprar uma nova.', 'Problema + plano.'), ex('The kitchen is dirty, so we are going to clean it today.', 'A cozinha está suja, então vamos limpá-la hoje.', 'Plano doméstico.')],
    recognitionPractice: [{ question: 'Household problems — qual vocabulário desta aula significa "vazar/vazamento"?', options: ['leak', 'sink', 'pipe'], answer: 'leak', explanation: 'leak = vazar/vazamento; vocabulário trabalhado nesta aula de Household problems.' }, task('Qual palavra é pia?', 'sink'), task('Qual palavra é cano?', 'pipe'), task('Qual expressão é chamar técnico?', 'call a technician')],
    usagePractice: [task('Complete: The sink is ___.', 'leaking'), task('Complete: The light is not ___.', 'working'), task('Complete: I am going to call a ___.', 'technician')],
    productionTasks: [task('Escreva 6 frases sobre problemas em casa.'), task('Crie 3 planos com going to para resolver problemas.'), task('Crie um diálogo sobre pia vazando ou luz quebrada.')],
    spacedReview: [task('Revise sink/pipe/leak/technician amanhã.'), task('Crie 3 frases com fix/call/clean.')],
    selfAssessment: [task('Consigo explicar problema doméstico?'), task('Consigo dizer plano para resolver?'), task('Consigo usar going to com casa?')],
    lessonRecap: ['Household problems combinam objeto, problema e solução.', 'Leak/sink/pipe são essenciais.', 'Going to ajuda a falar do plano.', 'Predictions usam evidência do problema.'],
    nextLessonBridge: 'Na Reading, você vai ler um plano de fim de semana usando going to.',
  }),

  createReadingLesson({
    ...common,
    id: 'A2-READING-011',
    order: 11,
    title: 'A weekend plan with going to',
    objectives: ['Ler um texto curto sobre planos de fim de semana.', 'Identificar planos, horários, pessoas e motivos.', 'Reconhecer going to para plano e previsão.', 'Responder com evidência textual.'],
    teacherOpening: 'Nesta leitura, você vai ler um plano de fim de semana. O objetivo é identificar o que a pessoa vai fazer, quando, com quem e por quê. Você também vai ver going to para planos e previsões com evidência.',
    whyItMatters: 'Planos de fim de semana são conversa real. Você precisa entender convites, horários, tarefas, problemas de casa e planos de estudo.',
    realLifeUseCases: ['Ler mensagem sobre fim de semana.', 'Entender plano de estudo e lazer.', 'Identificar tarefa doméstica.', 'Responder convite.', 'Separar plano e previsão.'],
    conceptExplanation: 'Procure be going to + verb para planos. Procure because para motivo e time expressions como on Saturday, in the morning, after lunch, at night.',
    mentalModel: { title: 'weekend plan = day + action + reason', summary: 'Leia dia, ação e motivo.', steps: ['Saturday/Sunday', 'going to + verb', 'with whom', 'why'] },
    stepByStep: [task('Leia para achar o plano geral.'), task('Marque Saturday/Sunday.'), task('Marque going to + verb.'), task('Procure pessoas/lugares.'), task('Responda com evidência.')],
    portugueseContrast: [task('Weekend = fim de semana.'), task('On Saturday/Sunday usa on.'), task('At night = à noite.'), task('After lunch = depois do almoço.')],
    guidedDiscovery: [task('I am going to clean mostra plano.'), task('The sky is dark. It is going to rain mostra previsão.'), task('Because explica motivo.')],
    guidedBeforeQuiz: [task('Procure going to.'), task('Procure Saturday.'), task('Procure Sunday.'), task('Procure because.')],
    readingPurpose: 'Entender planos de fim de semana com going to.',
    preReadingVocabulary: [vocab('weekend', 'fim de semana'), vocab('clean', 'limpar'), vocab('visit', 'visitar'), vocab('technician', 'técnico'), vocab('rain', 'chover'), vocab('plan', 'plano')],
    readingStrategy: [task('Sublinhe going to + verb.'), task('Separe planos de sábado e domingo.'), task('Procure evidência de previsão.'), task('Use evidência textual.')],
    mainText: `This weekend, I am going to stay home because the sink is leaking. On Saturday morning, I am going to call a technician. After lunch, I am going to clean the kitchen and review English vocabulary. On Sunday, I am going to visit my sister if it doesn't rain. The sky is very dark now, so I think it is going to rain tonight.`,
    firstReadTask: task('Qual é o assunto geral?', 'Planos de fim de semana e um problema em casa.'),
    secondReadTasks: [task('Por que vai ficar em casa?', 'because the sink is leaking'), task('O que vai fazer sábado de manhã?', 'call a technician'), task('O que vai revisar?', 'English vocabulary'), task('Quem vai visitar domingo?', 'sister')],
    evidenceQuestions: [q('Why is the person going to stay home?', 'because the sink is leaking', 'because the sink is leaking', '', ['sink is leaking','phone is broken','meeting canceled']), q('What is the person going to do on Saturday morning?', 'call a technician', 'On Saturday morning, I am going to call a technician.', '', ['call a technician','visit sister','buy a phone']), q('What is the person going to review?', 'English vocabulary', 'review English vocabulary', '', ['English vocabulary','phone password','restaurant menu']), q('Who is the person going to visit on Sunday?', 'sister', 'I am going to visit my sister', '', ['sister','teacher','technician']), q('Why does the person think it is going to rain?', 'the sky is very dark', 'The sky is very dark now', '', ['sky is dark','battery is low','sink is leaking'])],
    contextVocabularyTasks: [task('If it doesn’t rain cria condição.'), task('Going to stay home é plano.'), task('Going to rain é previsão com evidência.')],
    guidedSummary: task('Complete: The person is going to stay home because the ___ is leaking. On Saturday, they are going to call a ___ and review English ___.', '', 'sink / technician / vocabulary'),
    connectedProduction: task('Escreva 4 frases sobre seus planos de fim de semana.'),
    selfAssessment: [task('Consigo identificar planos?'), task('Consigo separar sábado/domingo?'), task('Consigo diferenciar plano e previsão?')],
    lessonRecap: ['Weekend plans usam going to.', 'On Saturday/Sunday localiza o plano.', 'Because explica motivo.', 'Going to também faz previsão com evidência.'],
    nextLessonBridge: 'No Listening, você vai ouvir pessoas combinando planos de fim de semana.',
  }),

  createListeningLesson({
    ...common,
    id: 'A2-LISTENING-011',
    order: 11,
    title: 'Making plans for the weekend',
    objectives: ['Ouvir conversa sobre planos de fim de semana.', 'Identificar convite, resposta, horário e plano.', 'Reconhecer going to em fala natural.', 'Praticar dictation e shadowing de planos.'],
    teacherOpening: 'Nesta escuta, você vai ouvir pessoas combinando o fim de semana. Primeiro descubra o plano principal. Depois, ouça dia, horário, lugar e motivo.',
    whyItMatters: 'Combinar planos é uma das funções mais úteis do A2. Você precisa entender convites e responder se pode ou não pode.',
    realLifeUseCases: ['Combinar sair no fim de semana.', 'Recusar por causa de tarefa de casa.', 'Marcar horário.', 'Falar de previsão de chuva.', 'Planejar estudo e lazer.'],
    conceptExplanation: 'Ouça blocos como What are you going to do? I am going to..., Are you going to...? Let’s meet at..., I can’t because....',
    mentalModel: { title: 'weekend listening = invite + plan + time', summary: 'Ouça convite, plano e horário.', steps: ['question', 'plan', 'reason', 'time/place'] },
    stepByStep: [task('Primeira escuta: plano geral.'), task('Segunda escuta: horário/lugar.'), task('Terceira etapa: motivo/condição.'), task('Leia transcript.'), task('Faça dictation.'), task('Faça shadowing.')],
    portugueseContrast: [task('What are you going to do? = o que você vai fazer?'), task('Let’s meet = vamos nos encontrar.'), task('I can’t because... = não posso porque...')],
    guidedDiscovery: [task('Going to marca plano.'), task('Because explica motivo.'), task('At 4 marca horário.')],
    guidedBeforeQuiz: [task('Primeira escuta: eles vão se encontrar?'), task('Segunda escuta: quando?')],
    listeningPreparation: [task('Não leia transcript antes da primeira escuta.'), task('Prepare: weekend, going to, meet, clean, rain, at four.'), task('Objetivo: plano + horário + motivo.')],
    keyWordsToHear: [vocab('weekend','fim de semana'), vocab('going to','vai'), vocab('meet','encontrar'), vocab('clean','limpar'), vocab('rain','chover'), vocab('at four','às quatro')],
    audioScript: `A: What are you going to do this weekend?
B: On Saturday, I am going to clean the kitchen. The sink is leaking.
A: Are you going to call a technician?
B: Yes, I am. What about Sunday?
A: I am going to visit the park if it doesn't rain.
B: Great. Let's meet at four.
A: Okay. See you then.`,
    firstListenTasks: [task('Sem transcript: há plano para sábado?', 'yes'), task('Sem transcript: há problema em casa?', 'yes')],
    secondListenTasks: [task('O que B vai fazer no sábado?', 'clean the kitchen'), task('Qual problema?', 'sink is leaking'), task('O que A vai fazer no domingo?', 'visit the park if it doesn’t rain'), task('Que horas vão se encontrar?', 'at four')],
    transcript: `A: What are you going to do this weekend?
B: On Saturday, I am going to clean the kitchen. The sink is leaking.
A: Are you going to call a technician?
B: Yes, I am. What about Sunday?
A: I am going to visit the park if it doesn't rain.
B: Great. Let's meet at four.
A: Okay. See you then.`,
    vocabulary: [vocab('what about Sunday?', 'e domingo?'), vocab('let’s meet', 'vamos nos encontrar'), vocab('see you then', 'te vejo então')],
    shadowing: [task('What are you going to do this weekend?'), task('I am going to clean the kitchen.'), task('Are you going to call a technician?'), task('I am going to visit the park.'), task('Let’s meet at four.')],
    dictationTasks: [task('Digite: What are you going to do this weekend?', 'What are you going to do this weekend?'), task('Digite: I am going to clean the kitchen.', 'I am going to clean the kitchen.'), task('Digite: Let’s meet at four.', 'Let’s meet at four.')],
    pronunciationChunks: [task('going to do', 'Em fala natural pode soar reduzido, mas pratique claro.'), task('let’s meet at', 'Convite + horário.'), task('if it doesn’t rain', 'Condição.')],
    listeningComprehension: [q('What is B going to do on Saturday?', 'clean the kitchen', 'I am going to clean the kitchen.', '', ['clean kitchen','visit park','study English']), q('Making plans for the weekend — What is the problem?', 'the sink is leaking', 'The sink is leaking.', '', ['sink leaking','phone broken','door broken']), q('What is A going to do on Sunday?', 'visit the park', 'I am going to visit the park', '', ['visit park','call technician','clean kitchen']), q('When are they going to meet?', 'at four', 'Let’s meet at four.', '', ['at four','at three','after lunch'])],
    oralProduction: task('Pratique convite e resposta: What are you going to do this weekend? I am going to...'),
    selfAssessment: [task('Consegui ouvir planos?'), task('Consegui ouvir horário?'), task('Consigo repetir perguntas com going to?')],
    lessonRecap: ['Weekend listening foca plano, motivo e horário.', 'Going to aparece em perguntas e respostas.', 'Let’s meet combina planos.', 'If it doesn’t rain cria condição simples.'],
    nextLessonBridge: 'No Speaking, você vai criar seus próprios planos de fim de semana.',
  }),

  createSpeakingLesson({
    ...common,
    id: 'A2-SPEAKING-012',
    order: 12,
    title: 'Make weekend plans',
    objectives: ['Falar sobre planos de fim de semana.', 'Fazer perguntas com going to.', 'Combinar horário, lugar e condição simples.', 'Gravar diálogo curto de planos.'],
    teacherOpening: 'Agora você vai falar de planos de fim de semana. Use: What are you going to do this weekend? I am going to visit my family. Are you going to study? Let’s meet at four.',
    whyItMatters: 'Falar de planos é comunicação real. Você combina encontro, estudo, tarefas de casa e lazer usando estruturas simples e úteis.',
    realLifeUseCases: ['Convidar amigo.', 'Dizer planos de sábado/domingo.', 'Marcar horário.', 'Falar de condição como chuva.', 'Explicar tarefa doméstica antes de sair.'],
    conceptExplanation: 'Organize a fala em: pergunta, plano, motivo, horário/lugar. Use going to para plano e let’s para convite. Use if para condição simples: if it doesn’t rain.',
    mentalModel: { title: 'weekend speaking = plan + time + invite', summary: 'Diga plano, combine horário e confirme.', steps: ['What are you going to do?', 'I am going to...', 'Let’s meet at...', 'See you then.'] },
    stepByStep: [task('Pergunte o plano da outra pessoa.'), task('Diga seu plano.'), task('Explique motivo se necessário.'), task('Proponha horário/lugar.'), task('Confirme e encerre.')],
    portugueseContrast: [task('Let’s meet = vamos nos encontrar.'), task('What about Sunday? = e domingo?'), task('See you then = até lá/te vejo então.')],
    guidedDiscovery: [task('What are you going to do? pede plano.'), task('I am going to... responde.'), task('Let’s meet at four combina horário.')],
    guidedBeforeQuiz: [task('Repita: What are you going to do this weekend?'), task('Repita: I am going to visit my family.'), task('Repita: Let’s meet at four.'), task('Repita: If it doesn’t rain.')],
    speakingSituation: 'Você está combinando planos de fim de semana com um amigo.',
    modelPhrases: [phrase('What are you going to do this weekend?', 'O que você vai fazer este fim de semana?'), phrase('I am going to clean the house on Saturday.', 'Vou limpar a casa no sábado.'), phrase('I am going to visit the park on Sunday.', 'Vou visitar o parque no domingo.'), phrase('Let’s meet at four.', 'Vamos nos encontrar às quatro.'), phrase('If it doesn’t rain.', 'Se não chover.')],
    pronunciationChunks: [task('what are you going to do', 'Pergunta em bloco.'), task('this weekend', 'Tempo final.'), task('let’s meet at four', 'Convite + horário.')],
    repeatAfterMe: [task('What are you going to do this weekend?'), task('I am going to study on Saturday.'), task('Are you going to call me?'), task('Let’s meet at four.'), task('See you then.')],
    substitutionDrills: [task('study → clean the house', 'I am going to clean the house.'), task('at four → after lunch', 'Let’s meet after lunch.'), task('park → restaurant', 'I am going to visit a restaurant.')],
    guidedSpeaking: [task('Pergunte o plano de sábado.'), task('Diga seu plano de domingo.'), task('Faça um convite com let’s.'), task('Adicione condição com if.'), task('Confirme o horário.')],
    recordingTasks: [task('Grave 5 frases de planos.'), task('Grave 5 perguntas com going to.'), task('Grave diálogo de 8 linhas sobre fim de semana.')],
    freeSpeaking: task('Fale por até 60 segundos sobre seus planos de fim de semana, incluindo estudo, casa e lazer.'),
    feedbackChecklist: [task('Usei going to?'), task('Fiz pergunta sobre plano?'), task('Disse sábado/domingo?'), task('Combinei horário/lugar?'), task('Usei let’s ou if?')],
    selfAssessment: [task('Consigo falar de planos?'), task('Consigo perguntar planos?'), task('Consigo combinar horário?')],
    lessonRecap: ['Weekend speaking usa going to e let’s.', 'Perguntas ajudam conversa real.', 'Horário/lugar deixam plano claro.', 'If cria condição simples.'],
    nextLessonBridge: 'Na Writing, você vai escrever seus planos de fim de semana e fechar o A2.3.',
  }),

  createWritingLesson({
    ...common,
    id: 'A2-WRITING-012',
    order: 12,
    title: 'Write weekend plans',
    objectives: ['Escrever planos de fim de semana com going to.', 'Incluir sábado, domingo, horário, motivo e condição.', 'Usar vocabulário de casa, estudo e lazer.', 'Revisar estrutura e clareza do plano.'],
    teacherOpening: 'Esta aula fecha o A2.3. Você vai escrever seus planos de fim de semana: On Saturday, I am going to clean the kitchen. After lunch, I am going to review English. On Sunday, I am going to visit my sister if it doesn’t rain.',
    whyItMatters: 'Escrever planos organiza futuro, tempo e intenção. É uma forma prática de usar going to em contexto real.',
    realLifeUseCases: ['Mandar plano para amigo.', 'Organizar fim de semana.', 'Planejar estudo e tarefas.', 'Responder convite.', 'Escrever mensagem curta de planejamento.'],
    conceptExplanation: 'Um texto de weekend plans tem 5 partes: Saturday plan, reason, study/leisure plan, Sunday plan, condition. Use going to e time expressions como on Saturday, after lunch, at night, on Sunday.',
    mentalModel: { title: 'weekend writing = Saturday + Sunday + details', summary: 'Organize por dia e use going to para cada plano.', steps: ['On Saturday...', 'After lunch...', 'At night...', 'On Sunday...', 'If...'] },
    stepByStep: [task('Comece com This weekend.'), task('Escreva plano de sábado.'), task('Adicione motivo/problema.'), task('Escreva plano de estudo ou lazer.'), task('Escreva plano de domingo.'), task('Adicione condição com if.'), task('Revise going to.')],
    portugueseContrast: [task('On Saturday/Sunday usa on.'), task('After lunch = depois do almoço.'), task('At night = à noite.'), task('Use going to + verbo base.')],
    guidedDiscovery: [task('On Saturday organiza o dia.'), task('I am going to clean mostra plano.'), task('If it doesn’t rain cria condição.'), task('Because explica motivo.')],
    guidedBeforeQuiz: [task('Modelo: This weekend, I am going to stay home.'), task('Modelo: On Saturday, I am going to clean the kitchen.'), task('Modelo: On Sunday, I am going to visit my family.'), task('Modelo: If it doesn’t rain.')],
    writingPurpose: 'Escrever texto curto de planos de fim de semana.',
    modelText: `This weekend, I am going to stay home on Saturday morning because the sink is leaking. I am going to call a technician and clean the kitchen. After lunch, I am going to review English vocabulary and practice listening. On Sunday, I am going to visit my sister if it doesn't rain. At night, I am going to rest and prepare for work.`,
    writingBlocks: [task('Opening', 'This weekend, I am going to stay home.'), task('Saturday plan', 'On Saturday morning, I am going to clean the kitchen.'), task('Reason', 'The sink is leaking.'), task('Study plan', 'After lunch, I am going to review English.'), task('Sunday plan', 'On Sunday, I am going to visit my sister.'), task('Condition/closing', 'If it doesn’t rain, I am going to go to the park.')],
    guidedSubstitution: [task('Troque clean the kitchen por fix my phone.'), task('Troque review vocabulary por practice speaking.'), task('Troque visit my sister por meet my friend.'), task('Troque if it doesn’t rain por if I have time.')],
    grammarForWriting: [task('Use am/is/are going to + base verb.'), task('Use on + day.'), task('Use after + meal/time.'), task('Use because para motivo.'), task('Use if para condição simples.')],
    checklist: [task('Incluí sábado?'), task('Incluí domingo?'), task('Usei going to corretamente?'), task('Incluí tempo/horário?'), task('Incluí motivo ou condição?'), task('Revisei verbo base depois de to?')],
    draftTask: task('Escreva um texto de 5 a 7 frases sobre seus planos de fim de semana.'),
    revisionTask: task('Revise dias, going to, horários, motivo e condição.'),
    commonMistakes: [mistake('I going to study.', 'I am going to study.', 'Falta am.'), mistake('I am going to studying.', 'I am going to study.', 'Depois de to, verbo base.'), mistake('In Saturday', 'On Saturday', 'Dias usam on.')],
    productionTasks: [task('Escreva versão 1 dos planos.'), task('Adicione um problema de casa e um plano de solução.'), task('Reescreva com if e because.'), task('Produza versão final com 6 frases.')],
    selfAssessment: [task('Consigo escrever planos com going to?'), task('Consigo organizar sábado/domingo?'), task('Consigo revisar erros de going to?')],
    lessonRecap: ['Weekend plans fecham A2.3.', 'Going to organiza futuro planejado.', 'On Saturday/Sunday localiza planos.', 'Because e if deixam o texto mais real.'],
    nextLessonBridge: 'A2.3 está fechado. O próximo pacote correto será A2.4 Choices, quantities and comparisons.',
  }),
]);

export const A2_DEEP_PLANS_AND_NOW_PART4_BY_PILLAR = Object.freeze({
  grammar: Object.freeze(A2_DEEP_PLANS_AND_NOW_PART4.filter((lesson) => lesson.pillar === 'grammar')),
  vocabulary: Object.freeze(A2_DEEP_PLANS_AND_NOW_PART4.filter((lesson) => lesson.pillar === 'vocabulary')),
  reading: Object.freeze(A2_DEEP_PLANS_AND_NOW_PART4.filter((lesson) => lesson.pillar === 'reading')),
  listening: Object.freeze(A2_DEEP_PLANS_AND_NOW_PART4.filter((lesson) => lesson.pillar === 'listening')),
  speaking: Object.freeze(A2_DEEP_PLANS_AND_NOW_PART4.filter((lesson) => lesson.pillar === 'speaking')),
  writing: Object.freeze(A2_DEEP_PLANS_AND_NOW_PART4.filter((lesson) => lesson.pillar === 'writing')),
});
