export { storage, storageKeys } from './storage.js';
export { diagnostics } from './diagnostics.js';
export { LESSON_TYPES, normalizeLessonType, normalizeLesson, isReadingLesson } from './lessonTypes.js';
export { GEMINI_LESSON_STATUS, generateLessonDraft, isValidGeminiKey, maskApiKey, normalizeLessonKeys } from './geminiLessons.js';
export { AZURE_PRONUNCIATION_STATUS, analyzePronunciation } from './azurePronunciation.js';
export { getFirebaseApp, getFirebaseAuth, getFirebaseStatus, hasFirebaseConfig } from './firebase.js';
export { subscribeAuth, signInWithGoogle, logout } from './auth.js';
export { getAccessSession, setAccessSession, clearAccessSession, validateAccessCode } from './accessCode.js';
export { getLessonFlashKeys, saveLessonFlashKeys, addLessonFlashKey, removeLessonFlashKey, getLessonProKey, saveLessonProKey, clearLessonProKey, getLessonKeysStatus, buildLessonKeyPlan } from './lessonKeys.js';
export { getCurrentLesson, saveCurrentLesson, clearCurrentLesson, getLessonHistory, getLessonPromptDraft, saveLessonPromptDraft } from './lessonStore.js';
export { unlockAudioForIOS, isAudioUnlocked, getAudioContext } from './audioUnlock.js';
export { speakText, stopSpeech, getAvailableVoices } from './tts.js';
export { startRecording, stopRecording, cancelRecording, isRecording } from './recorder.js';
export { generateGeminiTtsAudio, playGeminiTtsAudio } from './geminiTts.js';
export { AI_REVIEWER_VERSION, buildReviewerPromptForType } from './aiReviewerPrompts.js';
export { AI_REVIEW_APPROVAL_SCORE, AI_REVIEW_MAX_RETRIES, reviewLessonWithAI, shouldRegenerateLesson, mergeReviews } from './aiTeacherReviewer.js';
export { LESSON_HISTORY_CONTEXT_VERSION, LESSON_HISTORY_CONTEXT_MAX_CHARS, buildLessonHistoryContext, formatHistoryContextForPrompt, buildLessonHistoryPromptPrefix } from './lessonHistoryContext.js';
export { extractTopicKeywords, recordCurrentCurriculumUnit, recordLessonAsCurrentCurriculumUnit, getCurrentCurriculumUnit, buildCurriculumContextForBuilder, getCurrentCurriculumContextForBuilder } from './curriculumPracticeAdapter.js';
